### ISSUE TITLE
Universal Sentence Encoder for clustering

### ISSUE THREAD

**Issue by bonoboris** [tensorflow/hub#100]
Hi,

I would like to use Universal Sentence encoder to perform clustering on (little) messy data. Items go from single words to full paragraphs, from meaningless words /  proper nouns to highly specific paragraphs (in a semantic way). I might as well go for semi-supervised classification if unsupervised clustering isn't efficient .
It's important that i keep overfiting really low as my goal is to cluster a growing database with new unrelated clusters in the future.

Any advice on how to do that ? 

Thx a lot.

**Comment by vbardiovskyg** [comment]
Hi,

I would start with something simple like tf.contrib.factorization.KMeansClustering. The embeddings from USE can be either pre-computed or you could apply a module directly inside the input function, depending on the format and size of the data.
