### ISSUE TITLE
Pre-trained UMLFiT's language model on tensorflow-hub?

### ISSUE THREAD

**Issue by tuvuumass** [tensorflow/hub#101]
Should we have this state-of-the-art language model for text classification?

https://arxiv.org/pdf/1801.06146.pdf
http://nlp.fast.ai/classification/2018/05/15/introducting-ulmfit.html

**Comment by vbardiovskyg** [comment]
Thanks for the tip! We are currently not planning to release ULMFiT as a Tensorflow Hub module. However, we would be very supportive if there was interest in the community to create it.

**Comment by loretoparisi** [comment]
@vbardiovskyg what about ELMO?

**Comment by vbardiovskyg** [comment]
@loretoparisi: Hi, we already have an [ELMO module](https://tfhub.dev/google/elmo/2).

**Comment by vivekverma239** [comment]
@vbardiovskyg do you have idea if anyone is working on ULMFiR for TF-Hub ?

**Comment by vbardiovskyg** [comment]
Hi, I don't know of anybody working on that at the moment.

**Comment by rjurney** [comment]
This would be great...

**Comment by hubertkarbowy** [comment]
Please don't close yet - reports of the death of recurrent language models have been greatly exaggerated.

I am working on making ULMFiT available as a Tensorflow Hub module for English and Polish. The code is at quite a mature stage (https://github.com/hubertkarbowy/awd_lstm_tensorflow2/ - it will be moved to my company's account later) but I need around two more weeks to clean up some legacy code and write updated docs.

**Comment by akhorlin** [comment]
We would definitely welcome a new model contribution for tfhub.dev irregardless of the status of this issue.

**Comment by j-grimstad** [comment]
@hubertkarbowy Echoing @akhorlin - we'd very much appreciate a contribution whenever you're ready! Please let us know if you have any questions about the publishing process -- [documentation can be found here](https://www.tensorflow.org/hub/publish).

**Comment by edrone** [comment]
@j-grimstad I'm not able to get past the CLA bot here: https://github.com/tensorflow/tfhub.dev/pull/61

I think I have all the emails set up correctly and the CLA page says "You have already signed this CLA" when I try to resubmit. Can you please help? Thanks.

**Comment by akhorlin** [comment]
This is the issue due to newly rolled out "first time committer" protection in GitHub. The repo owners have to approve a workflow to run, which includes "cla/google". 

I approved it for this run. There is also no way to do one-time approval. So we may need to provide an approval very time a workflow needs to run.

**Comment by edrone** [comment]
Okay, thanks. Since I filled out the CLA form several days ago on behalf of my company - is there anything else I need to do right now regarding this CLA? Or does it just take some time to get processed?

**Comment by edrone** [comment]
ULMFiT is now available for English and Polish from this collection: https://tfhub.dev/edrone/collections/ulmfit/1

@akhorlin @j-grimstad - can you please have a look at our models' metadata? The publisher and the architecture fields are there, but are somehow not displayed on the above page (publisher) and the individual model pages (architecture). Thanks.

**Comment by j-grimstad** [comment]
Hi @edrone -- per @WGierke's note on https://github.com/tensorflow/tfhub.dev/pull/61, it looks like these issues are resolved -- let us know on that thread if that's not the case.

**Comment by edrone** [comment]
Hi, it looks that everything is OK. Thanks!

I think we can close this issue now.

**Comment by arghyaganguly** [comment]
Closing this based on the discussion in the comment trace.Thank you.
