### ISSUE TITLE
toco model

### ISSUE THREAD

**Issue by kaiwalya4850** [tensorflow/hub#107]
The toco model just doesn't run due to some error and due to that we just cannot deploy our models in android!

**Comment by andresusanopinto** [comment]
Can you please provide more information on the error and also on what it changed from when it was working vs now (e.g. upgraded to newer version of tf? trying to run on a new machine?).

**Comment by PaulWoitaschek** [comment]
"Doesnt build" does not help. Post the build error.

**Comment by hgadig** [comment]
Closing this as there is no response received about the build error.
Please retry with the latest version of hub and create a new issue(if there are any errors). Thanks !
