### ISSUE TITLE
Feature request: Using hub.Module with TensorRT

### ISSUE THREAD

**Issue by dchichkov** [tensorflow/hub#108]
I'm trying it with TensorRT and hitting an issue:  'Graph' object has no attribute 'SerializeToString'.  Is this expected?  By the way, does it make sense to try to quantize/prune your MobilNet model with TensorRT?

```
graph = tf.Graph()
with graph.as_default():  
      mobilnet_op = hub.Module("https://tfhub.dev/google/imagenet/mobilenet_v2_100_128/feature_vector/2", trainable=True)
...
trt.create_inference_graph(input_graph_def = graph, outputs = "image_feature_vector",
    max_batch_size=1, max_workspace_size_bytes=50000000, precision_mode="FP16", minimum_segment_size=3)
```

**Comment by vbardiovskyg** [comment]
Hi, the graph object here is not a GraphDef. You can get it by calling graph.as_graph_def().

As for the second question, we haven't yet looked into using TensorFlow Hub graph defs with TensorRT, so we don't fully understand all the implications at this moment. We can keep this issue open to track any progress.

**Comment by captain-pool** [comment]
@vbardiovskyg, as discussed earlier, I'ld like to work on this as a part of GSoC (most probably this month or in the coming month). can you assign this to me?

**Comment by akhorlin** [comment]
Closing due to deprecated status of hub.Module()
