### ISSUE TITLE
label_image does not work with quantized MobilenetV1 .tflite 

### ISSUE THREAD

**Issue by jonkoi** [tensorflow/hub#109]
Hi,

I used retrain.py to retrain quantized mobilenet v1 from https://tfhub.dev/google/imagenet/mobilenet_v1_050_128/quantops/classification/1.

Then I converted the graph to tflite as following:

```
toco \
--input_format=TENSORFLOW_GRAPHDEF \
--input_file=/home/khoi/mobilenet_slim/exp2_1_1/graph.pb \
--output_format=TFLITE \
--output_file=/home/khoi/mobilenet_slim/exp2_1_1/exp2.tflite \
--inference_type=QUANTIZED_UINT8 \
--input_shape=1,128,128,3 \
--input_array=Placeholder \
--output_array=final_result \
--input_data_type=FLOAT
```

When I run the [label_image](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/label_image/label_image.cc),
```

bazel run --config=opt //tensorfl/lite/examples/label_image:label_image -- \
--tflite_model=/home/khoi/mobilenet_slim/exp2_1_1/exp2.tflite \
--image=/home/khoi/mobilenet_slim/exp2_1_1/3.bmp \
--labels=/home/khoi/mobilenet_slim/exp2_1_1/labels.txt
```

 the process stop at `resolved reporter` without any error.

Does anyone know what the problem can be?

**Comment by arnoegw** [comment]
Hi jonoki, thanks for the report. We're looking into it, not clear yet which component is even at fault...

**Comment by vikrambukka** [comment]
How to run quantized mobilenet v1 inference model?

**Comment by arnoegw** [comment]
@jonkoi: This reproduces for me (and --config=dbg plus gdb shed some light). The issue appears to be a boundary condition in TFLite's handling of quantization scales. I'll see if I can work around that in the quantops modules itself...

**Comment by arnoegw** [comment]
Please try again with https://tfhub.dev/google/imagenet/mobilenet_v1_050_128/quantops/classification/3

For me, that fixed the problem. Please reopen (with repro details) if it persists for you. Thank you for your patience.

**Comment by XMK233** [comment]
Hi, arnoegw. I'm curious about what did you do to build the V3? Did you do something in module_fn()? 

By the way, are the module_fn() in ModuleSpec you guys used to generate TensorFlow hub modules open-sourced? Actually I'm also interested in them and I hope to learn these implementations. 

Thank you very much.

**Comment by XMK233** [comment]
Hi, @arnoegw . I'm curious about what did you do to build the V3? Did you do something in module_fn()?

By the way, are the module_fn() in ModuleSpec you guys used to generate TensorFlow hub modules open-sourced? Actually I'm also interested in them and I hope to learn these implementations.

Thank you very much.

**Comment by arnoegw** [comment]
Hi @XMK233, the module_fn for google/imagenet/mobilenet_v1... is just a thin wrapper around the TF-Slim implementation (and likewise for any of our image models that mention TF-Slim in the documentation). Unfortunately, it is not open-sourced at this time.

That wrapper contains a scaling from the canonical input range [0,1] of pixel values to the one expected internally by slim, which is [-1,+1]. Before commit https://github.com/tensorflow/tensorflow/commit/01ebab40444bc20202336a36012aedc02210661e, toco did not work when using the precise range [-1,+1] for quantization, so I worked around that and made it [-1,+1.001].

**Comment by XMK233** [comment]
Thanks. ;-)
