### ISSUE TITLE
DataLossError : Checksum does not match

### ISSUE THREAD

**Issue by nikitacs16** [tensorflow/hub#111]
Even after saving the cached module to custom directory, the checkpoint gets corrupted after less than 10 runs of the same file. 
How to download the entire module for once ?
This is happening for Universal Sentence Encoder module of tensorflow hub
``DataLossError (see above for traceback): Checksum does not match: stored 1387380197 vs. calculated on the restored bytes 2093217975
	 [[Node: checkpoint_initializer_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](checkpoint_initializer/prefix, checkpoint_initializer_7/tensor_names, checkpoint_initializer/shape_and_slices)]]
``

**Comment by andresusanopinto** [comment]
The module is just downloaded once and then cached in the directory for future uses.
The directory is just read from and never written so the error you describe is very weird and I can't imagine a software reason for the data to become corrupted as you use it.

**Comment by nikitacs16** [comment]
Precisely my point as well. Since it just gets cached from that folder, the module itself has no chances of getting corrupted. Even after downloading and storing in a separate cache folder, it ends up leading to this error. I re-tried downloading the module. But yes, the weird error persists.

**Comment by hgadig** [comment]
@nikitacs16  Apologies for the late response. Just want to confirm if you are still running into the same error with the latest versions. Please keep us posted.

**Comment by nikitacs16** [comment]
I think you can close this issue now. Thank you
