### ISSUE TITLE
Using retrain.py to export model for ML Engine

### ISSUE THREAD

**Issue by Stroemgren** [tensorflow/hub#118]
Hi

I've used retrain.py with the --saved_model_dir flag to export a model that I've deployed to ML Engine.
When trying to use it for prediction I get an error saying that it expects to float32 input but receives a string.

`{"error": "Prediction failed: Error processing input: Expected float32, got '\\xff\\xd8\\xff\\xe0 ...' of type 'str' instead."}`

My request looks like this

`{"image": {"b64": "/9j/4AAQxh6AP/2Q== ..."}}`

Am I missing something? Is the export method from retrain.py not meant for exporting to ML Engine? Can I modify it to do so?

**Comment by vbardiovskyg** [comment]
Hi,

the input placeholder for exported graph is specified here: https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py#L305.

The input will have to be converted to array of float32s unless the export graph is changed to accept string encoded jpeg on input.

**Comment by hgadig** [comment]
Closing this issue as it has been answered. For further questions, please open a new issue with the latest information. Thanks!
