### ISSUE TITLE
Failed to download model

### ISSUE THREAD

**Issue by herbertchen1** [tensorflow/hub#119]
I can‘t download the model  cause I'm in China ...
Is there any command i can use to download the model?
Sincerely thanks.

**Comment by manishprasadthapliyal** [comment]
use proxy to download the model

**Comment by andresusanopinto** [comment]
We added a [cannot download module](https://github.com/tensorflow/hub/blob/master/docs/common_issues.md#cannot-download-a-module) section in a new common issues page.
