### ISSUE TITLE
Clarify module licensing

### ISSUE THREAD

**Issue by aleksandar** [tensorflow/hub#12]
i can't find any information about license for the models. maybe the apache 2.0?

**Comment by agasparovic** [comment]
Yes, the modules are licensed under the Apache 2.0 Licence, just like the library code itself. I will leave this issue open to track clarifying module licensing in our documentation.

Thanks!

**Comment by hgadig** [comment]
I see the licence information is updated now(please see below snippet). Hence closing the issue. Please add your comments(just in case if what I understand is wrong). I'll reopen the issue with necessary comments. Thank you !



![image](https://user-images.githubusercontent.com/42781361/54377934-70c19a00-4643-11e9-960f-dcbae9b4e39a.png)
