### ISSUE TITLE
downloading universal sentence encoder pre-trained model

### ISSUE THREAD

**Issue by AlfredAM** [tensorflow/hub#122]
Hi,

I would like to try the Universal Sentence encoder pre-trained model for a text classification task with the following code, but it has hung for hours, and the network connection is fine. 

module_url = "https://tfhub.dev/google/universal-sentence-encoder/2"
embed = hub.Module(module_url)

Any advice on how to access the pre-trained model? 

Thx a lot.

**Comment by YuangZhang** [comment]
I meet the same question, do you solve it yet?

**Comment by AlfredAM** [comment]
Attaching ?tf-hub-format=compressed to the URL solved the problem. Thanks for your help!

**Comment by PrajapatiManoj** [comment]
Hi, 
Is there any pre-trained-model available for the lite version?

https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder_lite.ipynb#scrollTo=dMTa6V4a-cmf

It would be great if anyone can help me.
