### ISSUE TITLE
retrain.py stuck creating bottlenecks when using module with input 1,224,224,3

### ISSUE THREAD

**Issue by JoseGnRLuis** [tensorflow/hub#130]
I downloaded and executed retrain.py

The problem I have is when I change:
https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1
by, for example:
https://tfhub.dev/google/imagenet/resnet_v2_152/feature_vector/1

When I do this, the script stucks at the line:
  bottleneck_values = sess.run(bottleneck_tensor,
                               {resized_input_tensor: resized_input_values})

It happens when it tries to create the first bottleneck, using a jpg image normal size (350x120) or previously resized (224x224)

Any ideas?

**Comment by andresusanopinto** [comment]
Closing as innactive.
