### ISSUE TITLE
Are the tf hub modules open source?

### ISSUE THREAD

**Issue by theoqian** [tensorflow/hub#131]
Hi, I'm interested in the implement of the modeules such as elmo, nnlm and so on. Are they open source?

**Comment by arnoegw** [comment]
https://tfhub.dev/google/elmo/2 is referenced from https://github.com/allenai/bilm-tf

The google/nnlm-* modules are essentially lookup tables with input splitting; effectively all the smartness is in training the table contents. The actual code to generate the module is not open sourced, but the module documentation has a literature reference how it is done, see https://tfhub.dev/google/nnlm-en-dim50/1
