### ISSUE TITLE
colab notebooks are not working

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/hub#14]
![image](https://user-images.githubusercontent.com/112599/38444741-61f3ff6e-39a5-11e8-853a-abe3d2a132d5.png)

**Comment by gridcellcoder** [comment]
I tried it from the github link directly and it seems to find it:

https://github.com/tensorflow/hub/tree/master/examples

e.g for each demo:

Click on the `try live in colab` 

https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder.ipynb

https://github.com/tensorflow/hub/blob/master/examples/colab/text_classification_with_tf_hub_on_kaggle.ipynb

**Comment by vbardiovskyg** [comment]
Thanks for reporting!

Switched all colab links to master branch, so they should open even when opening from the r0.1 branch view.
