### ISSUE TITLE
Previously working U.S.E. fails with tf api 1.10

### ISSUE THREAD

**Issue by abster95** [tensorflow/hub#141]
os: Microsoft Windows 10 Enterprise   Version	10.0.17134 Build 17134
python: Python 3.5.5 | packaged by conda-forge
tensorflow                1.0.0                    py35_0    conda-forge
tensorflow-gpu            1.10.0                    <pip>
tensorflow-hub            0.1.1                      py_0    conda-forge
cudnn                     7.1.4                 cuda9.0_0
graphics card: GeForce GTX 1070

Sample code:
`module = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/2")`
`text = ["the quick brown fox jumps over the lazy dog"]`
`op = module(text)`
`with tf.Session() as sess:`
`  sess.run(tf.global_variables_intializer())`
`  sess.run(tf.tables_initializer())`
`  print(op.eval())`

Fails on multiple machines, but worked on all of them before the new API. It failed with the following error:

> NotFoundError: No registered 'Size' OpKernel for GPU devices compatible with node module_1_apply_default/compound_bigrams/boolean_mask/Prod = Size[T=DT_STRING, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_1_apply_default/compound_bigrams/concat_2/_91, ^module_1_apply_default/compound_bigrams/boolean_mask/Shape_1/_95)
         (OpKernel was found, but attributes didn't match)
        .  Registered:  device='CPU'; out_type in [DT_INT32]
  device='CPU'; out_type in [DT_INT64]
  device='GPU'; T in [DT_HALF]; out_type in [DT_INT32]
  device='GPU'; T in [DT_HALF]; out_type in [DT_INT64]
  device='GPU'; T in [DT_BFLOAT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_BFLOAT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; out_type in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; out_type in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; out_type in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT64]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_type in [DT_INT64]
  device='GPU'; T in [DT_UINT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_UINT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_UINT8]; out_type in [DT_INT32]
  device='GPU'; T in [DT_UINT8]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT8]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT8]; out_type in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; out_type in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; out_type in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; out_type in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; out_type in [DT_INT64]
  device='GPU'; T in [DT_BOOL]; out_type in [DT_INT32]
  device='GPU'; T in [DT_BOOL]; out_type in [DT_INT64]
  device='GPU'; T in [DT_VARIANT]; out_type in [DT_INT32]
  device='GPU'; T in [DT_VARIANT]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT32]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_type in [DT_INT64]

         [[Node: module_1_apply_default/compound_bigrams/boolean_mask/Prod = Size[T=DT_STRING, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_1_apply_default/compound_bigrams/concat_2/_91, ^module_1_apply_default/compound_bigrams/boolean_mask/Shape_1/_95)]]

Caused by op 'module_1_apply_default/compound_bigrams/boolean_mask/Prod'

**Comment by opokualbert** [comment]
I think I have similar issue. This line worked about 5 days ago. Today, it won't work.
Python 3.6 anaconda
Tensorflow 1.9.0
tensorhub 0.1.1
windows 10
CPU

CODE
`description_embeddings = hub.text_embedding_column("descriptions", module_spec="https://tfhub.dev/google/universal-sentence-encoder/2", trainable=False)`

ERROR
NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\kirk\AppData\Local\Temp\tfhub_modules\1fb57c3ffe1a38479233ee9853ddd7a8ac8a8c47\tfhub_module.pb : The system cannot find the file specified.
; No such file or directory

**Comment by opokualbert** [comment]
I found the solution to my problem. turns out there was an update. need to replace with the new version  `https://tfhub.dev/google/universal-sentence-encoder-large/3`

**Comment by abster95** [comment]
@opokualbert thanks, that fixed it.
