### ISSUE TITLE
How can I use my own pretrained model as feature extractor module?

### ISSUE THREAD

**Issue by priyakansal** [tensorflow/hub#148]

**Comment by vbardiovskyg** [comment]
This depends very much on how you trained the model, e.g. did you use the estimator framework?

In any case, the most straightforward way is to define a part of your model you will want to later export as a **module** and then use one of approaches from the [documentation](https://www.tensorflow.org/hub/creating).

**Comment by andresusanopinto** [comment]
Closed due to innactivity.
