### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'estimator'

### ISSUE THREAD

**Issue by damienpontifex** [tensorflow/hub#150]
After I install `tensorflow_hub`, tensorflow and tensorflow_hub get the error "tf.estimator package not installed."

Steps to reproduce:
1. Install tensorflow with `pip3 install tensorflow`
2. Run python code
```python
import tensorflow as tf
tf.estimator # Output: <module 'tensorflow.python.estimator.api.estimator' from '/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/api/estimator/__init__.py'>
```
3. Install tensorflow hub with `pip3 install tensorflow_hub`
4. Run python code
```python
import tensorflow as tf # Output: tf.estimator package not installed.
import tensorflow_hub as hub
# Error output of
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-5c017171c13e> in <module>()
----> 1 import tensorflow_hub as hub

/usr/local/lib/python3.6/site-packages/tensorflow_hub/__init__.py in <module>()
     21 import tensorflow as tf
     22 
---> 23 from tensorflow_hub.estimator import LatestModuleExporter
     24 from tensorflow_hub.estimator import register_module_for_export
     25 from tensorflow_hub.feature_column import image_embedding_column

/usr/local/lib/python3.6/site-packages/tensorflow_hub/estimator.py in <module>()
     59 
     60 
---> 61 class LatestModuleExporter(tf.estimator.Exporter):
     62   """Regularly exports registered modules into timestamped directories.
     63 

AttributeError: module 'tensorflow' has no attribute 'estimator'
```

If I uninstall tensorflow hub with `pip3 uninstall -y tensorflow_hub`, `tf.estimator` works again in TensorFlow

Environment:

- macOS 10.14 Beta (18A384a)
- Python 3.6.5
- pip 10.0.1
- TensorFlow 1.10.1
- TensorFlow Hub 0.1.1

**Comment by arnoegw** [comment]
Sorry, could not reproduce (on MacOS 10.13 with Python 3.6.4). Could you dig deeper?

**Comment by Tracy6465** [comment]
Have you solved this problem? @damienpontifex

**Comment by sometimescasey** [comment]
Came across this today because I was using an old version of Tensorflow from a super old conda environment (1.0.1). Updating to anything from r1.1 onwards should resolve.

`tf.estimator` doesn't appear to exist prior to Tensorflow r1.1 - verify using the branch dropdown at top left here: (https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/python/estimator/estimator.py)
