### ISSUE TITLE
how to load module without tensorflow hub

### ISSUE THREAD

**Issue by Louagyd** [tensorflow/hub#151]
hello, I want to fine-tune a mobilenet for my dataset and so I'm using tensorflow-hub to create and save model, but I should train this model in server and our server doesn't have tensorflow-hub installed. then I tried many ways for saving and restoring model and variables. but they didn't work.
here is how I create and save model with tensorflow-hub:
```
module = hub.Module("https://tfhub.dev/google/imagenet/mobilenet_v2_050_160/feature_vector/2", trainable=True, tags = {"train"})

images_placeholder_init = tf.placeholder(tf.float32, [None, None, None, 3], name = "images_ph_init")
images_scaled = tf.image.resize_images(images_placeholder_init, [height, width])
labels_placeholder = tf.placeholder(tf.int32, [None, number_of_classes], name = "labels_ph")
features = module(images_scaled)

saver = tf.train.Saver()
sess.run(tf.global_variables_initializer())
saver.save(sess, 'mobilenet_v2_050_160/model_init', global_step=0)
```

and when I want to load it in server:
```
saver = tf.train.import_meta_graph("mobilenet_v2_050_160/model_init-0.meta")
saver.restore(sess, 'mobilenet_v2_050_160/model_init-0')
```

so I got this error:

> Traceback (most recent call last):
>   File "application.py", line 98, in <module>
>     thub.train_mobile_net(train_pkl_path=os.path.join(movie_path, "train_data"), valid_pkl_path=os.path.join(movie_path, "valid_data"), number_of_classes=3, num_epoch=num_epochs, save_end = True, save_target = model_target, error_path=error_path)
>   File "/users/home/reutenauer/workarea/git/Velours/python/mtr/ironcar/tensorHUB.py", line 101, in train_mobile_net
>     sess.run(tf.global_variables_initializer())
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 895, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
>     options, run_metadata)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for mobilenet_v2_050_160\variables\variables
>          [[Node: checkpoint_initializer = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](checkpoint_initializer/prefix, checkpoint_initializer/tensor_names, checkpoint_initializer/shape_and_slices)]]
>          [[Node: init_1/NoOp_1/_5854 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_3165_init_1/NoOp_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
> 
> Caused by op 'checkpoint_initializer', defined at:
>   File "application.py", line 98, in <module>
>     thub.train_mobile_net(train_pkl_path=os.path.join(movie_path, "train_data"), valid_pkl_path=os.path.join(movie_path, "valid_data"), number_of_classes=3, num_epoch=num_epochs, save_end = True, save_target = model_target, error_path=error_path)
>   File "/users/home/reutenauer/workarea/git/Velours/python/mtr/ironcar/tensorHUB.py", line 90, in train_mobile_net
>     saver = tf.train.import_meta_graph("mobilenet_v2_050_160/model1-0.meta")
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1698, in import_meta_graph
>     **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/meta_graph.py", line 656, in import_scoped_meta_graph
>     producer_op_list=producer_op_list)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
>     op_def=op_def)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for mobilenet_v2_050_160\variables\variables
>          [[Node: checkpoint_initializer = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](checkpoint_initializer/prefix, checkpoint_initializer/tensor_names, checkpoint_initializer/shape_and_slices)]]
>          [[Node: init_1/NoOp_1/_5854 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_3165_init_1/NoOp_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
> 
> Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f8870021e10>>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 701, in __del__
> TypeError: 'NoneType' object is not callable

**Comment by arnoegw** [comment]
Hi Louagyd, when I run what you described above (with `height = width = 160` and `num_classes = 5`), it doesn't crash:

```
$ python
>>> import tensorflow as tf
>>> saver = tf.train.import_meta_graph("mobilenet_v2_050_160/model_init-0.meta")
>>> sess = tf.Session()
>>> saver.restore(sess, 'mobilenet_v2_050_160/model_init-0')
INFO:tensorflow:Restoring parameters from mobilenet_v2_050_160/model_init-0
>>> sess.run("module_apply_default/MobilenetV2/Logits/AvgPool:0",
             {"images_ph_init:0": [[[[0.1, 0.2, 0.3]]*160]*160]})
array([[[[0.2826413 , 0.5169555 , 0.36947623, ..., 0.09137403,
          0.54979557, 0.24664913]]]], dtype=float32)
```

Looking at the stack trace in your report, I suspect the problem is this here:

```
File "/users/home/reutenauer/workarea/git/Velours/python/mtr/ironcar/tensorHUB.py", line 101, in train_mobile_net
sess.run(tf.global_variables_initializer())
```

Instantiating a hub.Module (as in the very first line of your example code) creates the module's variables **and** changes their initializers to read from the checkpoint that is packaged in the module. This set-up survives the trip from your machine through the metagraph file onto the server, except that restoring from the local copy of the module on your machine is no longer possible: that file doesn't exist on the server, so you get an error message like `Failed to find any matching files ...`.

From what I can see, there is no need to run variable initializers on the server: variables were already initialized on your machine before writing the metagraph and checkpoint. Restoring from the checkpoint should suffice to provide initial values to all variables, including the pre-trained ones from the hub.Module.
