### ISSUE TITLE
"retrain.py": image duplicates are added by "create_image_lists" on Windows

### ISSUE THREAD

**Issue by andreas-seiderer** [tensorflow/hub#154]
Hello,
I noticed that the retrain.py script on Windows finds exactly the double count of jpg files during the search process. The reason for that is that on Windows the paths are case insensitive and with this line in "create_image_lists" it will add duplicates:
`extensions = ['jpg', 'jpeg', 'JPG', 'JPEG']`
https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py#L176

I don't think the retraining process is disturbed by having duplicates (probably just slightly slower) but I shortly fixed this with following addition:
```
        import platform
        if platform.system() == "Windows":
            extensions = ['jpg', 'jpeg']
        else:
            extensions = ['jpg', 'jpeg', 'JPG', 'JPEG']
```

**Comment by arnoegw** [comment]
The fix was merged into master by
https://github.com/tensorflow/hub/commit/1fa48fe991f22bebf4c8d4cd375eaf0daf5fa937
