### ISSUE TITLE
ELMo training error on GPU

### ISSUE THREAD

**Issue by Navhkrin** [tensorflow/hub#157]
I have made multiple tests, including following;

- Wrapping embedding code with tf.device("/cpu:0")
- Using other options ( lstm_outputs1-2 , world_emb )
- Setting trainable to false

The part of the code im using for embeddings is below

         with tf.name_scope("Embedding"):
             def getEmbedding(embedInput,tokenLengths):
            elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)

            embeddings = elmo(
            inputs={
                "tokens": nn_inputs,
                "sequence_len": token_lengths
            },
            signature="tokens",
            as_dict=True)["elmo"]
            
            return embeddings
    
        embeddings = getEmbedding(nn_inputs,token_lengths)

And it works fine if i do any of the options listed above, however, if i set trainable to True and place the embedding code on GPU, i get the following error. Im not sure if im doing something wrong or if there is a bug in the elmo module.
I also tried using following config options but they didnt help

1. config = tf.ConfigProto(allow_soft_placement=True)
2. config.gpu_options.allow_growth = True

> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
>    1277     try:
> -> 1278       return fn(*args)
>    1279     except errors.OpError as e:
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
>    1262       return self._call_tf_sessionrun(
> -> 1263           options, feed_dict, fetch_list, target_list, run_metadata)
>    1264 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
>    1349         self._session, options, feed_dict, fetch_list, target_list,
> -> 1350         run_metadata)
>    1351 
> 
> InvalidArgumentError: Could not colocate node with its resource and reference inputs; devices /job:localhost/replica:0/task:0/device:CPU:0 and /job:localhost/replica:0/task:0/device:GPU:0 are not compatible.
> 	 [[Node: Adam/update_module/aggregation/weights/ResourceApplyAdam = ResourceApplyAdam[T=DT_FLOAT, _class=["loc:@Adam/update_module/aggregation/weights/Read/ReadVariableOp"], use_locking=false, use_nesterov=false](module/aggregation/weights, module/aggregation/weights/Adam, module/aggregation/weights/Adam_1, beta1_power/read, beta2_power/read, Adam/learning_rate, Adam/beta1, Adam/beta2, Adam/epsilon, gradients/Embedding/module_apply_tokens/aggregation/Reshape_grad/Reshape)]]
> 
> During handling of the above exception, another exception occurred:
> 
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-53-b884676ef752> in <module>()
>      10         accList = []
>      11         batcher = batchIterator(trainData,trainTarget,configs["batchSize"])
> ---> 12         trainModel(150000,batcher,configs,accList)
>      13         #tf_embedding.load(embedding_matrix,sess)
>      14         #del embedding_matrix
> 
> <ipython-input-52-b15a3f757180> in trainModel(iterations, batcher, configs, accList)
>      25 
>      26         fd = {nn_inputs:data,nn_outputs:target,isTraining:True,token_lengths:tokens_length}
> ---> 27         _,acc,los = sess.run([train_op,accuracy,loss],feed_dict=fd)
>      28 
>      29         nnTime = time.clock() - nnTime
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
>     875     try:
>     876       result = self._run(None, fetches, feed_dict, options_ptr,
> --> 877                          run_metadata_ptr)
>     878       if run_metadata:
>     879         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
>    1098     if final_fetches or final_targets or (handle and feed_dict_tensor):
>    1099       results = self._do_run(handle, final_targets, final_fetches,
> -> 1100                              feed_dict_tensor, options, run_metadata)
>    1101     else:
>    1102       results = []
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
>    1270     if handle is None:
>    1271       return self._do_call(_run_fn, feeds, fetches, targets, options,
> -> 1272                            run_metadata)
>    1273     else:
>    1274       return self._do_call(_prun_fn, handle, feeds, fetches)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
>    1289         except KeyError:
>    1290           pass
> -> 1291       raise type(e)(node_def, op, message)
>    1292 
>    1293   def _extend_graph(self):
> 
> InvalidArgumentError: Could not colocate node with its resource and reference inputs; devices /job:localhost/replica:0/task:0/device:CPU:0 and /job:localhost/replica:0/task:0/device:GPU:0 are not compatible.
> 	 [[Node: Adam/update_module/aggregation/weights/ResourceApplyAdam = ResourceApplyAdam[T=DT_FLOAT, _class=["loc:@Adam/update_module/aggregation/weights/Read/ReadVariableOp"], use_locking=false, use_nesterov=false](module/aggregation/weights, module/aggregation/weights/Adam, module/aggregation/weights/Adam_1, beta1_power/read, beta2_power/read, Adam/learning_rate, Adam/beta1, Adam/beta2, Adam/epsilon, gradients/Embedding/module_apply_tokens/aggregation/Reshape_grad/Reshape)]]
> 
> Caused by op 'Adam/update_module/aggregation/weights/ResourceApplyAdam', defined at:
>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
>     app.launch_new_instance()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
>     app.start()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
>     self.io_loop.start()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
>     self.asyncio_loop.run_forever()
>   File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
>     self._run_once()
>   File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
>     handle._run()
>   File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 145, in _run
>     self._callback(*self._args)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
>     handler_func(fileobj, events)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
>     return fn(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
>     self._handle_recv()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
>     self._run_callback(callback, msg)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
>     callback(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
>     return fn(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
>     return self.dispatch_shell(stream, msg)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
>     handler(stream, idents, msg)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
>     user_expressions, allow_stdin)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
>     raw_cell, store_history, silent, shell_futures)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
>     interactivity=interactivity, compiler=compiler, result=result)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
>     if self.run_code(code, result):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-49-182bfb75cb62>", line 131, in <module>
>     train_op = optimizer.minimize(loss,global_step=global_step,colocate_gradients_with_ops=True)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 410, in minimize
>     name=name)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 605, in apply_gradients
>     update_ops.append(processor.update_op(self, grad))
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 166, in update_op
>     update_op = optimizer._resource_apply_dense(g, self._v)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\adam.py", line 174, in _resource_apply_dense
>     grad, use_locking=self._use_locking)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\gen_training_ops.py", line 1340, in resource_apply_adam
>     use_nesterov=use_nesterov, name=name)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
>     return func(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
>     op_def=op_def)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): Could not colocate node with its resource and reference inputs; devices /job:localhost/replica:0/task:0/device:CPU:0 and /job:localhost/replica:0/task:0/device:GPU:0 are not compatible.
> 	 [[Node: Adam/update_module/aggregation/weights/ResourceApplyAdam = ResourceApplyAdam[T=DT_FLOAT, _class=["loc:@Adam/update_module/aggregation/weights/Read/ReadVariableOp"], use_locking=false, use_nesterov=false](module/aggregation/weights, module/aggregation/weights/Adam, module/aggregation/weights/Adam_1, beta1_power/read, beta2_power/read, Adam/learning_rate, Adam/beta1, Adam/beta2, Adam/epsilon, gradients/Embedding/module_apply_tokens/aggregation/Reshape_grad/Reshape)]]

**Comment by rmothukuru** [comment]
@Navhkrin ,
Sorry for the delayed response. Can you please confirm if the issue still persists.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
