### ISSUE TITLE
USE .How to identify  whether DAN model or Transformer  model

### ISSUE THREAD

**Issue by SriniNaga** [tensorflow/hub#162]
Eg:
https://tfhub.dev/google/universal-sentence-encoder/1  (DAN)??
https://tfhub.dev/google/universal-sentence-encoder-large/1 (Transformer)??
I mean  _Sentence-encoder-large_ are trained with Transformer model?

**Comment by vbardiovskyg** [comment]
Hi,

this can be found in the module documentation.

https://tfhub.dev/google/universal-sentence-encoder/1
> The universal-sentence-encoder model is trained with a deep averaging network (DAN) encoder.


https://tfhub.dev/google/universal-sentence-encoder-large/1
> The universal-sentence-encoder-large model is trained with a Transformer encoder.

**Comment by SriniNaga** [comment]
@vbardiovskyg  Thank you!
