### ISSUE TITLE
Semantic similarity from retrained module

### ISSUE THREAD

**Issue by SaulAryehKohn** [tensorflow/hub#165]
I'm trying to understand how to obtain output from a retrained hub module. I used the Universal Sentence Encoder 2 module to provide features for a `tf.estimator.DNNClassifier` object, such that I had:

```
embedded_text_feature_column = hub.text_embedding_column(key="k", module_spec=hub_module,  trainable=True)
clf = tf.estimator.DNNClassifier(...,  feature_columns=[embedded_text_feature_column], ...)
```

Now that I have a retrained embedding, I would love to use it to look at semantic similarities. How would  extract this from my `clf` object? Or does `embedded_text_feature_column` now point to the retrained module?

**Comment by arnoegw** [comment]
Using the module in the Estimator makes it part of that Estimator's model. Using the Estimator normally after training will include the effects of retraining the module. To use the module outside the Estimator that retrained it, you need to
1) call hub.register_module_for_export() from within the Estimator's model_fn,
2) pass a LatestModuleExporter to Estimator eval, as you would normally pass an Exporter for the full model. Once invoked by a successful eval, this will write out the a new module with the retrained weights to the filesystem.
For details, see the docstrings in https://github.com/tensorflow/hub/blob/master/tensorflow_hub/estimator.py
