### ISSUE TITLE
cannot import name 'image_module_info_pb2'

### ISSUE THREAD

**Issue by RickZLLiao** [tensorflow/hub#167]
When i run : python retrain.py --image_dir='G:\work\Other\Band/Data', i got an error : 
cannot import name 'image_module_info_pb2'
File 'image_module_info_pb2' was lost in the github.

**Comment by arnoegw** [comment]
If I may ask, what was the exact workflow that got you there?

The source file image_module_info.proto was added by
https://github.com/tensorflow/hub/commit/acdacbd149c5f45a47e5aa726d8f880d82bcb4cb
Just like other *.proto files (including the most fundamental module_def.proto), it requires running `bazel build ...` to be compiled into a *_pb2.py file.

**Comment by RickZLLiao** [comment]
@arnoegw
Thanks for your reminding. I had  compiled  *.proto to  *_pb2.py file. And I will try it.

**Comment by arnoegw** [comment]
I hope that solves it for you. Please reopen if not.

**Comment by newistar** [comment]
> If I may ask, what was the exact workflow that got you there?
> 
> The source file image_module_info.proto was added by
> [acdacbd](https://github.com/tensorflow/hub/commit/acdacbd149c5f45a47e5aa726d8f880d82bcb4cb)
> Just like other *.proto files (including the most fundamental module_def.proto), it requires running `bazel build ...` to be compiled into a *_pb2.py file.

I am getting this error, while trying Bazel build command on a .proto file

**ERROR: Skipping 'tensorflow_hub/image_module_info.proto': error loading package 'tensorflow/examples/image_retraining/tensorflow_hub': Unable to load package for '//tensorflow_hub:protos.bzl': BUILD file not found on package path**

**Comment by davelet** [comment]
any progress? or how to solve it? I met the issue too:

```python -m retrain.py -h
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/sheldon/pythonProjects/hub/examples/image_retraining/retrain.py", line 132, in <module>
    import tensorflow_hub as hub
  File "/Users/sheldon/pythonProjects/hub/tensorflow_hub/__init__.py", line 32, in <module>
    from tensorflow_hub.feature_column import image_embedding_column
  File "/Users/sheldon/pythonProjects/hub/tensorflow_hub/feature_column.py", line 24, in <module>
    from tensorflow_hub import image_util
  File "/Users/sheldon/pythonProjects/hub/tensorflow_hub/image_util.py", line 21, in <module>
    from tensorflow_hub import image_module_info_pb2
ImportError: cannot import name 'image_module_info_pb2' from 'tensorflow_hub'
```

**Comment by vbardiovskyg** [comment]
I am actually not sure how this is happening. If you have installed tensorflow_hub, the retrain script should be importing from there, so:
`pip install tensorflow_hub --upgrade"

Otherwise you have to make it to import from your working directory and the way to build the files is to use:
`bazel build tensorflow_hub:all` from the top level directory.

(Not `bazel build ...`)
