### ISSUE TITLE
retrain.py : fine tuning after first retrain

### ISSUE THREAD

**Issue by saiaman** [tensorflow/hub#171]
Hello, after some 50k steps, i'd like to "continue" training on same parameters. But if i launch the same code it will start back from 0.
Any ideas ?

**Comment by IamSierraCharlie** [comment]
this might be of use:
https://github.com/tensorflow/hub/issues/37

The idea being that you need to restore from the checkpoint before proceeding with the training

In the retrain.py script, you need to change the following
Original in retrain.py (around line 1015)

`  with tf.Session(graph=graph) as sess:
    # Initialize all weights: for the module to their pretrained values,
    # and for the newly added retraining layer to random initial values.
    init = tf.global_variables_initializer()
    sess.run(init)
`
change to:
`with tf.Session(graph=graph) as sess:
    # Initialize all weights: for the module to their pretrained values,
    # and for the newly added retraining layer to random initial values.
    tf.train.Saver().restore(sess, CHECKPOINT_NAME)
`

I have tested this and the code works, but I haven't run it through to the end to see if there was any improvement.  I'm not sure where the numbers start (i.e. back from zero), but I think what you want is to start training from the last checkpoint saved off, not back at the start again.

Best of luck!

**Comment by hgadig** [comment]
@saiaman  Any update on this ?

**Comment by hgadig** [comment]
Closing this as it is in "awaiting response" status for more than 3 days. Feel free to add comments(if any) and we will reopen. Thanks!

**Comment by anacej** [comment]
are there any updates on this matter?
I was wondering how to continue my traning from my last saved checkpoint? First time I want to train up to 1000 steps and the second time retrain from 1000 to 2000 steps for example.
Thanks in advance!
