### ISSUE TITLE
link to supported modle is nto working ...

### ISSUE THREAD

**Issue by initmahesh** [tensorflow/hub#174]
https://github.com/tensorflow/hub/blob/master/docs/modules/image.md#mobilenet

this link pointed **here** 
"On the other hand, if you intend to deploy your model on mobile devices or other resource-constrained environments, you may want to trade a little accuracy for much smaller file sizes or faster speeds (also in training). For that, try the different **modules** implementing the MobileNet V1 or V2 architectures, or also nasnet_mobile."

**Comment by andresusanopinto** [comment]
Thanks for reporting.

While it gets fixed and upstreamed you can check those modules in:
 https://tfhub.dev/s?keywords=mobilenet

**Comment by arnoegw** [comment]
AFAIU, andresusanopinto's change has fixed this.
