### ISSUE TITLE
Feature request: option to remove the layer at the top of the network

### ISSUE THREAD

**Issue by vmsp** [tensorflow/hub#175]
With Keras I can do this
```python
bottleneck = keras.applications.inception_v3.InceptionV3(include_top=False,
                                                         weights='imagenet')
y = Dense(200, activation='softmax')(bottleneck)
```
Which allows me to remove Inception's classification layer and plug in a top layer of my choice but still use the pre-trained weights on the rest of the network. It would be great if I could do the same thing using hub.

Looking at [retrain.py](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py), you can currently do something similar by plugging in your own layers at the top of the module:
```python
bottleneck = module(x)
y = tf.matmul(W, bottleneck) + b
```
But the first workflow I mentioned doesn't seem to be supported.

**Comment by andresusanopinto** [comment]
Hi @vmsp this is possible todo.

E.g.:
https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1
vs
https://tfhub.dev/google/imagenet/inception_v3/classification/1

All modules that help producing representations from images have been uploaded in two flavors: "classification" and "feature vector". Also all modules have signatures with extra outputs that you can access when passing "as_dict=True".

See documentation about https://www.tensorflow.org/hub/common_signatures/images

**Comment by Queequeg92** [comment]
@andresusanopinto Hi, how do feature extractors handle unused layers? Will the unused layers occupy GPU memory and their parameters be saved in checkpoints?

**Comment by Queequeg92** [comment]
@andresusanopinto Hi, how do feature extractors handle unused layers? Will the unused layers occupy GPU memory and their parameters be saved in checkpoints?
