### ISSUE TITLE
Lose connection with tfhub.dev

### ISSUE THREAD

**Issue by Rosaugo** [tensorflow/hub#176]
Hi,
I faced with problems when learning Image Retraining tutorial at the sentence below
`python retrain.py --image_dir ~/flower_photos`
and my error log seems to indicate a connection problem with tfhub.dev

I've read most of the other issues, but failed to solve this problem

with the sentence curl -L, it did't work either
A timeout error said it also failed to connect to tfhub.dev
Visit [tfhub.dev](url) with google chrome also failed

In Addition, I visit the website [tfhub.dev](url) with my smartphone successfully, safari as the browser

According to the Common Issues,
"cannot verify tfhub.dev's certificate" maybe a right key but I have no idea how to deal with it.

I'm using a nearly-new laptop with only a little software such as google chrome browser and python ide jupyter notebook

Is this a problem with server or domain or only my laptop?
I want to know why does it happen and how I can deal with it?

THANKYOU

**Comment by andresusanopinto** [comment]
Hi Rosaugo,

There is no problem with the server. This is an issue with your machine/network. You will need to debug dns resolution.

PS: If you have not seen it yet, you might want to read https://github.com/tensorflow/hub/blob/master/docs/common_issues.md

**Comment by Rosaugo** [comment]
> Hi Rosaugo,
> 
> There is no problem with the server. This is an issue with your machine/network. You will need to debug dns resolution.
> 
> PS: If you have not seen it yet, you might want to read https://github.com/tensorflow/hub/blob/master/docs/common_issues.md

Thanks for you reply, I have completed the tutorial successfully.
The error log didn't appear when I tried the same  sentence this afternoon.
Though I can't recognize what happened and what's the matter yesterday, I'm going on with my work.
For other users facing with the same problem, all I can recommend is to restart your computer, that's how my problem solved.
Thanks again for replying my issue.
