### ISSUE TITLE
Moblenet V2: Importing graph with lower producer version into a graph with higher producer version

### ISSUE THREAD

**Issue by danhamill** [tensorflow/hub#180]
I developing a transfer learning application where I am retraining MobileNetV2 for my data stream.

I am retraining the model with [retrain.py](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py) from tensorflow-hub and have made no modifications.  

When I run the script from a terminal, I get this warning directly after the model is downloaded to a temporary directory in my user profile.

    Importing a graph with a lower producer version 26 into an existing graph with producer 
    version 27. Shape inference will have run different parts of the graph with different 
    producer versions.

During my debugging efforts, I created a `test.py` script to find out where the warning is coming from:

    import tensorflow as tf
    import tensorflow_hub as hub
    
    def create_module_graph(module_spec):
      """Creates a graph and loads Hub Module into it.
    
      Args:
        module_spec: the hub.ModuleSpec for the image module being used.
    
      Returns:
        graph: the tf.Graph that was created.
        bottleneck_tensor: the bottleneck values output by the module.
        resized_input_tensor: the input images, resized as expected by the module.
        wants_quantization: a boolean, whether the module has been instrumented
          with fake quantization ops.
      """
      FAKE_QUANT_OPS = ('FakeQuantWithMinMaxVars',
                         'FakeQuantWithMinMaxVarsPerChannel')
      height, width = hub.get_expected_image_size(module_spec)
      with tf.Graph().as_default() as graph:
        resized_input_tensor = tf.placeholder(tf.float32, [None, height, width, 3])
        m = hub.Module(module_spec)
        bottleneck_tensor = m(resized_input_tensor)
        wants_quantization = any(node.op in FAKE_QUANT_OPS
                                 for node in graph.as_graph_def().node)
      return graph, bottleneck_tensor, resized_input_tensor, wants_quantization
    
    
    def main():
    
       
       
       module_spec = hub.load_module_spec('https://tfhub.dev/google/imagenet/mobilenet_v2_100_96/classification/2')
       
       graph, bottleneck_tensor, resized_input_tensor, wants_quantization = create_module_graph(module_spec)
    
    
    
    if __name__ =='__main__':
       main()

And found it originated from the `create_module_graph` function in `retrain.py`.  When I run the script from the terminal using `python test.py`, I get producer warning from above.  However, when I run `main()` from an ipython console I do not get the producer version warnings.  

What do these warnings mean?

My tensorflow info:
```
# packages in environment at C:\Anaconda3\envs\dl_tools:
#
# Name                    Version                   Build  Channel
tensorflow-gpu            1.11.0                    <pip>
tensorflow-hub            0.1.1                     <pip>
```

**Comment by Builtor** [comment]
i have the same question

**Comment by arnoegw** [comment]
Hi, danhamill and Builtor, thanks for reaching out.

TensorFlow Hub modules contain tf.GraphDefs at the core, and these have a format version number to help with correctly importing graphs into newer versions of TensorFlow. It so happened that this format version was bumped from 26 to 27 between the upload of TF-Hub modules for the public launch on 31 March 2018 and the current TensorFlow release.

However, we are currently not aware of any visible effect on module users from the reported change in shape inference, so our current recommendation is to ignore these warnings. They will go away with the 
next refresh of modules.

Please speak up if you do experience an actual problem in using them. -- I'm keeping this bug open for that.

Thank you
arnoegw

**Comment by danhamill** [comment]
Thanks for the information @arnoegw.  I haven't had any problems, but will report back if I do.

**Comment by hgadig** [comment]
@danhamill  Any update on this ? If you haven't faced any issues(till date), please do let us know. We will close this issue. Thanks !

**Comment by danhamill** [comment]
No Updates.  Considered this issue closed.

**Comment by tyadav** [comment]
I am getting this same issue:

tensorflow/core/graph/graph_constructor.cc:1248] Importing a graph with a lower producer version 22 into an existing graph with producer version 26. Shape inference will have run different parts of the graph with different producer versions.
