### ISSUE TITLE
occurs error when integrating tensorflow hub mode of ELMO into my graph

### ISSUE THREAD

**Issue by zjh-nudger** [tensorflow/hub#183]
the core information:
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'inference/module_apply_tokens/map/while/Merge' has inputs from different frames. The input 'inference/module_apply_tokens/map/while/Enter' is in frame 'inference/module_apply_tokens/map/while/while_context'. The input 'global_step/add' is in frame ''.

how can I solve it. thanks

**Comment by arnoegw** [comment]
Can you share some details on how you use the module? In particular, do you use it from inside a tf.cond, tf.while, or tf.Dataset.map?

**Comment by zjh-nudger** [comment]
> Can you share some details on how you use the module? In particular, do you use it from inside a tf.cond, tf.while, or tf.Dataset.map?

yeah, I use it from tf.Datasest.map where I use estimator api to train the model

**Comment by arnoegw** [comment]
Using a module from within Dataset.map() does not work at this time (issue https://github.com/tensorflow/hub/issues/140). I am sorry to not have a better answer.
