### ISSUE TITLE
BERT embeddings as tensorflow hub module 

### ISSUE THREAD

**Issue by r-wheeler** [tensorflow/hub#187]
Are there any plans to convert the BERT [checkpoints](https://github.com/google-research/bert) into a tensorflow hub module? Would be great to be able to get word vectors similar to elmo for further downstream tasks.

**Comment by akhorlin** [comment]
We are working with the authors of BERT to explore making it available as a
TF Hub module. Once there is something concrete we will update the thread.

**Comment by r-wheeler** [comment]
Sounds good, thanks for the update.

**Comment by alberduris** [comment]
Sounds really promising. Subscribed!

**Comment by akhorlin** [comment]
BERT modules have been published on tfhub.dev: https://tfhub.dev/s?q=bert
