### ISSUE TITLE
TF HUB with Custom Estimator for Text Classification

### ISSUE THREAD

**Issue by bjayakumar** [tensorflow/hub#191]
I could not find a single example where TF HUB is used with the custom estimator for Text Classification. Can you please provide an example?

**Comment by akhorlin** [comment]
Are looking for an example of publishing a module from the estimator or
consuming a module?

**Comment by bjayakumar** [comment]
Cosuming a module. For example, I like to ELMo with the custom estimator, not with the canned estimator.

**Comment by akhorlin** [comment]
Does your custom estimator accept feature columns? If yes, you could try
using
https://www.tensorflow.org/hub/api_docs/python/hub/text_embedding_column.
