### ISSUE TITLE
transfer learning sample does not work in Python3

### ISSUE THREAD

**Issue by martin-gorner** [tensorflow/hub#195]
https://github.com/tensorflow/hub/blob/master/examples/colab/image_feature_vector.ipynb

Steps to reproduce:

Open the notebook in Colab
Select a Python 3 backend
Run the first few cells

> ModuleNotFoundError: No module named 'StringIO'

**Comment by akshoop** [comment]
@martin-gorner 
You're absolutely right, I just came across this Colab notebook sample and decided to try it for myself. I came across a few bugs. Here are the exact errors that I discovered. The github repo notebook should get updated:

-  In the library import code cell, `from StringIO import StringIO` ==> `from io import BytesIO`
- In the downloading flowers dataset code cell, `examples = zip(full_filenames, [label_class] * len(filenames))` ==> `examples = list(zip(full_filenames, [label_class] * len(filenames)))`
- In the exploring data code cell, `return plt.imread(StringIO(get_encoded_image(example)), format='jpg')` ==> `return plt.imread(BytesIO(get_encoded_image(example)), format='jpg')`
- Finally, in the confusion matrix code cell, `axis_labels = CLASSES.values()` ==> `axis_labels = list(CLASSES.values())`

Once you make the above Python3 code changes in your own Colab notebook running this Transfer Learning sample, you should get the expected results. Good luck 👍

**Comment by vbardiovskyg** [comment]
Hi Martin and Alex,

thanks for reporting and for further elaborating.

We are not planning to make changes to colabs to make them both Python 2 & Python 3 compatible for now. Obviously we would welcome such changes if somebody feels strong about this :)
