### ISSUE TITLE
ELMo small model

### ISSUE THREAD

**Issue by schmidek** [tensorflow/hub#196]
tfhub has a single module for ELMo, which I assume is based on the original pretrained model from https://allennlp.org/elmo.

It would be nice to be able to use the small and medium pretrained models as well. 

Is there any documentation or code available to build the ELMo module so we can use those other pretrained models?

**Comment by vbardiovskyg** [comment]
Treating this as a module request as I am not aware of any code or documentation that you could use to train your own modules.

**Comment by Nimishkhurana** [comment]
Hello @vbardiovskyg  @hgadig I would like to work on this as part of GSoC under the project `TensorFlow Hub Module Creation and Support for TensorFlow.js`

**Comment by vbardiovskyg** [comment]
Hi Nimish, I saw your proposal on the GSoC page, we can move the discussion there.

**Comment by Nimishkhurana** [comment]
Ok @vbardiovskyg sure.

**Comment by Nimishkhurana** [comment]
@vbardiovskyg Please comment on the proposal draft. I have recommended new models to be added, but I also have few other in my mind. We can discuss this. Waiting for your feedback.
