### ISSUE TITLE
export model with raw jpeg as input layer on image classifier

### ISSUE THREAD

**Issue by rola93** [tensorflow/hub#198]
I have trained a model for image classification with the [retrain module](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py), then I exported it and serve it on tensorflowServing.

However, the served model is expecting as input a tensor with four dimensions (batch size, height, width, channel) instead of a raw jpeg binary string (it was the case for previous version of this script.).

As far a I understand, to process an image there are two steps, which are very clear on the `run_bottleneck_on_image` method:

```python
def run_bottleneck_on_image(sess, image_data, image_data_tensor,
                            decoded_image_tensor, resized_input_tensor,
                            bottleneck_tensor):
  """Runs inference on an image to extract the 'bottleneck' summary layer.

  Args:
    sess: Current active TensorFlow Session.
    image_data: String of raw JPEG data.
    image_data_tensor: Input data layer in the graph.
    decoded_image_tensor: Output of initial image resizing and preprocessing.
    resized_input_tensor: The input node of the recognition graph.
    bottleneck_tensor: Layer before the final softmax.

  Returns:
    Numpy array of bottleneck values.
  """
  # First decode the JPEG image, resize it, and rescale the pixel values.
  resized_input_values = sess.run(decoded_image_tensor,
                                  {image_data_tensor: image_data})
  # Then run it through the recognition network.
  bottleneck_values = sess.run(bottleneck_tensor,
                               {resized_input_tensor: resized_input_values})
  bottleneck_values = np.squeeze(bottleneck_values)
  return bottleneck_values

```

`resized_input_values` is the line were the raw JPEG string is decoded as a matrix and resized to an standard size, them the next line run it througth the network to get the bottleneck values. This second part is the one that is currently being exported (not exactly _this_ because it also has the last layer with its learned weigths). 

What I'd like to do is to export the complete network: from the raw JPEG string to the learn predictions.

The export_model method does not takes into account  the jpeg decoder/resizer even as a parameter to it:

```python
def export_model(module_spec, class_count, saved_model_dir):
  """Exports model for serving.

  Args:
    module_spec: The hub.ModuleSpec for the image module being used.
    class_count: The number of classes.
    saved_model_dir: Directory in which to save exported model and variables.
  """
```

I'd like to send raw JPEG data to the tensorflowServing since it makes the client independent of the architecture used to train the model, just send a JPEG raw string and get back a prediction. I I send the image decoded/resized, I have to take care of the model that is being served which input is expecting to send it properly.

It'd be awesome to have this feature! or at least if you can tell me how to code it.

**Comment by arnoegw** [comment]
Hi rola93, thanks for your interest in TensorFlow Hub. I'd encourage you to try coding this yourself; you have all the ingredients on the table. (retrain,py itself is complex enough, I'd much prefer to not squeeze more things into it.)

As you can see from the code, export_model() gets called at the very end when a trained checkpoint of the full model (incorporating the weights from the  Hub module) has been written to disk. You can build any graph you like as long as the weights (variables) you use can be restored from that checkpoint.

**Comment by nanshihui** [comment]
any volunteer?

**Comment by chrisdee8** [comment]
Hi nanshishui, I struggled with this same problem for too long. I wanted to use a jpeg image to make a prediction using the saved model. My answer is in two parts.
1. The input to the graph is not jpeg_data_tensor. If you read the code you will see this tensor is used to convert images to a resized tensor. This resized tensor is the input to the graph. Try this
tf.saved_model.simple_save(sess, Model_path, 
            #inputs={"input": graph.get_tensor_by_name('input:0')}, # I think this works as well
            inputs={"input": resized_image_tensor},                 
            outputs={"final_result": final_tensor})

If you use the command line tool you should see the input now has shape (1,224,224,3) (224 for MobileNet) e.g.
!saved_model_cli show --dir "{Model_path}" --all

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 224, 224, 3)
        name: input:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['final_result'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 2)
        name: final_result:0
  Method name is: tensorflow/serving/predict


2. Having now deployed the saved model you have to modify your request for a list.
In the following code I use the helper function to read a tensor of shape (1,224,224,3) from my image file. I then convert it to a list and then pass the list in a json instance to my tensorflow serving docker.
im = read_tensor_from_image_file(file_name,
                              input_height=input_height,
                              input_width=input_width,
                              input_mean=input_mean,
                              input_std=input_std)
instance = im.tolist()

import json
data = json.dumps({"instances": instance})
print(data[:60] + " ... " + data[-10:])
print("json length:"+str(len(data)))

import requests
import numpy as np
BASE_URL = 'http://172.17.0.1:8501/v1/models/smoke:predict'   # docker IP
content_type = 'application/json'
tfs_headers ={'Content-Type': content_type}

json_response = requests.post(BASE_URL, data=data, headers=tfs_headers)
print(json_response)
predictions = np.array(json.loads(json_response.text)["predictions"])
print(predictions)

The output I get
<Response [200]>
[[0. 1.]]

**Comment by nanshihui** [comment]
@chrisdee8  finally, i combine to model  , and achieve model with raw jpeg as input layer on image classifier
