### ISSUE TITLE
Running inference gives different results for two runs of the same image scene

### ISSUE THREAD

**Issue by agshift** [tensorflow/hub#204]
Hi,
I trained my network using retrain.py and used resnet-50.
Next, I ported the model to serving and ran inference.
Strangely, if I run the inference multiple times on the same image scene (no change in the scene, except may be a little lighting variation), I see the results starkly different. And the scores are very different too. Has anyone faced the similar issue? Any suggestion would be really helpful.
Thanks,
Amit

**Comment by andresusanopinto** [comment]
If I read your report correct, applying your model is deterministic [if not, it sounds like there is a bug somewhere].

So this is not a about an issue with tensorflow hub, but with ML in general.
