### ISSUE TITLE
TensorFlow Hub caching model - permission denied when loading

### ISSUE THREAD

**Issue by timpal0l** [tensorflow/hub#206]
I am trying to save a TensorFlow Module to disk to avoid downloading it for every use.

I read about caching modules here: https://www.tensorflow.org/hub/basics

```
$ export TFHUB_CACHE_DIR=/tf_models
$ echo $TFHUB_CACHE_DIR
/tf_models
```

So the environment variable is set, I also added it to .bashrc, and reloaded .bashrc with `source`.

In python:

```
import tensorflow_hub as hub
embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/2")


~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

PermissionDeniedError: /tf_models; Permission denied
```

I can run the hub modules fine when TFHUB_CACHE_DIR is default.

Why do I get permission denied?

**Comment by akhorlin** [comment]
It looks like you don't have permission to write to the directory in
question. You could validate this assumption by doing "mkdir /tf_models &&
touch /tf_models/test".

**Comment by timpal0l** [comment]
That's funny! I have permission when removing the slash sign such as `mkdir tf_models && touch tf_models/test` so its solved.
