### ISSUE TITLE
Preprocessing in Universal Sentence Encoder

### ISSUE THREAD

**Issue by apiro** [tensorflow/hub#209]
Hi, 

Playing around with USE, https://tfhub.dev/google/universal-sentence-encoder/2, I was wondering if the data fed to the embed function is supposed to be already preprocessed ( meaning lowercased, punctuation splitted, bla, bla ) or if the module performs a special preprocessing by itself.

Thank you,

Alberto

**Comment by vbardiovskyg** [comment]
Hi,

from the author:
"There is no preprocess requirement for current USE/2 model. We hope the user can just use it as is. 
The only model we require preprocessing is the Lite model, which is documented in the Lite module page."

I will also update the documentation to be clear about it.
