### ISSUE TITLE
Wrong sampling procedure for BigGAN

### ISSUE THREAD

**Issue by MarcosPividori** [tensorflow/hub#214]
Hi,
For modules: `biggan-128`, `biggan-256` and `biggan-512`, the "example use" code seems to implement something different to the truncation trick described in the original paper: [Large Scale GAN Training for High Fidelity Natural Image Synthesis](https://arxiv.org/abs/1809.11096).
In the paper, the truncation trick is described as: "... sampling z from a truncated normal (where values which fall outside a range are resampled to fall inside that range) ... "
However, the "example use" in [TensorflowHub](https://tfhub.dev/deepmind/biggan-128/20) samples from a truncated normal in `[-2, 2]` and then scales the values to `[-2*truncation, 2*truncation]`. This results in a different distribution than directly sampling from a truncated normal in `[-2*truncation, 2*truncation]`.

Example use from [biggan-128](https://tfhub.dev/deepmind/biggan-128/20):
```python
batch_size = 8
truncation = 0.5  # scalar truncation value in [0.02, 1.0]
z = truncation * tf.random.truncated_normal([batch_size, 120])  # noise sample
```

Instead, I propose that it is modified to use `tfp.distributions.TruncatedNormal`:
```python
batch_size = 8
truncation = 0.5  # scalar truncation value in [0.02, 1.0]
trunc_normal = tfp.distributions.TruncatedNormal(loc=0., scale=1., low=-2*truncation, high=2*truncation)
z = trunc_normal.sample([batch_size, 120])  # noise sample
```

This graphic shows the difference between both distributions (truncation=0.5):
![truncation](https://user-images.githubusercontent.com/4282009/50479968-012efd80-09b8-11e9-88fd-d46380cff14d.png)

**Comment by MarcosPividori** [comment]
@ajbrock

**Comment by andresusanopinto** [comment]
This is WAI -- it uses [truncated_normal](https://www.tensorflow.org/api_docs/python/tf/random/truncated_normal) which always truncates between [-2,2] stdevs, and vary the stdev (same as multiplying by the stdev with stdev fixed to 1).

**Comment by MarcosPividori** [comment]
Hi @andresusanopinto ,

Sampling from a truncated normal in [-2 * stdev, 2 * stdev] is not the same than sampling from a truncated normal in [-2, 2] and then multiplying by a scalar.

You can generate the graphic that I have included with this script:

```python
import matplotlib.pyplot as plt 
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp 

fig, ax = plt.subplots(1, 1)

batch_size = 10000
truncation = 0.5  # scalar truncation value in [0.02, 1.0]
z_dim = 120 

# Example use from biggan-128:
z1 = truncation * tf.random.truncated_normal([batch_size, z_dim])  # noise sample

# Instead,I propose that it is modified to use tfp.distributions.TruncatedNormal
trunc_normal = tfp.distributions.TruncatedNormal(\
    loc=0., scale=1., low=-2*truncation, high=2*truncation)
z2 = trunc_normal.sample([batch_size, z_dim])  # noise sample

with tf.Session() as sess:
  sample1, sample2 = sess.run([z1, z2])

ax.hist(sample1.reshape(-1), bins=30, alpha=0.5)
ax.hist(sample2.reshape(-1), bins=30, alpha=0.5)

plt.show()
```

**Comment by MarcosPividori** [comment]
"(same as multiplying by the stdev with stdev fixed to 1)" is not right.
