### ISSUE TITLE
ELMo module request (Provide all three word representations as an output option)

### ISSUE THREAD

**Issue by iliaschalkidis** [tensorflow/hub#216]
Hi,

I would suggest providing all three word representations [word_emb, lstm_outputs1, lstm_outputs2] as a single 4D ([batch_size, max_length, 3, 1024]) output option. In order to get a similar result, someone needs to run the module 3x times, one for each of the available options ([word_emb, lstm_outputs1, lstm_outputs2]), while all these are computed anyway in every single run, so it is a waste of both time and computations.

Thanx!

**Comment by vbardiovskyg** [comment]
Hi Ilias,

thanks for the suggestion! Please note however that if you run ```sess.run([word_emb, lstm_outputs1, lstm_outputs2])```, the graph is evaluated only once for that call, so there is no waste of computation.

For example you could write something like this:
```python
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
tokens_input = [["the", "cat", "is", "on", "the", "mat"], ["dogs", "are", "in", "the", "fog", ""]]
tokens_length = [6, 5]
embeddings = elmo(
  inputs={
    "tokens": tokens_input,
    "sequence_len": tokens_length
  },
signature="tokens",
as_dict=True)

word_emb = embeddings["word_emb"]
lstm_outputs1 = embeddings["lstm_outputs1"]
lstm_outputs2 = embeddings["lstm_outputs2"]

...

sess.run([word_emb, lstm_outputs1, lstm_outputs2]) 
```

In the above example, module is applied only once (so there is only one full graph) and the session call runs everything at the same time.

**Comment by andresusanopinto** [comment]
The answer above from vbardiovskyg is correct. You can just use all the outputs from the first call.
