### ISSUE TITLE
ELMo in other languages (Spanish)

### ISSUE THREAD

**Issue by alberduris** [tensorflow/hub#218]
ELMo module is available in English.

There are text embedding modules in other languages (basically NNLM in Spanish, German, Chinesse...)

It would be great if we could have ELMo in Spanish and other languages (like [ELMoForManyLangs](https://github.com/HIT-SCIR/ELMoForManyLangs))

**Comment by vbardiovskyg** [comment]
Keeping open as a module request.

**Comment by alberduris** [comment]
Many thanks!

**Comment by captain-pool** [comment]
@vbardiovskyg , Is it okay, if I work on this issue? or is there someone else working on this already?

**Comment by vbardiovskyg** [comment]
Hi Adrish, thanks for the application, we can move the discussion there.

**Comment by captain-pool** [comment]
Hi @vbardiovskyg Thanks for the reply. 
Is it about GSOC proposal?
Where should we move the discussion to?

**Comment by vbardiovskyg** [comment]
Hi Adrish, I meant the GSoC proposal, but I see now that it is not about ELMo. Sorry for confusion.

I don't think anybody is working on this at the moment, so feel free to do so :)

**Comment by captain-pool** [comment]
> Hi Adrish, I meant the GSoC proposal, but I see now that it is not about ELMo. Sorry for confusion.
> 
> I don't think anybody is working on this at the moment, so feel free to do so :)

Hi @vbardiovskyg thanks for the reply. About the GSOC proposal, can you please drop your valuable reviews? Around 10 Hours is left for final submission.

**Comment by captain-pool** [comment]
@vbardiovskyg , I'm trying to export the ELMo Graph from torch to ONNX and Then form a TF Graph from it. However, torch.onnx.export says
`ONNX export failed: Couldn't export operator aten::sort`.
According to Pytorch, There's no support for aten::sort, right now. (https://github.com/pytorch/pytorch/issues/17519#issuecomment-471638973)
 Can you suggest some work around?

**Comment by vbardiovskyg** [comment]
Hi Adrish, I don't actually have much experience with exporting Pytorch models to ONNX.

If I understand correctly, on the path Pytorch -> ONNX -> TensorFlow, this fails on the first step? Then it would be a question for the ONNX exporting tool project.

A very general answer would be: could you try to understand why that operator is used in the model and whether it could be replaced by something else or dropped? Not sure why one would depend on sorting.

**Comment by j-grimstad** [comment]
Hi @alberduris  - if you haven't seen this already, we've added many text embedding models in different languages over the years since this comment was left (although ELMo is not one of them) -- you can take a look here & use the left hand filter to select for the languages you'd like: https://tfhub.dev/s?subtype=module,placeholder
