### ISSUE TITLE
Custom Universal Sentence Encoder (USE) corpus

### ISSUE THREAD

**Issue by richardonichol** [tensorflow/hub#219]
How can I train a USE module unsupervised on my own database of 11 million job ads to generate reusable sentence embeddings? This is quite simple to do with FastText for word embeddings but I don't see a way to do this for USE without trying to recreate the steps from the original paper.

**Comment by vbardiovskyg** [comment]
Hi Richard,

please refer to https://github.com/tensorflow/hub/issues/155 for training from scratch,

and to https://github.com/tensorflow/hub/issues/46 for fine-tuning.
