### ISSUE TITLE
"Illegal instruction" when importing

### ISSUE THREAD

**Issue by theCalcaholic** [tensorflow/hub#22]
When importing tensorflow_hub python crashes with `Illegal instruction`. No stack trace is given.
. I installed both tensorflow-gpu and tensorflow-hub via pip.

* python version: 3.5.2
* tensorflow version: tensorflow-gpu 1.7.0
* tensorflow_hub version: 0.1.0
* cuda version: 9.0
* cudnn version: 7.0.5
* OS: Ubuntu 16.04 "xenial" x86_64
* CPU: Intel i5 750

**Comment by andresusanopinto** [comment]
This seems to be an issue with tensorflow. I guess the same error happens when you run:

```shell
$ python3 -c "import tensorflow"
```
A quick search pointed to: https://github.com/tensorflow/tensorflow/issues/17411

**Comment by theCalcaholic** [comment]
No it doesn't. I'm using tensor flow (without tensorflow hub) for the same project.

This error only occurs when importing `tensorflow_hub`.

**Comment by andresusanopinto** [comment]
tensorflow_hub is a pure python pip package (with dependencies on non-pure python packages), so I am clueless on what is going on that is specific to "import tensorflow_hub" :/

What is the output of:
```
$ pip2 show tensorflow tensorflow-gpu tf-nightly tensorflow-hub
$ python2 -c "import tensorflow"
$ python2 -c "import tensorflow_hub"

$ pip3 show tensorflow tensorflow-gpu tf-nightly tensorflow-hub
$ python3 -c "import tensorflow"
$ python3 -c "import tensorflow_hub"
```

**Comment by theCalcaholic** [comment]
I'm so sorry, you were right. The error **does** appear even when only importing tensorflow. I did recently update to tensorflow 1.7 (which I had been testing, but not on the same machine) and didn't run the program ever since. The problem certainly has to do with tensorflow>=1.6 expecting CPU features (AVX) which this machine's CPU does not provide.

Sorry for wasting your time.
