### ISSUE TITLE
Question: Retarin.py: Is the final test accuracy shown after training image data set is of top-1 accuracy or top-5 accuracy

### ISSUE THREAD

**Issue by tunicashashi** [tensorflow/hub#220]
Is the final test accuracy which is printed in the screen after training of image data using retrain.py for image classification based on top-1 accuracy?

**Comment by vbardiovskyg** [comment]
Seems like top-1: https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py#L819
