### ISSUE TITLE
TF-hub BIG-GAN example generation script does not work in local jupyter.

### ISSUE THREAD

**Issue by rishabh135** [tensorflow/hub#223]
**System Information**
OS : Ubuntu 16.04
TF version : 1.9.0-rc2 (GPU)
tensorflow-gpu            1.9.0rc2             <pip>                                                                        
tensorflow-hub            0.2.0                <pip>
CUDA version : release 9.0, V9.0.176  
Local Environment :  jupyterlab                0.32.1                   py36_0    conda-forge 
Python version  : Python 3.6.5  inside Anaconda, Inc.

**Code used for reproduction of the error **
The script use for the [Colab](https://colab.research.google.com/github/zaidalyafeai/Notebooks/blob/master/BigGanEx.ipynb#scrollTo=h7tClPCnDCFQ)

**The current behaviour**
Error Generated : 
```
tensorflow/core/framework/tensor_shape.cc:44] Check failed: NDIMS == dims() (2 vs. 3)Asking for tensor of 2 dimensions from a tensor of 3 dimensions
```
The error is replicated even in the case when it is run as a python script

**Expected Behaviour **
The example works perfectly in colab and generated an image of the spaniel 

**Other info**
The same code generates error in the local jupyter-lab setup with TF 1.9 and 1.10 (could not confirm whether it works with local jupyter-lab setup with TF 1.12)
 
The error message is also not very enlightening and it would help tremendously more if it was more transparent as we are essentially dealing with a black box model (w.r.t tf-hub).

@ajbrock @lamberta

**Comment by lamberta** [comment]
@MarkDaoust

**Comment by MarkDaoust** [comment]
Hi @rishabh135, 

Sorry, I don't think we can help you on this one.

BigGan was launched in October, TF1.9 in july.

There are no backwards compatibility guarantees for these notebooks.

Please try again with a more recent TensorFlow version.
