### ISSUE TITLE
error when loading a frozen biggan model

### ISSUE THREAD

**Issue by eyaler** [tensorflow/hub#224]
error message
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node import/module_apply_default/cond/AssignVariableOp/Switch was passed float from import/module/prev_truncation:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/python/biggan/optimize_model.py", line 18, in <module>
    tf.import_graph_def(gd)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node import/module_apply_default/cond/AssignVariableOp/Switch was passed float from import/module/prev_truncation:0 incompatible with expected resource.

Process finished with exit code 1
```

code to recreate
```
import tensorflow as tf
import tensorflow_hub as hub
import os

with tf.Session() as sess:
    module = hub.Module('https://tfhub.dev/deepmind/biggan-128/2')
    sess.run(tf.global_variables_initializer())
    inputs = {k: tf.placeholder(v.dtype, v.get_shape().as_list(), k) for k, v in module.get_input_info_dict().items()}
    output = module(inputs)
    converted_graph_def = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, [output.name.replace(':0','')])
    tf.train.write_graph(converted_graph_def, 'c:/temp/saved1', 'frozen_model.pb', as_text=False)

tf.reset_default_graph()
with tf.Session() as sess:
    with tf.gfile.GFile(os.path.join('c:/temp/saved1', 'frozen_model.pb'), 'rb') as f:
        gd = sess.graph_def
        gd.ParseFromString(f.read())
        tf.import_graph_def(gd)
```
it works fine for other modules. the advice here did not help either: https://github.com/tensorflow/tensorflow/issues/3628

**Comment by hgadig** [comment]
@eyaler  Please provide the exacts steps you followed and a sample code snippet to reproduce the error. This would help to look into the issue and understand it clearly.

**Comment by vbardiovskyg** [comment]
Hi, this seems like an issue of tf.graph_util.convert_variables_to_constants.

It is producing a GraphDef that cannot be loaded back, the reason seems to be that the switch statement expects a variable, not a constant.

Please try to find a corresponding issue here: https://github.com/tensorflow/tensorflow/issues?utf8=%E2%9C%93&q=convert_variables_to_constants+

If you don't find the same, you can either use https://github.com/tensorflow/tensorflow/issues/25721 or file a new one.

**Comment by eyaler** [comment]
@hgadig provided above

**Comment by arnoegw** [comment]
@eyaler: I share vbardiovskyg's view that this looks like a problem with processing the graph in tf.graph_util.convert_variables_to_constants(), not an issue with TF Hub and how it helps build the graph. Can this be closed for tensorflow/hub?

**Comment by eyaler** [comment]
cannot the switch statement be changed to something that is compatible with current tf.graph_util.convert_variables_to_constants() ?

**Comment by arnoegw** [comment]
With all due respect, I think that is an issue in core TF and its convert_variables_to_constants, not TF Hub.
