### ISSUE TITLE
Error on inference of retrained model

### ISSUE THREAD

**Issue by nvidiarox000** [tensorflow/hub#226]
**System Information**
OS : Ubuntu 16.04
TF version : 1.5.0 (GPU)
Tensorflow-hub : 0.2.0 
CUDA version : release 9.0
Cudnn version : 7.0.5
Python version : Python 3.5.2

I have retrained the mobilenet v1 model on my custom dataset using the `retrain.py` file by passing the default parameters. I was able to generate the `output_graph.pb` after the training. But when I tried to visualize the result on a test image using the `label_image.py` file, I got this error which I have mentioned below. I tried to generate graphs for mobilenet v2 and inception v3 too. But I'm facing the same error. The command I used is:

`python3 label_image.py --graph=/home/../output_graph_ssdv1.pb --labels=/home/../output_label.txt --input_layer=Placeholder --output_layer=final_result --image=/home/../test.jpg`

The error is get is this:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Error while reading resource variable module/MobilenetV1/Conv2d_0/weights from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/module/MobilenetV1/Conv2d_0/weights)
	 [[Node: import/module_apply_default/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](import/module/MobilenetV1/Conv2d_0/weights)]]`
	 [[Node: import/module_apply_default/hub_output/feature_vector/SpatialSqueeze/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_359_import/module_apply_default/hub_output/feature_vector/SpatialSqueeze", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "label_image.py", line 133, in <module>
    input_operation.outputs[0]: t
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Error while reading resource variable module/MobilenetV1/Conv2d_0/weights from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/module/MobilenetV1/Conv2d_0/weights)
	 [[Node: import/module_apply_default/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](import/module/MobilenetV1/Conv2d_0/weights)]]
	 [[Node: import/module_apply_default/hub_output/feature_vector/SpatialSqueeze/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_359_import/module_apply_default/hub_output/feature_vector/SpatialSqueeze", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`

Caused by op 'import/module_apply_default/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D/ReadVariableOp', defined at:
`  File "label_image.py", line 118, in <module>
    graph = load_graph(model_file)
  File "label_image.py", line 33, in load_graph
    tf.import_graph_def(graph_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 554, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access`

`NotFoundError (see above for traceback): Error while reading resource variable module/MobilenetV1/Conv2d_0/weights from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/module/MobilenetV1/Conv2d_0/weights)
	 [[Node: import/module_apply_default/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](import/module/MobilenetV1/Conv2d_0/weights)]]
	 [[Node: import/module_apply_default/hub_output/feature_vector/SpatialSqueeze/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_359_import/module_apply_default/hub_output/feature_vector/SpatialSqueeze", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`

**Comment by vbardiovskyg** [comment]
Running `sess.run(tf.global_variables_initializer())` before trying to compute the output should fix this.

@arnoegw: retrain.py is producing a graph with Hub module inlined. Is it possible to add tf.global_variables_initializer inside the graph somehow so that it is always run (and is made compatible with label_image.py out of the box)?

**Comment by arnoegw** [comment]
@nvidiarox000: Are you really using TensorFlow 1.5 (one dot five)? That is super-old, and may have problems converting the ResourceVariables found in Hub modules to constants when creating the "frozen" output_graph.pb.

Even at launch a year ago, TF Hub has required TF1.7 or newer. The current release is TF1.13.1. Hub no longer has an explicit version check for the underlying TF library, but please try a recent one.

**Comment by hgadig** [comment]
Closing as it is in "awaiting response" for more than 7 days. Feel free to add your comments and we will reopen. Thanks!
