### ISSUE TITLE
Is there any way to get bounding boxes from the Image Retraining?

### ISSUE THREAD

**Issue by mayankmehtani** [tensorflow/hub#228]
Hi I'm trying to also get the bounding objects for the detected class in the image, is there any way to do this?

**Comment by arnoegw** [comment]
Not with retrain.py and modules for image feature vectors, but you might want to take a look at https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1
https://tfhub.dev/google/faster_rcnn/openimages_v4/inception_resnet_v2/1
