### ISSUE TITLE
Universal Sentence Encoder (USE) - Calculating similarity

### ISSUE THREAD

**Issue by Sathibhu** [tensorflow/hub#229]
Can the dot product of sentence embedding vectors (cosine similarity) from USE be negative value? If yes, I would like to have two sample sentences which can show case that.

**Comment by Sathibhu** [comment]
Yeah, the sentence similarity scores from USE can be negative. As per USE paper, it makes sense to take angular distance of cosine similarity to make the value between 0 & 1.

Sample sentences: 
sent1: I don't know, we'll see.
sent2: Do you recall Mr. Robinsons Neighborhood commercials and his version of the Pump shoe?

score: -0.16182984
module: USE large encoder 3

**Comment by gknor** [comment]
Do you have any idea why the similarity distribution (based on cosine metric) is not uniform? I mean, it is hard to find examples with negative cosine similarity value. It suggest that USE vectors do not cover the whole space, an I wonder why?
