### ISSUE TITLE
GloVe + Elmo

### ISSUE THREAD

**Issue by sunipa** [tensorflow/hub#231]
Hi!
Is there a way I can use the GloVe embeddings in the bottom layer instead of the character gram based embeddings. There was a mention of this in the paper but I have not been able to find a way to do it in the tutorial or code yet.

Thanks!

**Comment by vbardiovskyg** [comment]
Hi Sunipa,

the only API to the modules is described by the signatures.

If you'd just like to use Glove embeddings in TF-Hub, it should be easy to create a module using https://github.com/tensorflow/hub/blob/master/examples/text_embeddings/export.py by pointing to a [pre-trained Glove vector file](https://nlp.stanford.edu/projects/glove/). Of course these will not be fine-tuned as they are in the Elmo training.

**Comment by anbasile** [comment]
This solution work, but setting `trainable=True` results in a crash. @vbardiovskyg do you have any info about this?

**Comment by vbardiovskyg** [comment]
Hi,

what kind of crash was that? I.e. can you please copy-paste a stack trace? Also a code snippet in question.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
