### ISSUE TITLE
Training USE(DAN) on Plain Urdu(language) Text Corpus from scratch

### ISSUE THREAD

**Issue by MFarhatUllah** [tensorflow/hub#232]
Hi !
Hub Team!
Is there any way to train USE(DAN) or USE(Transformer) on **Urdu (language)** unsupervised plain text corpus. 

I have read issues #155, #46 but there is no clear instructions about how to train USE on other than English language. 

@vbardiovskyg 
Thanks in Advance

**Comment by arghyachaks** [comment]
Hi, Hub Team,
I also have the same question. How can we train universal-sentence-encoder for other language?
Thanks in Advance

**Comment by arnoegw** [comment]
As explained in https://github.com/tensorflow/hub/issues/155#issuecomment-422299981 there is no way to retrain the TF Hub modules with U.S.E. for a new language.
