### ISSUE TITLE
loadTfHubModule seems not working with text embeddings model in js

### ISSUE THREAD

**Issue by daliearn** [tensorflow/hub#234]
Hello, 
I'm trying to use tfHub's models in tfjs with the loadTfHubModule method. The documentation example works fine for some models (inception v3) but not for text embedding models.
When I add ?tf-hub-format=compressed at the end of the url, it let me download the model but since I don't have 1GB of free space this won't be fine for me.
Moreover, when I look at the network request, it seems to target a storage.googleapi url with a xml file where you can find a large set of models for image classification but not fr text embedding.
Are text embedding models still available for tfjs or I will have to download and convert them by myself ?

**Comment by vbardiovskyg** [comment]
Hi,

I think text embeddings are not supported by tfjs yet, because of some missing ops (table lookups, etc.). I would recommend opening the issue on https://github.com/tensorflow/tfjs/issues. That way the tfjs team can prioritize which ops they will focus on.

**Comment by vbardiovskyg** [comment]
Referencing the tfjs team: @tensorflow/tfjs

**Comment by nsthorat** [comment]
cc @pyu10055

It looks like some models aren't actually converted, e.g. elmo.

I filed another issue in tfjs to track this: https://github.com/tensorflow/tfjs/issues/1408

**Comment by vbardiovskyg** [comment]
There are actually quite a lot of modules that are nonconvertible at the moment because of the missing ops, not sure how to track it effectively.

**Comment by nsthorat** [comment]
Got it -- thanks. We should at least improve the error messaging to inform the user that the module isn't ready in TensorFlow.js yet.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
