### ISSUE TITLE
Batch Normalization renorm with tensorflow_hub

### ISSUE THREAD

**Issue by amirmazaheri1990** [tensorflow/hub#238]
Hi,

I have observed an issue in Tensorflow hub and batch normalization. It seems that I cannot have a batch normalization layer with renorm in a module. Consider the following short script:
```
import tensorflow as tf
import tensorflow_hub as hub



def myfunc():
    input = tf.placeholder(tf.float32, [5, 10])
    output = tf.layers.batch_normalization(input, renorm = True)

    outputs = dict(default=output)
    inputs = dict(input_txt=input)
    hub.add_signature(inputs=inputs, outputs=outputs)

g_spec = hub.create_module_spec(myfunc)
```
which gives me the following error:

> Traceback (most recent call last):
  File "..../codes/5/test.py", line 16, in <module>
    g_spec = hub.create_module_spec(myfunc)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_hub/native_module.py", line 189, in create_module_spec
    if err: raise ValueError(err)
ValueError: A state-holding node x of a module's graph (e.g., a Variable op) must not be subject to a tf.colocate_with(y) constraint unless y is also a state-holding node.
Details: node 'batch_normalization/renorm_mean_weight' has op 'VarHandleOp', which counts as state-holding, but Operation.colocation_groups() == [b'loc:@batch_normalization/Read/ReadVariableOp']. 

The problem does NOT exist with ```renorm=False```.

Is there anything that I am missing? I have not found a similar problem on Stackoverflow.

**Comment by akhorlin** [comment]
Thank you for the convenient repro. I think if you try running this code
against tf-nightly it should work (see example below). TF is loosening
co-location constraints which I think might address this issue.

Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensorflow_hub as hub
>>> def myfunc():
...   input = tf.placeholder(tf.float32, [5, 10])
...   output = tf.layers.batch_normalization(input, renorm = True)
...   outputs = dict(default=output)
...   inputs = dict(input_txt=input)
...   hub.add_signature(inputs=inputs, outputs=outputs)
...
>>> g_spec = hub.create_module_spec(myfunc)
WARNING: Logging before flag parsing goes to stderr.
W0226 09:13:14.521587 140166725330688 deprecation.py:323] From <stdin>:3:
batch_normalization (from tensorflow.python.layers.normalization) is
deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
W0226 09:13:14.575267 140166725330688 deprecation.py:323] From
/home/akhorlin/.local/lib/python3.5/site-packages/tensorflow_hub/saved_model_lib.py:109:
build_tensor_info (from tensorflow.python.saved_model.utils_impl) is
deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library
as tf.compat.v1.saved_model.utils.build_tensor_info or
tf.compat.v1.saved_model.build_tensor_info.
>>> print(tf.__version__)
1.13.0-dev20190226
