### ISSUE TITLE
why the sentence embedding attained using 'default' key and mean pooling over the word embeddings retrieved through 'elmo' key are different?

### ISSUE THREAD

**Issue by MVenkata-Rathnam** [tensorflow/hub#240]
Case 1:
```
elmo = hub.Module("https://tfhub.dev/google/elmo/1", trainable=True)
embedding_op = elmo(text,signature="default",as_dict=True)
default = embedding_op["default"]
embedding = sess.run(default)

```
Case 2:

```
      elmo_op = embedding_op["elmo"]
      embedding = sess.run(elmo_op)
      new_embedding = []
      for index, embed in enumerate(embedding):
        temp = embed[0]
        for i in range(1,embed.shape[0]):
          temp = np.add(temp, embed[1])
        temp = temp / embed.shape[0]
        new_embedding.append(temp.tolist())

```
I am not able to understand why these two operations are giving me different values in the resultant sentence embedding.  In the Tensorflow hub, they have stated so,

> default: a fixed mean-pooling of all contextualized word representations with shape [batch_size, 1024].

Where am I going wrong??  Can anybody help me to sort this out??

**Comment by andresusanopinto** [comment]
I checked with the module producers.

The issue here is that real inputs almost always have padding since the sequence lengths are usually different. You have to normalize by using the correct sequence_len and not include the padding there.

**Comment by yonatanbitton** [comment]
Do you have a fixed version for this? 
I would like to know how to get sentence embedding from the elmo embedding
Thanks
