### ISSUE TITLE
GPU memory usage is close to the limit in colab

### ISSUE THREAD

**Issue by Malathi15** [tensorflow/hub#246]
When I tried to run Action Recognition on the UCF101 Dataset Notebook [https://github.com/tensorflow/hub/blob/master/examples/colab/action_recognition_with_tf_hub.ipynb](url) in colab I got the result (input video size is below 2MB)  

But if I gave input video more than 2 MB I got ResourceExhausted Error. 
![screenshot 141](https://user-images.githubusercontent.com/46995564/53802981-4ac43780-3f69-11e9-9720-4e8d992de7a3.png)

Even I terminate the notebook and start the new one I got the same error.

**Comment by arnoegw** [comment]
Colabs are "free compute" for demonstration purposes, but they do have resource limits (independent of TF Hub). Raw pixel data from videos is bigger than the encoded data in the file. For bigger input data, please take the colab as a starting point for how to use the module on your own hardware.

Multiple colabs run under your Google account share resources. From menu "Runtime", select "Manage sessions" to find (and possibly terminate) your other ongoing colab sessions.

**Comment by Malathi15** [comment]
Thanks for your reply @arnoegw . Is it possible to run a live video in colab? If it's possible then How can I run a live video in colab with out any memory error? I'm using 4 Megapixel IP CCTV camera.

**Comment by 16cs19** [comment]
how you give an other input video to that sample_video,
are you using your own dataset ?
