### ISSUE TITLE
How to specify which layer or how many layers to set Trainable in TF Hub Module?

### ISSUE THREAD

**Issue by kshitizrimal** [tensorflow/hub#247]
Hi, In the docs there is only mention of setting **hub.Module(..., trainable=True)** for fine tuning but how do I specify how many layers or which particular layer to set trainable to true or false in TF Hub module? Is there any docs for that, that I don't seem to find?

**Comment by arnoegw** [comment]
Setting `trainable=True` makes all the originally trainable variables trainable again (weights etc. from all layers). Fine-tuning some but not all layers requires knowing the name scopes (or other naming conventions) for the variables from the desired layers, and filtering the variables passed to the optimizer accordingly.

**Comment by random-forests** [comment]
Good question Kshitiz!  @MarkDaoust, fyi from earlier today.

Arno, thanks for the info! I think a lot of users will be interested in fine-tuning, it'd be very helpful if there was an example for this in the TF 2.0 tutorials (https://github.com/tensorflow/docs/tree/master/site/en/r2/tutorials). 

I know everyone is busy, do you happen to know a hub expert who'd be willing to write a short example, or get one started?

**Comment by hgadig** [comment]
@arnoegw  Any update on this please ?

**Comment by arnoegw** [comment]
I believe I answered the technical question for TF1 in as much as there is a solution with hub.Module().

I've followed up with Josh and my colleagues internally about next steps for tutorials, but we have no statement at this point.
