### ISSUE TITLE
Is it possible to run a live video in colab for Action Recognition?

### ISSUE THREAD

**Issue by Malathi15** [tensorflow/hub#248]
I tried to run Action Recognition on the UCF101 Dataset Notebook [https://github.com/tensorflow/hub/blob/master/examples/colab/action_recognition_with_tf_hub.ipynb](url) in colab I got the result. 

Now I tried to give live video for Action Recognition. 
1) Is it possible to run a live video in colab? If it's possible then How can I run a live video in colab with out any memory error? I'm using 4 Megapixel IP CCTV camera.

**Comment by akhorlin** [comment]
This seems to be a general Colab question. It might be worth asking
via stackoverflow
with google-colaboratory tag
<https://stackoverflow.com/questions/ask?tags=google-colaboratory>.

**Comment by arnoegw** [comment]
This was essentially answered (within the scope for TF-Hub) in https://github.com/tensorflow/hub/issues/246

**Comment by ashwanimandloi** [comment]
@Malathi15  if you got the solution of running your ip camera on ubuntu please help me and also how to have live feed from ip camera on google colab
