### ISSUE TITLE
Can't access specific layer output in hub module. 

### ISSUE THREAD

**Issue by meet-minimalist** [tensorflow/hub#249]
There is no way to access the intermediate layers of a pretrained tf hub module. Like in the case of style transfer or in the case when we need to use the last conv layer and build another couple of conv layers on top of that just like Yolo v1.

**Comment by arnoegw** [comment]
For the google/{imagenet,inaturalist}/... modules, you can get access to a whole set of intermediate activations by passing `as_dict=True` hen calling the module.

**Comment by pablotopazium** [comment]
Could you finally solve the problem? I need to use the output of the last conv layer to build a Class Activation Mapping.
