### ISSUE TITLE
Logs of retrain.py break web browser when launched in Colab

### ISSUE THREAD

**Issue by frogermcs** [tensorflow/hub#251]
When you play with [retrain.py](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py) locally on your machine (I use Jupyter Notebook and Docker) it is fine to do 10k-20k training steps.

But when you try to launch it on Colab, it seems that the amount of logs is way too big, and usually it breaks Chrome, making it's card impossible to launch (tested on Macbook Pro 2017, 16GB Ram, i7). 

Maybe it would be a good idea to define level of logs as a input argument in retrain.py script? 

How to reproduce:
Launch my project in Colaboratory: https://github.com/frogermcs/GTSRB-TensorFlow-Lite. It's pretty likely Chrome will crash during the learning process (3/4 tries crash).

**Comment by hgadig** [comment]
@frogermcs  Could you please confirm if you selected the "Hardware accelerator" from the Colab ? If so, which one you selected ?

**Comment by frogermcs** [comment]
Usually it's TPU. Do you think it can have something with it?

**Comment by akhorlin** [comment]
@frogermcs it might be useful what specific error message(s) is overly verbose. In general if the messages are printed through standard Python or standard TF Logger, they could be disabled by tweaking the logging level before running the function from retrain.py. 

For standard TF logger you can do something like "tf.logging.set_verbosity(tf.logging.FATAL)" before running the function in question. For standard Python logging it would be "logging.root.setLevel(logging.FATAL)"

If the message are produced by print() you could just redirect all stdin into a file, e.g.

sys.stdout = open('file', 'w')
print("Blah")  # Will be written to file.

**Comment by frogermcs** [comment]
I think setting logging level is not possible with current `retrain.py` implementation because of [that](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py#L970):

```
def main(_):
  # Needed to make sure the logging output is visible.
  # See https://github.com/tensorflow/tensorflow/issues/3047
  tf.logging.set_verbosity(tf.logging.INFO)
```

Maybe it would be good to differentiate logs a little bit? For example:

```
          tf.logging.info(
              str(how_many_bottlenecks) + ' bottleneck files created.')
```

should be logging.debug()? And just some final info about script outputs should be `.info()`? And then we could parametrize it via input args. What do you think 🤔?

**Comment by frogermcs** [comment]
And the issues I have? "Aww snap" from Chrome. Tab is either crashing or when I launch it, view isn't rendered. Usually when I'm in a half way of `retrain.py` - bottlenecks are probably already created, and training process is in progress.

**Comment by akhorlin** [comment]
What about as an immediate work-around, just redirecting stdout and stderr as I mentioned in my last post?

But in general I think it makes sense to add a flag to be able to set the logging level for the script. @arnoegw to see if there are any concerns with the approach.

**Comment by arnoegw** [comment]
@frogermcs, I think tf.logging.info every 100 files is ok, but logging for each file (e.g., at line retrain.py:354) should be logging.debug.

Would you like to send me a pull request that adds a --logging_verbosity flag and fixes the per-file logging?

**Comment by frogermcs** [comment]
Just created Pull Request (#252). I also tested it in my [project](https://github.com/frogermcs/GTSRB-TensorFlow-Lite) and works fine in Chrome and Colab. Finally I could leave the Chrome tab open and come back to it after an hour. :)

**Comment by arnoegw** [comment]
I merged the pull request earlier today.

Folks who like to train an image classifier in a colab **and** enjoy living on the cutting edge of TF 2.0.0alpha0 ([announced](https://www.youtube.com/playlist?list=PLQY2H8rRoyvzoUYI26kHmKSJBedn3SQuB) last week) might want to take a look at  [examples/colab/tf2_image_retraining.ipynb](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb) which is considerably smaller, faster (if you use a GPU), and even supports fine-tuning the image module.
