### ISSUE TITLE
NotImplementedError: TF Hub module 'https://tfhub.dev/google/nnlm-en-dim128/1' is stored using TF 1.x format. Loading of the module using hub.load() is not supported.

### ISSUE THREAD

**Issue by sswapnil2** [tensorflow/hub#254]
I am trying to import tfhub module for inference in tensorflow 2.0-alpha version. 
I am getting this error **TF 1.x format. Loading of the module using hub.load() is not supported**. How should use tfhub in tensorflow 2.0  then. <br>
If I try to create a module using **module = tfhub.Module("https://tfhub.dev/google/nnlm-en-dim128/1")** but I am getting following error **RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.**

**Comment by akhorlin** [comment]
Currently only modules that were exported in TF 2.0 format can be loaded
via hub.load() API in TF 2. The list of modules that are in TF 2 format
could be found tf2-preview:
https://tfhub.dev/s?module-type=text-embedding&q=preview

We are aiming for more complete compatibility story and module list before
the transition out of 'alpha'.

**Comment by sswapnil2** [comment]
thanks for help
