### ISSUE TITLE
Download of universal sentence encoder throws RuntimeError

### ISSUE THREAD

**Issue by stsievert** [tensorflow/hub#262]
I run this code:

``` python
>>> import tensorflow as tf
>>> import tensorflow_hub as hub
>>> tf.__version__
1.13.1
>>> hub.__version__
0.3.0
>>> embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/2")
```

which throws a `RuntimeError: Missing implementation that supports: loader(*('/var/folders/_p/t_mfcz_90vx3shw664l6kpbr0000gq/T/tfhub_modules/1fb57c3ffe1a38479233ee9853ddd7a8ac8a8c47',), **{})`. Here's the traceback:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-a4163f1a0a44> in <module>()
----> 6 embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/2")

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/module.py in __init__(self, spec, trainable, name, tags)
--> 147     self._spec = as_module_spec(spec)

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/module.py in as_module_spec(spec)
---> 36     return load_module_spec(spec)

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/module.py in load_module_spec(path)
---> 61   return registry.loader(path)

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/registry.py in __call__(self, *args, **kwargs)
---> 45             self._name, args, kwargs))

RuntimeError: Missing implementation that supports: loader(*('/var/folders/_p/t_mfcz_90vx3shw664l6kpbr0000gq/T/tfhub_modules/1fb57c3ffe1a38479233ee9853ddd7a8ac8a8c47',), **{})
```

How do I resolve this?

**Comment by rmothukuru** [comment]
Hello stsievert,
Can you please let us know the details of Operating System you are using.

**Comment by stsievert** [comment]
I'm on macOS 10.14.3.

**Comment by stsievert** [comment]
I think this issue is upstream.

I restarted my machine because I had a weird issue where Safari was hanging between running and not (couldn’t force quit but in the force quit menu).

After I restarted, the example above ran.

**Comment by maziyarpanahi** [comment]
Sometimes, '/var/folders/_p/t_mfcz_90vx3shw664l6kpbr0000gq/T/tfhub_modules/1fb57c3ffe1a38479233ee9853ddd7a8ac8a8c47' or the path is complaining about is empty. Just check and if it's empty delete it and run it again.
https://github.com/tensorflow/hub/issues/212
