### ISSUE TITLE
Stuck when loading Module? 

### ISSUE THREAD

**Issue by hamzaLeb** [tensorflow/hub#265]
Hi,
I tried the tutorial at [https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder.ipynb#scrollTo=zwty8Z6mAkdV](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder.ipynb#scrollTo=zwty8Z6mAkdV) and everything works great.
But when I am on my local machine (MacOS) the following code stucks/freezes infinitely:
```
import tensorflow_hub as hub
module_url = "https://tfhub.dev/google/universal-sentence-encoder-large/3" 
embed = hub.Module(module_url)
```
I tried the suggested solution I found on the web to add the TFHUB_CACHE_DIR variable but the problem persists:
```
import os
import tensorflow_hub as hub
os.environ['TFHUB_CACHE_DIR'] = '/Path/To/A/Standard/Local/Directory'
module_url = "https://tfhub.dev/google/universal-sentence-encoder-large/3" 
embed = hub.Module(module_url)
```
Can anyone help me please?

**Comment by hgadig** [comment]
This is some what related to https://github.com/tensorflow/hub/issues/261.
