### ISSUE TITLE
How-to self-hosted http://tfhub.dev ?

### ISSUE THREAD

**Issue by elgalu** [tensorflow/hub#266]
How to spin up a privately hosted TF Hub ?

Is the file-system mode the only way?

Is it in the roadmap to allow self-hosted TF Hubs ?

**Comment by rmothukuru** [comment]
TensorFlow Hub accepts modules from several paths:

* Local filesystem: e.g.: "/tmp/my-module"
* Remote filesystem: e.g.: "gs://my-bucket/my-module"
* HTTPS endpoints: e.g.: "https://myserver/module.tar.gz" (see more in [1])

There are no plans to open-source the tfhub.dev implementation. The recommendation for creating a self-hosted repository is to share models models via https, you can see details in module hosting in: https://github.com/tensorflow/hub/blob/master/docs/hosting.md

**Comment by elgalu** [comment]
Thanks!
