### ISSUE TITLE
Feature request: replacing variable initializer

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/hub#267]
TensorFlow Hub seems to fix its initializer and load the values from the checkpoint file.
However, for example, we might need random initializer in the case of training ImageNet in scratch for research.
Do you have any plan to add the feature to replace initializer?

**Comment by arnoegw** [comment]
In TF2, a variable gets its variable set right at creation time; there will no longer be an explicit initializer op that gets executed at some time. This carries over to TF Hub modules in TF2 format, and makes your feature request infeasible in the TF2 world. To not complicate the transition from TF1 to TF2, we are not going to add this for TF1.

Unfortunately, that means TF Hub does not (currently) support an option to take module x and then choose between training from scratch vs warmstarting from its pre-trained weights.
