### ISSUE TITLE
create module from existing graph

### ISSUE THREAD

**Issue by breezeai** [tensorflow/hub#27]
I'm trying to create a module from a existing graph.  From the module creation documentation I need to completely construct the entire graph.  

Is there a way to load an existing graph from file and convert it to a module.

My use case is I have retrained an existing model and created a new retrained model / graph stored on disk.  I would like to now create a module and publish it for use with tensorflow hub

**Comment by hdmetor** [comment]
Also see 
https://stackoverflow.com/questions/50747981/create-hub-module-from-existing-checkpoint/50764655#50764655

**Comment by RaghavaDhanya** [comment]
You could do 
```python
def module_fn():
    input_name = "your_input_tensor_name:0"
    output_name = "your_output_tensor_name:0"
    graph_def = tf.GraphDef()
    with open('example.pb', "rb") as f:
        graph_def.ParseFromString(f.read())

    input_ten=tf.placeholder(tf.float32, shape = input_tensor_shape)
    output_ten,=tf.import_graph_def(graph_def, input_map = {input_name: input_ten}, return_elements = [output_name])
    hub.add_signature(inputs = input_ten, outputs = output_ten)



spec = hub.create_module_spec(module_fn)
module = hub.Module(spec)
with tf.Session() as session:
    module.export('test_module',session)


```
for example, I convert my GAN generator to hub module as
```python
def module_fn():
    gen_input_name="input_2:0"
    gen_output_name="output_node0:0"
    gen_graph_def = tf.GraphDef()
    with open('gen.pb', "rb") as f:
        gen_graph_def.ParseFromString(f.read())


    z=tf.placeholder(tf.float32,shape=(1,100))
    gen_imgs,=tf.import_graph_def(gen_graph_def,input_map={gen_input_name:z}, return_elements=[gen_output_name])
    hub.add_signature(inputs=z, outputs=gen_imgs) 

spec = hub.create_module_spec(module_fn)
module=hub.Module(spec)
with tf.Session() as session:
    module.export('new_test_module',session) 
```
and load it as 
``` python
with tf.Graph().as_default():
      module=hub.Module('new_test_module')
      test=module(np.random.normal(0, 1, (1, 100)))
      with tf.Session() as session:
          img=session.run(test)
```

**Comment by andresusanopinto** [comment]
We added some features to easy creation of modules. There are more error prone than the other APIs and users need to know more details of graph mode.

Particularly:
 - We added "ModuleSpec.export" method. Now one doesn't needs to create a session to load the state into vars and can do "hub.create_module_spec(...).export(path, "checkpoint")".
 - We added a "hub.create_module_spec_from_saved_model", which is highly experimental and error-prone if one doesn't knows what is going the graphs.

**Comment by yangyn2018** [comment]
Hi @RaghavaDhanya ,
i am reference your code to convert a existing frozen model to a tensorflow hub module. i can successful get the new module but the inference accuracy of my new module is quite low, i suspect my new module is not generated correctly, can you shed some light on it?

The model i am using is "Mobilenet_V1_1.0_224" get from "http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz". 
And i use the "retrain.py" example code from tensorflow_hub github repository to verify my new module.

my hub convert code is as blew:
```
MODEL="mobilenet_v1_1.0_224/mobilenet_v1_1.0_224_frozen.pb"
MODULE_PATH="output_hub"

def module_fn():
    input_name="input:0"
    output_name="MobilenetV1/Predictions/Reshape_1:0"
    with tf.gfile.GFile(MODEL, 'rb') as f:
        graph_def=tf.GraphDef()
        graph_def.ParseFromString(f.read())
        input_tensor = tf.placeholder(tf.float32, [None, 224,224, 3])
        output_tensor, = tf.import_graph_def(graph_def, input_map = {input_name: input_tensor}, return_elements=[output_name])
        hub.add_signature(inputs = {"images": input_tensor}, outputs = output_tensor)

spec = hub.create_module_spec(module_fn)
with tf.Graph().as_default():
    module = hub.Module(spec)
    with tf.Session() as session:
        module.export(MODULE_PATH, session=session)
```
