### ISSUE TITLE
global variables initializer

### ISSUE THREAD

**Issue by mhajiaghayi** [tensorflow/hub#270]
I can see that after loading the module, we run the 
tf.global_variables_initializer(). however, doesn't this command reinitialize all the variables of the model? I have noticed that the model still works fine but i'm not sure if we don't do it, what would be the performance. For fine-tuning, it seems there are some optimization variables that need to be initialized and are usually included in the global_variables, but if we don't want to do fine-tuning, why we would need to initialize global variables?

**Comment by rmothukuru** [comment]
Hello mhajiaghayi,
Answers to your questions are mentioned below.

Q: However, doesn't this command reinitialize all the variables of the model?
A: Yes, this command reinitialize all the variables of the model, especially, its weights.

Q. If we don't do it, what would be the performance?
A: If we don't initialize the variables, it results in Error.

Q: If we don't want to do fine-tuning, why we would need to initialize global variables?
A: When we load a TF Hub Module, we are actually loading its TensorFlow graph, along with its weights. So, in order to leverage the weights of the Pre-Trained Model, we have to initialize them.

**Comment by mhajiaghayi** [comment]
thanks for your reply. it is interesting, because when we load a model with saver.restore(), then tf.global_variables_initializers() initializes all the variables with the random values, depending on their initializer random function. so, here, you are saying that for tf hub module, the variables are initialized with their trained values and not with their initial random functions. am I right?

**Comment by arnoegw** [comment]
Yes, the variables in a hub.Module() have their initializers changed to restore from the checkpoint included in the module. (They no longer initialize randomly.) This way, running tf.global_variables_initializer() does the right thing at the start of training: user-defined variables (e.g., in your own layers) are initialized randomly as usual; module-defined variables are initialized to their pre-trained values (which makes sense for using the module with or without fine-tuning).

**Comment by mhajiaghayi** [comment]
Hi there, sorry for activating this email thread again. I have a question about the discrepancy that exists between the notebook version of this model and what is posted on the website. on TensorFlow Hub,  we can see that for 
the example is # Embedding for: The quick brown fox jumps over the lazy dog.
# [0.0387121252716, -0.00189059402328, -0.00533464271575, ...]
however, if we use your notebook version  https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder.ipynb#scrollTo=Q8F4LNGFqOiq to change the module_url = "https://tfhub.dev/google/universal-sentence-encoder-large/3" then for the same input, i get the following output 


Message: The quick brown fox jumps over the lazy dog
Embedding size: 512
Embedding: [0.0036696437746286392, 0.06560932099819183, 0.03254513815045357, ...]

which is quite different than what is posted in the website. which one is correct then? thanks, mahdi 


| 
| 
|  | 
TensorFlow Hub


 |

 |

 |




    On Thursday, April 11, 2019, 01:13:27 a.m. PDT, arnoegw <notifications@github.com> wrote:  
 
 
Yes, the variables in a hub.Module() have their initializers changed to restore from the checkpoint included in the module. (They no longer initialize randomly.) This way, running tf.global_variables_initializer() does the right thing at the start of training: user-defined variables (e.g., in your own layers) are initialized randomly as usual; module-defined variables are initialized to their pre-trained values (which makes sense for using the module with or without fine-tuning).
