### ISSUE TITLE
Bazel Build Failing

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/hub#274]
Hi! I'm having a problem with Building TF Hub from Source. Can Anyone please help me out? I've been following the steps as given in https://github.com/tensorflow/hub/blob/master/tensorflow_hub/pip_package/PIP.md
I've installed bazel 0.24.1.

Error I'm Getting:
```
ERROR: /home/tf_hub/hub/WORKSPACE:17:1: name 'git_repository' is not defined
ERROR: /home/tf_hub/hub/WORKSPACE:40:1: name 'http_archive' is not defined
ERROR: /home/tf_hub/hub/WORKSPACE:47:1: name 'new_http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'tools/build_defs/repo/http.bzl': no such package '@bazel_tools//tools/build_defs/repo': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'tools/build_defs/repo/http.bzl': no such package '@bazel_tools//tools/build_defs/repo': error loading package 'external': Could not load //external package
INFO: Elapsed time: 2.552s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
Bazel Version: 0.24.1
Python Version: 3
Tensorflow Version: 2.0.0a
Commands to Reproduce:
```
(env)~/tf_hub$ git clone https://github.com/tensorflow/hub
(env)~/tf_hub$ cd hub && bazel build tensorflow_hub/pip_package:build_pip_package
```
Expected Output: No Error. Build Sucessful

----------------------------------------
Suggested Fix: Using Bazel 0.18.1 or similar. Latest Version of Bazel Doesn't support git_repository, http_archive and new_http_archive

**Comment by hgadig** [comment]
@gunan As far as I know TF 2.0 should work successfully for bazel versions between 0.19 and 0.24. Could you please look into this as the user says only 0.18.1 works fine.

**Comment by gunan** [comment]
TensorFlow does, but I do not know about hub.
I have no experience with tensorflow hub code.
Please redirect to tf hub team.

**Comment by andresusanopinto** [comment]
The WORKSPACE file was updated to work with blaze 0.24.

This should work since https://github.com/tensorflow/hub/commit/b3d2da9232df371ca61c11d80d7541ae68c59a64

**Comment by zhaidejah** [comment]
root@BDC11-L-G01ERU9:/mnt/c/Sai/RnD/paraphrasing/temp/models/research/syntaxnet# bazel test ...
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/mnt/c/Sai/RnD/paraphrasing/temp/models/research/syntaxnet/tools/bazel.rc
ERROR: /mnt/c/Sai/RnD/paraphrasing/temp/models/research/syntaxnet/WORKSPACE:10:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.164s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
