### ISSUE TITLE
What to do after creating creating Tensorflow Graph [CONTRIBUTING]

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/hub#277]
Hi! I've been working on a model, and created a Frozen Tensorflow Graph out of it. What would be my next steps to Add it to TF-Hub? There's no such documentation available in TF-Hub Guide Page.
@vbardiovskyg

**Comment by vbardiovskyg** [comment]
Hi Adrish, thanks a lot for interest!

Currently we don't have a streamlined process to get modules onto tfhub.dev.

When you have exported a shareable module, I think these would be the next steps for community to benefit from the effort:
1) Submit the code used to export the module somewhere on your GitHub so other people can reproduce this.
2) Put the tar.gz'd module on the hosting of your choice.
3) Update the issue and invite people to try the module out.

Additional note: you are saying the model is a frozen TF graph. Would it be possible to get a proper graph+variables? If not done this way, it might have some performance drawbacks if huge variables are frozen into graph definition.

**Comment by captain-pool** [comment]
> Hi Adrish, thanks a lot for interest!
> 
> Currently we don't have a streamlined process to get modules onto tfhub.dev.
> 
> When you have exported a shareable module, I think these would be the next steps for community to benefit from the effort:
> 
>     1. Submit the code used to export the module somewhere on your GitHub so other people can reproduce this.
> 
>     2. Put the tar.gz'd module on the hosting of your choice.
> 
>     3. Update the issue and invite people to try the module out.
> 
> 
> Additional note: you are saying the model is a frozen TF graph. Would it be possible to get a proper graph+variables? If not done this way, it might have some performance drawbacks if huge variables are frozen into graph definition.

Thanks for the reply @vbardiovskyg . I'll not freeze the graph, instead will tar it, as Graph+Variables. Apart from that, Is the Community allowed to make a Project to provide a streamlined Application to Push new Graphs to tfhub.dev after getting reviewed by the maintainers?

**Comment by vbardiovskyg** [comment]
As discussed outside of GitHub, we don't currently have a process to push community made modules to TF-Hub.
