### ISSUE TITLE
What should I do after running retrain.py?

### ISSUE THREAD

**Issue by laminggg** [tensorflow/hub#279]
After running retrain.py,if I want to predict a image what should I do?

**Comment by hgadig** [comment]
You can use the label_image script for predicting the image.

[label_image script](https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/scripts/label_image.py)

**Comment by laminggg** [comment]
thinnks,but still have some troubles,that i can not find the lable_image.py script in my project,and both tf_files/retrained_graph.pb;tf_files/retrained_labels.txt can not be found.how can i do?

**Comment by vbardiovskyg** [comment]
Hi,

the link to label_image script is above. You'll have to `git clone` the other repository to access this file (or theoretically just download the file directly, if there are no special deps).

As for the other two files, take a look at:
https://github.com/tensorflow/hub/blob/09f45963f6787322967b6fec61459f3ac56fbb27/examples/image_retraining/retrain.py#L1176
https://github.com/tensorflow/hub/blob/09f45963f6787322967b6fec61459f3ac56fbb27/examples/image_retraining/retrain.py#L1197

**Comment by rmothukuru** [comment]
@laminggg ,
Can you please confirm if you could Predict an image successfully now.

**Comment by laminggg** [comment]
@rmothukuru 
yes,it works well now
