### ISSUE TITLE
Is there a module for Chinese text classifier ?

### ISSUE THREAD

**Issue by lugq1990** [tensorflow/hub#28]
Hello, every one:
I am working on the Chinese  text classifier model, since the TF-HUB is just like the Caffe model zoo, so I am  wondered if is there a Chinese text classifier model for TensorFlow. Like the fastText, it provide a Chinese Word2Vec result as a directory for Chinese.
Hope repsonsed.

**Comment by andresusanopinto** [comment]
No. Currently there are no module for chinese text classifier published in https://tfhub.dev/text.

Please :+1: to show interest, and let others in the community know they could focus in creating such modules.

**Comment by vbardiovskyg** [comment]
The Chinese NNLM modules are now available: https://github.com/tensorflow/hub/blob/master/docs/modules/text.md.

**Comment by keyingwu2-c** [comment]
https://github.com/tensorflow/hub/blob/master/docs/modules/text.md. 
404 now

**Comment by vbardiovskyg** [comment]
The above page was moved to https://tfhub.dev/google/collections/nnlm/1 since.
