### ISSUE TITLE
Converted tflite model cannot classify images properly

### ISSUE THREAD

**Issue by nfathoni79** [tensorflow/hub#284]
Hello!
I used this [retrain.py](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py) script to retrain my own food images datasets with these arguments:
```
python retrain.py ^
--image_dir food_images ^
--tfhub_module https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/feature_vector/2 ^
--output_graph output_graph.pb ^
--output_labels output_labels.txt ^
--summaries_dir summaries ^
--bottleneck_dir bottleneck ^
--saved_model_dir saved_model
```
Then I test the output graph by running [label_image.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/label_image.py) script:
```
python label_image.py ^
--graph output_graph.pb ^
--labels output_labels.txt ^
--input_layer Placeholder ^
--output_layer final_result ^
--input_height 224 ^
--input_width 224 ^
--image food_images\chicken\33341.jpg
```
And I got these result:
```
chicken 0.9983601
duck 0.0010556207
steak 0.00040414903
salmon 7.6234384e-05
curry 3.443898e-05
```
Then I used `tflite_convert` to convert the output graph to tflite format with these arguments:
```
tflite_convert ^
--graph_def_file output_graph.pb ^
--output_file optimized_graph.lite ^
--input_format TENSORFLOW_GRAPHDEF ^
--output_format TFLITE ^
--input_shapes 1,224,224,3 ^
--input_arrays Placeholder ^
--output_arrays final_result ^
--inference_type FLOAT ^
--inference_input_type FLOAT
``` 
I test the tflite model on Android phone by running this [project](https://github.com/googlecodelabs/tensorflow-for-poets-2/tree/master/android/tflite) from [TensorFlow for Poets 2](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/#0). I pointed my camera at the same food image as I tested before and I got these result on the screen:
```
cheesecake: 0.33
sushi: 0.16
tuna: 0.12
```
Why can't the tflite model classify the image properly? Where did I do wrong?
Thanks in advance.

**Comment by rmothukuru** [comment]
@nfathoni79,
Can you please provide the results by running TF Lite Convert on already validated image like,  "food_images\chicken\33341.jpg".  Then we can actually try to understand the drop in performance because of its conversion.

**Comment by nfathoni79** [comment]
@rmothukuru 
I just tested my tflite model with tflite interpreter by modifying the script [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/convert/python_api.md#using-the-interpreter-from-a-model-file-). I used the `read_tensor_from_image_file` function from the [label_image.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/label_image.py) script to turn the "food_images\chicken\33341.jpg" image into a tensor. Here is my script:
```
# Read tensor from image file
file_name = "food_images/chicken/33341.jpg"
input_height = 224
input_width = 224
image_tensor = read_tensor_from_image_file(file_name, input_height, input_width)

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="optimized_graph_100.lite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model
input_shape = input_details[0]['shape']
interpreter.set_tensor(input_details[0]['index'], image_tensor)

interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```
And surprisingly I got these results:
```
[[9.98360097e-01 1.05565100e-03 1.99441529e-05 6.45590490e-07
  1.02031201e-07 1.31657885e-08 8.65402171e-07 6.16448403e-08
  6.74352947e-08 3.44396394e-05 2.78956168e-06 4.17489173e-06
  1.35173582e-06 9.83086608e-08 1.54677909e-05 3.55562442e-08
  1.53483022e-08 1.49937046e-06 2.45400679e-06 1.72795683e-06
  2.54611621e-08 5.75562780e-08 2.14812577e-08 8.65700531e-06
  7.62361233e-05 1.38726375e-06 4.04161547e-04 8.63593300e-07
  3.67860942e-08 7.03735714e-06]]
```
My image dataset has 30 labels and the image is perfectly classified as label one (label one is the chicken). I don't know why it doesn't work when I put the tflite model on my Android app. The intended label is not in the top three, and the top three confidence are very low (below 30%).

**Comment by rmothukuru** [comment]
@nfathoni79 ,
Can you please raise an issue in Tensorflow Repository of Github or in Stackoverflow or may be any avenue related to Android. Closing this issue as it is not related to TF Hub.
