### ISSUE TITLE
build_pip_package does not work on Mac OS

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/hub#285]
As [`PIP.md`](https://github.com/tensorflow/hub/blob/09f45963f6787322967b6fec61459f3ac56fbb27/tensorflow_hub/pip_package/PIP.md) say "Creating the TensorFlow Hub pip package using Linux", actually [`build_pip_package.sh`](https://github.com/tensorflow/hub/blob/09f45963f6787322967b6fec61459f3ac56fbb27/tensorflow_hub/pip_package/build_pip_package.sh) does not work on Mac OS.

I guess the main cause is here:
https://github.com/tensorflow/hub/blob/09f45963f6787322967b6fec61459f3ac56fbb27/tensorflow_hub/pip_package/build_pip_package.sh#L33

I guess `mktemp` with `--suffix` option does not work on Mac OS and only`TMPDIR=$(mktemp -d)` will do on both of Linux and Mac OS.

Could I send a PR?

**Comment by rmothukuru** [comment]
@arnoegw ,
Can you PTAL

**Comment by arnoegw** [comment]
@sfujiwara: Thanks for reaching out! If you have a way to test it end-to-end on MacOS, I'm happy to accept a change that also works in our Linux configuration.

**Comment by sfujiwara** [comment]
OK, I'll try it!
