### ISSUE TITLE
Following rc files are not being read

### ISSUE THREAD

**Issue by zhaidejah** [tensorflow/hub#291]
I am trying to run Syntaxnet in ubuntu application installed in windows. I was following this blog http://www.davidsbatista.net/blog/2017/03/25/syntaxnet/   ........... but i encountered error in the bazel test .....

root@BDC11-L-G01ERU9:/mnt/c/Sai/RnD/paraphrasing/temp/models/research/syntaxnet# bazel test ...
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/mnt/c/Sai/RnD/paraphrasing/temp/models/research/syntaxnet/tools/bazel.rc
ERROR: /mnt/c/Sai/RnD/paraphrasing/temp/models/research/syntaxnet/WORKSPACE:10:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.164s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

does anybody know how to solve this

**Comment by gowtham-kp** [comment]
@zhaidejah Can you import tensorflow without any issue?

**Comment by zhaidejah** [comment]
yes

**Comment by gowtham-kp** [comment]
@zhaidejah Can you please answer the below questions
Tensorflow version:
Bazel version:

Thanks!

**Comment by gowtham-kp** [comment]
@zhaidejah Closing this issue due to the lack of recent activity. Please feel free to add additional comments and we can open the issue again. Thanks!
