### ISSUE TITLE
google cloud ML engine + TF-hub universal sentence encoder model prediction error

### ISSUE THREAD

**Issue by Aashish-1008** [tensorflow/hub#292]
Hello,
I trained a text classification model using TF-hub universal sentence encoder.
The model trained successfully and hosted on google cloud ML engine as well.

When i will try to prediction on model using
gcloud ml-engine predict --model $MODEL_NAME --version v1 --json-instances ./request.json
This is error i am getting:

> {"error": "Prediction failed: Error during model execution: 
    AbortionError(code=StatusCode.UNAVAILABLE, details=\"Connect Failed\")"
}

**Comment by gowtham-kp** [comment]
@Aashish-1008. Looks like the client failed to connect with the server. Can you please take a look at the similar [issue](https://github.com/tensorflow/serving/issues/591) and let me know if it helps. Thanks!

**Comment by Aashish-1008** [comment]
That issue, you have linked it’s serving the model using tf-serving.
I have hosted my model on google cloud ml engine which is up and running 
But when i am trying to make predictions using command “ gcloud ml-engine predict _______ “  then it’s gives me this error.

**Comment by Aashish-1008** [comment]
It’s resolved.
I am closing this issue.
