### ISSUE TITLE
Request: Module Download Progress

### ISSUE THREAD

**Issue by ZeroCool2u** [tensorflow/hub#30]
Would it be possible to provide a bit more information on module download progress? I think this would be helpful for larger modules like the USE, because otherwise it seems like they're stalling out. I'd be happy to do the implementation myself and submit a pull request if the authors can point me to an example they'd be happy with. 

Thanks!

**Comment by akhorlin** [comment]
This is similar to request
https://github.com/tensorflow/hub/issues/25. We are working on adding
progress info to the download logic. So we should be able to push it soon.

**Comment by ZeroCool2u** [comment]
Duplicate of #25 

Got it @akhorlin thank you!
