### ISSUE TITLE
Universal Sentence Encoder - Combined Transfer Models

### ISSUE THREAD

**Issue by chiapas** [tensorflow/hub#314]
In section 5.2 **Combined Transfer Models** of the paper **Universal Sentence Encoder**, the authors mentioned

> We explore combining the sentence and word level transfer models by concatenating their representations prior to feeding the combined representation to the transfer task classification layers.

In Table 2, they also have a model USET+CNN (w2v w.e.), which combines sentence embedding and word embeddings for a downstream CNN network for classification tasks.

It's not clear to me how the combination of sentence embedding and word embeddings is done.
Given a sentence, it's sentence embedding is a single vector (here with dim=512). But it produces a sequence of word embeddings (one word embedding, most likely of dim=300,  for each word in the sentence). How these two things (a single vector and a sequence vector, with different dimension) are combined as an input to the CNN network?

Could you explain how the combination is done, how is it used as input to a downstream CNN network. Thanks.

**Comment by rmothukuru** [comment]
@chiapas ,
We separately pool across the top layers of both the CNN and USET. We then concatenate the two pooled representations (CNN+USET) and feed the resulting vectors to additional task specific classification layers.

As the time of the release, USET made use of averaging pooling. We got the CNN from Clara and I believe it made use of max pooling.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
