### ISSUE TITLE
Probabilities of each class

### ISSUE THREAD

**Issue by lovePizza** [tensorflow/hub#317]
How can I get the probabilities of each class during the validation?

**Comment by gowtham-kp** [comment]
@lovePizza 
Here you take argmax of probabilities:

predict = tf.argmax(y_pred, dimension=1)
If you return simply "y_pred" you should get probabilities.
Please let me know if this helps. Thanks!

**Comment by lovePizza** [comment]
Thank you for the link but I'm not able to apply that code to the retrain.py example

**Comment by gowtham-kp** [comment]
Can you please share the code that you are trying to apply @lovePizza

**Comment by lovePizza** [comment]
In the last line I'm only able to print the first class, not all the classes and ther probabilities.

`  test_bottlenecks, test_ground_truth, test_filenames = (
      get_random_cached_bottlenecks(train_session, image_lists,
                                    FLAGS.test_batch_size,
                                    'testing', FLAGS.bottleneck_dir,
                                    FLAGS.image_dir, jpeg_data_tensor,
                                    decoded_image_tensor, resized_image_tensor,
                                    bottleneck_tensor, FLAGS.tfhub_module))

  (eval_session, _, bottleneck_input, ground_truth_input, evaluation_step,
   prediction) = build_eval_session(module_spec, class_count)
  test_accuracy, predictions = eval_session.run(
      [evaluation_step, prediction],
      feed_dict={
          bottleneck_input: test_bottlenecks,
          ground_truth_input: test_ground_truth
      })
print(list(image_lists.keys())[predictions[i]])
`

**Comment by gowtham-kp** [comment]
@lovePizza Did you find the solution?

**Comment by lovePizza** [comment]
I created a custom script based on label_image.py example

**Comment by gowtham-kp** [comment]
@lovePizza  Can you please share the script as it will be useful to the open source community. Thanks!
