### ISSUE TITLE
USE and TF2

### ISSUE THREAD

**Issue by sveah** [tensorflow/hub#319]
Hi there
are the Universal Sentence Encoder Models trainable with Tensorflow 2 beta?

I saw that some hub models got an extra update for tf2 but the USE did not. 

Thanks in advance!

**Comment by gowtham-kp** [comment]
@sveah Universal Sentence Encoder Models are not trainable with Tensorflow 2 beta as of now. We will come up with an update soon. Thanks!

**Comment by gowtham1997** [comment]
@gowtham-kp  Any updates on this?

**Comment by cinash** [comment]
@gowthamkpr is it planned and if yes do you know any rough timeline when it will be available?

**Comment by andriikrupka** [comment]
any updates?

**Comment by vbardiovskyg** [comment]
Hi Andrii,

some of the USE models have been recently published with TF2 compatibility. See for example: https://tfhub.dev/google/universal-sentence-encoder-large/4.
