### ISSUE TITLE
How does the ELMo model compute word embeddings if the learned embeddings are character based?  

### ISSUE THREAD

**Issue by rragundez** [tensorflow/hub#323]
I have reviewed all the issues, the documentation, implementation and several blogs but I can't figure out how to merge the concepts of "word representations using character-based word representations" and that the actual implementation of the model gives word embeddings.

In the original paper is clear that the input to the model are tokens (https://arxiv.org/pdf/1802.05365.pdf) which I can imagine for the model in TFHub those tokens are characters (as stated in the docs). If is not this way it couldn't find embeddings for never seen words. Which it does. So far so good. 
Then the actual pre-trained embeddings in the model are character based, which makes sense as it agrees with explanations in issues, original paper and documentation (https://tfhub.dev/google/elmo/2). 

Then it comes what I don't understand. When I use the model, if I input the single phrase "I do not understand what pulchritudinous means", I will get an output of shape (1, 7, 512) from each LSTM layer, which means the embeddings I am getting back are per word, how is that possible if the embeddings of ELMo are per character?, I would expect an output of size (1, 46, 512) from each layer where each character has its own embedding. 

So I am left with one of the three options:
1. The ELMo implementation in TFHub was actually trained on words as tokens and not character tokens (which means documentation is misleading, many blog posts citing this model in TFHub and answers to issues).
2.   There is something under the hood being done with character embeddings to generate those word embeddings (which is not documented).
3. I'm missing something very obvious and I apologize in advance.

I hope I am clear, if not please ask I will try to clarify. Thanks in advance.

**Comment by gowtham-kp** [comment]
@rragundez ELMo is based off of [arXiv:1602.02410 ](https://arxiv.org/abs/1602.02410), and you should be able to understand once you read Figure 1. More precisely, ELMo uses the configuration in Figure 1(b). Please go through it and let me know if it helps. Thanks!

**Comment by rragundez** [comment]
thanks, I'll have look.
