### ISSUE TITLE
Using hub.create_module_spec with TensorFlow 2.0

### ISSUE THREAD

**Issue by dfalbel** [tensorflow/hub#331]
What's the recommended way to create Module specs with TensorFlow 2.0.

[The guide](https://www.tensorflow.org/hub/creating) uses `tf.placeholder`s in order to define the input signature, but this is not idiomatic TF2.0.

I wonder if it would be possible to get all the information from a `tf.function` with define input signatures, eg. something like this:

```
@tf.function(input_signature=[tf.TensorSpec(shape=None, dtype=tf.float32)])
def f(x): return tf.add(x, 1.)
``` 

Thanks very much!

**Comment by akhorlin** [comment]
We are still in the progress of updating our documentation to reflect TF 2.0 changes. The guide in question hasn't been updated yet. https://github.com/tensorflow/hub/blob/master/examples/text_embeddings_v2/export_v2.py is a better example of how to define and export modules in TF2.

**Comment by dfalbel** [comment]
Great! Thanks very much! So the recommendation is to just use the `tf.saved_model.save` and set the signature via `tf.function` if required. 

One thing that is not really clear to me yet is how do I create a module that exports both the final output and some hidden layers in TF 2.

**Comment by andresusanopinto** [comment]
There has been more documentation changes about creating tf-2 saved models, in particular the following:
 https://github.com/tensorflow/hub/blob/master/docs/tf2_saved_model.md#creating-savedmodels-for-tf-hub
