### ISSUE TITLE
Is it possible to fully fine-tune universal-sentence-encoder-multilingual-qa adding new entries to the existing vocab? 

### ISSUE THREAD

**Issue by adai183** [tensorflow/hub#355]
Sorry. I am aware that there are a couple of related issues. But the responses are a  fuzzy and and also do not seem up to date.

I am building a semantic retrieval application at reply.ai. We have been getting some stunning results with [universal-sentence-encoder-multilingual-qa](https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/1) but our corpus is very domain specific and named entities like product names are crucial. So we need to adjust the vocab to our corpus and fine-tune.

Here are the steps I want to implement:
* Add new tokens to the vocab (there should be a term frequency threshold to decide whether a token makes it into the updated vocab)
* Initialize the embedding vectors of the new vocab entries with the mean vector of the entire vocab
* Retrain and update the weights

Is this possible to integrate with [universal-sentence-encoder-multilingual-qa](https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/1) ?
I can see there is a planned [Cloud AI Workshop](https://aihub.cloud.google.com/u/0/p/products%2F069e31ff-9dd1-4681-a8fe-06ec2ebe490f). I am hoping the workshop will address this.

Thanks in advance to everybody who can help clarify this.

**Comment by vp1993pr** [comment]
Same here. Our corpus is very domain specific. We are getting good results with the pre-trained model, but we need to train it further to include words that are specific to our domain

**Comment by vbardiovskyg** [comment]
Hi, it is not currently unfortunately not possible to add (or change) terms to vocabulary.

**Comment by vitojph** [comment]
Hi, 

Any news on the starting dates for the [experiment on Semantic Similarity for Natural Language](https://aihub.cloud.google.com/u/0/p/products%2F069e31ff-9dd1-4681-a8fe-06ec2ebe490f)? Looking forward to fine tune the models. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been answered. Please add additional comments and we can open the issuer again. Thanks!

**Comment by vbardiovskyg** [comment]
Please see: https://groups.google.com/a/tensorflow.org/forum/#!topic/hub/6ZH6UzKtwgA

**Comment by adai183** [comment]
Hey @vp1993pr !
I can see how it is difficult to to add (or change) terms to vocabulary because of the underlying bucket structure. But I still would like to fine tuned using domain-specific data without modifying the vocab. In the [blogpost](https://ai.googleblog.com/2019/07/multilingual-universal-sentence-encoder.html) it says this is possible. Could you please shed some light on how a training pipeline like this would look like? Maybe there is some public code and I just couldn't find it.
Thank you!

**Comment by ArmandGiraud** [comment]
Hello, 
I have the same issue here, I would like to fine-tune or retrain a model from scratch using this module. I could not find the code or data used for the initial training, only the graph or the paper.
Providing the original code and/or data could be very helpful to understand better the behaviour of the model and possibly design a script to fine-tune on another ranking task. Thank you !

**Comment by bhavsarpratik** [comment]
Hi guys, can we fine-tune the newly released Multilingual USE without adding any vocab as it uses a 128k sentencepiece tokeniser unlike the original which uses GloVe vocab of 400k? 

https://arxiv.org/pdf/1907.04307.pdf
"SentencePiece tokenization (Kudo and Richardson, 2018) is used for all of the 16 languages supported by our models. A single 128k SentencePiece vocabulary is trained from 8 million sentences sampled from our training corpus and balanced across the 16 languages."

**Comment by dayyass** [comment]
Hi, everyone!

I exported mUSE model from TF to PyTorch and I want to share it with you!

The model itself is available in [HF Models](https://huggingface.co/dayyass/universal-sentence-encoder-multilingual-large-3-pytorch), directly through torch (currently, without native support for transformers), the conversion code and the work done itself are available in [GitHub](https://github.com/dayyass/muse_tf2pt).

To be honest, the work was not the easiest, and in fact I completely manually rewrote the TFcalculation graph in PyTorch. I hope that this will be useful, especially given the RAG approaches trend, where good and strong encoders are needed for end-to-end training and fine-tuning 🙏
