### ISSUE TITLE
TF2.0 Tutorial Error 

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/hub#359]
# Here is the colab raised the error.
https://colab.research.google.com/gist/MokkeMeguru/788255c93d4a4d8d4485098a7ba5e9f5/hub_with_keras.ipynb

# Problem
I had tried tf2.0 tutorial (https://www.tensorflow.org/beta/tutorials/images/hub_with_keras).

I found this issue (https://github.com/tensorflow/hub/issues/356), so I change tf_hub version 0.5.0 -> 0.6.0.

But I get this error. 

```
InvalidArgumentError: ValueError: `generator` yielded an element of shape (22, 224, 224, 3) where an element of shape (32, 224, 224, 3) was expected.
Traceback (most recent call last):

  File "/home/meguru/Github/tensorflow-2.0tutorial-with-emacs/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/home/meguru/Github/tensorflow-2.0tutorial-with-emacs/venv/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 621, in generator_py_func
    "of shape %s was expected." % (ret_array.shape, expected_shape))

ValueError: `generator` yielded an element of shape (22, 224, 224, 3) where an element of shape (32, 224, 224, 3) was expected.


	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]
```

I think this is whether because of tf 2.0 or tf hub 0.6.0...

Thanks!

**Comment by maximneumann** [comment]
Thanks for reporting the bug. The issue with the hub version is due to a not updated colab. We will update it soon.

The second issue is not related to hub, and I was able to reproduce it using tf.keras alone. Will file a bug with tf.

**Comment by maximneumann** [comment]
FYI, the second issue was due to ".fit()" needed to be replaced with ".fit_generator()". 
The colab will be updated soon.

**Comment by MokkeMeguru** [comment]
Thanks!  
I experimented with the code. Everything looks fine!

Here is the my updated Colab. https://colab.research.google.com/gist/MokkeMeguru/983ddb62a06c83d7ce1191586014988f/hub_with_keras.ipynb

And It's my hope, Can you print tensorflow and tensorflow_hub's version in your tutorials?

Anyway, if you want to close this issue, you can do it. 
Thanks help!

**Comment by maximneumann** [comment]
Thanks, and good point about having the module versions printed out.
