### ISSUE TITLE
SkipThought fine-tuning for USE

### ISSUE THREAD

**Issue by shiredude95** [tensorflow/hub#360]
Is it possible to fine-tune Universal Sentence encoder for skip-thought like tasks? Assuming we have sentences (ordered) to the order of a million samples, is there a way to do it? The fine tuning examples I have seen are all variations of supervised learning tasks and this would be an unsupervised task. Just wanted to know if this was possible using the current distribution framework.

**Comment by arnoegw** [comment]
I am sorry to say that we have not gotten an answer on this from the model authors. Since this is more of an open-ended question and not an actual issue (bug) with the TH Hub library or models, I am going to close this.
