### ISSUE TITLE
Changing the  input size of Imagenet models?  [Support]

### ISSUE THREAD

**Issue by Moondra** [tensorflow/hub#363]
From the examples I see and what I have tried out, it seems you can't change the 
model input size for Imagenet models?

https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/image_feature_vector.ipynb

This is possible in Keras (applications models) with Tensorflow backend, but tensorflow hub has a more diverse selection of models. So I wanted to try some of those out.

**Comment by arnoegw** [comment]
Some image feature vector models allow variable-size input, while others fix the input size as a side effect of the original module implementation in Python. Please see section "Usage" in the module documentation. For example, https://tfhub.dev/google/imagenet/inception_v3/feature_vector/3 supports variable input sizes.
