### ISSUE TITLE
Loading TF Hub modules in tensorflow.js

### ISSUE THREAD

**Issue by kenjitoyama** [tensorflow/hub#364]
Hi,

Any chance of supporting loading TF Hub modules in tensorflow.js?

Thanks

**Comment by gowthamkpr** [comment]
Please go through the following [link](https://www.tensorflow.org/js/tutorials/conversion/import_saved_model) where you can find how to convert tensorflow graph def based models which include [1. TensorFlow SavedModel 2. Frozen Model 3. Session Bundle 4. Tensorflow Hub module] into Tensorflow.js and let me know if it helps!

**Comment by vbardiovskyg** [comment]
Hi @kenjitoyama, you are right, it's not a great user experience.

We are currently hosting some TF.js models on TF-Hub, although this is very poorly documented.

For example https://tfhub.dev/google/imagenet/mobilenet_v1_025_128/classification/1 is available as a TF.js model and there is a public API on the TF.js side to load it, see https://github.com/tensorflow/tfjs/blob/f94df0f384130940ba1343900a049f8319f7f51e/tfjs-converter/src/executor/graph_model.ts#L286.

It is clear that the messaging of this feature is very poor and we are currently rethinking about how to improve those.

+@dsmilkov from TF.js.

**Comment by vbardiovskyg** [comment]
Please take a look at the new UI, you can find the converted TF.js models for many original models now, for example: https://tfhub.dev/google/imagenet/mobilenet_v1_025_128/classification/1

You should be able to load this (as described on the TF.js tabs) by doing:
tf.loadGraphModel("https://tfhub.dev/google/tfjs-model/imagenet/mobilenet_v1_025_128/classification/1/default/1", { fromTFHub: true })

**Comment by kenjitoyama** [comment]
Cool, that's exactly what I wanted. Thanks, Vojtech!
