### ISSUE TITLE
KerasLayer produces "Non-callable result from hub.load" error when using the universal-sentence-encoder

### ISSUE THREAD

**Issue by hanneshapke** [tensorflow/hub#366]
I would like to reuse the universal sentence encoder in a Keras model. I noticed that the loading of any `universal sentence encoder` model, loaded with the `KerasLayer` with the following code, 
```
embedding = "https://tfhub.dev/google/universal-sentence-encoder/2"
hub_layer = hub.KerasLayer(embedding, input_shape=[], dtype=tf.string, trainable=False)
```

leads to the error below:

```
ValueError: Non-callable result from hub.load('https://tfhub.dev/google/universal-sentence-encoder/2')
```

[Colab notebook to reproduce it](https://colab.research.google.com/drive/1Z1u7m3W9cRTF4hl4tU8w3igqocGKSU1T)

I have tried various combinations of tf versions (1.14, 1.15, tf-nightly, 2.0rc1) and tensorflow_hub (0.5, 0.6, nightly) on CPU hardware.

Also, I went back to the documentation (https://www.tensorflow.org/beta/tutorials/keras/basic_text_classification_with_tfhub) and double-checked the tutorial, the setup of loading the `gnews-swivel-20dim` model. In that case, everything works fine.

I noticed that the `universal-sentence-encoder` model hasn't been converted to TF2, but the `KerasLayer` requires TF2 to run. Is that correct?

There was a similar issue reported. The suggestion was to load the model using `hub.load` and use it as a layer. The loading of the model works in that case, but the dimensions seem misaligned.

```
embedding_url = "https://tfhub.dev/google/universal-sentence-encoder/2"
module = hub.load(embedding_url, tags=[])
input_text = tf.keras.layers.Input(shape=[1], dtype=tf.string)
embedding = module.signatures["default"](input_text)
```

leads to 
```
ValueError: The argument 'text' (value Tensor("input_4:0", shape=(?, 1), dtype=string)) is not compatible with the shape this function was traced with. Expected shape (?,), but got shape (?, 1).
```

[Colab notebook to reproduce it](https://colab.research.google.com/drive/1FNRZigQ3UFGna0K-a1UbpOM4_33IrR83)

How can I correctly load the `universal-sentence-encoder` at this point in time while the hub models are being converted to TF 2.0?

**Comment by gowthamkpr** [comment]
@hanneshapke Answering your question:
`I noticed that the universal-sentence-encoder model hasn't been converted to TF2, but the KerasLayer requires TF2 to run. Is that correct?`
Yes. As mentioned [here](https://github.com/tensorflow/hub/blob/2555031dd854439d99e5349ed9020697aca950c9/tensorflow_hub/keras_layer.py#L75) it requires tensorflow 2.0.

Correct me if I am wrong, But i don't see any error related to 
`ValueError: The argument 'text' (value Tensor("input_4:0", shape=(?, 1), dtype=string)) is not compatible with the shape this function was traced with. Expected shape (?,), but got shape (?, 1).`

My [github gist](https://colab.sandbox.google.com/gist/gowthamkpr/3fe9801ae21906b06883a31ff2fe138a/copy-of-example_keraslayer_tf_hub.ipynb) is here.

**Comment by hanneshapke** [comment]
hi @gowthamkpr, 

I am sorry I accidentally overwrote the colab example. I reverted to the original error message.

Thank you for looking into this issue.

**Comment by andresusanopinto** [comment]
Hi @hanneshapke 

`hub.KerasLayer` is only compatible with newer SavedModels that provide an object based interface compatible with it. E.g. they were created using `tf.saved_model.save()` and they provide among others a "__call__" function. Old hub modules typically only provide signatures and so are not compatible with it. In this case you need to use it via `hub.load()` and then via `.signatures`.

Additionally it is the case that the text modules expect a signature of (?,) meaning just a tensor of rank 1 containing the sentences to embed (a batch of strings). However Keras uses a convention of passing rank 2 and the code you tried ends up passing a tensor of rank 2 (i.e. a batch of vectors of length 1 containing a string). So you will need to make the shapes match. For example:

```
input_text = tf.reshape(input_text, [-1])
embedding = module.signatures["default"](input_text)
```

Note: KerasLayer does not explicitly requires eager mode or tf-2. It should work fine in a recent tf-1.x in graph mode.

**Comment by hanneshapke** [comment]
Hi @andresusanopinto 
Thank you for the response and explanations. I tried the reshaping of the input text, unfortunately that also didn't work.

```
input_text = tf.keras.layers.Input(shape=(1,), dtype=tf.string)
input_text = tf.reshape(input_text, [-1])
embedding = module.signatures["default"](input_text)
dense = tf.keras.layers.Dense(256, activation='relu')(embedding)
pred = tf.keras.layers.Dense(category_counts, activation='softmax')(dense)
model = tf.keras.models.Model(inputs=input_text, outputs=pred)
```

caused this error
```
ValueError: invalid literal for int() with base 10: 'default'
```
on tensorflow `'1.15.0-dev20190821'`.

What has worked in the meantime was a suggestion by @uglyboxer. He mentioned that he saw a hub load operation as part of a `CustomLayer` in Keras. The code below worked for me and I happy to use it until all tf hub models are converted.

```
class UniversalEmbeddingLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        self.output_dimensions = 512
        super(UniversalEmbeddingLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.usenet = hub.Module('https://tfhub.dev/google/universal-sentence-encoder/2', trainable=False,
                               name="{}_module".format(self.name))

        try:
            tf.global_variables_initializer().run(session=K.get_session())
            tf.tables_initializer().run(session=K.get_session())
        except Exception:
            pass
        super(UniversalEmbeddingLayer, self).build(input_shape)

    def call(self, x, **kwargs):
        x = tf.reshape(x, shape=(-1,))
        vector = self.usenet(
            inputs=dict(text=x, ), as_dict=True, signature='default')['default']
        return vector

    def compute_output_shape(self, **kwargs):
        return self.output_dimensions
```

For odd reasons, the reshaping operation works within the `CustomLayer` `call` method.
