### ISSUE TITLE
Universal Sentence Encoder large 3 Tensorflow

### ISSUE THREAD

**Issue by nandhini2312** [tensorflow/hub#367]

**Comment by nandhini2312** [comment]
I need to train the model with  my own corpus of doman specific data.Can anyone help me.And also I need to improve the speed of USE.

**Comment by gowthamkpr** [comment]
@nandhini2312 As mentioned in this [issue](https://github.com/tensorflow/hub/issues/155) please note thet you can train your data on USE but the vocabulary (English) is fixed. So, if your vocabulary is extending outside the vocabulary that USE is trained on, you might get biased results.

**Comment by nandhini2312** [comment]
I need to add and train the domain specific vocabulary to USE.Please,help
me to resolve the problem.

**Comment by nandhini2312** [comment]
Please add me some implemented code for my reference.

**Comment by gowthamkpr** [comment]
As of now USE cannot support domain specific vocabulary as mentioned in the issue [#155 ](https://github.com/tensorflow/hub/issues/155)@nandhini2312 But you can follow this [answer](https://github.com/tensorflow/hub/issues/110#issuecomment-407111353) to train USE on your data but please keep in mind that this will not help your case if you have too many domain specific words

**Comment by gowthamkpr** [comment]
Closing this issue as it has been answered. Please add additional comments and we can open the issue again. Thanks!
