### ISSUE TITLE
TF hub in sagemaker

### ISSUE THREAD

**Issue by rv-ltran** [tensorflow/hub#368]
How do I import tensorflow hub into AWS sagemaker? I'm looking to use this model https://tfhub.dev/google/universal-sentence-encoder/1

**Comment by rmothukuru** [comment]
@rv-ltran ,
Can you please let us know if you have tried importing TF Hub as mentioned in [this link](https://www.tensorflow.org/hub)?

If you have tried executing the commands mentioned in the above link, is it resulting in error, and if so, can you please provide the error log.

**Comment by rv-ltran** [comment]
<img width="1126" alt="1" src="https://user-images.githubusercontent.com/49695537/65183297-3214fe00-da31-11e9-9bc0-3eb03f023bfc.png">
<img width="1143" alt="2" src="https://user-images.githubusercontent.com/49695537/65183298-3214fe00-da31-11e9-8b00-b68551247815.png">
<img width="1041" alt="3" src="https://user-images.githubusercontent.com/49695537/65183299-3214fe00-da31-11e9-90ee-5a3ed11f2de8.png">
<img width="1124" alt="4" src="https://user-images.githubusercontent.com/49695537/65183300-3214fe00-da31-11e9-8f11-f28702912147.png">




I have performed the following commands, and got the errors (attached):

!pip install "tensorflow_hub==0.4.0"
!pip install "tf-nightly"
import tensorflow as tf
import tensorflow_hub as hub

**Comment by rmothukuru** [comment]
@rv-ltran,
I ran your comments in a fresh virtual environment and I could successfully install and import Tensorflow and TF_Hub.
Can you create a New Virtual Environment in Anaconda and execute those commands and let me know if your issue is resolved.
Thanks!

**Comment by rv-ltran** [comment]
I opened a new notebook (conda-python3) within AWS Sagemaker , and ran these cmmds but still receiving the errors (attached). Did I follow your instruction correctly?

![1](https://user-images.githubusercontent.com/49695537/65185915-84a4e900-da36-11e9-86ff-b2acefb85f54.png)
![2](https://user-images.githubusercontent.com/49695537/65185916-84a4e900-da36-11e9-9af0-05d089dbd31d.png)
![3](https://user-images.githubusercontent.com/49695537/65185917-84a4e900-da36-11e9-93fd-73eb4267b0f7.png)

**Comment by akhorlin** [comment]
In general we haven't looked into sagemaker support yet but looking at the error message it seems there is an issue with importing tensorflow. Have you tried running a simple tensorflow program without tf hub to see if everything works properly?

**Comment by rv-ltran** [comment]
I switched to kernel conda-tensorflow and was able to import tensorflow. However, when I tried to import "https://tfhub.dev/google/universal-sentence-encoder/2", I ran into an error of RuntimeError: variable_scope module_3/ was unused but the corresponding name_scope was already taken.

<img width="1133" alt="Screen Shot 2019-09-23 at 9 58 54 AM" src="https://user-images.githubusercontent.com/49695537/65432199-c93ed480-dde8-11e9-9172-88778594f98e.png">

**Comment by rv-ltran** [comment]
Nvm, I removed tf.enable_eager_execution() cmmd and it works

**Comment by arghyaganguly** [comment]
Closing this based on the previous comment from @rv-ltran.Thanks.
