### ISSUE TITLE
KerasLayer failure in Keras 2.2.5 with USE module

### ISSUE THREAD

**Issue by LanceNorskog** [tensorflow/hub#374]
I'm having a little trouble using the KerasLayer class with the Universal Sentence Embedding modules. Keras 2.2.5, Tensorflow Hub 0.6.

Here's a test program:
[KerasLayer_bug_report.txt](https://github.com/tensorflow/hub/files/3684211/KerasLayer_bug_report.txt)

And here is the output. 

[KerasLayer_bug_report.txt](https://github.com/tensorflow/hub/files/3684225/KerasLayer_bug_report.txt)

This is the input specification for the USE module: 
`{'text': <hub.ParsedTensorInfo shape=(?,) dtype=string is_sparse=False>}`

I don't know how to create a matching spec shape, but is seems like this shape should be '(1,)'.

**Comment by rmothukuru** [comment]
@LanceNorskog,
You have attached the same file for the `Test Program` and the `Bug Report`. Can you please provide the error details, which would help us in reproducing the error. 

Also, can you please let us know what version of Tensorflow you are using. Thanks!

**Comment by LanceNorskog** [comment]
Oops! It's Tensorflow 1.14.0. 

Test program:
[KerasLayer_bug_report.txt](https://github.com/tensorflow/hub/files/3687927/KerasLayer_bug_report.txt)


Bug output:
[KerasLayer_bug_output.txt](https://github.com/tensorflow/hub/files/3687930/KerasLayer_bug_output.txt)

This is the input spec for the loaded module: 
`{'text': <hub.ParsedTensorInfo shape=(?,) dtype=string is_sparse=False>}`

**Comment by arnoegw** [comment]
The crucial line in your code is 

```python
model = hub.KerasLayer(hub.Module(module_url), ...)
```

It's not meant to be done that way. Please see our recently updated documentation on TF1 and TF2 modules, esp. https://www.tensorflow.org/hub/migration_tf2#loading_legacy_hubmodules

**Comment by arnoegw** [comment]
(You'll need tensorflow-hub 0.7 and ideally also tensorflow 2.0/1.15.)
