### ISSUE TITLE
what does  tf.image.convert_image_dtype(img, tf.float32)[tf.newaxis, ...] means?

### ISSUE THREAD

**Issue by sunshuofeng** [tensorflow/hub#376]
I don't understand 【tf.newaxis,...】what this code does. Would you like to help me understand this code?

**Comment by rmothukuru** [comment]
@sunshuofeng,
As per my understanding, this issue is related to Tensorflow, and not related to TF Hub. You can raise an issue in [Tensorflow Repo](https://github.com/tensorflow/tensorflow/issues), which will be looked into by Tensorflow Experts. Thanks!

**Comment by sunshuofeng** [comment]
i'm sorry about that and thank you
