### ISSUE TITLE
is hub/examples/image_retraining/retrain.py  can be used by tensorflow2.0?

### ISSUE THREAD

**Issue by btdan** [tensorflow/hub#381]
Hello, I use the command :
  python retrain.py  --image_dir ./flower_photos
with tensorflow2.0, and then get several error:
such as 
AttributeError: module 'tensorflow' has no attribute 'app'
AttributeError: module 'tensorflow' has no attribute 'gfile'
etc
Can you tell me how to solve this problem?
Thanks very much

**Comment by andresusanopinto** [comment]
That file requires TF-1.x, but we revamped that script as a tool in tf-hub pip repository.

Have a look at:
https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier

Which is made for TF-2.x
