### ISSUE TITLE
tfhub model SSGAN 128x128 seems unavailable

### ISSUE THREAD

**Issue by RuiLiFeng** [tensorflow/hub#382]
Hi TFhub team, I've found that the SSGAN model which the authors claim still on tfhub with link https://tfhub.dev/google/compare_gan/ssgan_128x128/1    is unavailable now. We open an issue (https://github.com/google/compare_gan/issues/33 )on the author's github repo, and he/she said that he could make sure it still works. He/she suggest me to contact tfhub team for more support.  I search the key word 'SSGAN' in tfhub, it shows no model found.
![image](https://user-images.githubusercontent.com/33709183/66639031-a87bd900-ec48-11e9-9d55-9b151599af0d.png)
![image](https://user-images.githubusercontent.com/33709183/66639039-a9ad0600-ec48-11e9-9f84-8ef84f248ec3.png)
I am looking forward to your help!

**Comment by andresusanopinto** [comment]
Thanks for reporting. It has been fixed.
