### ISSUE TITLE
How this two sentence are so similar

### ISSUE THREAD

**Issue by dheerajiiitv** [tensorflow/hub#387]
**Sentence 1"** - "Airtel is a big reputed telecom company.  I would be proud to work for a company with such a long history of leadership in the telecom industry. Leaders of airtel are someone to look upto. They are highly professional and very innovative. Millions of customers are in airtel network and I want to make a necessary contribution in service. big platform with lots of opportunities. I heard about your company good culture, employee benefits.- As it is the largest telecom it will definitely help in the growth of my career. Want a career change, to reallocate, big branded company.",

**Sentence 2"** - "in april 2015 acquired a delhi-based mobile marketing automation firm"

Vectors are calculated using USE-large version 3

**Cosine similarity between this two sentence is ** - 0.65 

Can someone tell me how this two-sentence so similar.

**Comment by dheerajiiitv** [comment]
This two-sentence are not at all relevant to each

**Comment by rmothukuru** [comment]
@dheerajiiitv,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gowthamkpr** [comment]
@dheerajiiitv USE is mainy used to find the semantic textual similarity between the sentences. I tried to visualize the similarity between the embededding of the sentences given below [here](https://colab.sandbox.google.com/gist/gowthamkpr/a9b02ebd10d6e3c64dcf046a5459b608/semantic-similarity-with-tf-hub-universal-encoder.ipynb).

messages = [
    # Smartphones
    "I like my phone",
    "My phone is not good.",
    "Your cellphone looks great.",

    # Weather
    "Will it snow tomorrow?",
    "Recently a lot of hurricanes have hit the US",
    "Global warming is real",
    
    #company1
    "Airtel is a big reputed telecom company. I would be proud to work for a company with such a long history of leadership in the telecom industry. Leaders of airtel are someone to look upto. They are highly professional and very innovative. Millions of customers are in airtel network and I want to make a necessary contribution in service. big platform with lots of opportunities. I heard about your company good culture, employee benefits.- As it is the largest telecom it will definitely help in the growth of my career. Want a career change, to reallocate, big branded company."

    
    # Food and health
    "An apple a day, keeps the doctors away",
    "Eating strawberries is healthy",
    "Is paleo better than keto?",

    # Asking about age
    "How old are you?",
    "what is your age?",
    

    #company
    "in april 2015 acquired a delhi-based mobile marketing automation firm"

  ]

You can actually see that the similarty between the two sentences mentioned is a bit high but you have to realize that the Universal sentence encoder(USE) is looking for semantics to the words in the sentence itself.

Fore example lets say if you add sentences [1] and [2]
[1]"Airtel is a big reputed telecom company. I would be proud to work for a company with such a long history of leadership in the telecom industry."
[2] "in april 2015 acquired a delhi-based mobile marketing automation firm"

the resultant sentance would be
"Airtel is a big reputed telecom company. I would be proud to work for a company with such a long history of leadership in the telecom industry. In april 2015 acquired a delhi-based mobile marketing automation firm" which does make some sense. This is how USE is coming to that conclusion.

For more indepth understanding on how it exactly  derives the embeddings,  can go through this [paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46808.pdf).
