### ISSUE TITLE
Universal Sentence Embedding Inference Speed

### ISSUE THREAD

**Issue by r-wheeler** [tensorflow/hub#39]
More of a general question, but is there a way to speed up multiple calls to the Universal Sentence embedding module when trying to run inference on batches of 1? 

For example: 
After creating a session and initializing global variables- 
```
%%time 
r2 = session.run(embed(['and this is another test'], signature='default'))
CPU times: user 10.9 s, sys: 8 ms, total: 10.9 s
Wall time: 10.9 s
```

And again with new data
```
%%time 
r2 = session.run(embed(['test it a second time'], signature='default'))
CPU times: user 10.6 s, sys: 8 ms, total: 10.6 s
Wall time: 10.6s
```

Is there something being reloaded at ever call?
Outside of running on a GPU is it possible to speed up the inference for subsequent calls? 

When profiling the tensorflow code with `Timeline` and viewing the trace with chrome trace, the total execution time of all the ops is less than 1 second. Any thoughts?

**Comment by andresusanopinto** [comment]
You should use tensorflow graph building vs graph execution mechanisms. See answer for a similar question in: https://groups.google.com/a/tensorflow.org/d/msg/hub/ONjFEdpJFp8/si6Vpk_QAwAJ
