### ISSUE TITLE
Embeddings for context (Multilingual QA Embedding)

### ISSUE THREAD

**Issue by coderTazz** [tensorflow/hub#393]
Hi, I was wondering if we can also somehow retrieve the embedding of the response_contexts which are used to generate response embeddings in [https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/1](https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/1).

While I am aware that the model supports only response and question signatures, I also wanted to retrieve the embeddings of the context that the model uses.

Are they embeddings from the standard TensorFlow Universal sentence encoder or something else? 

Thanks in advance! and thanks also for the amazing library.

**Comment by gowthamkpr** [comment]
@coderTazz We do not currently expose the signature to get the embedding for response context at this time.
