### ISSUE TITLE
TypeError: len() of unsized object when loading tensorflow dataset

### ISSUE THREAD

**Issue by ReemSuwaileh** [tensorflow/hub#395]
I'm trying to follow this tutorial for text classification: https://github.com/tensorflow/hub/blob/master/examples/colab/tf2_text_classification.ipynb

with the following configs:
`Version:  2.0.0
Eager mode:  True
Hub version:  0.6.0
GPU is NOT AVAILABLE`

However, when I try loading the dataset using this line:
`train_data, test_data = tfds.load(name="imdb_reviews", split=["train", "test"], batch_size=-1, as_supervised=True)`

I get the following error:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-0dbf7da0e006> in <module>()
----> 1 train_data, test_data = tfds.load(name="imdb_reviews", split=["train", "test"], batch_size=-1, as_supervised=True)
      2 train_examples, train_labels = tfds.as_numpy(train_data)
      3 test_examples, test_labels = tfds.as_numpy(test_data)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\registered.py in load(name, split, data_dir, batch_size, in_memory, shuffle_files, download, as_supervised, decoders, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    312   as_dataset_kwargs.setdefault("shuffle_files", shuffle_files)
    313 
--> 314   ds = dbuilder.as_dataset(**as_dataset_kwargs)
    315   if with_info:
    316     return ds, dbuilder.info

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in as_dataset(self, split, batch_size, shuffle_files, decoders, as_supervised, in_memory)
    418         in_memory=in_memory,
    419     )
--> 420     datasets = utils.map_nested(build_single_dataset, split, map_tuple=True)
    421     return datasets
    422 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    151     if isinstance(data_struct, tuple(types)):
    152       mapped = [map_nested(function, v, dict_only, map_tuple)
--> 153                 for v in data_struct]
    154       if isinstance(data_struct, list):
    155         return mapped

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py in <listcomp>(.0)
    151     if isinstance(data_struct, tuple(types)):
    152       mapped = [map_nested(function, v, dict_only, map_tuple)
--> 153                 for v in data_struct]
    154       if isinstance(data_struct, list):
    155         return mapped

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    157         return tuple(mapped)
    158   # Singleton
--> 159   return function(data_struct)
    160 
    161 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in _build_single_dataset(self, split, shuffle_files, batch_size, decoders, as_supervised, in_memory)
    481     if batch_size:
    482       # Use padded_batch so that features with unknown shape are supported.
--> 483       dataset = dataset.padded_batch(batch_size, dataset.output_shapes)
    484 
    485     if as_supervised:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py in padded_batch(self, batch_size, padded_shapes, padding_values, drop_remainder)
   1095     """
   1096     return PaddedBatchDataset(self, batch_size, padded_shapes, padding_values,
-> 1097                               drop_remainder)
   1098 
   1099   def map(self, map_func, num_parallel_calls=None):

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py in __init__(self, input_dataset, batch_size, padded_shapes, padding_values, drop_remainder)
   3346     self._padding_values = nest.map_structure_up_to(
   3347         input_shapes, _padding_value_to_tensor, padding_values,
-> 3348         get_legacy_output_types(input_dataset))
   3349     self._drop_remainder = ops.convert_to_tensor(
   3350         drop_remainder, dtype=dtypes.bool, name="drop_remainder")

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\util\nest.py in map_structure_up_to(shallow_tree, func, *inputs)
    469                          for input_tree in inputs]
    470 
--> 471   results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
    472   return pack_sequence_as(structure=shallow_tree, flat_sequence=results)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\util\nest.py in <listcomp>(.0)
    469                          for input_tree in inputs]
    470 
--> 471   results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
    472   return pack_sequence_as(structure=shallow_tree, flat_sequence=results)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py in _padding_value_to_tensor(value, output_type)
   3286     TypeError: if the padding value's type does not match `output_type`.
   3287   """
-> 3288   value = ops.convert_to_tensor(value, name="padding_value")
   3289   if not value.shape.is_compatible_with(tensor_shape.TensorShape([])):
   3290     raise ValueError("Padding value should be a scalar, but is not: %s" % value)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py in convert_to_tensor(value, dtype, name, preferred_dtype, dtype_hint)
   1182   preferred_dtype = deprecation.deprecated_argument_lookup(
   1183       "dtype_hint", dtype_hint, "preferred_dtype", preferred_dtype)
-> 1184   return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
   1185 
   1186 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py in convert_to_tensor_v2(value, dtype, dtype_hint, name)
   1240       name=name,
   1241       preferred_dtype=dtype_hint,
-> 1242       as_ref=False)
   1243 
   1244 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx, accept_composite_tensors)
   1294 
   1295     if ret is None:
-> 1296       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1297 
   1298     if ret is NotImplemented:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_conversion_registry.py in _default_conversion_function(***failed resolving arguments***)
     50 def _default_conversion_function(value, dtype, name, as_ref):
     51   del as_ref  # Unused.
---> 52   return constant_op.constant(value, dtype, name=name)
     53 
     54 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in constant(value, dtype, shape, name)
    225   """
    226   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 227                         allow_broadcast=True)
    228 
    229 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    233   ctx = context.context()
    234   if ctx.executing_eagerly():
--> 235     t = convert_to_eager_tensor(value, ctx, dtype)
    236     if shape is None:
    237       return t

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
     94       dtype = dtypes.as_dtype(dtype).as_datatype_enum
     95   ctx.ensure_initialized()
---> 96   return ops.EagerTensor(value, ctx.device_name, dtype)
     97 
     98 

ValueError: TypeError: len() of unsized object
`

**Comment by gowthamkpr** [comment]
@ReemSuwaileh Tried reproducing it on colab but was unable to reproduce it. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/a573b15623f0b56b9673c20d7cbafc5e/basic-text-classification.ipynb). Also can you uninstall and install your anaconda or execute the example in a clean environment and let me know if it works. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 10 days. Please add additional commnts and we can open the issue again. Thanks!
