### ISSUE TITLE
USE vectors consistent across implementations? 

### ISSUE THREAD

**Issue by ydennisy** [tensorflow/hub#397]
I have a few questions regarding USE, sorry if this is not the correct place to post them.

My primary question is wether using the USE Lite model and USE Large for example produces vectors which can be compared between each other? For example I am using USE Large on the server and the lite version on a mobile device.

Stemming from this I would like to understand how the lite version is so much smaller, I believe around 30x smaller - is this just down to a smaller vocab?

**Comment by gowthamkpr** [comment]
@ydennisy You can actually go through this [blog](https://blog.rasa.com/compressing-bert-for-faster-prediction-2/) which gives you much clearer idea of why lite models are very small compared to the original version of the model.

Also this is not a hub related issue, its more related [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) repo as your question is mainly based on Tensorflow Lite.

**Comment by ydennisy** [comment]
@gowthamkpr Can you help out on the main part of the questions? Are vectors usable across implementations?
