### ISSUE TITLE
Importing TF1 model into TF2 hub - unable to create python object.

### ISSUE THREAD

**Issue by ydennisy** [tensorflow/hub#398]
I have managed to import USE model using the new `hub.load` API as per the migration guide. However I am seeing an error for what looks like each separate variable.

The error:

```
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'Encoder_en/hidden_layers/tanh_layer_0/bias:0' shape=(512,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
```

How would one suppress this warning?

Or even better fix the source :)

**Comment by jeon11** [comment]
Hey @ydennisy I am getting the same warning messages in tensorflow 2.0 version. When I use:
```
module_url = "https://tfhub.dev/google/universal-sentence-encoder/2"

embed = hub.load(module_url)
```
I get a bunch of warning print outs saying unable to create a python object for variable. Did you manage to fix this problem?

**Comment by ydennisy** [comment]
Yeah I just switched off the warning messages!

There is no way to fix this without recreating the model.

**Comment by arnoegw** [comment]
I'm happy to report that many versions of Universal Sentence Encoder have been republished in the new TF2 SavedModel format. When using `hub.load()` or `hub.KerasLayer`, please use those new versions, such as https://tfhub.dev/google/universal-sentence-encoder/3 and the others linked from its documentation.

I guess that obviates the need to go back to the TF1 versions and fix their variable type.

**Comment by jeon11** [comment]
Oh great. Thank you. I'll take a look at them!

**Comment by ibrahimishag** [comment]
> Hey @ydennisy I am getting the same warning messages in tensorflow 2.0 version. When I use:
> 
> ```
> module_url = "https://tfhub.dev/google/universal-sentence-encoder/2"
> 
> embed = hub.load(module_url)
> ```
> 
> I get a bunch of warning print outs saying unable to create a python object for variable. Did you manage to fix this problem?

I hope you were able to fix this. I am ran into this problem when I converted an old TF checkpoint (.ckpt) to .pb and tried to load it using TF-hub under TF2. 
After printing a bunch of Warnings, it also prints error message that reads:
ValueError: Signature name has to be specified for non-callable saved models (if not legacy Hub.Module).
