### ISSUE TITLE
Why do I get "ValueError: Unknown layer: KerasLayer" while converting from .hdf5 to .tflite?

### ISSUE THREAD

**Issue by osemars** [tensorflow/hub#401]
Hello, I used a pretrained model from Tensorflow hub to train on my data and it gave me significantly higher val_acc. I saved the model as a .hdf5 file and intend to convert it into .tflite so I can import to my android application. This is the code I used in converting:

from tensorflow_core.lite.python.lite import TFLiteConverter
model_path = 'C:/Users/1/Desktop/data_sets/86%.hdf5'
converter = TFLiteConverter.from_keras_model_file(model_path)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

it outputs "ValueError: Unknown layer: KerasLayer"

I am using tf version 2.0.

This is how I saved the model. The below code was in a callback.
ModelCheckpoint(filepath=data_dir + '/weights.hdf5', monitor='val_accuracy',
 verbose=1, save_best_only=True, save_weights_only=False, mode='auto', period=1)
![issue](https://user-images.githubusercontent.com/33398656/68009343-0452e400-fc82-11e9-9795-0b3bb1a2d7ab.PNG)

**Comment by gowthamkpr** [comment]
Pleae take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/26835#issuecomment-499368554) and it should help you in resolving the issue.

**Comment by osemars** [comment]
thanks @gowthamkpr . it gave a different error message "tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to import metagraph, check error log for more info."

**Comment by gowthamkpr** [comment]
@osemars What version of tensorflow are you using, Can you please post the entire errormessage. Also please provide some reproducible code for me to reproduce the issue.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been in awaiting response for more than a week. Please add additional comments and we can open the issue again. Thanks!

**Comment by Gaurav37** [comment]
I am getting same error. How did you resolve it?
