### ISSUE TITLE
KerasLayers are not trainable in Tensorflow 2.0.0

### ISSUE THREAD

**Issue by r-wheeler** [tensorflow/hub#407]
`tensorflow==2.0.0`
`tensorflow-hub==0.7.0` 

With a very minimal example, the weights of albert and other modules do not show as trainable.

```
import tensorflow as tf 
import tensorflow_hub as hub

input_ids = tf.keras.layers.Input(shape=[None], dtype=tf.int32)
input_mask = tf.keras.layers.Input(shape=[None], dtype=tf.int32)
sequence_mask = tf.keras.layers.Input(shape=[None], dtype=tf.int32)

albert = hub.KerasLayer(
    "https://tfhub.dev/google/albert_xlarge/2",
    trainable=True,
    signature="tokens",
    output_key="pooled_output",
)

features = {
    "input_ids": input_ids,
    "input_mask": input_mask,
    "segment_ids": sequence_mask,
}
out = albert(features)
model = tf.keras.Model(inputs=[input_ids, input_mask, sequence_mask], outputs=out)
model.compile("adam", loss="sparse_categorical_crossentropy")
model.summary()
```

Produces the following summary: 
```
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_28 (InputLayer)           [(None, None)]       0                                            
__________________________________________________________________________________________________
input_29 (InputLayer)           [(None, None)]       0                                            
__________________________________________________________________________________________________
input_30 (InputLayer)           [(None, None)]       0                                            
__________________________________________________________________________________________________
keras_layer_60 (KerasLayer)     (None, 2048)         59017392    input_28[0][0]                   
                                                                 input_29[0][0]                   
                                                                 input_30[0][0]                   
==================================================================================================
Total params: 59,017,392
Trainable params: 0
Non-trainable params: 59,017,392
```
Expected Behavior: Trainable variables of Albert or bert models to be shown as trainable parameters

Observed Behavior: There are 0 trainable parameters shown in the model summary when setting trainable to `True`. 

#402 also mentions this with elmo.

**Comment by r-wheeler** [comment]
A colleague of mine pointed out that some of the models are not yet ported over to save model v2 per the [list of v2 saved models](https://tfhub.dev/s?format=saved_model_2&module-type=text-embedding)  and additionally documented [here](https://www.tensorflow.org/hub/tf2_saved_model). 

Is it planned to eventually support all 1.* legacy assets to be fine tunable in the new api?

**Comment by arnoegw** [comment]
The problem here is indeed with the model format: `hub.KerasLayer(..., trainable=True)` does not work as expected for models in the hub.Module format for TF1.

I'll look into better error messaging. I have no specific news on upgrading the format of albert_large at this time.

**Comment by arnoegw** [comment]
@r-wheeler, thank you for reporting this. While I have no immediate solution for albert (that depends on the model publisher), at least commit https://github.com/tensorflow/hub/commit/a98a141209e6639e7ca3e44b458a289c45a828ee will provide clearer messaging for users in the future. It will go out eventually with tensorflow-hub 0.8.0.
