### ISSUE TITLE
Impossible to use saved model USE4 with KerasLayer

### ISSUE THREAD

**Issue by andriikrupka** [tensorflow/hub#409]
According to sample ([Transfer learning with TensorFlow Hub](https://www.tensorflow.org/tutorials/images/transfer_learning_with_hub)), I try to finetune universal sentence encoder (version 4):

```
use_url = "https://tfhub.dev/google/universal-sentence-encoder-large/4"


feature_extractor_layer = hub.KerasLayer(use_url, input_shape=[], 
                           dtype=tf.string, trainable=True)
model = tf.keras.Sequential([
    feature_extractor_layer,
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.summary()

model.predict([['hello']]) 

import time
t = time.time()

export_path = "/tmp/saved_models/{}".format(int(t))
model.save(export_path, save_format='tf')

reloaded = tf.keras.models.load_model(export_path)

```

when I try predict from my reloaded model I get error:

```
reloaded.predict([["hello"]])
```

> FailedPreconditionError:  Table not initialized.
> 	 [[{{node keras_layer_22_1/cond/else/_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor_1/hash_table_Lookup/hash_table_Lookup/LookupTableFindV2}}]] [Op:__inference_keras_scratch_graph_1888313]
> 
> Function call stack:
> keras_scratch_graph

ps
> tf.__version__
> '2.0.0'

**Comment by gowthamkpr** [comment]
@arnoegw Was able to replicate this bug. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/8ab7605eb059a7c58f33fa557cd43ab9/untitled225.ipynb).

**Comment by arnoegw** [comment]
Thank you, @andriikrupka and @gowthamkpr, for the report. Your code seems to work for https://tfhub.dev/google/nnlm-en-dim50/2 (arguably the simplest text embedding with a lookup table). I've reached out to the module publisher for the specifics of U.S.E.

**Comment by eduardofv** [comment]
It seems the model has been updated to solve this issue ([v5](https://tfhub.dev/google/universal-sentence-encoder-large/5))
But I've filed another issue regarding trainable KerasLayer for this and for USEv4 (not large): #437

**Comment by arnoegw** [comment]
Hi @eduardofv, let me close this issue then, and defer to https://github.com/tensorflow/hub/issues/437 for the rest. (There seems to be a fix for it already.)
