### ISSUE TITLE
Unable to load model from Tensorflow Hub  following issue are raised:     

### ISSUE THREAD

**Issue by rameez471** [tensorflow/hub#410]
``embedding = 'https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1'
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:3])

Error:
OSError: https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1 does not appear to be a valid module.

**Comment by gowthamkpr** [comment]
Similar to the issue here
