### ISSUE TITLE
Unable to train model with USE4 in KerasLayer

### ISSUE THREAD

**Issue by jdeason23** [tensorflow/hub#417]
The example works to produce a tensor based on a provided sentence, but when trying to build a model with the embedding layer, it errors.

embed_layer = hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder-large/4",input_shape=[],dtype=tf.string,trainable=True)

model = tf.keras.Sequential()
model.add(embed_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.summary()

The Output shape looks odd - why the dictionary
Model: "sequential"

Layer (type)                         Output Shape                   Params 
keras_layer (KerasLayer)     {'outputs': (None, 512)}  147354880 
dense (Dense)                             (None, 16)                8208      
dense_1 (Dense)                          (None, 1)                 17 

Total params: 147,363,105
Trainable params: 147,363,105
Non-trainable params: 0

history = model.fit(train_dataset,
                    validation_data=validation_dataset,
                    epochs=30,
                    verbose=1
                   )

ERROR:
ValueError: Error when checking input: expected keras_layer_input to have 1 dimensions, but got array with shape ()

**Comment by gowthamkpr** [comment]
I did it using colab and I was able to run it successfully. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/af1c2e2cf758ce090ffe87505aeedb2c/copy-of-basic-text-classification.ipynb).
