### ISSUE TITLE
USE MultiLingual Large 2 unable to load in Google Colab

### ISSUE THREAD

**Issue by vprelovac** [tensorflow/hub#418]
https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/2

is not possible to use in Google Colab due to tf-sentencepiece incompability.

Tried with TF 1.14.0 and TF 2.0.0.

Please provide an example how to use this model in Colab.

**Comment by arnoegw** [comment]
Hi @vprelovac, thanks for your message. Please see the excellent summary by @brenting in issue https://github.com/tensorflow/hub/issues/404#issuecomment-553983816

I suppose that will resolve your problem. If not, please reopen.

**Comment by vprelovac** [comment]
@arnoegw It would be wonderful if USEML documentation would be updated to reflect that fact as I lost an entire morning on this

**Comment by arnoegw** [comment]
https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/2 says

> ## Prerequisites
> This module relies on the Tensorflow Text for input preprocessing. On Google Colaboratory,
> the  Tensorflow Text library is available by:
>
> ```shell
> !pip3 install tensorflow_text>=2.0.0rc0
> ```

@brenting concurs in https://github.com/tensorflow/hub/issues/404#issuecomment-553983816

What exactly would you like to have changed?
