### ISSUE TITLE
Universal Sentence encoder Multilingual V2-V3 (Received a feature column from TensorFlow v1, ...)

### ISSUE THREAD

**Issue by aykonsvk** [tensorflow/hub#420]
I'm using new V2 https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/2

That should be  trained on Tensorflow 2. But when I add it as feature I receive this message 

> ValueError: Received a feature column from TensorFlow v1, but this is a TensorFlow v2 Estimator. Please either use v2 feature columns (accessible via tf.feature_column.* in TF 2.x) with this Estimator, or switch to a v1 Estimator for use with v1 feature columns (accessible via tf.compat.v1.estimator.* and tf.compat.v1.feature_column.*, respectively.

This is example of my code:

```
description_embeddings = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/2")

multi_label_head = tf.estimator.MultiLabelHead(
    n_classes=3,
    loss_reduction=tf.losses.Reduction.SUM_OVER_BATCH_SIZE 
)

labels = np.array(train_encoded).astype(np.float32)

def train_input_fn():
  data = tf.data.Dataset.from_tensor_slices(({"descriptions": np.array(train_txt).astype(np.str)}, labels) )
  data_batches = (
      data.cache().repeat().shuffle(500)
      .prefetch(tf.data.experimental.AUTOTUNE))
  return data_batches

estimator = tf.estimator.DNNEstimator(
    model_dir='My model Dir,
    head=multi_label_head,
    hidden_units=[64,10], 
    feature_columns=[description_embeddings])

estimator.train(input_fn=train_input_fn, steps=1000)
```

Isnt there left code from tensorflow 1?

**Comment by gowthamkpr** [comment]
@aykonsvk Can you please share the colab gist of this issue. I am running into a errors. Please find my gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/48f095575c0a9d39d779cf1dc9185590/untitled243.ipynbhttps://colab.sandbox.google.com/gist/gowthamkpr/48f095575c0a9d39d779cf1dc9185590/untitled243.ipynb). Thanks!

**Comment by aykonsvk** [comment]
@gowthamkpr your gist is not working :) Here is simple reproduction of my issue [https://colab.research.google.com/drive/1KUU6JPla5V0PEPcRopeHoeYg2xP2gCx_](https://colab.research.google.com/drive/1KUU6JPla5V0PEPcRopeHoeYg2xP2gCx_)

**Comment by gowthamkpr** [comment]
@j-grimstad @vbardiovskyg Can you PTAL. Thanks!

**Comment by tangwiki** [comment]
Any update this issue? Thanks.

**Comment by vbardiovskyg** [comment]
Update: we are actively working on this and trying to find a good solution. I will update the issue when that succeeds.

**Comment by aykonsvk** [comment]
Hey, I tried it with a new V3 version and that is still not working

**Comment by vbardiovskyg** [comment]
Hi Martin,

the feature_column_v2 has been submitted (https://github.com/tensorflow/hub/blob/master/tensorflow_hub/feature_column_v2.py#L57) and will be included in the next release.

If you want to try it out (early test) before the release, you can build TF-Hub from source: https://github.com/tensorflow/hub/blob/master/docs/build_from_source.md.

**Comment by aykonsvk** [comment]
@vbardiovskyg Thank you a lot! I'm going to try it a right now.

**Comment by aykonsvk** [comment]
It looks like that Universal Sentence encoder Multilingual needs to be recompiled with that new method.

**Comment by vbardiovskyg** [comment]
That shouldn't be the case, the new feature column is just a wrapper around the model. What error did you get?

**Comment by aykonsvk** [comment]
```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-40-7e5239b2e166> in <module>()
     62     feature_columns=[description_embeddings])
     63 
---> 64 estimator.train(input_fn=train_input_fn, steps=1000)

7 frames

/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/dnn.py in __init__(self, units, hidden_units, feature_columns, activation_fn, dropout, batch_norm, name, **kwargs)
    303       else:
    304         raise ValueError(
--> 305             'Received a feature column from TensorFlow v1, but this is a '
    306             'TensorFlow v2 Estimator. Please either use v2 feature columns '
    307             '(accessible via tf.feature_column.* in TF 2.x) with this '

ValueError: Received a feature column from TensorFlow v1, but this is a TensorFlow v2 Estimator. Please either use v2 feature columns (accessible via tf.feature_column.* in TF 2.x) with this Estimator, or switch to a v1 Estimator for use with v1 feature columns (accessible via tf.compat.v1.estimator.* and tf.compat.v1.feature_column.*, respectively.


```

**Comment by vbardiovskyg** [comment]
Ok, that's because you haven't actually created a feature column, please take a look at https://github.com/tensorflow/hub/blob/master/tensorflow_hub/feature_column_v2_test.py#L179 for some examples.

**Comment by aykonsvk** [comment]
@vbardiovskyg  Now I have completely different error. 
```
module_url = 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'
description_embeddings = hub.text_embedding_column_v2("descriptions", module_path=module_url, trainable=False)
# description_embeddings = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")
```
This is the message:
```
---------------------------------------------------------------------------

NotImplementedError                       Traceback (most recent call last)

<ipython-input-52-962e2a6fcbbe> in <module>()
      1 module_url = 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'
----> 2 description_embeddings = hub.text_embedding_column_v2("descriptions", module_path=module_url, trainable=False)
      3 # description_embeddings = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")

/usr/local/lib/python3.6/dist-packages/tensorflow_hub/feature_column_v2.py in text_embedding_column_v2(key, module_path, output_key, trainable)
     77   """
     78   if not hasattr(feature_column_v2.StateManager, "has_resource"):
---> 79     raise NotImplementedError("The currently used TensorFlow release is not "
     80                               "compatible. To be compatible, the symbol "
     81                               "tensorflow.python.feature_column."

NotImplementedError: The currently used TensorFlow release is not compatible. To be compatible, the symbol tensorflow.python.feature_column.feature_column_v2.StateManager.has_resource must exist.

```

**Comment by vbardiovskyg** [comment]
Right, the requiredTensorFlow changes has not been probably released yet, this is a very new feature.

Can you please try with 
```
pip uninstall tensorflow
pip install tf-nightly
```

**Comment by aykonsvk** [comment]
I tried that also :)  Okay in that case I will wait until it is supported :) Anyway than you a lot for support!! 
```
NotImplementedError                       Traceback (most recent call last)

<ipython-input-7-962e2a6fcbbe> in <module>()
      1 module_url = 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'
----> 2 description_embeddings = hub.text_embedding_column_v2("descriptions", module_path=module_url, trainable=False)
      3 # description_embeddings = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")

/usr/local/lib/python3.6/dist-packages/tensorflow_hub/feature_column_v2.py in text_embedding_column_v2(key, module_path, output_key, trainable)
     77   """
     78   if not hasattr(feature_column_v2.StateManager, "has_resource"):
---> 79     raise NotImplementedError("The currently used TensorFlow release is not "
     80                               "compatible. To be compatible, the symbol "
     81                               "tensorflow.python.feature_column."

NotImplementedError: The currently used TensorFlow release is not compatible. To be compatible, the symbol tensorflow.python.feature_column.feature_column_v2.StateManager.has_resource must exist.


---------------------------------------------------------------------------
NOTE: Current TensorFlow version is 2.1.0. To use TF 1.x instead,
restart your runtime (Ctrl+M .) and run "%tensorflow_version 1.x" before
you run "import tensorflow".
---------------------------------------------------------------------------
```

**Comment by vbardiovskyg** [comment]
Sounds good, btw the code snippet is saying that you are running 2.1.0.

If are running from colab, I think you have to restart the kernel before doing
```
!pip uninstall tensorflow
!pip install tf-nightly
```

Your version should show something more like: `tf-nightly 2.2.0.dev20200330`

**Comment by vbardiovskyg** [comment]
Hi, with the tensorflow-hub=0.8.0 release a new implementation of feature columns (https://github.com/tensorflow/hub/blob/master/tensorflow_hub/feature_column_v2.py#L57) is available that applies TF2.0 Saved Models.

This is dependent on changes in TensorFlow core, so until TensorFlow makes a new release (most likely tensorflow==2.2.0), it will need `tf-nightly` to work.

**Comment by andresusanopinto** [comment]
The missing feature from tensorflow to be able to use "hub.text_embedding_column_v2" will be in the tensorflow==2.3 release (which already has a release candidate).

Closing issue since there is nothing left to do from tensorflow_hub side. Just use the release candidate or wait for the 2.3 to have a stable release..
