### ISSUE TITLE
Image preprocessing for transfer learning confusing

### ISSUE THREAD

**Issue by jsgonsette** [tensorflow/hub#422]
I'm really confused about what preprocessing to apply on image data when working with pre-trained models for transfer learning. Of course, this is very specific for each model, but I thought Keras brought some disambiguation by bringing the preprocess_input function. By using it, users should normally not worry about how to transform an image before pushing it into the pre-trained model.

I recently tried to use one of such model provided in Tensorflow 2.Keras. Even if this function exists, the related documentation is, let's say, minimal:
https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet_v2/preprocess_input

But what is very disturbing is that this function is not used at all in the provided tutorials. For example, this one (https://www.tensorflow.org/tutorials/images/transfer_learning_with_hub) pre-processes images by dividing raw pixels by 255.

    image_generator = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1/255)

In this other tutorial (https://www.tensorflow.org/tutorials/images/transfer_learning), pre-processing is done like this:

    image = (image/127.5) - 1

However, both tutorial are supposed to use a mobilenet_v2 model pre-trained on ImageNet

This makes 3 different ways to process an image, without any helping documentation to shed some light on what appears to me like "black magic". Any help would be welcome, along with an appropriate documentation of course.

**Comment by arnoegw** [comment]
The proliferation of different conventions for the range of pixel values is unfortunate.

TF Hub promotes the convention to keep all pixel values in the range [0,1], which is what TF provides out of the box when decoding an image and then using `tf.image.convert_image_dtype(..., tf.float32)`. This is stated clearly in the model documentation found at the same URL.

**Comment by jsgonsette** [comment]
Sorry for this inconvenience. However, if there is such a proliferation of questions about the pixel value range, this may be because it is indeed, well, not clear.

If I understand you well, TF Hub takes the convention for the range [0,1], but for the second tutorial the convention is obviously [-1,1], and none of them takes care to use the provided Keras function "preprocess_input", for an unknown reason. If everybody is happy with this very clear definition, I will not argue anymore.

**Comment by getsanjeevdubey** [comment]
@jsgonsette Were you able to find anything convincing on this?
