### ISSUE TITLE
which version is universal-sentence-encoder-multilingual having transformer architecture?

### ISSUE THREAD

**Issue by Cumberbatch08** [tensorflow/hub#425]
there are some url link`https://storage.googleapis.com/tfhub-modules/` about use-multilingual, but nothing about them. I want to to use the transformer architecture no the DAN.
So, who can tell me the describution about the pretrained module?

**Comment by gowthamkpr** [comment]
@Cumberbatch08 You can try using **universal-sentence-encoder-multilingual-large** which is [here](https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/2) It is based on the paper [here](https://arxiv.org/abs/1810.12836) which uses a transformer architecture. You can refer to the following [paper](https://arxiv.org/pdf/1810.12836.pdf).

**Comment by gowthamkpr** [comment]
@Cumberbatch08 I am closing this issue as it has been answered. Please add additional comments and we can open this issue again.
