### ISSUE TITLE
Converting USE-QA v2 to KerasLayer

### ISSUE THREAD

**Issue by xhlulu** [tensorflow/hub#427]
The model: https://tfhub.dev/google/universal-sentence-encoder-qa/2

Is it possible to convert that module to three separate `KerasLayer`s i.e., one for "question_embedding" and one for "response_embedding"? I figured out that for we could leverage the signatures to create the keras layers, i.e.:

```python
import tensorflow_hub as hub
module = hub.load("https://tfhub.dev/google/universal-sentence-encoder-qa/2")
qemb = hub.KerasLayer(module.signatures['question_embedding'])
remb = hub.KerasLayer(module.signatures['response_embedding'])
```

although `qemb` can be correctly added to a Keras `Model` using the functional API, `remb` cannot, since it specifically takes two inputs: "input" and "context".

Is there a way to correctly resolve this? Thanks!

**Comment by jaxlaw** [comment]
For question_encoder you can use:

```
module_url = "https://tfhub.dev/google/universal-sentence-encoder-qa/3"
hub.KerasLayer(module_url, input_shape=[], dtype="string", signature='question_encoder', output_key='outputs')
```

and for multiple inputs with response_encoder, you can use the keras functional API, e.g. :

```
import tensorflow.compat.v2 as tf
import tensorflow_hub as hub

module_url = "https://tfhub.dev/google/universal-sentence-encoder-qa/3"
i = tf.keras.Input((), dtype='string', name='input')
c = tf.keras.Input((), dtype='string', name='context')
outputs = hub.KerasLayer(module_url, input_shape=[], dtype="string", signature='response_encoder', output_key='outputs')({'input': i, 'context': c})

model = tf.keras.Model(inputs={'input': i, 'context': c}, outputs=outputs)
model.predict({'input':tf.constant(["Hello"]), 'context':tf.constant(["World"])})
```
