### ISSUE TITLE
The universal-sentence-encoder-multilingual-qa and universal-sentence-encoder-qa seems to have extremely similar pages on AIHub. 

### ISSUE THREAD

**Issue by XMK233** [tensorflow/hub#431]
Hi, Team. 

I just notice that [`universal-sentence-encoder-multilingual-qa`](https://aihub.cloud.google.com/p/products%2F558c8a34-563c-481c-baca-887e082794be
) and [`universal-sentence-encoder-qa`](https://aihub.cloud.google.com/p/products%2F8150e0fd-bcf2-4cb0-8cc0-942cb4d93d60) seems to have extremely similar pages on AIHub. 

In my humble opinion, their pages should not be that similar. For example, their reference papers should be not the same. The `universal-sentence-encoder-multilingual-qa` should refer to 2 papers and `universal-sentence-encoder-qa` should refer to the original paper [Universal Sentence Encoder](https://arxiv.org/abs/1803.11175).  

So I guess the page of `universal-sentence-encoder-qa` should be similar to the page of the original page [`universal-sentence-encoder`](https://aihub.cloud.google.com/p/products%2F79c78579-2208-4f1c-ab08-c0d94f2adad1)

Am I right?

I'm a SE researcher so I regard the pages as documentation, and I think it will be important. That's why I raise such an issue. 

Thank you.

**Comment by j-grimstad** [comment]
@XMK233 

Thanks for the feedback -- I'll follow up with the model publisher internally to see what they think.

**Comment by j-grimstad** [comment]
@XMK233 

Hi, sorry for the delayed reply -- here's what the model publisher shared with me with respect to the differences (lightly edited for clarity):

> 1. They use different vocab / tokenization, we can see USE-QA is larger
> than USE-MLING-QA as the vocab difference.
> 
> 2. USE-QA covers English only and USE-Mling-QA covers 16 languages.
> 
> 3. As it is English specific, USE-QA has better performance on English.

The publisher will also update the documentation (potentially as soon as today) to better clarify these differences. Hope this helps -- please reopen if you have further questions.
