### ISSUE TITLE
Example Missing the correct import statement of TensorFlow_hub

### ISSUE THREAD

**Issue by shivajid** [tensorflow/hub#432]
import tensorflow as tf

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/3")
embeddings = embed([
    "The quick brown fox jumps over the lazy dog.",
    "I am a sentence for which I would like to get its embedding"])["outputs"]

print embeddings

**Comment by maximneumann** [comment]
Thank you for informing us about it, and we'll correct this asap.
