### ISSUE TITLE
URLs "Run in Google Colab" and "View source on GitHub" are reversed.

### ISSUE THREAD

**Issue by Elucidation** [tensorflow/hub#434]
The URL links at the head of http://github.com/tensorflow/hub/blob/master/examples/colab/object_detection.ipynb are reversed in order (ie. 'Run in Google Colab' links to github source, and 'View source on GitHub' links to the colab)

**Comment by j-grimstad** [comment]
Not sure if this was somehow fixed in the meantime, but the links appear to be correct/properly ordered for me -- please double check & reopen if I'm missing something.
