### ISSUE TITLE
Minimal code for Fine Tuning and Exporting TF2 Module

### ISSUE THREAD

**Issue by meethariprasad** [tensorflow/hub#438]
In TF2 Module Document or even in examples given, it is not clear on minimal code to fine tune a module and export for reuse.
https://www.tensorflow.org/hub/tf2_saved_model#creating_savedmodels_for_tf_hub

Let us take simple example of finetuning below. I am not not sure how can I export hub_layer which gets fine tuned to export, so that I can reuse as hub.Module() and get fine tuned embeddings.

#Fine Tuning TF2 Module using simple keras network. 
```
hub_layer = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim50/2",
                           input_shape=[], dtype=tf.string,trainable=True)

model = keras.Sequential()
model.add(hub_layer)
model.add(keras.layers.Dense(16, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop', loss='binary_crossentropy')

model.summary()
from tensorflow import keras
text_values_list=['java','hadoop','.net']
labels=[0,0,1]
model.fit(x=text_values_list,y=labels,epochs=100)
```

**Comment by arnoegw** [comment]
For [TF2 SavedModels](https://www.tensorflow.org/hub/tf2_saved_model) like https://tfhub.dev/google/nnlm-en-dim50/2, please use an approach along the lines of

```python
# Do tf.saved_model.load(), but from a Hub URL.
obj = hub.load("https://tfhub.dev...")
hub_layer = hub.KerasLayer(obj, trainable=True, ...)
# Use hub_layer in a Model and .fit() it.
tf.saved_model.save(obj, "/your/local/target/dir")
```

The result can then be loaded again in the style of
```python
hub.KerasLayer("/your/local/target/dir")
```

For the deprecated [TF1 hub.Modules](https://www.tensorflow.org/hub/tf1_hub_module), there is [`hub.Module.export()`](https://www.tensorflow.org/hub/api_docs/python/hub/Module#export) for the analogous purpose. Note that TF1 hub.Modules cannot be fine-tuned in a TF2-style hub.KerasLayer.

**Comment by meethariprasad** [comment]
> For [TF2 SavedModels](https://www.tensorflow.org/hub/tf2_saved_model) like https://tfhub.dev/google/nnlm-en-dim50/2, please use an approach along the lines of
> 
> ```python
> # Do tf.saved_model.load(), but from a Hub URL.
> obj = hub.load("https://tfhub.dev...")
> hub_layer = hub.KerasLayer(obj, trainable=True, ...)
> # Use hub_layer in a Model and .fit() it.
> tf.saved_model.save(obj, "/your/local/target/dir")
> ```
> 
> The result can then be loaded again in the style of
> 
> ```python
> hub.KerasLayer("/your/local/target/dir")
> ```
> 
> For the deprecated [TF1 hub.Modules](https://www.tensorflow.org/hub/tf1_hub_module), there is [`hub.Module.export()`](https://www.tensorflow.org/hub/api_docs/python/hub/Module#export) for the analogous purpose. Note that TF1 hub.Modules cannot be fine-tuned in a TF2-style hub.KerasLayer.

Thanks for reply. I will revert post experimentations. I strongly feel an example similar to your simple and straight explanation must go in to TFHub main document on fine tuning. Current doc is abstract.

**Comment by arnoegw** [comment]
Hi @meethariprasad, if your experiments succeed, I'd be very happy to incorporate a verified (but brief) recipe into our documentation. Feel free to send me a pull request that adds a new subsubsection

```
# Fine-Tuning
## For SavedModel consumers
### Re-exporting the fine-tuning result
```
in https://github.com/tensorflow/hub/blob/master/docs/tf2_saved_model.md below. The GitHub UI should let you do that with the pencil icon shown on the top right of that file (select "Create a new branch for this commit and start a pull request" if applicable).

**Comment by meethariprasad** [comment]
> ### Re-exporting the fine-tuning result

@arnoegw : I did the quick experiment an it is working as expected. I have requested the pull on same and added the text and code. Please feel free to correct it or let me know if it needs to be corrected. Thanks for guidance.

**Comment by arnoegw** [comment]
I'm sorry, I don't see it yet at [https://github.com/tensorflow/hub/pulls](https://github.com/tensorflow/hub/pulls).

**Comment by meethariprasad** [comment]
> I'm sorry, I don't see it yet at https://github.com/tensorflow/hub/pulls.

I am bit new to this. I am getting following error and signed CLA too. Is it coming now?

All checks have failed
1 failing check
@googlebot
cla/google — Need a CLA for one or more commit authors
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

**Comment by meethariprasad** [comment]
Re-exporting the fine-tuning result
Following section has minimal example for fine tuning a simple text embedding module like NNLM, exporting it and reusing the module from exported path to get fine tuned embedding.

Please note following facts about fine tuning a word embedding module.

Fine Tuning will not add Out of Vocabulary Words to Exported Module.
Fine tuning modifies the Variables Associated with Hash Buckets which generate Out of Vocabulary Embeddings.
Fine tuning loose generalization, if not done cautiously as explained in Fine Tuning section above.
```
#Let us fine tune using a simple objective function of classification, to bring two words together.

#Caution: Please note the other weights also change during fine tuning loosing generalization. Tune with Caution!
```


```
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow import keras


module_obj=hub.load("https://tfhub.dev/google/nnlm-en-dim50/2")
hub_layer=hub.KerasLayer(module_obj,trainable=True,input_shape=[], dtype=tf.string)

model = keras.Sequential()
model.add(hub_layer)
model.add(keras.layers.Dense(16, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy')

#A simple classification problem, briging related wordds together.
test=['hive','hadoop','.net']
labels=[0,0,1]
model.fit(x=text_values_list,y=labels,epochs=50)
model.summary()

import os
os.makedirs("finetuned_module_export", exist_ok=True)
export_module_dir = os.path.join(os.getcwd(), "finetuned_module_export")
tf.saved_model.save(module_obj, export_module_dir)

import tensorflow_hub as hub
import pandas as pd
import numpy as np
print ("export_module_dir",export_module_dir)
finetuned_exported_hub_path=export_module_dir
embed = hub.KerasLayer(finetuned_exported_hub_path)
embeddings = embed(test)
```
Complete example with similiarity comparision and notes can be found [here].(https://github.com/meethariprasad/phd/blob/master/TF2_Fine_Tuning_Minimal_Coding_Experiment.ipynb)

**Comment by meethariprasad** [comment]
> Re-exporting the fine-tuning result
> Following section has minimal example for fine tuning a simple text embedding module like NNLM, exporting it and reusing the module from exported path to get fine tuned embedding.
> 
> Please note following facts about fine tuning a word embedding module.
> 
> Fine Tuning will not add Out of Vocabulary Words to Exported Module.
> Fine tuning modifies the Variables Associated with Hash Buckets which generate Out of Vocabulary Embeddings.
> Fine tuning loose generalization, if not done cautiously as explained in Fine Tuning section above.
> 
> ```
> #Let us fine tune using a simple objective function of classification, to bring two words together.
> 
> #Caution: Please note the other weights also change during fine tuning loosing generalization. Tune with Caution!
> ```
> 
> ```
> import tensorflow as tf
> import tensorflow_hub as hub
> from tensorflow import keras
> 
> 
> module_obj=hub.load("https://tfhub.dev/google/nnlm-en-dim50/2")
> hub_layer=hub.KerasLayer(module_obj,trainable=True,input_shape=[], dtype=tf.string)
> 
> model = keras.Sequential()
> model.add(hub_layer)
> model.add(keras.layers.Dense(16, activation='relu'))
> model.add(keras.layers.Dense(1, activation='sigmoid'))
> model.compile(optimizer='rmsprop', loss='binary_crossentropy')
> 
> #A simple classification problem, briging related wordds together.
> test=['hive','hadoop','.net']
> labels=[0,0,1]
> model.fit(x=text_values_list,y=labels,epochs=50)
> model.summary()
> 
> import os
> os.makedirs("finetuned_module_export", exist_ok=True)
> export_module_dir = os.path.join(os.getcwd(), "finetuned_module_export")
> tf.saved_model.save(module_obj, export_module_dir)
> 
> import tensorflow_hub as hub
> import pandas as pd
> import numpy as np
> print ("export_module_dir",export_module_dir)
> finetuned_exported_hub_path=export_module_dir
> embed = hub.KerasLayer(finetuned_exported_hub_path)
> embeddings = embed(test)
> ```
> 
> Complete example with similiarity comparision and notes can be found [here].(https://github.com/meethariprasad/phd/blob/master/TF2_Fine_Tuning_Minimal_Coding_Experiment.ipynb)

This is the change I wanted to add and commit through pull request.

**Comment by meethariprasad** [comment]
> > I'm sorry, I don't see it yet at https://github.com/tensorflow/hub/pulls.
> 
> @arnoegw I am bit new to this. I am getting following error. I signed CLA too now to get rid of this error as instructed by google bot. Is it coming now? Any thing Else I need to do?
> 
> All checks have failed
> 1 failing check
> @googlebot
> cla/google — Need a CLA for one or more commit authors
> This branch has no conflicts with the base branch
> Only those with write access to this repository can merge pull requests.

Sorry. My bad. I had to say @googlebot I signed it! for it to make CLA=Yes :-) Now I did the same and it must be coming in pull request.

**Comment by arnoegw** [comment]
Thanks, I'm seeing https://github.com/tensorflow/hub/pull/444 now. That will cover the docs improvement you suggested. I'll follow up with comments there.

Closing this now, as the original issue has been resolved.
