### ISSUE TITLE
[hub+MirroredStrategy]  much slower than [tf.keras.applications + MirroredStrategy]

### ISSUE THREAD

**Issue by soldier828** [tensorflow/hub#440]
# Question: 
I found when using hub+MirroredStrategy, GPU utility is very low. However, tf.keras.applications+MirroredStrategy gpu utility is very high to ~90%.  
Maybe I use tf-hub in wrong way? Please have a look.

# ENV:
 Centos6.3 + tensorflow2 + 4 V-100 gpus in single machine
<img width="361" alt="tf2-env" src="https://user-images.githubusercontent.com/10766225/70589354-7bc54d00-1c0a-11ea-8b3c-1dcd4cdb1a29.png">

# Full Code:
```
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub
import os
import ssl

num_epochs = 5
batch_size_per_replica = 64
num_classes = 2
input_size = 224

learning_rate = 0.001

strategy = tf.distribute.MirroredStrategy()
print('Number of devices: %d' % strategy.num_replicas_in_sync)  
batch_size = batch_size_per_replica * strategy.num_replicas_in_sync
assert strategy.num_replicas_in_sync == 4


def resize(image, label):
    image = tf.image.resize(image, [input_size, input_size]) / 255.0
    return image, label

dataset = tfds.load("cats_vs_dogs", split=tfds.Split.TRAIN, as_supervised=True)
dataset = dataset.map(resize, num_parallel_calls=tf.data.experimental.AUTOTUNE).shuffle(1024).batch(batch_size)
dataset = dataset.prefetch(tf.data.experimental.AUTOTUNE)


# ----- use tf.keras.applications + MirroredStrategy -----
with strategy.scope():
    base_model = tf.keras.applications.MobileNetV2()
    base_model.trainable = True
    model = tf.keras.Sequential([base_model, tf.keras.layers.Dense(num_classes, activation='softmax')])
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        loss=tf.keras.losses.sparse_categorical_crossentropy,
        metrics=[tf.keras.metrics.sparse_categorical_accuracy]
    )
model.summary()

# ----- use hub + MirroredStrategy -----
# with strategy.scope():
#     hub_add = "https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/classification/4"
#     base_model = hub.KerasLayer(hub_add)
#     base_model.trainable = True
#     model = tf.keras.Sequential([base_model,  tf.keras.layers.Dense(num_classes, activation='softmax')])
#     model.build([None, input_size, input_size, 3])  # Batch input shape.
#     model.compile(
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         loss=tf.keras.losses.sparse_categorical_crossentropy,
#         metrics=[tf.keras.metrics.sparse_categorical_accuracy]
#     )
# model.summary()

model.fit(dataset, epochs=num_epochs)
```

# Related screenshots:
- hub+MirroredStrategy
<img width="746" alt="hub-arch" src="https://user-images.githubusercontent.com/10766225/70588223-0310c180-1c07-11ea-8d4d-aeababbe9582.png">

<img width="1204" alt="hub-epoch2" src="https://user-images.githubusercontent.com/10766225/70588308-40754f00-1c07-11ea-87c6-b317de8a5f03.png">

use nvidia-smi dmon, the last column is gpu utility.
<img width="285" alt="hub-gpu" src="https://user-images.githubusercontent.com/10766225/70588366-71558400-1c07-11ea-9d79-440255894fd4.png">

- tf.keras.applications+MirroredStrategy
<img width="739" alt="keras-arch" src="https://user-images.githubusercontent.com/10766225/70588342-57b43c80-1c07-11ea-9c7b-c69a2b9b7875.png">
<img width="1194" alt="keras-epoch2" src="https://user-images.githubusercontent.com/10766225/70588311-41a67c00-1c07-11ea-8889-d88d101dc9f2.png">

use nvidia-smi dmon, the last column is gpu utility.
<img width="291" alt="keras-gpu" src="https://user-images.githubusercontent.com/10766225/70588714-98f91c00-1c08-11ea-9fba-1f9cfc504071.png">

**Comment by arnoegw** [comment]
Please try installing a recent tf-nightly-gpu PIP package. In TF2.0 and TF2.1rc0, there are known issues with MirroredStrategy and SavedModels.

**Comment by soldier828** [comment]
> Please try installing a recent tf-nightly-gpu PIP package. In TF2.0 and TF2.1rc0, there are known issues with MirroredStrategy and SavedModels.

Thanks！  
One more thing. Where could I get these type of known issues? In Tensorflow GitHub repo issue or any other suggestions?

**Comment by arnoegw** [comment]
TensorFlow and TensorFlow Hub are the right GitHub repos to look at. As it happened, this particular issue was not reported externally, though, before you did.

**Comment by gowthamkpr** [comment]
@soldier828 Did installing `tf-nightly-gpu` resolve the issue? Thanks!

**Comment by soldier828** [comment]
> @soldier828 Did installing `tf-nightly-gpu` resolve the issue? Thanks!

I tried in Dec and didn't solve that time.

**Comment by phiwei** [comment]
Is it possible that this issue still persists in tensorflow 2.1? Speed difference is one order of magnitude when using a hub model VS keras.applications.

**Comment by rmothukuru** [comment]
@soldier828,
Can you please check and let us know if your issue is resolved? Thanks!

**Comment by rmothukuru** [comment]
@soldier828,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
