### ISSUE TITLE
Is there any model for se-resnext ?

### ISSUE THREAD

**Issue by angryhen** [tensorflow/hub#441]
I didn't find anything about se-resnet series

**Comment by arnoegw** [comment]
Thanks for expressing your interest in Squeeze-and-Excitation ResNe[x]t. You are right that tfhub.dev has none at the moment. I'll keep this issue open to track this, but there is no concrete timeline I could advise of.

**Comment by WGierke** [comment]
Hi @angryhen 
Unfortunately, we currently don't have bandwidth to work on training & publishing these models. I'm thus closing this issue for now but will add a comment if the models get published in the future. As always, we are happy to receive contributions!
