### ISSUE TITLE
Need for Inbuilt Input Text Normalizer for Embedding Modules

### ISSUE THREAD

**Issue by meethariprasad** [tensorflow/hub#449]
Dear TF Team,

Minor suggestion.

I have recently seen when an unnormalized text enters in to embedding module with hidden characters, its embedding significantly changes compared to the one without these hidden characters and affects similarity. In large and diverse text corpus it is indeed a problem.

Is it a fair expectation to have normalization code ( or ignore hidden characters!?) in built in to embedding modules (if they are not already present) so that consumers of module need not worry about the normalization of text?

I completely understand Garbage in Garbage out philosophy, but I believe this implementation will improve the usability.

**Comment by vbardiovskyg** [comment]
Hi @meethariprasad, in many of the models, there already is a built in normalization logic. This logic might be different on a per model basis.

In general it is hard to design a normalization logic that works well for everything (especially with UTF8 input), but what would help here is some real examples of when does the embedding change considerably on what inputs. If that will show to have a very high impact on model usability, then that would be a good feature request for the publisher.
