### ISSUE TITLE
Why is XLNet not on Tensorflow Hub?

### ISSUE THREAD

**Issue by PradyumnaGupta** [tensorflow/hub#451]
I want to know that why are not Xlnet models hosted on tensorflow hub ? It would be so much useful , since the current official implementation requires a lot of setup . Xlnet hosted on hub will make it so much easier to use it simply as a TF layer as well......

**Comment by vbardiovskyg** [comment]
Thanks for opening the issue, XLNet would be a great addition to TF-Hub. Let's keep this open to track interest for the future.

**Comment by xhlulu** [comment]
@PradyumnaGupta XLNet is available in the `transformers` library as a tensorflow 2.0 model; in theory it would be possible to convert it into a Hub Module!

**Comment by Xyz35** [comment]
XLnet is implemented and available on the tensorflow official model repository.
Link :- https://github.com/tensorflow/models/tree/master/official/nlp/xlnet

**Comment by rgrupesh** [comment]
How to import XLnet on tensorflow?

**Comment by tgsmith61591** [comment]
@Xyz35 having the model architecture implemented is really handy, but it doesn't solve the original issue. Anyone wanting to use XLNet would need to completely train its embeddings from scratch. Is there any plan to publish the embedding weights as a `saved_model` on tf-hub?
