### ISSUE TITLE
Wrong link provided for bert_en_uncased_L-12_H-768_A-12

### ISSUE THREAD

**Issue by vishalkesti382** [tensorflow/hub#452]
The copy URL to clipboard button on the TensorFlow hub website for bert_en_uncased_L-12_H-768_A-12 points to [https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1](url) whereas the correct link is [https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1](url). Kindly verify and update the page.

**Comment by gowthamkpr** [comment]
I see that both the links are working but to use the hub module you have to use the link below as shown in the code. 
```
bert_layer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1",
                            trainable=True)
```
I think https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1 is the right link. Correct me if I am wrong. Thanks!

**Comment by gowthamkpr** [comment]
I am closing this issue as it has been resolved. Please add additional comments and we can open this issue again. Thanks!
