### ISSUE TITLE
sequence_output of bert lose the dimension "max_seq_len"

### ISSUE THREAD

**Issue by iamxpy** [tensorflow/hub#457]
I am building a model using bert from tf hub, but when I pass my batch to bert, the sequence_output of bert layer seems to lose the dimension "max_seq_len".

the code I wrote:

```python
question_bert_layer = hub.KerasLayer(BERT_PATH, trainable=False)
_, question_sequence_output = question_bert_layer(
        [input_question_ids, input_question_masks, input_question_segments])
print(question_sequence_output.shape)
```
what I expected:
the shape of question_sequence_output shoud be `[None, max_seq_len, 768]`

what I got:
the shape of question_sequence_output is actually `[None, None, 768]`

why would this happened? And can I set the output shape, especially the max_seq_len dimension of bert layer? I need this because the following layer use the max_seq_len and it cannot be `None`, may be I can explicitly pass my actual max_seq_len to the following layer?

**Comment by albertnanda** [comment]
@iamxpy Did you find out the reason for [None, None, 768] ?
