### ISSUE TITLE
How to control the max_seq_len of BERT when using hub.KerasLayer()?

### ISSUE THREAD

**Issue by iamxpy** [tensorflow/hub#458]
I tried to split my text and feed them to multiple bert, thus recdusing the `max_seq_len` of bert and save memory. But even if I specify the `output_shape` of bert layer by using `hub.KerasLayer(BERT_PATH, output_shape=[[768], [BERT_SEQUENCE_LEN, 768]], trainable=True)`, the number of parameters does not decrease.
 
Without splitting, my model contains two bert layers, the actual `max_seq_len` in this case is `512`(see the shape of several Input layer). And the number of param is about **200 million**, which is dominated by the two bert layers.

![before](https://user-images.githubusercontent.com/20579310/71428056-353b1c80-26f9-11ea-9414-5803c13d7252.png)

As far as I know, the main part of self-attention in Bert is just some Matrix multiplication, so the number of parameters should be `O(n^2)` where `n` is `max_seq_len` or `hidden_size`.

Then I design another arch, split the text example and feed it to multiple bert, each of which will have reduced parameters depending on how much parts I split the text into. But the model summary tells me the number of parameters is about  **800 million** when I split each text into **4**. The actual `max_seq_len` now is 128 already, see the shape of the Input Layers. Why the number of param doesn't decrease? 

![after_1](https://user-images.githubusercontent.com/20579310/71428427-b1cefa80-26fb-11ea-887d-239f146319b7.png)
![after_2](https://user-images.githubusercontent.com/20579310/71428459-d4611380-26fb-11ea-9a7d-6c5a07d6ddb7.png)

I thought it may be because I didn't specify the `max_seq_len` of bert. I found [this flag](https://github.com/google-research/bert/blob/cc7051dc592802f501e8a6f71f8fb3cf9de95dc9/run_classifier.py#L64) in original bert, but I don't know the corresponding one in `hub.KerasLayer()` for controlling the `max_seq_len`.

If you have any suggestions, please let me know! It would be highly appreciated!

**Comment by arnoegw** [comment]
For the record: @iamxpy has posted a solution at https://stackoverflow.com/questions/59483067/hub-keraslayer-always-comsumes-the-same-gpu-memory-despite-the-changing-max-se

**Comment by arnoegw** [comment]
...and also at https://github.com/tensorflow/hub/issues/459
