### ISSUE TITLE
Examples or Reasons for usage of Distance Based on Arc Cosine for Similiarity in USE Paper

### ISSUE THREAD

**Issue by meethariprasad** [tensorflow/hub#462]
Dear TF Hub Team,

USE [paper ](https://arxiv.org/pdf/1803.11175.pdf) Section 5 has a interesting paragraph on evaluation where authors use Arc Cosine (Cos Inverse) whose range is 0 to Pi in radians instead of plain cosine distance with range 0 to 2.

". For the pairwise semantic similarity task, we directly assess
the similarity of the sentence embedding produced by our two encoders. As shown Eq. 1, we
first compute the cosine similarity of the two sentence embedding and then use arccos to convert
the cosine similarity into an angular distance. 

We find that using a similarity based on angular distance
performs better on average than raw cosine similarity.
"
This is interesting at the same time vague without giving much clarity on pressing reason for the usage of same when we have simple 1-cosine similarity (Clipped at -1 and 1) giving cosine distance in the range 0 to 2. 

Can we get empirical evidences,examples or intuitions in addition to the statement above ("We find that using a similarity based on angular distance performs better on average than raw cosine similarity.") that made authors to use 1 - arccos(cosine similarity)/pi instead of 1- cosine similarity? What do we mean by perform here? Against what parameters the performance was better? Do we have a reasoning for this improvement in performance?

This question is important as many downstream tasks use USE for semantic similarity and if there is strong empirical evidence to use the 1-arccos instead of 1-cosine_similiarity, then it will be highly beneficial for consumers to use the same in their applications.

**Comment by meethariprasad** [comment]
Answering my own query. It appears to be because at small angles plain cosine distance may not provide a good separation. Beautifully explained [here ].  What happens because of this is if there are two sentences both are highly similar to given sentence, but for some reason intuitively one is little more similar to another, plain cosine distance will not be able to give clear separation distance scores, while arccosine based distance can do it. (https://math.stackexchange.com/questions/2874940/cosine-similarity-vs-angular-distance). This information helps a lot to use arccos based distance as objective rather than plain similiarity in siamese finetuning task I am working on. Thanks for

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved. Thanks!
