### ISSUE TITLE
'KerasLayer' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ajonatanu-pk** [tensorflow/hub#464]
When trying to use hub.KerasLayer with Functional API we are getting below errors

`import tensorflow as tf`
`import tensorflow_hub as hub`
`from tensorflow.keras.layers import Dense`
`tfhub_path="https://tfhub.dev/google/universal-sentence-encoder-large/5"`
`hub_layer = hub.KerasLayer(tfhub_path, input_shape=[],
                          dtype=tf.string, trainable=False)`

`output_1 = Dense(64, activation='relu')(qstn_layer)`

Below are the error details.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-47-ad7c136b8eab> in <module>
----> 1 output_1 = Dense(64, activation='relu')(qstn_layer)

/app/AI_RD/conda/envs/cont_tag_use_sup/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    885         # Eager execution on data tensors.
    886         with backend.name_scope(self._name_scope()):
--> 887           self._maybe_build(inputs)
    888           cast_inputs = self._maybe_cast_inputs(inputs)
    889           with base_layer_utils.autocast_context_manager(

/app/AI_RD/conda/envs/cont_tag_use_sup/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   2120     if not self.built:
   2121       input_spec.assert_input_compatibility(
-> 2122           self.input_spec, inputs, self.name)
   2123       input_list = nest.flatten(inputs)
   2124       if input_list and self._dtype_policy.compute_dtype is None:

/app/AI_RD/conda/envs/cont_tag_use_sup/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
    161         spec.min_ndim is not None or
    162         spec.max_ndim is not None):
--> 163       if x.shape.ndims is None:
    164         raise ValueError('Input ' + str(input_index) + ' of layer ' +
    165                          layer_name + ' is incompatible with the layer: '

AttributeError: 'KerasLayer' object has no attribute 'shape'

**Comment by ck37** [comment]
I also ran into that yesterday and found that using an input layer first resolved the issue. Example code:

```python
input_text = tf.keras.Input((), dtype = tf.string, name = 'input_text')
embed_use = hub.load("https://tfhub.dev/google/universal-sentence-encoder-large/5")
embedding = hub.KerasLayer(embed_use, input_shape = [],
                           dtype = tf.string,
                           #trainable = True
                           trainable = False
                           )(input_text)
```

**Comment by rmothukuru** [comment]
@ajonatanu-pk,
Can you please let us know if @ck37's workaround has resolved your issue? Thanks!

**Comment by rmothukuru** [comment]
@ajonatanu-pk,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
