### ISSUE TITLE
Where to get tfhub_module.pb?

### ISSUE THREAD

**Issue by iamxpy** [tensorflow/hub#465]
I am trying to get the immediate layer output of Bert, and according to the solution in [this issue](https://github.com/tensorflow/hub/issues/290#issuecomment-502993680), it seems like I have to use tensorflow 1.0. 

But when I change from tf 2.0 to tf 1.0, I got the error in [this issue](https://github.com/tensorflow/hub/issues/212#issuecomment-477492760), and according to the comment it is because I do not have the file `tfhub_module.pb` which is expected by `hub.Module`

What can I do? Any suggestions will be highly appreciated!

**Comment by vbardiovskyg** [comment]
Hi @iamxpy,

the TF2 Bert models don't expose intermediate layers. You can try using TF1 models, like this one: https://tfhub.dev/google/bert_cased_L-12_H-768_A-12/1.

**Comment by iamxpy** [comment]
@vbardiovskyg Thanks for your reply! Still I want to know what is the difference between [bert_uncased_L-12_H-768_A-12](https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1) and [bert_en_uncased_L-12_H-768_A-12](https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1)? Implemention Version (tf1 or tf2)? Or the former is not pre-trained on English corpus (Its name does not contain "en")?

**Comment by vbardiovskyg** [comment]
They are both trained on English, not sure why the "en" was not included in the handle. Those two models were published by different publishers (internal teams), so they might have different naming schemes.

**Comment by iamxpy** [comment]
@vbardiovskyg Got it, thanks a lot!
