### ISSUE TITLE
openimages_v4/ssd/mobilenet_v2 always returns 100 detections

### ISSUE THREAD

**Issue by simonfojtu** [tensorflow/hub#467]
Hi,

when running the SSD Openimages v4 model (openimages_v4/ssd/mobilenet_v2) I always get 100 detection. Is there a way to get the actual number of detected bounding boxes?
```
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np

detector = hub.Module('https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1')
input_img_placeholder = tf.compat.v1.placeholder(tf.float32)
features = detector(input_img_placeholder, as_dict=True)
session = tf.compat.v1.Session()
session.run([tf.compat.v1.global_variables_initializer(), tf.compat.v1.tables_initializer()])
detections = session.run(features, feed_dict={ input_img_placeholder: np.zeros((1, 300, 300, 3)) })

assert len(detections['detection_boxes']) == 100
```

I've tried to get the `num_detection` graph node, but I'm getting the same result:
```
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np

session = tf.compat.v1.Session()
with session.graph.as_default():
    detector = hub.Module('https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1')
    input_img_placeholder = tf.compat.v1.placeholder(tf.float32)
    features = _detector(input_img_placeholder, as_dict=True)
    session.run([tf.compat.v1.global_variables_initializer(), tf.compat.v1.tables_initializer()])

num_detections = session.run(
    session.graph.get_tensor_by_name('module/num_detections:0'),
    feed_dict={session.graph.get_tensor_by_name('module/hub_input/image_tensor:0'): np.zeros((1, 300, 300, 3))})
assert num_detection == 100
```

When using a SSD MobileNet v2 from TF model zoo (http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_oid_v4_2018_12_12.tar.gz) then the number of detections is correct (and not hardcoded to 100).

Used versions:
- tensorflow==1.15.0
- tensorflow-hub==0.6.0

Thanks,
Simon

**Comment by gowthamkpr** [comment]
@simonfojtu This is a well know question. Please refer to the following questions [[1] ](https://stackoverflow.com/questions/48915003/get-the-bounding-box-coordinates-in-the-tensorflow-object-detection-api-tutorial) and [[2]](https://stackoverflow.com/questions/56118540/how-to-find-bounding-boxes-coordinates-in-tensorflow-object-detection-api) and this should help you in answering your question. 

If you have furthur more questions, you can post them in stackoverflow. Thanks!
