### ISSUE TITLE
tfhub.dev - Switch Away from US MM/DD/YYYY Date format for the updated information

### ISSUE THREAD

**Issue by mr-ubik** [tensorflow/hub#470]
The "updated" information of the models on https://tfhub.dev is displayed in the MM/DD/YYYY date format. A non-US-Specific standard like the YYYY-MM-DD would make the information easier to parse.

**Comment by vbardiovskyg** [comment]
Thanks for the suggestion. This will be fixed in the new tfhub.dev release as per https://en.wikipedia.org/wiki/ISO_8601 (yyyy-mm-dd).
