### ISSUE TITLE
Potential memory leak loading hub modules

### ISSUE THREAD

**Issue by edugp** [tensorflow/hub#472]
It looks like loading a module multiple times leaks memory:
```
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text
import gc
import os
import psutil


process = psutil.Process(os.getpid())
memory = [process.memory_info().rss / (1024.0 ** 3)]
for i in range(10):
    embedder = hub.load('https://tfhub.dev/google/universal-sentence-encoder-large/5')
    del embedder
    gc.collect()
    memory.append(process.memory_info().rss / (1024.0 ** 3))
```
![memoy_tfhub](https://user-images.githubusercontent.com/17855740/72294956-75603180-360b-11ea-8b0a-ec6acbb0d45e.png)
I am using:
```
tensorflow-gpu==2.0.0
tensorflow-hub==0.7.0
tensorflow-text==2.0.1
```
This is also an issue with tf.keras models using hub layers. Here is an example of a tf.keras model using a hub layer leaking memory:
```
def embedder_model():
    text = tf.keras.layers.Input(shape=[], dtype=tf.string)
    embedding_layer = hub.KerasLayer(MODULE_URL, input_shape=[], dtype=tf.string, trainable=True)
    embeddings = embedding_layer(text)
    return tf.keras.models.Model(inputs=text, outputs=embeddings)

process = psutil.Process(os.getpid())
memory = [process.memory_info().rss / (1024.0 ** 3)]
for i in range(10):
    model = embedder_model()
    del model
    gc.collect()
    memory.append(process.memory_info().rss / (1024.0 ** 3))
```
![image](https://user-images.githubusercontent.com/17855740/72298812-0509de00-3614-11ea-8611-2196566d897a.png)
In comparison, a tf.keras model that does not use hub, only holds a significant amount of memory on the first load:
```
def dummy_model():
    inputs = tf.keras.layers.Input(shape=(10,))
    dense_layer = tf.keras.layers.Dense(10000)
    outputs = dense_layer(inputs)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)

process = psutil.Process(os.getpid())
memory = [process.memory_info().rss / (1024.0 ** 3)]
for i in range(10):
    model = dummy_model()
    del model
    gc.collect()
    memory.append(process.memory_info().rss / (1024.0 ** 3))
```
![image](https://user-images.githubusercontent.com/17855740/72298893-3da9b780-3614-11ea-951d-b66278dd9404.png)

**Comment by edugp** [comment]
It looks like this issue is partially fixed in 2.1.0, using `tf.keras.backend.clear_session()`:
```
memory = [process.memory_info().rss / (1024.0 ** 3)]
for i in range(10):
    embedder = hub.load('https://tfhub.dev/google/universal-sentence-encoder-large/5')
    tf.keras.backend.clear_session()
    del embedder
    gc.collect()
    memory.append(process.memory_info().rss / (1024.0 ** 3))
```
![image](https://user-images.githubusercontent.com/17855740/76039774-4925aa80-5f02-11ea-97c7-906672863dfd.png)

It still leaks memory, but way less.
Also, `tf.keras.backend.clear_session()` is not ideal. In my case, I have multiple models loaded in memory at once, so that would remove all of them.
Does anyone understand the underlying issue here?
And also, does anyone know if there is any way to only clear a part of the graph rather than the whole thing with `tf.keras.backend.clear_session()`?

**Comment by arnoegw** [comment]
Thank you, @edugp, for your updated report!

`hub.load()` is really just a wrapper to call `tf.saved_model.load()` after downloading the SavedModel, so the core issue is with TensorFlow, not TF Hub, and your reports have been forwarded accordingly.

**Comment by gkumbhat** [comment]
Is there any solution or workaround for this issue? I am also seeing same issue. 

Similar script:
```
import gc

import tensorflow as tf
import tensorflow_hub as hub

model_path = 'universal-sentence-encoder_5'

sample_texts = ["This is a sample sentence."]

@profile
def do_it():
    for i in range(50):
        print("Loading...\n\n\n")
        # Load model
        use_embedding = hub.load(model_path)

        # Run model
        emb = use_embedding(sample_texts)

        # Extra processing
        result = tf.cast(emb, tf.float32).numpy()

        print("Deleting...\n\n\n")
        # Delete model
        del use_embedding
        del emb
        del result

        # cleanup
        tf.keras.backend.clear_session()
        n = gc.collect()
        print("Number of unreachable objects collected: ", n)

if __name__ == "__main__":
    do_it()
```

**Comment by laurachiticariu** [comment]
@arnoegw regarding https://github.com/tensorflow/hub/issues/472#issuecomment-597102937 can you or anyone else link the issues in TensorFlow that are related, so that we can follow those issues?

**Comment by monicadsong** [comment]
Okay, I think the memory leak is much less severe now (without`tf.keras.backend.clear_session()`) when I use "https://tfhub.dev/tensorflow/efficientnet/b0/classification/1":

```
def get_memory(model_path, trials=10):
  process = psutil.Process(os.getpid())
  memory = [process.memory_info().rss / (1024.0 ** 3)]
  for i in range(trials):
      model = hub.load(model_path)
      del model
      gc.collect()
      m = process.memory_info().rss / (1024.0 ** 3)
      memory.append(m)
      print(m)
  return memory

model_path = "https://tfhub.dev/tensorflow/efficientnet/b0/classification/1"
memory=get_memory(model_path)
```
This prints out:
```
0.7159385681152344
0.730224609375
0.7430763244628906
0.7481880187988281
0.752166748046875
0.7557334899902344
0.7583236694335938
0.7603797912597656
0.762298583984375
0.7653656005859375
```
![image](https://user-images.githubusercontent.com/17239878/118061776-782b7d80-b34a-11eb-935f-bcf7ccabcd89.png)

It may be possible that the `universal-sentence-encoder-large` is creating hash tables, and it is a known issue that hash tables do not release their resources when the SavedModel is destroyed: https://github.com/tensorflow/tensorflow/issues/44403.

If the model is not creating hash tables, then I am not sure why there would be a difference in our observations.

**Comment by akhorlin** [comment]
Please reopen the issue if you the problem for models without large hash table. 

In general, hub.load() is a thin wrapper around tf.saved_model.load(). So if the example can be re-worked to use tf.saved_model.load(), then the best way is to file an issue with TensorFlow directly.

**Comment by Ghostvv** [comment]
the issue still exist in tensorflow 2.5

**Comment by stefan-falk** [comment]
I have a similar issue using 2.6.2 (for details see [stackoverflow question](https://stackoverflow.com/questions/70438025/training-runs-out-of-memory-as-ram-consumption-keeps-growing)).
