### ISSUE TITLE
Fine-tunable object detection model (e.g.Coco SSD MobileNet)

### ISSUE THREAD

**Issue by JesseWebDotCom** [tensorflow/hub#473]
How can I use the make_image_classifier with Coco SSD MobileNet models?

**Comment by rmothukuru** [comment]
@JesseWebDotCom,
Can you please clarify why do you want to use MobileNet for Image Classification because those are the Pre-Trained Models for Object Detection. For Image Classification, you can use `Inception_ResNet` or `EfficientNet` or `MNAS_Net`, etc..

For more details, please check this [Image Classification Link](https://tfhub.dev/s?module-type=image-classification). Thanks!

**Comment by JesseWebDotCom** [comment]
I’m new to all this so please bear with me.  I current use the coco ssd mobilenet v2 to detect objects seen through my home security cameras (ex there is a car in the driveway).  That model was recommended because the of the amount of camera feeds that need to be processed.   I would like to get the granularity of “car in the driveway” to “fedex truck in the driveway”.  I thought this project would help.  Thanks

**Comment by rmothukuru** [comment]
@JesseWebDotCom,
[Here ](https://tfhub.dev/s?module-type=image-augmentation,image-classification,image-feature-vector,image-generator,image-object-detection,image-others,image-style-transfer,image-rnn-agent&q=mobilenet) is the Link for Pre-Trained Models related to MobileNet. Code and Description of each Model will be present in the respective page. Please let me know if this is what you are looking for. Thanks!

**Comment by JesseWebDotCom** [comment]
I looking for an easy way to train object detection tensorflow models.

**Comment by rmothukuru** [comment]
> I looking for an easy way to train object detection tensorflow models.

We are not clear on what exactly you need because usage of Pre-Trained Models using TF Hub makes training easy. Can you please elaborate about your requirement and use case, if possible. Thanks!

**Comment by vbardiovskyg** [comment]
Hi @JesseWebDotCom, as far as I know, currently none of our object detection models are fine-tunable.

FYI, make_image_classifier is really meant for creating image classifiers only, and is not fit for object detection.

The best I can recommend at this point is the TensorFlow object detection API: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md.

I will reframe this thread into a module request and keep it open for further reference.

**Comment by maximneumann** [comment]
Hi JesseWebDotCom,

as pointed out by Vojtech above, make_image_classifier cannot be used with Coco SSD MobileNet models, as it targets image classification, and not object detection.

Closing the issue for now. 
Feel free to check for instance the TensorFlow object detection API to fine-tune it on your own data: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md.
