### ISSUE TITLE
Source distribution not available on PyPi

### ISSUE THREAD

**Issue by akjindal53244** [tensorflow/hub#475]
Hi Tensorflow Team,

I need to use recent versions of tensorflow-hub (>=`0.5.0`) but the source distribution is not available. In order to use newer versions, we need source distribution available as per company guidelines.

In my understanding, if it's open-source, source distribution should be provided, along with a binary blob. Request to help. TIA!

**Comment by gowthamkpr** [comment]
@akjindal53244 You can install tensorflow-hub 0.7.0 version using the following command
`pip install tensorflow-hub
`
You can find it in pypi [here](https://pypi.org/project/tensorflow-hub/)

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Please add additional comments and we can open this issue again
