### ISSUE TITLE
Running Inference on preloaded model on TF 2.0 and USE v5

### ISSUE THREAD

**Issue by radames** [tensorflow/hub#479]
Hello,
Would you have any advice on how to run inference on pre loaded model using TF2.0? and [USE model v5](https://tfhub.dev/google/universal-sentence-encoder-large/5)? Trying to follow those steps below and to convert to TF2.0. Would you have any advice?

From https://github.com/tensorflow/hub/blob/master/docs/common_issues.md#running-inference-on-a-pre-initialized-module

```python
import tensorflow as tf
import tensorflow_hub as hub

# Create graph and finalize (finalizing optional but recommended).
g = tf.Graph()
with g.as_default():
  # We will be feeding 1D tensors of text into the graph.
  text_input = tf.placeholder(dtype=tf.string, shape=[None])
  embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/2")
  embedded_text = embed(text_input)
  init_op = tf.group([tf.global_variables_initializer(), tf.tables_initializer()])
g.finalize()

# Create session and initialize.
session = tf.Session(graph=g)
session.run(init_op)
```

**Comment by vbardiovskyg** [comment]
Hi Radamés, the guide has been updated for TF2 use-case in 7e217af37d4f69224fe4e0491c8eb8726cdefa7c.
