### ISSUE TITLE
Cannot save keras model based on hub module

### ISSUE THREAD

**Issue by cipri-tom** [tensorflow/hub#482]
Hi,

I am trying to follow the fine-tuning tutorial for my own dataset, and I have built a model as follows:
```
module = hub.Module(tuning_model_url, trainable=True, name='efficientnet_b1')
#... some code for getting module expected image size and inputs

model = tf.keras.Sequential([
    hub.KerasLayer(module, trainable=False),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(100, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(train_data.num_classes, activation='softmax', 
                          kernel_regularizer=tf.keras.regularizers.l2(0.0001)),
])

model.build(input_shape=(None, img_size[0], img_size[1], 3)) # Saver warn

model.compile(optimizer='rmsprop', 
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True, label_smoothing=0.1),
              metrics=['accuracy'])
```

### Saving before training

If I don't train the model, and I try to save it directly, I get:

- `model.save('../models/keras_effnet_b1')`

```
WARNING:tensorflow:Skipping full serialization of Keras model <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f8c1c107e50>, because its inputs are not defined.

ValueError: Model <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f8c1c107e50> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call model._set_inputs(inputs).
```

- `tf.saved_model.save(model, '../models/effnet_b1_1')`

```
WARNING:tensorflow:Skipping full serialization of Keras model <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f8c1c107e50>, because its inputs are not defined.

INFO:tensorflow:Assets written to: ../models/effnet_b1_1/assets
```

So, it appears the the `tf` version works, there are some files on disk, though I'm not 100% sure of their content due to the warning.

### Saving after training

If I run `model.fit(...)`, then each of the above methods gives the same error:
```
RuntimeError: Module must be applied in the graph it was instantiated for.
```

Also, when calling `model.build` in the line marked with `# Saver warn`, I get the following warning: `INFO:tensorflow:Saver not created because there are no variables in the graph to restore`. What is interesting is that I also get this warning when calling `model.fit(...)` afterwards, which suggests that the model / session / graph is reinitialised, hence probably the error about the module not belonging to the graph.

### Solution ?

How can I overcome the error `Module must be applied in the graph it was instantiated for.` ?

**Comment by rmothukuru** [comment]
@cipri-tom,
Can you please specify the versions of Tensorflow and TF Hub. Also, in order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by cipri-tom** [comment]
Hi @rmothukuru 

Sure, the versions are:  tf==2.1.0, tf-hub==0.7.0

The reproduction is in the notebook at this gist: https://gist.github.com/cipri-tom/ff2f81c1b7e896e5ede73af8672f19c5

Thank you !

**Comment by gowthamkpr** [comment]
@cipri-tom I am not surw why you are using hub.module(...) inside hub.KerasLayer(..).

An example of using hub.KerasLayer() is given below.
```
hub.KerasLayer(
    "/tmp/text_embedding_model",
    output_shape=[20],  # Outputs a tensor with shape [batch_size, 20].
    input_shape=[],     # Expects a tensor of shape [batch_size] as input.
    dtype=tf.string)    # Expects a tf.string input tensor.
```

**Comment by cipri-tom** [comment]
@gowthamkpr Indeed, if we use the link directly, it works. Thank you !

I was using the `hub.Module(...)` call in order to get some information about the model before adding my own layers, such as input image size and output shape in order to know how to structure the following layers.

**Comment by gowthamkpr** [comment]
You can load your model either using hub.module() or hub. KerasLayer() but not both. Please just use one of them @captain-pool

**Comment by cipri-tom** [comment]
I understand. Thank you! 

Could you please explain a bit what are the differences between the two ? Why would one use `hub.module()` vs the `hub.KerasLayer()` ? Thank you

**Comment by gowthamkpr** [comment]
@cipri-tom As shown [here](https://www.tensorflow.org/hub/api_docs/python/hub/KerasLayer), hub.KerasLayer  Wraps a Hub module (or a similar callable) for TF2 as a Keras Layer.

To understand more about saving from keras,  you can take a look at this [guide](https://www.tensorflow.org/hub/tf2_saved_model#saving_from_keras).

The hub.Module API and file format works for TF1 only. For TF2, switch to plain SavedModels and hub.load(). Refer [here](https://github.com/tensorflow/hub/blob/24e6ed6c2a36840f90ecef04148100ec651e99c6/tensorflow_hub/module.py#L86).

**Comment by cipri-tom** [comment]
Nice ! Thank you very much !
