### ISSUE TITLE
object detection notebook has decode error

### ISSUE THREAD

**Issue by yufengg** [tensorflow/hub#487]
In this notebook: https://github.com/tensorflow/hub/blob/master/examples/colab/object_detection.ipynb

If you run it top to bottom, it currently hits an error on this cell:
`run_detector(detector, downloaded_image_path)`

The error reads: `'bytes' object has no attribute 'numpy'`

It's because draw_boxes() runs the following line:
`class_names[i].numpy().decode("ascii")`

which for some reason (maybe python2 compat???) calls `.numpy()` on the class names, which are coming back as bytestrings in python3. propose removing the `.numpy()` call and keeping `.decode("ascii")`. Seems to work in py2 and py3 with this change.

**Comment by vbardiovskyg** [comment]
+@kargeor, who authored the https://github.com/tensorflow/hub/pull/478 change that added this call.

@kargeor, do you happen to remember what environments you used for the colab where having numpy() did work? Seems like it does not always work.

**Comment by vbardiovskyg** [comment]
Will approve the PR since some a few lines above, this line is already calling numpy():

`result = {key:value.numpy() for key,value in result.items()}`
