### ISSUE TITLE
Segmentation Fault loading USE Xling Embeddings TF==1.15.0

### ISSUE THREAD

**Issue by jasonw247** [tensorflow/hub#490]
I am running into a seg fault when loading :

`universal-sentence-encoder-multilingual-large/1` or `universal-sentence-encoder-xling-many/1`

using Tensorflow 1.15.0

Environment:
```
pip freeze | grep -iE "tensor|sentence"
bert-tensorflow==1.0.1
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
tensorflow-hub==0.7.0
tf-sentencepiece==0.1.85
```

Error:
```
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow_hub
>>> import tf_sentencepiece
>>> tensorflow_hub.Module('https://tfhub.dev/google/universal-sentence-encoder-xling-many/1')
Segmentation fault (core dumped)
```

I am able to load the module using tensorflow==1.14.0 and tf-sentencepiece==0.1.85

**Comment by gowthamkpr** [comment]
@jasonw247 Thank you for the report. This module is crashing in colab too using tensorflow 1.15.0 cpu and gpu versions and with hub version 0.7.0.

But it is not crashing with Tensorflow 1.13.0.

**Comment by maximneumann** [comment]
This is unfortunately an issue with the publisher of USE models, and is not related to TF-Hub. 

It seems that tf-sentencepiece is not fully compatible with tf 1.15. 
Please note that this is implied in the colab attached to the modules ("latest Tensorflow that supports sentencepiece is 1.13.1"):
https://colab.research.google.com/github/tensorflow/hub/blob/3880b82596d2cf5401095b6ada51cb2d543c2050/examples/colab/cross_lingual_similarity_with_tf_hub_multilingual_universal_encoder.ipynb

**Comment by maximneumann** [comment]
Added a comment to the documentation of these hub modules to check for compatibility between the sentencepiece and tensorflow version.

**Comment by jasonw247** [comment]
@maximneumann thank you for the reply. I have followed up with the Sentencepiece team. 

To clarify compatibility, I was able to use the modules with: tensorflow==1.14.0 sentencepiece>=0.1.83 tf-sentencepiece>=0.1.83, as mentioned in: https://github.com/tensorflow/hub/issues/345

**Comment by maximneumann** [comment]
Thanks.
I've looked as well on the sentencepiece page: https://github.com/google/sentencepiece
and it has commits to support tensorflow 1.14 (and 1.15 on Windows).

**Comment by thusithaC** [comment]
I guess questioning about TF 2.0 + is not relevant? For the record I get this on tf 2.0
```
module_url = "https://tfhub.dev/google/universal-sentence-encoder-xling-many/1"
embed = hub.KerasLayer(module_url)

Segmentation fault
```
