### ISSUE TITLE
Multilingual-USE-3 : Expose parameters as trainable? TF2

### ISSUE THREAD

**Issue by Killthebug** [tensorflow/hub#497]
Hi,

I'm attempting to fine-tune the Multilingual USE Large 3 model (https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3) and am facing various issues. But before I go ahead, I wanted to know if there's something I need to do to expose the weights as trainable.

For the regular USE-Large-3 model (https://tfhub.dev/google/universal-sentence-encoder-large/3), passing the parameter "trainable=True" would expose the weights. 

What would be the right procedure to retrain the Multilingual Model using TF2?

**Comment by gowthamkpr** [comment]
@Killthebug At this point of time, **Multilingual USE Large 3**  model does not support `trainable=True`.

**Comment by vbardiovskyg** [comment]
Hi Jaipal, we will need a bit more information here.

As per @gowthamkpr last comment, the typical way to use TF2 SavedModels from Hub is to use hub.KerasLayer(model, trainable=?).

Indeed running the following shows trainable variables.
```
model = hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3", trainable=True)
model.trainable_variables
```

**Comment by gowthamkpr** [comment]
@Killthebug Closing this issue as it has been resolved. Please add additional comments for us to open this issue again. Thanks!
