### ISSUE TITLE
Releasing MobileBERT as KerasLayer/Hub Module

### ISSUE THREAD

**Issue by xhlulu** [tensorflow/hub#498]
Is there any plan on releasing [MobileBERT](https://tfhub.dev/tensorflow/mobilebert/1) as a KerasLayer or Hub Module? I'd like to compare the finetuning performance against other distillation methods for downstream tasks such as text classification.

I know the intent of the model is to be used in a mobile device, but without finetuning the best performance we can get out of it is limited. Thus, will a .h5 or .pb version of the model be made available along the .tflite? Otherwise, is there any plan to support conversion **from TFLite back to TFKeras** (this [thread](https://stackoverflow.com/questions/59559289/is-there-any-way-to-convert-the-tflite-file-back-to-keash5) seems to tell me it is not currently possible)?

**Comment by j-grimstad** [comment]
Hi @xhlulu , sorry for the delay -- I'm following up with the relevant internal team to see if they're able to support your request. Will follow up as soon as I have more information on if/when this can be published.

**Comment by j-grimstad** [comment]
Hi @xhlulu, sorry for the (additional) extended delay -- unfortunately, the internal team is unable to release MobileBERT as a KerasLayer or Hub Module at this time. They're aware of the request and will hopefully be able to release it after certain other dependencies are lifted.

**Comment by j-grimstad** [comment]
Hi @xhlulu, you can now find MobileBERT as a TF1 hub.Module here: https://tfhub.dev/google/mobilebert/uncased_L-24_H-128_B-512_A-4_F-4_OPT/1
