### ISSUE TITLE
AttributeError: module 'tensorflow_hub.tools.make_image_classifier.make_image_classifier_lib' has no attribute 'build_model'

### ISSUE THREAD

**Issue by PrinceP** [tensorflow/hub#507]
AttributeError                            Traceback (most recent call last)
<ipython-input-13-c6c91b75df2e> in <module>
----> 1 model = image_classifier.create(train_data)

~/work/classifier/tf2_symbol_classifier/lib/python3.6/site-packages/tensorflow_examples/lite/model_customization/core/task/image_classifier.py in create(train_data, model_export_format, model_spec, shuffle, validation_data, batch_size, epochs, train_whole_model, dropout_rate, learning_rate, momentum)
     79       train_data.num_classes,
     80       shuffle=shuffle,
---> 81       hparams=hparams)
     82 
     83   tf.compat.v1.logging.info('Retraining the models...')

~/work/classifier/tf2_symbol_classifier/lib/python3.6/site-packages/tensorflow_examples/lite/model_customization/core/task/image_classifier.py in __init__(self, model_export_format, model_spec, index_to_label, num_classes, shuffle, hparams)
    113                          num_classes, shuffle, hparams.do_fine_tuning)
    114     self.hparams = hparams
--> 115     self.model = self._create_model()
    116 
    117   def _create_model(self, hparams=None):

~/work/classifier/tf2_symbol_classifier/lib/python3.6/site-packages/tensorflow_examples/lite/model_customization/core/task/image_classifier.py in _create_model(self, hparams)
    122     module_layer = hub.KerasLayer(
    123         self.model_spec.uri, trainable=hparams.do_fine_tuning)
--> 124     return lib.build_model(module_layer, hparams,
    125                            self.model_spec.input_image_shape, self.num_classes)
    126 

AttributeError: module 'tensorflow_hub.tools.make_image_classifier.make_image_classifier_lib' has no attribute 'build_model'

**Comment by gowthamkpr** [comment]
@PrinceP Please provide a reproducible code to reproduce this issue. Thanks!

**Comment by gowthamkpr** [comment]
I am not sure why this error is happening but `_build_model` exists as shown [here](https://github.com/tensorflow/hub/blob/e12761bfdec7f8c971f195f726b6c4e4b41ef4b2/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py#L167). I am closing this issue for now. Please add additional comments and we can open this issue again. Thanks!
