### ISSUE TITLE
Why is there no pretrained object detection models trained on COCO on TF Hub?

### ISSUE THREAD

**Issue by zacwellmer** [tensorflow/hub#509]
A starting point could just be porting the models listed in [tf model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)

**Comment by gowthamkpr** [comment]
@zacwellmer We do have a few modules in tensorflow hub already like
https://tfhub.dev/google/tf2-preview/mobilenet_v2/classification/4
https://tfhub.dev/google/imagenet/resnet_v2_152/feature_vector/4 etc.., 

Please go through these modules. Also if I have misinterpreted your question please correct me. Thanks!

**Comment by zacwellmer** [comment]
Both of those links are trained on the imagenet dataset and not the coco dataset

**Comment by gowthamkpr** [comment]
@zacwellmer You can train them on coco dataset by using `hub.KerasLayer(url, trainable=True)` as you can finetune the model for the dataset you want.

**Comment by gowthamkpr** [comment]
@zacwellmer Can I close this issue?

**Comment by zacwellmer** [comment]
well I don't think either of your suggestions actually apply for two reasons:
1) Both resnet and mobilenet are for classification not object detection(COCO is object detection)
2) Isn't the point of TF Hub to offer pretrained models? Seems like COCO is a pretty great dataset to offer a pretrain a model on

**Comment by gowthamkpr** [comment]
@zacwellmer We do have pretrained modules on object detection [here](https://tfhub.dev/s?q=object%20detection). If you can mention a specific model architecture that is not in hub which will help the community, we can take a look into it.

**Comment by gowthamkpr** [comment]
@zacwellmer Can you please respond to the above comment. Thanks!

**Comment by zacwellmer** [comment]
Maybe I'm misunderstanding the purpose of Tensorflow Hub. I was under the impression that the purpose of Tensorflow Hub is hosting models trained from different architectures or datasets for folks who don't have the compute to train the model themself.

If my understanding above is correct, that means hosting a version trained on COCO would be useful. Otherwise, the focus is on giving users a model for a specific architecture and leaving it up to them to find the compute to train on a large dataset like COCO

**Comment by vbardiovskyg** [comment]
Hi Zac, thanks for the interest! And you are right that that is the whole purpose of TensorFlow Hub and transfer learning in general.

I will relabel this as a module request to keep track.

**Comment by ChanchalKumarMaji** [comment]
Can I port some models from - [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).

**Comment by ManishAradwad** [comment]
I would like to help porting these models. I tried finding some documentation about it but couldn't find anything. Can anyone plz help me on how to do it?

**Comment by j-grimstad** [comment]
Hi @ChanchalKumarMaji and @ManishAradwad, we'd be happy accept external contributions! See our documentation here: https://github.com/tensorflow/hub/tree/master/tfhub_dev

Please let us know if you have any questions.

**Comment by WGierke** [comment]
Hi @zacwellmer and everyone involved
We received lots of contributions since this issue has been opened. By now, we can offer [41 models](https://tfhub.dev/s?dataset=coco-2017&subtype=module,placeholder) trained on the COCO 2017 dataset. Hope this helps!
