### ISSUE TITLE
Universal Sentence Encoder - Gradients at Token Level

### ISSUE THREAD

**Issue by vinitrinh** [tensorflow/hub#512]
Hi I'm trying to build visualizations to interpret USE-QA, using simple gradients. 
In particular, I need the gradients at token level.

The gradients from GradientTape seems to track only trainable weights. 
Is there a way I can access these gradients up to the tokenizer?

**Comment by gowthamkpr** [comment]
@vinitrinh Can you please go through the following [comment](https://github.com/tensorflow/hub/issues/403#issuecomment-578929302) and let me know if it helps. Thanks!

**Comment by vinitrinh** [comment]
Hi @gowthamkpr Thanks for your prompt reply and the link. I did see the link previously, but I couldnt see how to get to the graph tokenizer and embedding_look function concretely with code. 

Using Tensorboard, I seem to be able to see the text text_preprocessor of the `question_encoder` signature. 

![image](https://user-images.githubusercontent.com/28703546/74894605-759dda80-53ca-11ea-8d1f-4323dc2cbee7.png)

How do I access the tokenizer, embedding_look or the text_preprocessor?
They do not appear in the module's operations as well. 
```
import tensorflow as tf
import tensorflow_hub as hub
import datetime
import tensorflow_text

module = hub.load('https://tfhub.dev/google/universal-sentence-encoder-qa/3')
module.signatures['question_encoder'].graph.get_operations()
```

**Comment by akhorlin** [comment]
Unfortunately depending on the model's architecture and the ops used it may be hard or impossible to get the underlying gradients at the token level.
