### ISSUE TITLE
I found below issue when trying to import tensorflow-hub - have no clue with this issue and appreciate your help.

### ISSUE THREAD

**Issue by venkatamaguluri** [tensorflow/hub#513]
I found below issue when trying to import tensorflow-hub - have no clue with this issue and appreciate your help.

ImportError Traceback (most recent call last)
in ()
1 import tensorflow as tf
----> 2 import tensorflow_hub as hub

C:\Program Files\Anaconda3\envs\tensorflow_sessions\lib\site-packages\tensorflow_hub_init_.py in ()
27 # error message is thrown instead of an obscure error of missing
28 # symbols at executing the imports.
---> 29 from tensorflow_hub.estimator import LatestModuleExporter
30 from tensorflow_hub.estimator import register_module_for_export
31 from tensorflow_hub.feature_column import image_embedding_column

C:\Program Files\Anaconda3\envs\tensorflow_sessions\lib\site-packages\tensorflow_hub\estimator.py in ()
23 from absl import logging
24 import tensorflow as tf
---> 25 from tensorflow_hub import tf_utils
26 from tensorflow_hub import tf_v1
27

C:\Program Files\Anaconda3\envs\tensorflow_sessions\lib\site-packages\tensorflow_hub\tf_utils.py in ()
31 # depending on TensorFlow internal implementation details.
32 # pylint: disable=g-direct-tensorflow-import
---> 33 from tensorflow.python.feature_column import feature_column_v2
34 # pylint: enable=g-direct-tensorflow-import

**Comment by gowthamkpr** [comment]
What environment are you importing, what is the version of Tensorflow_hub? Also can you give us the exact steps you followed for us to reproduce the issue. Thanks!

**Comment by gowthamkpr** [comment]
@venkatamaguluri Are you still facing the same issue?

**Comment by venkatamaguluri** [comment]
its a Anaconda windows environment - Tensorflow 1.10.0 and Tensorflow_hub 0.7.0

Thanks - Venkata

**Comment by gowthamkpr** [comment]
@venkatamaguluri I am also running into this error using Tensorflow 1.10.0 and 1.11. Please start using  versions of Tensorflow that are 1.12 or beyond that.

I would strongly recommend you to use Tensorflow 1.15 or Tensorflow 2.x.

**Comment by gowthamkpr** [comment]
@venkatamaguluri Can you please let me know if the above comment helps. Thanks!

**Comment by venkatamaguluri** [comment]
i donot find mentioned versions in annaconda, how can find mentioned versions?

**Comment by khimraj** [comment]
@venkatamaguluri, First open anaconda navigator then select your environment and then search for tensorflow package. You will find 1.15.0 version.
![Screenshot from 2020-03-15 03-45-22](https://user-images.githubusercontent.com/36735394/76691314-ac84aa80-666f-11ea-8fa6-d25133a727e4.png)

**Comment by venkatamaguluri** [comment]
some how i donot see it in my environment

![Annotation 2020-03-17 081551](https://user-images.githubusercontent.com/42973643/76855469-94578b80-6827-11ea-9c5a-454f2c7125cb.jpg)

**Comment by khimraj** [comment]
@venkatamaguluri , select `All` in place of `Installed` or try to search after updating index.

**Comment by gowthamkpr** [comment]
@venkatamaguluri I can see that this issue is related to your environment not TF Hub itself. Can you please post it in [conda/conda](https://github.com/conda/conda/issues) and close the issue here. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been awaiting response for more than 2 weeks. Please add additional comments and we can open this issue again. Thanks!
