### ISSUE TITLE
Fine-tuning of EfficientNet B0 not working

### ISSUE THREAD

**Issue by paulbauriegel** [tensorflow/hub#514]
Following the instructions from the [TF Hub Module](https://tfhub.dev/google/efficientnet/b0/feature-vector/1) I wanted to use the fine-tuning with Keras and TF2.

Setting `trainable=True` and `tags={"train"}` didn't help and all parameters from the feature extraction are still not changeable. Here is what I've tried:

```python
import tensorflow as tf
import tensorflow_hub as hub

model = tf.keras.Sequential([
    hub.KerasLayer("https://tfhub.dev/google/efficientnet/b0/feature-vector/1", 
                   trainable=True, tags={"train"}),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(6, activation='softmax',
                          kernel_regularizer=tf.keras.regularizers.l2(0.0001))
])
model.build((None, 224, 224, 3))
model.summary()
```

resulting in:

```
Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
keras_layer_6 (KerasLayer)   multiple                  4049564   
_________________________________________________________________
dropout_6 (Dropout)          multiple                  0         
_________________________________________________________________
dense_5 (Dense)              multiple                  7686      
=================================================================
Total params: 4,057,250
Trainable params: 7,686
Non-trainable params: 4,049,564
_________________________________________________________________
```

**Comment by gowthamkpr** [comment]
@paulbauriegel Thanks for reporting. I was able to reproduce it. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/df4fb87c063c1f17f9df611eb6f3cb80/untitled13.ipynb).

**Comment by vbardiovskyg** [comment]
Hi Paul, unfortunately hub.Modules are not trainable in TF2, see https://www.tensorflow.org/hub/migration_tf2#loading_legacy_hubmodules.

**Comment by paulbauriegel** [comment]
@vbardiovskyg The TF version doesn't matter. It isn't fine-tunable in TF1 aswell. See:
[Colab](https://colab.research.google.com/drive/1p_yzcIpbIzeNNi8VMmr2oxwqs3NSEK1Z)
The website however states:  Fine tunable: Yes

**Comment by vbardiovskyg** [comment]
Good point, I should probably rephrase: "Hub.module is not fine-tunable with the new APIs like `hub.load` or `hub.KerasLayer`." It is fine-tunable only when used with `hub.Module()`.

**Comment by TechnikEmpire** [comment]
Any idea when we're gonna see a trainable efficienctnet tf2 module?

**Comment by vbardiovskyg** [comment]
I think it's a reasonable request, unfortunately it is a bit out of control of TensorFlow Hub. We are hoping that it will happen soon, but have no concrete info.

**Comment by TechnikEmpire** [comment]
Thanks for the reply. I'm just a casual user without enough knowledge to execute make_image_classifier.py otherwise I'd contribute it lol.

**Comment by mwalmsley** [comment]
@TechnikEmpire you might find this walkthrough useful - https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/. It uses tensorflow.keras.applications rather than hub.KerasLayer.
