### ISSUE TITLE
GSoC Project

### ISSUE THREAD

**Issue by k4rth33k** [tensorflow/hub#516]
Hello, I'm new here. I'm interested in the TF Hub project,  New models + colab demos for the GSoC 2020 edition. Is this the right place to ask questions and communicate with mentors. Please provide the link to other discussions sites, if this is not the right place.

**Comment by rmothukuru** [comment]
@k4rth33k,
It can be the right place, but depending on your questions. So, please specify your question. Thanks!

**Comment by k4rth33k** [comment]
Thank you for your reply. My question is, how can I connect with mentors to send them drafts of the application and to ask any further questions in the future.

**Comment by rmothukuru** [comment]
@k4rth33k,
Sorry for the misunderstanding. There is a separate forum on how to connect with Mentors. Please refer [this link](https://summerofcode.withgoogle.com/help/) for the same. Thanks!

**Comment by khimraj** [comment]
@k4rth33k, It is clearly mentioned in google [doc](https://docs.google.com/document/d/1zT57PFMGZ04A4CvHxAKVpMTgXjsO92_oKeSKwZMc0Gs) of tensorflow gsoc ideas that After you create the first draft of your project proposal (7-10 pages), please send it to webpaige@google.com. Once they have received your proposal, engineering mentors will provide feedback over the course of the next month.

**Comment by k4rth33k** [comment]
@khimraj Oops. I haven't checked the doc after that part was added. Thank you very much.
