### ISSUE TITLE
Error while executing the Code mentioned in the Documentation of USE-5

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/hub#518]
In [USE 3](https://tfhub.dev/google/universal-sentence-encoder-large/3), it is specified that 

> Warning: An updated version of this module is available at https://tfhub.dev/google/universal-sentence-encoder-large/5 .

When the below mentioned code is run from this [USE-5 Link](https://tfhub.dev/google/universal-sentence-encoder-large/5), it is resulting in an error, 

> RuntimeError: Missing implementation that supports: loader(*('/tmp/tfhub_modules/c9fe785512ca4a1b179831acb18a0c6bfba603dd',), **{})

```
!pip install tensorflow==2.1
!pip install "tensorflow_hub>=0.6.0"
!pip3 install tensorflow_text>=2.0.0rc0

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text

module = hub.Module("https://tfhub.dev/google/universal-sentence-encoder-large/5")

embeddings = embed(["The quick brown fox jumps over the lazy dog.","I am a sentence for which I would like to get its embedding"])
```

I suspect something is wrong in the Code provided in the link.

Please find the [Github Gist](https://colab.sandbox.google.com/gist/rmothukuru/eba9ed2c3f916b4b220531b73b013f1c/use_5_error.ipynb) demonstrating the specified error. Thanks!

**Comment by arnoegw** [comment]
The asset type has changed:

  * https://tfhub.dev/google/universal-sentence-encoder-large/3 and older are in hub.Module format.
  * https://tfhub.dev/google/universal-sentence-encoder-large/4 and newer are in TF2 SavedModel format.

The documentation for each version appears to have the correct usage. Apparently, the red box about "an updated version of this module" has been confusing. Passing to vbardiovskyg for the implied UX aspect.

**Comment by vbardiovskyg** [comment]
I could be wrong, but I think we never display that sort of code, e.g.
```
hub.Module("https://tfhub.dev/google/universal-sentence-encoder-large/5")
```

If yes we should definitely fix it, but otherwise not sure what action we can make here. I will close it for now, but feel free to reopen if there are any associated UX ideas on how to make this less confusing.
