### ISSUE TITLE
Error when executed the code specified in the documentation of USE-Multilingual-qa-3

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/hub#519]
In [USE-Multilingual-qa-V2](https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/2), it is mentioned that 

> Warning: An updated version of this module is available at https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/3 .

But when executed the code specified in the [USE-Multilingual-V3](https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/3), it is resulting in the below mentioned error,

> TypeError: unsupported operand type(s) for *: 'dict' and 'dict'

Reproducible code is mentioned below:

```
!pip install tensorflow==2.1
!pip install "tensorflow_hub>=0.6.0"
!pip3 install tensorflow_text>=2.0.0rc0

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import tensorflow_text

questions = ["What is your age?"]
responses = ["I am 20 years old.", "good morning"]
response_contexts = ["I will be 21 next year.", "great day."]

module = hub.load('https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/3')

question_embeddings = module.signatures['question_encoder'](
            tf.constant(questions))
response_embeddings = module.signatures['response_encoder'](
        input=tf.constant(responses),
        context=tf.constant(response_contexts))

np.inner(question_embeddings, response_embeddings)
```

Please find the attached [Github Gist](https://colab.sandbox.google.com/gist/rmothukuru/7540269a3a4dfac2491c1e0f002f379b/use_qa_3_error.ipynb#scrollTo=wqlBss1AKtwU) as well.

**Comment by gowthamkpr** [comment]
The issue here is that np.inner() doesn't accept dictionaries as inputs. It accepts two arrays as input.
So if you can get the values from the dictionary and convert them into lists, then there should be no issue. Please find my gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/aad5a71ee2ee1dd9aa9b4d992bb93a35/untitled17.ipynb). Thanks!

**Comment by rakeshmothukuru1** [comment]
@gowthamkpr,
Thank you for the workaround but my intent is that the code provided in the Website should be correct, as many people consider  that as reference. TLDR, can we correct the code in this [USE-qa-v3 link](https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/3).

**Comment by ManishAradwad** [comment]
Hello, @gowthamkpr @rakeshmothukuru1 
I will start working on this issue. Can you please specify where can I find the required files??

**Comment by ManishAradwad** [comment]
Actually, I think this issue has already been resolved. The code on [USE-qa-v3 link](https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/3) works perfectly fine.

**Comment by maximneumann** [comment]
Thanks ManishAradwad and rakeshmothukuru1 for pointing it out.
We fixed the issue recently.
