### ISSUE TITLE
Missing Doc in signatures' __init__ API. 

### ISSUE THREAD

**Issue by XMK233** [tensorflow/hub#520]
The issue can be reproduced on CoLab: https://colab.research.google.com/drive/1V--H9ZDFsc1QEfsel8oNSlg_Ofr3azhh

------------------------------------

The model is `https://tfhub.dev/google/universal-sentence-encoder-qa/1` and `https://tfhub.dev/google/universal-sentence-encoder-qa/2`. I load the models with `hub.load()`: 

```
model1 = hub.load(r"https://tfhub.dev/google/universal-sentence-encoder-qa/1")
model2 = hub.load(r"https://tfhub.dev/google/universal-sentence-encoder-qa/2")
```

Choose a signature: `question_encoder`. Then see an functional API in V1 model: 

```
print(model1.signatures["question_encoder"].__init__.__doc__)
print(inspect.signature(model1.signatures["question_encoder"].__init__))
## None
## (fn_graph, variable_holder, attrs=None, signature=None)
```

...Then see the V2 model: 

```
print(model2.signatures["question_encoder"].__init__.__doc__)
print(inspect.signature(model2.signatures["question_encoder"].__init__))
## None
## (concrete_function)
```

... From the above cells, we can find that the argument list is different, but the documentation is still missing. It may be an issue and in my humble opinion, there should be some explanatory doc.

**Comment by maximneumann** [comment]
Thanks XMK233 for pointing it out. 
The documentation of the Hub modules is up to the module creators. We forwarded this issue to the original authors, and they might create a new version of the module in the near future.
In the meanwhile, please refer to the documentation on the module page and in the colab for the usage.
