### ISSUE TITLE
Regarding GSOC 2020

### ISSUE THREAD

**Issue by dhirensr** [tensorflow/hub#522]
Hello everyone,
I am interested in applying with TF Hub for GSOC 2020.
Are there any specific tasks to accomplish before writing the proposal for the same?

**Comment by rmothukuru** [comment]
@dhirensr,
This is not the forum related to GSOC. Request you to raise your question in the respective Repository. Closing this issue, as it is not a bug or feature request. 
Thanks!

**Comment by dhirensr** [comment]
@rmothukuru : there is one open forum discussion also where no one has replied regarding this.
Could you help me by guiding me how to contact the mentors?

**Comment by khimraj** [comment]
@dhirensr, It is clearly mentioned in google doc https://docs.google.com/document/d/1zT57PFMGZ04A4CvHxAKVpMTgXjsO92_oKeSKwZMc0Gs/ that to support your application, they highly recommend that you get started by exploring TensorFlow organization Github repos, and submitting PRs to add features or resolve issues.

**Comment by dhirensr** [comment]
@khimraj : thank you for replying. They changed the document I think because it wasn't mentioned before :smile:
