### ISSUE TITLE
USE/4 Preprocessing

### ISSUE THREAD

**Issue by akashsara** [tensorflow/hub#524]
Hiya,

The site for the Universal Sentence Encoder (https://tfhub.dev/google/universal-sentence-encoder/4) says "The module does not require preprocessing the data before applying the module, it performs best effort text input preprocessing inside the graph." However, I haven't been able to find out what exactly is being done as preprocessing. I wanted to know this to gain a better understanding of the model.

Cheers,
Akash

**Comment by jaxlaw** [comment]
Preprocessing in this model refers to tokenization of the input string into uni-grams and/or bi-grams in a predefined vocabulary that maps them to integer IDs. This model accomplishes this by using a combination of tf.split_text and tf.regex* and other tf.string* operations.

**Comment by akashsara** [comment]
Thanks! If you don't mind, I have a couple more follow up questions:
1. How does the model handle Out-of-Vocabulary words?
2. Is the model case sensitive?

**Comment by akashsara** [comment]
Got it. Thanks!

**Comment by akashsara** [comment]
Heya @djdongjin @jaxlaw, I was wondering if there's any place where I can actually take a look at the code for the preprocessing that's been done. Is this available anywhere?

**Comment by djdongjin** [comment]
> Heya @djdongjin @jaxlaw, I was wondering if there's any place where I can actually take a look at the code for the preprocessing that's been done. Is this available anywhere?

Hi, since the authors of USE didn’t open source their codebase, I’m afraid you cannot find the code.

**Comment by akashsara** [comment]
Ah, that is unfortunate. Do you happen to know if the normal USE (https://tfhub.dev/google/universal-sentence-encoder/4) does any sort of clipping to the text? I saw in other issues opened up that it clips the text at 128 tokens for the Lite and Large models. Do you have any intuition on why this was done for the Large model and if the same is happening here?

**Comment by djdongjin** [comment]
I suggest you go through the USE paper from which you can get more details and intuitions.
