### ISSUE TITLE
Do images need to be cropped and resized for make_image_classifier.py?

### ISSUE THREAD

**Issue by xulihang** [tensorflow/hub#525]
Hi there,

I want to train an image classifier to infer whether an image contains text or not. There may be some images which is very tall or wide, like this:

![robin-4](https://user-images.githubusercontent.com/5462205/75778883-9b948900-5d93-11ea-95bc-77e635a8a682.jpg)

Models like MobileNet have a fixed size. Do I need to crop and resize this kind of images before training and inference?

Thanks.

**Comment by gowthamkpr** [comment]
```
make_image_classifier \
  --image_dir my_image dir \
  --tfhub_module https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4 \
  --image_size 224 \
  --saved_model_dir my_dir/new_model \
  --labels_output_file class_labels.txt \
  --tflite_output_file new_mobile_model.tflite
```
Images are resized to the given `--image_size` after reading from disk. It depends on the TF Hub module whether it accepts only a fixed size (in which case you can omit this flag) or an arbitrary size (in which case you should start off by setting this to the standard value advertised in the module documentation)

As mentioned above, you can look at the modules input size and set the `mage_size` argument which should do the trick.

**Comment by xulihang** [comment]
I found that if the image is too long, the text in the resized one will be distorted.

![cropped](https://user-images.githubusercontent.com/5462205/75848003-c3c7ca80-5e1b-11ea-8fdb-78dac972b2df.jpg)

In this case, is it better to do a center crop? 

![cropped - 副本](https://user-images.githubusercontent.com/5462205/75848006-c75b5180-5e1b-11ea-8401-87c069f94692.jpg)

**Comment by gowthamkpr** [comment]
Yes its better to center the text here and resize it in a way such that the module input shape matches it.

**Comment by gowthamkpr** [comment]
@xulihang Can I go ahead and close this issue? Thanks!

**Comment by xulihang** [comment]
Yes, go ahead please.
