### ISSUE TITLE
fine- tuning universal sentence encoder large 5

### ISSUE THREAD

**Issue by starcsofnorth** [tensorflow/hub#526]
i am unable to fine it 
module_url = "https://tfhub.dev/google/universal-sentence-encoder-large/5"
sent1_input = tf.keras.layers.Input(shape=(32,128), name='sent1',dtype=tf.string) 
use_model = hub.KerasLayer(module_url, trainable= True)
output = use_model([sent1_input])

error:-
AssertionError: in converted code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_hub/keras_layer.py:209 call  *
        result = f()
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/saved_model/load.py:438 _call_attribute
        return instance.__call__(*args, **kwargs)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/eager/def_function.py:568 __call__
        result = self._call(*args, **kwds)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/eager/def_function.py:606 _call
        results = self._stateful_fn(*args, **kwds)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/eager/function.py:2363 __call__
        return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/eager/function.py:1611 _filtered_call
        self.captured_inputs)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/eager/function.py:1705 _call_flat
        "StatefulPartitionedCall": self._get_gradient_function()}):
    /usr/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/framework/ops.py:4727 _override_gradient_function
        assert not self._gradient_function_map

**Comment by gowthamkpr** [comment]
Was able to reproduce the error. Heres the [gist](https://colab.sandbox.google.com/gist/gowthamkpr/44557a54bb445e1ede1d2262fdcf03ef/untitled31.ipynb).Thanks!

**Comment by andresusanopinto** [comment]
The error message is indded not useful. However this works if you pass the right expected input shape (**shape=[]**)

```
module_url = "https://tfhub.dev/google/universal-sentence-encoder-large/5"
sent1_input = tf.keras.layers.Input(shape=[], name='sent1',dtype=tf.string)
use_model = hub.KerasLayer(module_url, trainable= True)
output = use_model(sent1_input)
```

Note: While debugging this I found that if first you run the bad code, then using the right code on the same process fails, if however you run the correct code right away, it seems to work fine.
