### ISSUE TITLE
Remove legacy Python 2 imports from future

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/hub#530]
Since the support for python 2 has been dropped, boilerplate code like
`from __future__ import absolute_import`
`from __future__ import division`
`from __future__ import print_function`
can be removed...

Related to : https://github.com/tensorflow/datasets/issues/1552

**Comment by gowthamkpr** [comment]
Adding context we do have a few examples as shown [here](https://github.com/tensorflow/hub/blob/master/examples/text_embeddings_v2/export_v2.py)

**Comment by ManishAradwad** [comment]
@gowthamkpr I didn't get what you're trying to say. Do u want me to change the above files as well?? They seem same to me.

**Comment by arnoegw** [comment]
Dear @ManishAradwad, you are very much correct in technical terms: Python 2 is no longer officially supported, and we will not make any extra efforts to accommodate Python 2 limitations.

That said, having those imports is a very small burden, and I think it would be unwise for an add-on library like ours to try and be more zealous than the "mothership" tensorflow in actively breaking Python 2 users that might still be hiding somewhere. Let's shelf this for now and come back to it when tensorflow at large is doing it.

I've renamed the issue to serve as a targeted reminder.

**Comment by arnoegw** [comment]
We're getting closer... The end of Python 2 for tensorflow_hub has been announced in https://groups.google.com/a/tensorflow.org/g/hub/c/STS3sNu46NE/m/06dDHJ9dAwAJ
and `tensorflow_hub/__init__.py` on the master branch fails for it since commit https://github.com/tensorflow/hub/commit/cc84a6e4f56921f5721d25155e5854e63342e2cb

**Comment by arnoegw** [comment]
This is happening now: commit https://github.com/tensorflow/hub/commit/acbfaf1d7540a282dc72775f57ff14e573082b41 removed the imports from future on the master branch, and there will be followups to remove the use of `six` and some other patterns of compatibility code.
