### ISSUE TITLE
Add a pre trained model for stair cases in tensorflow hub

### ISSUE THREAD

**Issue by Jitender46559** [tensorflow/hub#532]
@gowthamkpr Sir, I want to add the stair cases model in tensorflow hub in this gsoc 2020. As we know their are 30 to 40 % blind persons and they are not able to see. So I think this model should me added in the tensorflow hub.

**Comment by rohitg00** [comment]
I want to add one pre-trained model for disease detection for infected crop and amount of pesticides to cure it. How to do so?

**Comment by j-grimstad** [comment]
Hi @Jitender46559 and @rohitg00  -- both of your contributions would be very welcome! You can find more information on how to publish to tfhub.dev here: https://www.tensorflow.org/hub/publish
