### ISSUE TITLE
NNLM OOV Bucket Averaging Functionality Clarification

### ISSUE THREAD

**Issue by brycecf** [tensorflow/hub#539]
I have a clarifying question about the OOV bucket averaging as described in this comment:
https://github.com/tensorflow/hub/issues/168#issuecomment-426180212

Is the average embedding determined from only those in-vocab tokens (of the left-out 2.5%) that would also hash to the same bucket as the OOV token?  Or is it some other process?

**Comment by rmothukuru** [comment]
@brycecf,
Yes, the average embedding is initialized from the rest 97.5% vocab tokens. Later on they might be fine-tuned to the new tokens that hash to those bucket too.

**Comment by rmothukuru** [comment]
@brycecf,
Can you please let us know if your question is answered so that we can close this issue. Thanks!

**Comment by rmothukuru** [comment]
@brycecf,
Can you please respond to the above comment. Thanks!
