### ISSUE TITLE
How can I contribute to TF Hub?

### ISSUE THREAD

**Issue by Dynmi** [tensorflow/hub#542]
I want to add Cartoon-GAN model and publish it to TF Hub with useful colab demo to show them in use. But I'm not clear how can I do such thing. Could anyone show me a channel?

**Comment by hrishikeshmane** [comment]
How to contribute- https://github.com/tensorflow/hub/blob/master/README.md
How to publish- https://github.com/tensorflow/hub/tree/master/tfhub_dev

**Comment by j-grimstad** [comment]
Hi @Dynmi , @hrishikeshmane has added the right links -- please take a look and let us know if you have any questions about publishing. Looking forward to seeing your contribution!
