### ISSUE TITLE
Typo in tools/make_image_classifier/make_image_classifier_lib.py

### ISSUE THREAD

**Issue by rushabh-v** [tensorflow/hub#544]
The spelling of `input` is wrong on the below line.
https://github.com/tensorflow/hub/blob/d6ee95376e80ce8e1df9a1f1057402c7ca98d4fa/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py#L140

**Comment by arnoegw** [comment]
Thanks for sending the fix in pull request https://github.com/tensorflow/hub/pull/545. This has been merged, to this issue is resolved.
