### ISSUE TITLE
Incorrect URL in the docs- SavedModels from TF Hub in TensorFlow 2

### ISSUE THREAD

**Issue by hrishikeshmane** [tensorflow/hub#547]
Given URL in the [TensorFlow Hub SavedModels from TF Hub in TensorFlow 2](https://github.com/tensorflow/hub/blob/master/docs/tf2_saved_model.md) docs is incorrect. 

In "For SavedModel creators" the following given URL is not valid.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/saved_model/integration_tests/export_mnist.py

**Comment by hrishikeshmane** [comment]
I have corrected the docs. Here is the pull request

https://github.com/tensorflow/hub/pull/543

**Comment by rmothukuru** [comment]
@hrishikeshmane ,
Since the PR, [#543](https://github.com/tensorflow/hub/pull/543) is merged, can you please confirm if we can close this issue. Thanks!

**Comment by hrishikeshmane** [comment]
Yeah sure. You may close the issue. @rmothukuru
