### ISSUE TITLE
ImportError: cannot import name 'tools' from 'tensorflow_hub' 

### ISSUE THREAD

**Issue by rahulmarlabs** [tensorflow/hub#548]
OS: Ubuntu 18.04
Python: 3.6
Tensorflow Version: 2.1.0
Tensorflow_hub version: 0.7.0

Showing this error while importing tensorflow_hub
~/anaconda3/lib/python3.7/site-packages/tensorflow_hub/__init__.py in <module>
     64 # The package `tensorflow_hub.tools` is available separately for import, but
     65 # it is not meant to be available as attribute of the tensorflow_hub module.
---> 66 from tensorflow_hub import tools
     67 del tools
     68 # pylint: enable=g-bad-import-order

ImportError: cannot import name 'tools' from 'tensorflow_hub' (/home/user/anaconda3/lib/python3.7/site-packages/tensorflow_hub/__init__.py)

**Comment by rmothukuru** [comment]
@rahulmarlabs,
Can you please provide the steps of code you have followed. Below Code works for me.

```
!pip install "tensorflow_hub==0.7.0"
!pip install "tensorflow==2.1"
import tensorflow_hub as hub
``` 

You can try creating a New Virtual Environment in Anaconda and can try executing the above steps. Thanks!

**Comment by rahulmarlabs** [comment]
Worked in Virtual environment. Thank you.

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved. Thanks!

**Comment by leelaprabhu** [comment]
@rahulmarlabs Did you, by any chance, figure out why it wasn't working earlier. I'm running into the same issue, but with tensorflow_hub 0.9. 

It does work in a fresh virtual environment though.

**Comment by rahulmarlabs** [comment]
@leelaprabhu Couldn't figure out the reason behind this issue. But yes, it works in a fresh virtual environment.
