### ISSUE TITLE
Facenet based model

### ISSUE THREAD

**Issue by markatlarge** [tensorflow/hub#549]
Does anyone know of any FaceNet-based models trained models in TF2 format.  Maybe trained with the CASIA-WebFace or VGGFace2/  Models that are for facial recognition.

**Comment by akhorlin** [comment]
TensorFlow Hub team is not aware of such models at this time. Maybe others might now.

**Comment by arnoegw** [comment]
@shubham0204 sent https://github.com/tensorflow/tfhub.dev/pull/17 for FaceNet, but we are not publishing models of this nature at this time.
