### ISSUE TITLE
EfficientNet in SavedModel (TF2) on Hub

### ISSUE THREAD

**Issue by michal-kierzynka** [tensorflow/hub#550]
Hi all,

Is there any timeline for adding the EfficientNet pretrained models to the Hub in the SavedModel format that is compatible with TF2? Currently EfficientNet models are served only in hub.Module format which is not compatible with TF2.

Best regards

**Comment by TechnikEmpire** [comment]
I'm wondering if this is something that the community can get done with a little guidance? A ton of these issues seem to rely on the mysterious "tensorflower" and go back couple years... so I'm just wondering if maybe with some pointers we can get this done. I tried to migrate the modules to TF2 but it seems there's embedded model metadata that explicitly prevents TF2 from accepting this.

**Comment by vbardiovskyg** [comment]
Unfortunately, it is typically not possible to convert TF1 models to TF2 directly (at the least, fine-tuning would not work) and we have to wait until a respective team in TensorFlow or beyond decides to publish them. I can say that there are ongoing efforts in getting TF2 EfficientNet models, but no ETA.

**Comment by TechnikEmpire** [comment]
Thanks for the response.

**Comment by j-grimstad** [comment]
Hi @michal-kierzynka and @TechnikEmpire, these are now available here: https://tfhub.dev/s?tf-version=tf2&q=efficientnet

Will close this bug -- feel free to reopen if this isn't what you were looking for!

**Comment by TechnikEmpire** [comment]
@j-grimstad Fantastic, thank you!

**Comment by michal-kierzynka** [comment]
@j-grimstad thank you very much :)
