### ISSUE TITLE
Incorrect URL in text_classification_with_tf_hub

### ISSUE THREAD

**Issue by kikejimenez** [tensorflow/hub#553]
In notebook [Text Classification with TF Hub](https://github.com/tensorflow/hub/blob/master/docs/tutorials/text_classification_with_tf_hub.ipynb)

In the  *Feature columns* subsection, the following link appears to be broken
https://github.com/tensorflow/hub/blob/master/docs/api_docs/python/hub/text_embedding_column.md

**Comment by kikejimenez** [comment]
I fixed it in #555

**Comment by arnoegw** [comment]
Thank you; your fix has been merged into the master branch.
