### ISSUE TITLE
MobileNet V3 Feature Vector

### ISSUE THREAD

**Issue by CRosero** [tensorflow/hub#557]
Are there any news on whether the feature vector for Mobilenet V3 will be made available soon?

**Comment by TechnikEmpire** [comment]
Just out of curiosity, how can the community contribute this? Its marked for community contrib. I don't have billions of dollars in TPU units to train imagenet overnight, and I best most people don't.  I cannot find any guidance on how to take existing published checkpoints either.

Can we get some guidance on this? I'm happy to contribute but my lack of Google's resources and no documentation (that I can find) make it prohibitively difficult.

**Comment by MorganR** [comment]
Thank you for the comment; we could have been more clear here. The intention was not for folks to need to train their own models from scratch. The original trained MobileNet V3 checkpoints were [published along with their code](https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet). 

We've now converted these to SavedModel format and published them to tfhub.dev. You can find them linked in Google's [image collection](https://tfhub.dev/google/collections/image/1).

TFLite and TFJS versions will follow shortly.

**Comment by TechnikEmpire** [comment]
@MorganR beautiful. Thank you.
