### ISSUE TITLE
CamemBERT and FlauBERT on TensorFlow Hub

### ISSUE THREAD

**Issue by jusugac1** [tensorflow/hub#560]
Hello,

I searched the BERT-based models CamemBERT and FlauBERT on TensorFlow Hub but I could not find them. Does anyone know if they are available? Otherwise, do you know if they will be uploaded soon?

Thank you,

J.

**Comment by arnoegw** [comment]
Hi @jusugac1, thank you for your request! There is no information right now about future availability of those models. Let's keep this issue open as a request for them.

**Comment by WGierke** [comment]
Hi @jusugac1 
Unfortunately, we currently don't have bandwidth to work on training & publishing these models. I'm thus closing this issue for now but will add a comment if the models get published in the future. As always, we are happy to receive contributions from external contributors to tfhub.dev!
