### ISSUE TITLE
Multilingual Universal Sentence Encoder training is extremely slow

### ISSUE THREAD

**Issue by ns-hxue** [tensorflow/hub#561]
Is there anyone that has every used Multilingual Universal Sentence Encoder?

When I use it for training, it is extremely slow comparing to English only model. I could not find out why.

**Comment by gowthamkpr** [comment]
@ns-hxue Can you please provide us some reproducible code for us to reproduce this issue. Thanks!

**Comment by gowthamkpr** [comment]
@ns-hxue Can you please respond to the above comment so that we can take the discussion forward

**Comment by gowthamkpr** [comment]
@ns-hxue Closing this issue as it has been inactive for more than a week. Please add additional comments for us to open this issue again.
