### ISSUE TITLE
Explanation to the `bert_model/pooler_transform/kernel`

### ISSUE THREAD

**Issue by bastia1989** [tensorflow/hub#565]
If we load the bert model by:
```
import tensorflow_hub as hub
bert_layer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1",
                            trainable=True)
```
Then if we print out all inside components by using:
```
for variable in bert_layer.variables:
    print(variable.name, variable.trainable)
```
We find the last three objects are:
```
bert_model/pooler_transform/kernel:0 True
bert_model/pooler_transform/bias:0 True
Variable:0 False
```
As far as I know, the pooler layer with `tanh` activation function should apply to only `[cls]` token; however, it seems that it is applied to the whole sequence, if we call:
`pooled_output, sequence_output = bert_layer([input_word_ids, input_mask, segment_ids])`

Is this the correct way?  Thanks.

**Comment by BaoshengHeTR** [comment]
another question is. So for multihead attention, there should be a layer after all attention to concatenate the attention outs and convert to a new output with the same dimension as the embeddings. Here is what I found:
```
bert_model/encoder/layer_0/self_attention/query/kernel:0 True
bert_model/encoder/layer_0/self_attention/query/bias:0 True
bert_model/encoder/layer_0/self_attention/key/kernel:0 True
bert_model/encoder/layer_0/self_attention/key/bias:0 True
bert_model/encoder/layer_0/self_attention/value/kernel:0 True
bert_model/encoder/layer_0/self_attention/value/bias:0 True
bert_model/encoder/layer_0/self_attention_output/kernel:0 True
bert_model/encoder/layer_0/self_attention_output/bias:0 True
bert_model/encoder/layer_0/self_attention_layer_norm/gamma:0 True
bert_model/encoder/layer_0/self_attention_layer_norm/beta:0 True
```
I would like to know what is the `self_attention_output` do, and why it has 2 sets of parameters, namely kernel and bias. Thanks.

**Comment by arnoegw** [comment]
Thank you for your interest in BERT.

The tensorflow/bert* models are created by the open-source tool
https://github.com/tensorflow/models/blob/master/official/nlp/bert/export_tfhub.py
from the model-building code in the same project. In particular, the recent update
https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2
was built roughly at github commit https://github.com/tensorflow/models/tree/0e4029f0f26e242ed4ed08b758b6187e0e82c3c2

To understand the model at this level of detail, please peruse the tensorflow/models code. If you think that code is incorrect, please report it at https://github.com/tensorflow/models/issues or send a pull request to fix it. In case an issue gets confirmed and fixed, and an update to TF Hub does not happen automatically, feel free to request it here.
