### ISSUE TITLE
faster_rcnn/openimages_v4/inception_resnet_v2 location of ouput definition

### ISSUE THREAD

**Issue by zacwellmer** [tensorflow/hub#568]
I was looking at the outputs of [FRCNN open images model](https://tfhub.dev/google/faster_rcnn/openimages_v4/inception_resnet_v2/1) and noticed it outputs "detection_class_names". Can someone point me to where this is defined? I looked in the [Models](https://github.com/tensorflow/models) repo but could not find where this explicitly defined.

**Comment by gowthamkpr** [comment]
You can take a look at the model config file [here](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_inception_resnet_v2_atrous_oid.config)

**Comment by zacwellmer** [comment]
@gowthamkpr I assume you are referring to the post_processing step in that file. I don't think that specifies the outputs. To me it seems like the folks who uploaded the faster_rcnn/openimages_v4/inception_resnet_v2 modified the signature

**Comment by gowthamkpr** [comment]
They are using the default signature. Please take a look at the[ colab notebook](https://colab.sandbox.google.com/github/tensorflow/hub/blob/master/examples/colab/object_detection.ipynb#scrollTo=WUUY3nfRX7VF)

**Comment by zacwellmer** [comment]
@gowthamkpr That notebook does not tell you how the default signature was defined

**Comment by djdongjin** [comment]
@zacwellmer You can find all the label_map [here](https://github.com/tensorflow/models/tree/master/research/object_detection/data). According to the model [config](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_inception_resnet_v2_atrous_oid.config), it should be trained with `oid_bbox_trainable_label_map.pbtxt`.

**Comment by gowthamkpr** [comment]
@zacwellmer Is it still an issue or is it being resolved? Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for close to 3 weeks. Please add additional comments for us to open this issue again. Thanks!
