### ISSUE TITLE
Universal Sentence Encoder Notebook Error

### ISSUE THREAD

**Issue by zzj0402** [tensorflow/hub#570]
Download Data to Index:
```
Exception: URL fetch failure on http://opus.nlpl.eu/download.php?f=News-Commentary/v11/moses/en-ru.txt.zip: None -- [Errno -2] Name or service not known site:stackoverflow.com
```
https://tfhub.dev/google/universal-sentence-encoder-multilingual/3

**Comment by gowthamkpr** [comment]
@zzj0402 Can you please provide some reproducible code for us to reproduce this issue. Thanks!

**Comment by zzj0402** [comment]
https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/cross_lingual_similarity_with_tf_hub_multilingual_universal_encoder.ipynb

**Comment by gowthamkpr** [comment]
@zzj0402 Tried running the whole notebook but I was not able to run into any error.

**Comment by zzj0402** [comment]
> @zzj0402 Tried running the whole notebook but I was not able to run into any error.

Browse down.

**Comment by gowthamkpr** [comment]
I ran the entire notebook. But I am not running into any error.

**Comment by zzj0402** [comment]
`Downloading data from http://opus.nlpl.eu/download.php?f=News-Commentary/v11/moses/ar-en.txt.zip
24715264/24714354 [==============================] - 2s 0us/step
1,000 Arabic sentences
Downloading data from http://opus.nlpl.eu/download.php?f=News-Commentary/v11/moses/en-zh.txt.zip
18104320/18101984 [==============================] - 2s 0us/step
1,000 Chinese sentences
Downloading data from http://opus.nlpl.eu/download.php?f=News-Commentary/v11/moses/en-es.txt.zip
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1324                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1325                           encode_chunked=req.has_header('Transfer-encoding'))
   1326             except OSError as err: # timeout error

17 frames
gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
URLError: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    266         raise Exception(error_msg.format(origin, e.code, e.msg))
    267       except URLError as e:
--> 268         raise Exception(error_msg.format(origin, e.errno, e.reason))
    269     except (Exception, KeyboardInterrupt) as e:
    270       if os.path.exists(fpath):

Exception: URL fetch failure on http://opus.nlpl.eu/download.php?f=News-Commentary/v11/moses/en-es.txt.zip: None -- [Errno -2] Name or service not known`

**Comment by zzj0402** [comment]
![Screenshot_20200509-083341](https://user-images.githubusercontent.com/15345547/81446955-d8d02980-91cf-11ea-83a5-e0ae4021d031.png)
Replicated May 9th,2020

**Comment by gowthamkpr** [comment]
@zzj0402 I am not able to reproduce the error. I ran the entire notebook couple of times but an not running into any error. Heres my [gist](https://colab.research.google.com/gist/gowthamkpr/a8b8d25d185e65c87a72834d3470bd12/cross-lingual-similarity-and-semantic-search-engine-with-tf-hub-multilingual-universal-encoder.ipynb).

**Comment by zzj0402** [comment]
Ran the ##Download Data to Index section

**Comment by zzj0402** [comment]
Guess they fix it.
