### ISSUE TITLE
Using large vocabulary in SentencePiece Library to get sentence embeddings using USE Lite model degrades the embeddings

### ISSUE THREAD

**Issue by anurag89sharma** [tensorflow/hub#571]
I am currently working on using the Universal Sentence Encoder Lite model for getting text embeddings for our corpus to find similar items. The [documentations ](https://tfhub.dev/google/universal-sentence-encoder-lite/2) says to process the sentences using the [SentencePiece Library](https://github.com/google/sentencepiece) before passing them to the model. 

The default model of the SentencePiece library has a vocabulary size of 8K. Using this I am able to get good results. I then tried to use a larger vocabulary of size 30K from SentencePiece to see if the quality improves. I found out that the quality of the embeddings degrades.  

I used annoy library to build the index of the embedding vectors to get the K nearest matching items. The results I got with the embeddings from the larger vocabulary is giving very bad results (that have no significance to the input text).

Wanted to know if the USE Lite model is specifically trained on SentencePiece 8k vocabulary.

Thank you.

**Comment by arnoegw** [comment]
This is expected (beyond USE Lite): you can't just change the vocab of a pre-trained text embedding. The pre-training depends on the particular ids assigned by the original vocab.
