### ISSUE TITLE
universal-sentence-encoder-multilingual doesn't support automatic batching but universal-sentence-encoder does

### ISSUE THREAD

**Issue by shenkev** [tensorflow/hub#573]
I'm trying to figure out what's going on: I have a long list of 10,000,000 sentences I want to encode.

I can run the following code just fine.

```
    chunk_size = 100000

    for i in tqdm(range(0, len(all_sentences), chunk_size)):

        chunk = all_sentences[i: min(i+chunk_size, len(all_sentences))]
        emb = **universal_sentence_encoder**(chunk)
        all_embeddings.append(emb.numpy())
```

Given the size of the batch I pass into universal_sentence_encoder is quite large, I'm assuming batching is done automatically by the API.

When I use the multillingual version, I get an out-of-memory error.

```
    chunk_size = 100000

    for i in tqdm(range(0, len(all_sentences), chunk_size)):

        chunk = all_sentences[i: min(i+chunk_size, len(all_sentences))]
        emb = **universal_sentence_encoder_multilingual**(chunk)
        all_embeddings.append(emb.numpy())
```

```
OOM when allocating ten│
sor with shape[3930608,256] and type float on /job:localhost/replica:0/task:0/device:GPU│
:0 by allocator GPU_0_bfc                                                               │
         [[{{node StatefulPartitionedCall/StatefulPartitionedCall/EncoderDNN/CNN_layers/│
ngram_order_2/input_size_projection/dense/MatMul}}]]                                    │
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor│
_allocations_upon_oom to RunOptions for current allocation info.                        │
 [Op:__inference_restored_function_body_14376]                  
```

Is this expected behavior?

**Comment by gowthamkpr** [comment]
@shenkev When you are using `Multilingual USE` your GPU is running out of memory. Can you try reducing the batch size when using Multilingual USE. Thanks!

**Comment by jaxlaw** [comment]
No batching is done internally thus OOM is expected when using a large batch. Each model's memory consumption is different so one model may be able to handle a large batch size but another does not. We recommend batch of 1000.

**Comment by gowthamkpr** [comment]
@shenkev Is this issue resolved? Thanks!

**Comment by shenkev** [comment]
Yup thanks! For future reference the multilingual large runs 10x slower than multilingual regular for some reason.
