### ISSUE TITLE
BERT model does not have expected output names

### ISSUE THREAD

**Issue by 1duo** [tensorflow/hub#577]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 2.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

```
# model is from: https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/1

saved_model_dir = "path/to/bert_en_cased_L-12_H-768_A-12/1"
loaded_model = tf.saved_model.load(saved_model_dir)
concrete_func = loaded_model.signatures["serving_default"]
prediction = concrete_func(**inputs)
```

As an user, I'm expecting output names to be `["Identity", "Identity_1"]` as shown:

```
concrete_fn.outputs
Out[4]: 
[<tf.Tensor 'Identity:0' shape=(None, 768) dtype=float32>,
 <tf.Tensor 'Identity_1:0' shape=(None, None, 768) dtype=float32>]
```

**However, actual prediction returns a dict with different output names:** 

`["bert_model", "bert_model_1]`

```
prediction.keys()
Out[5]: [u'bert_model_1', u'bert_model']
```

**Describe the expected behavior**

Expecting the prediction output has same name as `concrete_func.outputs`.

**Comment by arnoegw** [comment]
https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/1 (and now also version /2) is a TF2 SavedModel. Please see https://www.tensorflow.org/hub/tf2_saved_model for how to reuse it, In particular, the discussion of serving signatures vs tf.function API under the heading "what to expect from the SavedModel after loading". Bottom line: use `loaded_model()`, not `loaded_model.signature["..."]()`.

Also, please note that signatures are meant to map between externally visible names (the keys you observed) and in-graph names (as reported in a tf.Tensor's string representation).
