### ISSUE TITLE
downloading universal sentence encoder pre-trained model

### ISSUE THREAD

**Issue by pramod2157** [tensorflow/hub#58]
I am using universal sentence encoder pre-trained model using below command:
embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/1")

Why do I need to get the model from cloud everytime?

I tried `wget https://tfhub.dev/google/universal-sentence-encoder/1`
Tried opening above link in browser, it's redirecting me to https://www.tensorflow.org/hub/modules/google/universal-sentence-encoder/1
How to download the pre-trained model?

**Comment by svsgoogle** [comment]
Seems you're looking for the section called "Caching Modules" at https://www.tensorflow.org/hub/basics

**Comment by pramod2157** [comment]
Yes, its working. Thanks

**Comment by joydeb28** [comment]
same issue please give some suggestion.
in my tmp folder i have tfhub_modules.
how to use it?

**Comment by sreenathelloti** [comment]
How to download the pre-trained model in windows 10?

**Comment by sreenathelloti** [comment]
> Yes, its working. Thanks



> Seems you're looking for the section called "Caching Modules" at https://www.tensorflow.org/hub/basics

How to download the pre-trained model in windows 10?

**Comment by rv-ltran** [comment]
How do I use U.S.E tensorflow hub in AWS Sagemaker?
