### ISSUE TITLE
Text styling issues in tfhub_dev README

### ISSUE THREAD

**Issue by Rishit-dagli** [tensorflow/hub#586]
There are text styling issue in tfhub_dev README, which can be seen here-

* [Exporting a model](https://github.com/tensorflow/hub/tree/master/tfhub_dev#model)
* [Best practices for SavedModel publishing](https://github.com/tensorflow/hub/tree/master/tfhub_dev#model)

I have proposed a PR solving this issue #587

**Comment by WGierke** [comment]
Solved via c7a526d72ea74983290d9c09323fd8e78e8045a7
