### ISSUE TITLE
Applying stylization on batches causes problems

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/hub#590]
Hi. 

I am currently using [the stylization module of TF-Hub](https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2) for a set of experiments where I am applying stylization at random on a set of images. Consider that as a data augmentation operation. 

After applying stylization, the images are coming out as the following: 

![image](https://user-images.githubusercontent.com/22957388/82208496-40514c00-9929-11ea-9d7c-5544e628c27a.png)

I am using the Cats-vs.-Dogs dataset and I am loading it using the following code listing:
```python
train_ds, validation_ds = tfds.load(
    'cats_vs_dogs',
    split=['train[:85%]', 'train[85%:]'],
    as_supervised=True
)
```

After this, I am creating a utility function to apply the stylization module to a given image and I am mapping that utility like so - 

```python
train_ds = (
    train_ds
    .map(preprocess_image, num_parallel_calls=AUTO)
    .shuffle(1024)
    .map(apply_random_stylization, num_parallel_calls=AUTO)
    .batch(BATCH_SIZE)
    .prefetch(AUTO)
)
```
`apply_random_stylization` is defined as - 

```python
def apply_random_stylization(image, label):
    image = random_apply(stylize_image, image, p=0.8)
    return (image, label)

def random_apply(func, x, p):
        return tf.cond(
          tf.less(tf.random.uniform([], minval=0, maxval=1, dtype=tf.float32),
                  tf.cast(p, tf.float32)),
          lambda: func(x),
          lambda: x)
        
def stylize_image(image):
    stylized_image = HUB_MODULE(tf.expand_dims(image, 0), tf.constant(STYLE_IMG))[0]
    stylized_image = tf.squeeze(stylized_image)
    return tf.clip_by_value(stylized_image, 0., 1.)
```

Here's the [Colab Gist](https://colab.research.google.com/gist/sayakpaul/2c5dbcce0ec659c9b9e5be0149304c35/scratchpad.ipynb) that reproduces this issue. 

Any help would be appreciated. Thanks!

**Comment by gowthamkpr** [comment]
@sayakpaul I would not recommend using this model for data augmentation as it is specifically designed for paintings. For more information you can refer to the code [here](https://github.com/tensorflow/magenta/blob/master/magenta/models/arbitrary_image_stylization/arbitrary_image_stylization_build_mobilenet_model.py).

**Comment by sayakpaul** [comment]
Okay but that does not explain why the pixel values are coming out as mentioned above. So let's say instead of augmentation I am trying to simply apply them in batches. I would be interested to know how could I do that.

**Comment by gowthamkpr** [comment]
@sayakpaul If you wanna learn about how Neural style transfer works  in depth, I would recommend you to read this [article](https://towardsdatascience.com/neural-style-transfer-with-tensorflow-hub-dfe003df0ea7). Also please post support questions like these on stackoverflow first as there is a wider community to respond. Thanks!

**Comment by sayakpaul** [comment]
I think think you are either not getting my question or I am not able to
make you understand that I am in search of the answers you have given so
far. None of your answers actually explains the cause behind the issue I am
facing.

Thanks for your inputs though.

**Comment by andresusanopinto** [comment]
Hi @sayakpaul,

Using BATCH_SIZE = 1 or BATCH_SIZE = 32 leads to similar effects so I don't think this particular  module is misbehaving when batch size is set.

In fact the main issue is that this module expectes images to be feed into range 0.0-1.0 and not 0-255. If one uses the correct range in both the image to stylize and the style image, e.g.:

```
-  return (image, label)
+ return (image/255.0, label)
```
and

```
--- STYLE_IMG = parse_single(STYLE_PATH)
+++ STYLE_IMG = parse_single(STYLE_PATH) / 255.0
```

Then one ends up with something like:
![4NSa2EimDFX](https://user-images.githubusercontent.com/580896/83112860-0faaa880-a0c7-11ea-9d6c-c3116f53bac0.png)
