### ISSUE TITLE
hub.KerasLayer is missing implementation of compute_output_shape()

### ISSUE THREAD

**Issue by qlzh727** [tensorflow/hub#596]
See https://github.com/tensorflow/tensorflow/issues/39542 for more details.

Currently hub.KerasLayer is missing implementation of compute_output_shape(), which cause error when used with keras.layers.TimeDistributed

**Comment by eliorc** [comment]
I've opened the original issue on tensorflow/tensorflow, the consequence of this missing implementation is that if you want to apply `hub.KerasLayer` over time using `tf.keras.layers.TimeDistributed` you can't as it will cause an error.

Since hub is used a lot for feature extraction from images, it is a very common use case as when working with a sequence of images (video/gifs etc.) you'll need to extract features over time

**Comment by MorganR** [comment]
A workaround has been implemented in the above linked commit. If users set the `output_shape` when initializing the keras layer, `compute_output_shape` can use this information. Eg:

```python
# Output_shape excludes the batch dimension
layer = hub.KerasLayer("https://tfhub.dev/some/model/1", output_shape=(4, 4))
...
# Input_shape includes the batch dimension (can be None)
expected_shape = layer.compute_output_shape(input_shape=(10, 2, 4)).as_list()
# expected_shape = [10, 4, 4]
```

This will be included in the next release.

**Comment by HunterTom94** [comment]
> A workaround has been implemented in the above linked commit. If users set the `output_shape` when initializing the keras layer, `compute_output_shape` can use this information. Eg:
> 
> ```python
> # Output_shape excludes the batch dimension
> layer = hub.KerasLayer("https://tfhub.dev/some/model/1", output_shape=(4, 4))
> ...
> # Input_shape includes the batch dimension (can be None)
> expected_shape = layer.compute_output_shape(input_shape=(10, 2, 4)).as_list()
> # expected_shape = [10, 4, 4]
> ```
> 
> This will be included in the next release.

Hello, I am having the same issue. Will this workaround be only in the latest tf-nightly or it will be in the stable release? When will I be able to upgrade so that I can fix this issue in my code? Thank you very much!

**Comment by MorganR** [comment]
This has been released in the most recent release, tensorflow-hub 0.12.0. @HunterTom94 please post here if this resolves your issue, or if you are still having trouble.

**Comment by HunterTom94** [comment]
> This has been released in the most recent release, tensorflow-hub 0.12.0. @HunterTom94 please post here if this resolves your issue, or if you are still having trouble.

Thanks for the reply. I just realized I wasn't using tensorflow-hub in particular but got the same error anyway

**Comment by MorganR** [comment]
In that case I am closing this issue as resolved. Folks can reopen this if the TF Hub workaround is not working for them.

**Comment by tchaye59** [comment]
I had similar issue and this trick works for me 

```
# Load KerasLayer
input = ...
layer = hub.KerasLayer("https://tfhub.dev/some/model/1",)
net  = layer(input)
net = tf.keras.Model(input , net)
# Add custom compute_output_shape 
net.compute_output_shape = lambda x : (x[0],x[1],512)

# now use net to build my model 
# Create model
model = tf.keras.Sequential([tf.keras.layers.TimeDistributed(net),...])

```
