### ISSUE TITLE
How to use TFhub module in TF-Serving

### ISSUE THREAD

**Issue by sun1638650145** [tensorflow/hub#599]
I want to use arbitrary-image-stylization, but I don't Know how to write code to send json, this model has two inputs, and the document is not found in the similar repository on tensorflow website and github. The error now is {'error': 'instances is a plain list, but expecting list of objects as multiple input tensors required as per tensorinfo_map'}. Thanks.

**Comment by rmothukuru** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Also, please share the SignatureDef for your Model. Thanks!

**Comment by abohosam1772** [comment]
[]()

**Comment by rmothukuru** [comment]
@sun1638650145,
Can you please provide the information asked in the comment above. Thanks!

**Comment by sun1638650145** [comment]
I have found a solution, it is enough to find out the input and output of the model, thanks

**Comment by SystemZ** [comment]
> I have found a solution, it is enough to find out the input and output of the model, thanks

Could you write down some details about this?

**Comment by sun1638650145** [comment]
> > I have found a solution, it is enough to find out the input and output of the model, thanks
> 
> Could you write down some details about this?

you can see my demo [Filter](https://github.com/sun1638650145/Filter).

**Comment by leidejun** [comment]
> nd a solution

How to solve this problem? I also met it

**Comment by leidejun** [comment]
> I have found a solution, it is enough to find out the input and output of the model, thanks

怎么解决的呢，我也遇到这个问题了

**Comment by sun1638650145** [comment]
你看我上面的链接，链接写的很清楚了
