### ISSUE TITLE
getting word from embeddings

### ISSUE THREAD

**Issue by 404Zack** [tensorflow/hub#603]
I need to get words for a given embeddings, is there any way ?

**Comment by gowthamkpr** [comment]
@404Zack Can you please describe this issue in detail? Thanks!

**Comment by 404Zack** [comment]
Suppose that I have generated embeddings of an unknown word, how can I get to know that word or the most similar one to that word.

**Comment by gowthamkpr** [comment]
@404Zack What module are you using to generate word embeddings?

**Comment by 404Zack** [comment]
@gowthamkpr  this model https://tfhub.dev/google/universal-sentence-encoder-multilingual/3

**Comment by jaxlaw** [comment]
Word(s) to embeddings is a non-reversible operation, thus embeddings back to words are not supported. However, you can generate the embeddings of all words and put them in an index such as https://simpleneighbors.readthedocs.io/en/latest/ and do a nearest neighbor search on the unknown word. That would give you top N similar words.

See https://www.tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa for an example.

**Comment by gowthamkpr** [comment]
I'm closing this issue as it has been answered.
