### ISSUE TITLE
clarification with TF datasets: more efficient to vectorize with unbatching (batch -> map -> unbatch) or just map?

### ISSUE THREAD

**Issue by jshyatt2** [tensorflow/hub#608]
Hi, 

First time reporting an issue on Github - as far as I can tell this is also the place to report or request anything related to the official documentation and guides as well, which is what this is about. (Apologies if this is not the case!)

I have seen in several (non-official) code examples posted online that people apply vectorized mapping in the following way using the dataset API: batch -> map -> unbatch. The relevant official guides at https://www.tensorflow.org/guide/data and https://www.tensorflow.org/guide/data_performance don't address this (either encourage or discourage). I originally implemented this myself, thinking that there must be a reason so many other people were doing it, but I've since found that in at least some cases this is very inefficient (at least in the cases I tested, it increased the time to apply the overall transformation by 150% over just applying map without adding batch/unbatch).

I posted on stackoverflow asking about this at https://stackoverflow.com/questions/61876941/tensorflow-datasets-more-efficient-to-vectorize-with-unbatching-batch-map but haven't received a response. If there is a good rule of thumb (other than testing every transformation, data type, batch size, hardware, etc. on a case-by-case basis) is it possible to add it to the documentation, or at least warn that it might cause a serious slowdown? I could see there being cases where this method does increase efficiency, but then again, maybe not.

Thanks.

**Comment by djdongjin** [comment]
@jshyatt2 Hi, you should report this issue to the [main TensorFlow repo](https://github.com/tensorflow/tensorflow) instead of TF Hub.

**Comment by rmothukuru** [comment]
@jshyatt2,
As suggested by @djdongjin, please report this issue in [Tensorflow Repo](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by jshyatt2** [comment]
Sorry, I did report it there, at https://github.com/tensorflow/tensorflow/issues/40386. I closed it after getting a response, but I guess I forgot to close this issue. Thanks for the reminder!
