### ISSUE TITLE
can i contribute pretrained models on speech domain ?

### ISSUE THREAD

**Issue by dathudeptrai** [tensorflow/hub#614]
Hi, I'm a creator of TensorflowTTS: Real-Time State-of-the-art Speech Synthesis for Tensorflow 2. on https://tfhub.dev/ i see no pretrained models on speech domain like Speech synthesis, Speech recognition, Voice conversion ... So i want to contribute it :)). Here is a samples and github link:

samples: https://dathudeptrai.github.io/TensorflowTTS/
github: https://github.com/dathudeptrai/TensorflowTTS

**Comment by kempy** [comment]
Sorry for the delay in response. Yes, we welcome community contributions! You can follow the process at https://github.com/tensorflow/hub/tree/master/tfhub_dev
