### ISSUE TITLE
AttributeError: module 'tensorflow_hub' has no attribute 'KerasLayer'

### ISSUE THREAD

**Issue by nickcorona** [tensorflow/hub#615]
AttributeError: module 'tensorflow_hub' has no attribute 'KerasLayer'
Hub version: 0.7.0
TF: 1.13.1

**Comment by rmothukuru** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by nickcorona** [comment]
`bert_layer = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1', trainable=True)`

**Comment by nickcorona** [comment]
> `bert_layer = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1', trainable=True)`

**Comment by rmothukuru** [comment]
@nickcorona,
As per [this comment](https://github.com/tensorflow/hub/issues/255#issuecomment-474315405),  `hub.KerasLayer` works with Tensorflow Version 2. I think you may have to upgrade to Tensorflow 2.x (2.2 is the latest version). Please refer #255 for more information. Thanks!

**Comment by rmothukuru** [comment]
@nickcorona,
Can you please confirm if above comment has answered your question so that we can close this issue. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nickcorona** [comment]
Yeah, it works on a later version of Tensorflow. Thanks.

**Comment by arnoegw** [comment]
For the record: `hub.KerasLayer` is targeted primarily at TF2.0+ but can be used in TF1.15 as well (modulo the bugs that were fixed in later TF2.x versions, or requirements from the model being loaded).
