### ISSUE TITLE
How to extract a graph_def from TFHub saved_model (e.g. mobilenet_v2/feature_vector)

### ISSUE THREAD

**Issue by jignparm** [tensorflow/hub#617]
There are several TFHub models, in saved_model format,  that would be useful to convert into a graph_def using standard TF2 API.

For example, the model here: https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4

The snippet below should be able to extract out concrete function into a graph_def, convert it into a graph, and then print out all the node names. However, it looks tricky to get extract out the concrete function (because there is no signature of `serving_default` in the `serve` tag).

What's the best way to get the graph_def from this saved_model?

```python
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

model_path = r'd:\models_tfhub\tf2-preview_mobilenet_v2_feature_vector'

imported = tf.saved_model.load(model_path, tags=[['serve']])  # pylint: disable=no-value-for-parameter
concrete_func = imported.signatures['serving_default']
#concrete_func = imported.signatures['__saved_model_init_op']
frozen_func = convert_variables_to_constants_v2(concrete_func, lower_control_flow=False)
graph_def = frozen_func.graph.as_graph_def(add_shapes=True)
with tf.Graph().as_default() as inferred_graph:
    tf.import_graph_def(graph_def, name="")

nodes = inferred_graph.get_operations()
for n in nodes:
    print (n.name)
```

**Comment by maringeo** [comment]
Hi @jignparm, 

one way to get a `concrete_function` out of `tf.saved_model.load` would be:

concrete_func = imported.__call__.get_concrete_function(...)

https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4 specifically has 4 concrete functions - you can use `imported.__call__.concrete_functions` to inspect them.

The rest of the sample code that you provided should work. Let me know if you run into any problems.

**Comment by jignparm** [comment]
@maringeo, thanks for the valuable insight! I am able to make the code snippet above work using

`concrete_func = imported.__call__.get_concrete_function(tensor_spec.TensorSpec([None, None, None, 3]))`

A couple of other questions I had were:
   1.  If a saved_model contains  `signature_def['serving_default']` (from which we can extract a concrete function ) as well as some additional concrete functions under  `imported.__call__.concrete_functions` ,  is there any preference regarding which concrete function is the best one to use for inference purposes?

   1. I noticed there are usually 4 functions under  `imported.__call__.concrete_functions`. Is there way to know which one is  the best one inference purposes?

It'd be great if there's a typical pattern to extract the inference graphs (don't care too much about training/fine-tuning).

**Comment by maringeo** [comment]
Sorry for the delayed response.

All concrete functions are derived (traced) from the same tf.function - see [Tensorflow concrete function guide](https://www.tensorflow.org/guide/concrete_function).

So in the example of https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4 with tags=[['serve']], the 4 concrete functions are:
```
call_fn(inputs, training = True, return_endpoints = True, batch_norm_momentum)
call_fn(inputs, training = True, return_endpoints = False, batch_norm_momentum)
call_fn(inputs, training = False, return_endpoints = True, batch_norm_momentum)
call_fn(inputs, training = False, return_endpoints = False, batch_norm_momentum)
```

and they were traced from a function like:
```
@tf.function
def call_fn(inputs, training, return_endpoints, batch_norm_momentum):
  # actual code

```
From Tensorflow 2.3 onward there is a convenient way to inspect the signatures of concrete functions - [guide](https://www.tensorflow.org/guide/concrete_function#inspecting_concrete_function_signatures).

In general, you don't need to explicitly call a given concrete function - you just need to call the `callable` with the correct parameters for you use-case (for example with `training=False` during inference and `training=True `during training). See the [TF Hub SavedModelV2 guide](https://www.tensorflow.org/hub/tf2_saved_model#using_a_savedmodel_in_low-level_tensorflow) for more details on how to call the TF 2 SavedModels.
