### ISSUE TITLE
make_image_classifier: Unknown command line flag 'summaries_dir'

### ISSUE THREAD

**Issue by worksasintended** [tensorflow/hub#618]
The Readme.md states the availability of this very useful flag to get information about the training. 
However, it does not seem to be working at the current state.

**Comment by rmothukuru** [comment]
@worksasintended,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow Hub version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by worksasintended** [comment]
I tried it on different platforms already, although I am pretty sure it origins is in the make_image_classifier itself: 
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ArchLinux (Kernel 5.7); CentOS8
- TensorFlow installed from (source or binary):
ArchLinux: From Source; CentOS8: Anaconda (binary)
- TensorFlow version (use command below):
2.2.0 (cuda and non cuda)
- Python version:
3.8.3; 3.7.6
- Bazel version (if compiling from source)
3.2.0
- GCC/Compiler version (if compiling from source):
10.1.0
- CUDA/cuDNN version:
10.2.89; 10.2.xx
- GPU model and memory:
GTX1070TI (8gb); K80 (2*12gb)


**Describe the current behavior**
When using the --sumaries_dir flag:
```
 FATAL Flags parsing error: Unknown command line flag 'summaries_dir'. Did you mean: image_dir ?
Pass --helpshort or --helpfull to see help on flags.

```


**Expected:**
Create summary folder

Code to reproduce:
```
make_image_classifier \
  --tfhub_module https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4 \
  --image_size 224 \
  --saved_model_dir saved_model \
  --labels_output_file labels.txt \
  --tflite_output_file traind_nn.tflite\
  --summaries_dir results 

```

**Comment by djdongjin** [comment]
@worksasintended Hi, the issue is that this flag (and some others) is not included in the current binary installation.

You can install tensorflow-hub from source to use the full functionality of this tool.

**Comment by worksasintended** [comment]
I just found out the same. Maybe the Readme should be adjusted accordingly,  as the installation instruction is for tensorflow-hub>0.6, and up until including 0.8 the example calling command does not work. 
I compiled from the github sources (together with tf-gpu 2.3) and now it works perfectly fine. Thank you for your assistance!

**Comment by djdongjin** [comment]
@worksasintended Thanks for your reminder. This tool is being strengthened recently with several PRs. I will discuss with others to see the timeline to release a new version or otherwise change the readme.
