### ISSUE TITLE
There seems to be a typo in docs.

### ISSUE THREAD

**Issue by canlion** [tensorflow/hub#619]
Hi. 
There seems to be a typo in docs.

https://github.com/tensorflow/hub/blob/master/docs/common_issues.md#cannot-change-a-models-dype-eg-float32-to-bfloat16

Cannot change a model's dype (e.g., float32 to bfloat16)
-----------------------------------👇
Cannot change a model's dtype (e.g., float32 to bfloat16)

**Comment by j-grimstad** [comment]
I'll fix this -- thank you!
