### ISSUE TITLE
View model as graph

### ISSUE THREAD

**Issue by J-Fo-S** [tensorflow/hub#62]
Hello, are there any pointers on how to view the tf.hub models as a graph? The usual boilerplate I use results in colaboratory notebooks dropping the data since it is so massive. If it matters the model I'm trying to view is the generative images module. Been trying to access the signatures and keys to figure out how to parse what I don't need for the graph, but any pointers before sinking more time into it would be great. Thank you

This is the usual boilerplate I use:

```# TensorFlow Graph visualizer code
import numpy as np
from IPython.display import clear_output, Image, display, HTML

def strip_consts(graph_def, max_const_size=32):
    """Strip large constant values from graph_def."""
    strip_def = tf.GraphDef()
    for n0 in graph_def.node:
        n = strip_def.node.add() 
        n.MergeFrom(n0)
        if n.op == 'Const':
            tensor = n.attr['value'].tensor
            size = len(tensor.tensor_content)
            if size > max_const_size:
                tensor.tensor_content = "<stripped %d bytes>"%size
    return strip_def

def show_graph(graph_def, max_const_size=32):
    """Visualize TensorFlow graph."""
    if hasattr(graph_def, 'as_graph_def'):
        graph_def = graph_def.as_graph_def()
    strip_def = strip_consts(graph_def, max_const_size=max_const_size)
    code = """
        <script src="//cdnjs.cloudflare.com/ajax/libs/polymer/0.3.3/platform.js"></script>
        <script>
          function load() {{
            document.getElementById("{id}").pbtxt = {data};
          }}
        </script>
        <link rel="import" href="https://tensorboard.appspot.com/tf-graph-basic.build.html" onload=load()>
        <div style="height:600px">
          <tf-graph-basic id="{id}"></tf-graph-basic>
        </div>
    """.format(data=repr(str(strip_def)), id='graph'+str(np.random.rand()))

    iframe = """
        <iframe seamless style="width:1200px;height:620px;border:0" srcdoc="{}"></iframe>
    """.format(code.replace('"', '&quot;'))
    display(HTML(iframe))```

**Comment by arnoegw** [comment]
Hi J-Fo-S,

viewing a Hub module's graph(s) is certainly a useful thing to do, but AFAIK, there is no ready-made solution for it. But it shouldn't be too hard to adapt the widely circulated techniques for visualizing GraphDefs in a colab notebook (your code above) or in TensorBoard (see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/import_pb_to_tensorboard.py -- if only somebody contributed SavedModel support right there ;-).

The key thing to note is that the current file format for Hub modules is essentially a SavedModel. So you can `tar xzf` the module, read the `saved_model.pb` file from it and parse it as a SavedModel protocol message (`from tensorflow.core.protobuf import saved_model_pb2`). Then select the MetaGraphDef for the tag set of interest (usually, the empty list `[]`), and pass its GraphDef to one of the existing solutions (cf. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/loader_impl.py).

Needless to say, this breaks through multiple API abstractions and comes with *zero guarantees* (future Hub modules might not be SavedModels, future SavedModels might use a different format). However, it should be good enough for an ad-hoc exploration.

BTW, you don't need to worry about big constants inlined into the graph. With a SavedModel, the trained weights go into a checkpoint that is packaged in the `variables` subdirectory and are restored as needed. This is one of the advantages over the old practice of using "frozen GraphDefs".

**Comment by hgadig** [comment]
Closing this issue as it has been answered.

**Comment by emckenzi123** [comment]
for those of you who are looking to just visualize the graph from a tf hub model, you can use the following: (almost completely copied and pasted from tensorflow/python/tools/import_pb_to_tensorboard.py, with a few small modifications so it'll work with tf hub)

```
import tensorflow_hub as hub
from tensorflow.python.framework import importer
from tensorflow.python.framework import ops
from tensorflow.python.summary import summary
from tensorflow.python.client import session

log_dir = '.' #where to save your tensorboard event file

model = hub.load(model_handle)  #Import your tf hub model here

#the signature here is 'default'.  you can figure you what yours is by calling 'model.signatures' and checking the output (e.g. _SignatureMap({'default': <tensorflow.python.eager.wrap_function.WrappedFunction object...)

model_graphdef = model.signatures['default'].graph.as_graph_def() 

with session.Session(graph=ops.Graph()) as sess:
  input_graph_def = model_graphdef
  
  importer.import_graph_def(input_graph_def)

  pb_visual_writer = summary.FileWriter(log_dir)
  pb_visual_writer.add_graph(sess.graph)
  print("Model Imported. Visualize by running: "
        "tensorboard --logdir={}".format(log_dir))
```

Cheers, E.
