### ISSUE TITLE
Typo in object detection API example

### ISSUE THREAD

**Issue by dwij2212** [tensorflow/hub#623]
The jupyter notebook at this [link](https://github.com/tensorflow/hub/blob/master/examples/colab/object_detection.ipynb) has an issue in its detect_img function.

```python
def detect_img(image_url):
  start_time = time.time()
  image_path = download_and_resize_image(image_url, 640, 480)
  run_detector(detector, image_path)
  end_time = time.time()
  #print("Inference time:",start_time-end_time) #This is wrong
  print("Inference time:",end_time-start_time)
```

**Comment by rmothukuru** [comment]
@dwij2212,
Can you please elaborate on what the problem exactly is. Also, if it is resulting in any error, please provide the complete Error Traceback which helps us in debugging the problem. Thanks!

**Comment by dwij2212** [comment]
The last code cell in the notebook was printing negative time taken for inference. I have also created a PR suggesting the necessary change.

**Comment by dwij2212** [comment]
My PR has been merged and the issue is solved.
