### ISSUE TITLE
Using TF-Hub models locally.

### ISSUE THREAD

**Issue by devspartan** [tensorflow/hub#630]
I've been working on a task using bert model  [https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2](bert-model). As per the instructions I've added the line:
 `bert_layer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2", trainable=True)`

But problem comes when it downloads the model again on every run. That's annoying. I've already spent a lot of time on searching   How to download and work with tf-hub models  . But i got no proper answer. That's why I'm here for guidance official tf-hub team.

I've downloaded the .tar.gz file from [https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2](link) and extracted the file. It contains <assets, variable, saved_model.pb>. Now please guide me how to use the model properly and efficiently. Please provide concerned information and script. Thanking You.

**Comment by rmothukuru** [comment]
@devspartan,
Please find the below code which demonstrates Accessing the `Bert_Model` from the Downloaded Path, in a `For Loop` as well.

```
import tensorflow_hub as hub

Bert_Model_URL = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2"
bert_layer = hub.KerasLayer(Bert_Model_URL, trainable=True)

Bert_Model_Path = '/home/mothukuru/Jupyter_Notebooks/Stack_Overflow/TF_Hub/bert_en_uncased_L-12_H-768_A-12_2'
bert_layer = hub.KerasLayer(Bert_Model_Path, trainable=True)

Bert_Model_Path = '/home/mothukuru/Jupyter_Notebooks/Stack_Overflow/TF_Hub/bert_en_uncased_L-12_H-768_A-12_2'
for _ in range(5):
    bert_layer = hub.KerasLayer(Bert_Model_Path, trainable=True)
```

Please let me know if it helps. If it doesn't, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Also, can you please explain why do you want to download the `Model` again on every run, rather than using the `Model` which is downloaded already? Thanks!

**Comment by arnoegw** [comment]
Hi @devspartan, the tensorflow_hub library attempts to cache downloaded models for reuse between different runs of your program. The location can be customized by setting the environment variable `TFHUB_CACHE_DIR` or the command-line flag `--tfhub_cache_dir`. The default location is `os.path.join(tempfile.gettempdir(), "tfhub_modules")`, which results in `/tmp/tfhub_modules` on many Linux systems.

To get more durable caching than what `/tmp` affords, consider adding
```bash
export TFHUB_CACHE_DIR=$HOME/.cache/tfhub_modules
```
to your `.bashrc` (or equivalent), start a new shell, and do `mkdir -p $TFHUB_CACHE_DIR` before the first use. There is no automated cache cleanup, though.

This works transparently, without having to change the canonical tfhub.dev/... URLs used in the code.

**Comment by devspartan** [comment]
This solution did work(the second code snippet) Thanks a lot.
 Sorry for not explaining my problem clearly but i don't want to download model again and again. I do prefer to download model only once and use it again wherever i want.

 I have one more question,

The models we use in tf.keras.applications.vgg16 or other models. When we use them first time they download the model architecture and pretrained weights and save them in local directory. When we use the same model(keras models) with same weights, I don't have to download them(architecture and weights) again. They just use the saved weights. I can use them in any script with single line of code. For e.g.
`vgg = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))` 

Now here question arises, When we use any tf-hub model first time it downloads the data that's obvious. Does it save the downloaded data in local directory? If yes, where ? Why don't on re-run it use the same downloaded data(so that i don't have to download again) . 
If tf-hub don't save the model locally as tf.keras.application.vgg16 does. It should for user betterment.

**Comment by arnoegw** [comment]
In response to this and other user inquiries, there is now expanded documentation at https://www.tensorflow.org/hub/caching

Thanks, @devspartan, for raising this, and thanks, @rmothukuru, for spelling out how to take complete control in case caching is not enough.
