### ISSUE TITLE
[Feature] Could anyone rewrite the bert model code ?

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/hub#635]
I find a pre-trained bert in tf-hub [https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/2](https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/2)  and its document says that I can find how to use it in [https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_classifier.py](https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_classifier.py)

But in ```run_classifier.py``` , the code is ugly and difficult to understand . Since the tf document contains a transformer model example use ```tf.keras.Model``` [https://www.tensorflow.org/tutorials/text/transformer](https://www.tensorflow.org/tutorials/text/transformer) , could anyone rewrite the bert model code and document like that ?

**Comment by rmothukuru** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-hub) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by DachuanZhao** [comment]
> This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-hub) since it is not a bug or feature request. There is also a larger community that reads questions there.

Perhaps This is an issue which asking for a more detailed documentation ...

**Comment by DachuanZhao** [comment]
@rmothukuru 
I get it in [https://github.com/tensorflow/models/issues/8801](https://github.com/tensorflow/models/issues/8801) .
Thank you all !
