### ISSUE TITLE
Expected input range [0,1] or [-1,1] for TensorFlow Hub's image modules

### ISSUE THREAD

**Issue by HaraBeron** [tensorflow/hub#637]
I have a question regarding image classification and using tranfer learning with MobileNetV2 and others (e.g. Inception).

[Here](https://www.tensorflow.org/tutorials/images/transfer_learning_with_hub) in the official tutorial by Google TensorFlow it says:
"All of TensorFlow Hub's image modules expect float inputs in the [0, 1] range."

In the [MobileNet](https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4) documentation it says:
"The input images are expected to have color values in the range [0,1], following the common image input conventions."

[Here](https://www.tensorflow.org/tutorials/images/transfer_learning) in the official tutorial by Google TensorFlow it says:
"Resize the images to a fixed input size, and rescale the input channels to a range of [-1,1]"

and indeed it is scaled to a range of [-1,1] and not [0,1]:
`image = (image/127.5) - 1`

Later on MobileNetv2 is used:
Create the base model from the pre-trained model MobileNet V2
```
base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')
```
but I thought it needs [0,1] and not [-1,1]?

Now this is a contradiction in my eyes or I do not understand it.

What is right and what is wrong here? When do I have to rescale to [0,1] and when use [-1,1]? I thought as it said in the other sources all pretrained models from the tf hub use a common standard, [0,1], however, now I see in this official Google tutorial that rescaling is done to [-1,1]. I don't get this.

**Comment by andresusanopinto** [comment]
This seems to be conflacting information.

When using `tf.keras.applications.MobileNetV2(weights="imagenet")` then documentation of that keras application applies and the weights are expected to be [-1,1].

When using `hub.KerasLayer("https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4")` then the documentation of that model applies and it expects inputs in the range [0, 1].
