### ISSUE TITLE
Tensorflow hub on raspbery pi 4 throwing out of memory while load

### ISSUE THREAD

**Issue by rupamroy** [tensorflow/hub#638]
I have raspberry pi 4 and on which I have the following versions:

Tensorflow : 2.2.0
Tensorflow-Hub :0.8.0

when the run the following code 
```python
module_handle = "https://tfhub.dev/google/faster_rcnn/openimages_v4/inception_resnet_v2/1" 

detector = hub.load(module_handle).signatures['default']
```

The raspberry pi eventually starts loosing on available memory and eventually we face an out of memory exception:
```bash
pi@raspberrypi:~/dev/eating-reminder $ python3 app.py 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

by using free -h tool i can see  while the program keeps running that system shows 3.1 G available memory and it keeps falling until it falls to 1.4 G (after around 2-3 min) after which it shows the above mentioned exception. 
Even if I use a downloaded model the same issue surfaces.

What is the fix for this? The model is around 250 MB , and the machine has 4 GB memory, which should it still give out of memory exception?

**Comment by rmothukuru** [comment]
@rupamroy,
As the issue is related to Raspbery Pi, please raise the issue in [Tensorflow Repository](https://github.com/tensorflow/tensorflow/issues/new?labels=comp%3Amicro&template=70-tflite-micro-issue.md) where Micro-Controller related Issues are addressed.  Thanks!
