### ISSUE TITLE
Can I add TF1 model to TensorFlow-hub that was converted from ONNX model?

### ISSUE THREAD

**Issue by AlexeyAB** [tensorflow/hub#640]
Hi,
Can I add TF1 model to TensorFlow-hub that was converted from ONNX model by using https://github.com/onnx/onnx-tensorflow and works well in TensorFlow 2.2.0?
So archive doesn't contain files `saved_model.pbtxt` and `saved_model.pb`.

Archive `model_hub.tar.gz` contains:
* `tfhub_module.pb` - is converted from ONNX
* `assets` - empty directory
* `variables` - empty directory

**Comment by AlexeyAB** [comment]
The issue has been resolved. 
I created `saved_model.pb` and tested it successfully with` hub.load`

**Comment by akhorlin** [comment]
Hi Alexey,

That's great that you figured how to create saved_model.pb from ONNX. Please consider sharing it on tfhub.dev (Sharing instructions: https://github.com/tensorflow/hub/tree/master/tfhub_dev).
