### ISSUE TITLE
train progan-128 on custom dataset

### ISSUE THREAD

**Issue by LucaSCostanzo** [tensorflow/hub#643]
Hi,
I would like to know if there could be the possibility to train the progan-128 in tf-hub on custom dataset....In case, is there any documentation or tutorial about?
Thanks.

**Comment by rmothukuru** [comment]
@LucaSCostanzo,
Can you please refer this [Progan-128 TF Hub Tutorial](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf_hub_generative_image_module.ipynb)  and let us know if it helps. Thanks!

**Comment by LucaSCostanzo** [comment]
**@rmothukuru**,
thanks for youy reply. I have seen that tutorial, but it refers to use progan-128 on the celeb dataset. I would like to train the Progressive GAN on a custom set of images. 
Thanks again.

**Comment by andresusanopinto** [comment]
The specific code used to train this model is not available and there are no plans to make so.
