### ISSUE TITLE
Non deterministic behavior with batching for universal-sentence-encoder-multilingual (USE-M)

### ISSUE THREAD

**Issue by longdt219** [tensorflow/hub#658]
We expect the representations from USE-M would be exactly the same with a different sentence order in the batch, however, it seems that there is some bugs in handling the first and last sentence in the batch. 

```
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import tensorflow_text

english_sentences = ["this is the first sentence", "and the second one", "the third sentence", "how about another one", "and another one"]
# Just reverse the order 
english_sentences_rv = list(reversed(english_sentences)) 

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual/3")

# Get the sentences representation 
en_result = embed(english_sentences)
# Just run with it again 
en_result_again = embed(english_sentences)
# Get the sentence representation in the reversed order 
en_result_rv = embed(english_sentences_rv)

# Expected result, no difference in representation. 
print(np.sum(en_result.numpy() - en_result_again.numpy(), axis=1) ) 
# ==> array([0., 0., 0., 0., 0.], dtype=float32)

# Weird result, small difference in representation for the first and last utterances. 
np.sum(en_result.numpy() - np.flip(en_result_rv.numpy(), axis=0), axis=1)
# ==> array([ 1.2551027e-07,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -1.7066486e-07], dtype=float32)

```
We observed the problem with both 
https://tfhub.dev/google/universal-sentence-encoder-multilingual/3 with Tensorflow 2 
and 
https://tfhub.dev/google/universal-sentence-encoder-multilingual/1 with Tensorflow 1 

With a bit of digging, it seems that USE-M concatenates all the sentences in the batch to form a very long sentence, compute the representations, and split them later. My guess is that there might be some problems in the splitting and joining process.

**Comment by akhorlin** [comment]
Are you running this code on CPU or GPU?

**Comment by akhorlin** [comment]
Please re-open issue with additional details about the environment (CPU/GPU) that the model was ran on.
