### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by dropthemasquerade** [tensorflow/hub#659]
I am following this [tutorial](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/?utm_campaign=chrome_series_machinelearning_063016&utm_source=gdev&utm_medium=yt-desc#3)

but when I do `python -m scripts.retrain -h`

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/scripts.py", line 138, in <module>
    from tensorflow.contrib import quantize as contrib_quantize
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by rmothukuru** [comment]
@dropthemasquerade,
In [Image_Retraining_Github_ReadMe](https://github.com/tensorflow/hub/tree/master/examples/image_retraining) it is mentioned as

WARNING: This code is deprecated.

> The retrain.py tool from this directory has been replaced by the make_image_classifier tool that gets installed as a command-line tool by the PIP package tensorflow-hub[make_image_classifier]. The new tool uses TensorFlow 2 and supports fine-tuning.

So, please install the Tool, [make_image_classifier](https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier) using the code, 

`pip install "tensorflow-hub[make_image_classifier]~=0.6"`

Please refer the [Github Repo of Make_Image_Classifier](https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier) for more info. Thanks!

**Comment by rmothukuru** [comment]
@dropthemasquerade,
Can you please confirm if your issue is resolved so that we can close this issue. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
