### ISSUE TITLE
How do I get the vocabulary used in universal-sentence-encoder?

### ISSUE THREAD

**Issue by jh88** [tensorflow/hub#67]
I would like to check if a few words are included in the vocabulary. Thanks.

**Comment by akhorlin** [comment]
Unfortunately, there is no easy to perform this check. Some modules use
vocab files stored inside the assets/ directory of the module, however
universal-sentence-encoder uses a different approach and stores the token
in the graph itself (in saved_model.pb). saved_model.pb is stored in
SavedModel format described in
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/programmers_guide/saved_model.md#structure-of-a-savedmodel-directory.
The module files can be found inside TF_CACHE_DIR after the module has been
used for first time on a machine.
