### ISSUE TITLE
Make Object detection models fine-tunable

### ISSUE THREAD

**Issue by RobinBaumann** [tensorflow/hub#678]
As I understand from #473, it is not possible to fine-tune object detection models fetched from TF Hub directly. It would be nice to have this as a feature. E.g., with the already existing Keras integration via hub.KerasLayer, it would be nice to enable a workflow similar to:

1. Load Model (e.g. https://tfhub.dev/tensorflow/ssd_mobilenet_v2/fpnlite_640x640/1 via TF Hub as hub.KerasLayer)
2. Add new input and output layers (In the [Retrain an Image classifier guide](https://www.tensorflow.org/hub/tutorials/tf2_image_retraining), this is done in a Sequential model, I think we need the functional API because the resulting hub.KerasLayer will have multiple outputs).
3. Build a new Keras Model with the desired inputs and outputs and fine tune it on custom dataset.

Please correct me if this is already possible. I played around with TF Hub the past few days and this is what I tried until now:

```python
import tensorflow as tf
import tensorflow_hub as hub
MODULE_HANDLE = "https://tfhub.dev/tensorflow/ssd_mobilenet_v2/fpnlite_640x640/1" 

# Try to set shapes for new dataset, which contains 10 foreground classes, note that this somehow does not work
shapes = {
    'num_detections': (None),
    'detection_boxes': (None, 4),
    'detection_classes': (None),
    'detection_scores': (None),
    'raw_detection_boxes': (None, 4),
    'raw_detection_scores': (None, 10),
    'detection_anchor_indices': (None),
    'detection_multiclass_scores': (None, 11)
}

module = hub.KerasLayer(MODULE_HANDLE, trainable=True, output_shape=shapes)
```

Results in 

> ERROR:absl:hub.KerasLayer is trainable but has zero trainable weights.
> ValueError: Tensor's shape (1, 100, 91) is not compatible with supplied shape (1, None, 11)

**Expected behavior (Feature Request):**

Regarding the workflow described above, in (pseudo-ish) code something like the following would be nice:

```python
MODULE_HANDLE = "https://tfhub.dev/tensorflow/ssd_mobilenet_v2/fpnlite_640x640/1" 
input_layer = tf.keras.layers.InputLayer(input_shape=(None, None, 3), dtype=tf.float32)
# instead of output_shape, it would be nice if the option exists to only provide the number of predicted classes of the new dataset
module = hub.KerasLayer(MODULE_HANDLE, trainable=True, num_classes=NEW_CLASSES)(input_layer)

model = tf.keras.Model(inputs=input_layer, outputs=[module['detection_boxes'], module['detection_scores']])
model.compile(...)
```

**Comment by akhorlin** [comment]
Thank you for your request!

The TensorFlow Hub team does not produce modules ourselves, but we’ll forward your request to potential internal publisher teams. Because we rely on other teams for our assets, we aren’t able to provide public estimates for new module availability, and requests may never be fulfilled.

However, we’ll keep this thread open until it is fulfilled -- we’re tagging this thread as a “Module Request” and adding it to our Community Module Requests (we also surface it in our publishing documentation). We are accepting submissions from 3rd party publishers, so if you or someone from the community is interested in producing and sharing these assets, we’d be happy to publish them.

Please let me know if you have any questions!

**Comment by MaxPRon** [comment]
@RobinBaumann 

Hi Robin, is there any progess on that feature ? I'm trying to achieve something similar and running into the same issues.



I want to to completely retrain an object detector from tensorflow hub with a different dataset but I am not able to adjust the output layer. Furthermore I am not sure if it is actually possible as the models don't support fine-tuning however I am not aiming to recover the weights but rather reuse the architecture.

Any feedback is welcome and please correct me if there is any miss understanding from my side.

**Comment by RobinBaumann** [comment]
Hi @MaxPRon,

some of the models from TensorFlow Hub are published by the [TensorFlow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) Team and can be retrained using their API. I think this is currently the best way to fine-tune an object detection model using TF.

**Comment by MaxPRon** [comment]
Thanks for the help @RobinBaumann.

Just to make it clear. So it's currently not possible to just reuse the architecture of the tensorflow hub models ?

The reason I'm trying to train from scratch is that I'm running an analysis about the impact of data quality on the performance of neural nets. Therefore it would be great if I can reuse "standard architectures" and train them with different datasets.


I had a look at the Tensorflow Object Detection API but I was hoping to be able to do it with a combination of tensorflow datasets and hub in the hope to have a small and compact solution.

Anyway thanks again for the reply.

**Comment by RobinBaumann** [comment]
> Thanks for the help @RobinBaumann.
> 
> Just to make it clear. So it's currently not possible to just reuse the architecture of the tensorflow hub models ?

Well, if I understand Andrey's reply correctly, there is no unique interface that you can expect from the models. But i think it should be possible to access tensors of at least some models. However, I think it is easier to use TF Object Detection API with your use case. 

> The reason I'm trying to train from scratch is that I'm running an analysis about the impact of data quality on the performance of neural nets. Therefore it would be great if I can reuse "standard architectures" and train them with different datasets.
> 
> I had a look at the Tensorflow Object Detection API but I was hoping to be able to do it with a combination of tensorflow datasets and hub in the hope to have a small and compact solution.

It is possible to use both, the TensorFlow Object Detection API and TFDS. In fact, I'm currently writing a blog article about this. You can see an [example in this gist](https://gist.github.com/RobinBaumann/bbcdea92a0af26f46ea7a77d62c0aea2).

Once you have created the TFRecords, you can train your model using the TF Object Detection API.

**Comment by MaxPRon** [comment]
@RobinBaumann 

Thanks again Robin. Well I'm going with the Tensorflow Object Api for now and see what I can do. 

I will share it here if there comes anything out of it.

Also looking forward to the blog. :)
