### ISSUE TITLE
Which model can be used to create a custom Action Recognition model using existing TFHub models.

### ISSUE THREAD

**Issue by snehitvaddi** [tensorflow/hub#682]
Which model in Tensorflow Hub can be used to train and detect custom action recognition?
It would be appreciable if any tutorial on how to do so!!

**Comment by gowthamkpr** [comment]
@snehitvaddi You can take a look at this tutorial [here](https://www.tensorflow.org/hub/tutorials/action_recognition_with_tf_hub)

**Comment by gowthamkpr** [comment]
@snehitvaddi Can you please close the issue as it has been resolved. Thanks!

**Comment by snehitvaddi** [comment]
@gowthamkpr I was looking for a training custom model, the reference you have given is just like any other. It does not have custom model training. 
So I was looking for some better references. I would definitely close getting something satisfactory.😁

**Comment by WGierke** [comment]
Hi @snehitvaddi 
https://tfhub.dev/google/collections/movinet/1 contains pre-trained models for action recognition. You can fine-tune them on your own data by following the instructions from the respective model pages. More information on how the models were trained can be found  [here](https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet).
