### ISSUE TITLE
MobileBERT support for eager execution

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/hub#689]
Referring to this module - https://tfhub.dev/google/mobilebert/uncased_L-24_H-128_B-512_A-4_F-4_OPT/squadv1/1. 

I was trying to use it inside in a Keras-like model but it seems like the MobileBERT model is not yet supported in eager mode. Any way to remedy this other than using `import tensorflow.compat.v1 as tf`?

**Comment by rmothukuru** [comment]
@sayakpaul,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
