### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by shreyapat** [tensorflow/hub#69]
I'm trying to follow a tutorial by Tensorflow on image classification. I've gotten up to the step where you retrain the model. I'm trying to run this retraining script using terminal, but I'm getting the following error:

<img width="795" alt="screen shot 2018-06-07 at 10 03 12 am" src="https://user-images.githubusercontent.com/16789305/41109039-a3029062-6a3b-11e8-99e9-a24655fca6f3.png">

Tutorial: https://www.tensorflow.org/tutorial
Retraining script: https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py
Terminal: https://github.com/llSourcell/tensorflow_image_classifier/blob/master/src/train.sh

**Comment by akhorlin** [comment]
This looks similar to the issue covered by this thread:
https://github.com/tensorflow/tensorflow/issues/18889.
