### ISSUE TITLE
tensorflow_hub import error

### ISSUE THREAD

**Issue by kja815** [tensorflow/hub#690]
I use tensorflow 2.2.0
python 3.6.9

I install tf-nightly-2.4.0.dev20200708 to deal with bug from decode_bmp.

but after that, I cannot import tensorflow_hub.

full error messages are below.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ae25cc1fd345> in <module>
      1 import tensorflow as tf
----> 2 import tensorflow_hub as hub

/usr/local/lib/python3.6/dist-packages/tensorflow_hub/__init__.py in <module>
     27 # error message is thrown instead of an obscure error of missing
     28 # symbols at executing the imports.
---> 29 from tensorflow_hub.estimator import LatestModuleExporter
     30 from tensorflow_hub.estimator import register_module_for_export
     31 from tensorflow_hub.feature_column import image_embedding_column

/usr/local/lib/python3.6/dist-packages/tensorflow_hub/estimator.py in <module>
     62 
     63 
---> 64 class LatestModuleExporter(tf_v1.estimator.Exporter):
     65   """Regularly exports registered modules into timestamped directories.
     66 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py in __getattr__(self, item)
     60 
     61   def __getattr__(self, item):
---> 62     module = self._load()
     63     return getattr(module, item)
     64 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py in _load(self)
     43     """Load the module and insert it into the parent's globals."""
     44     # Import the target module and insert it into the parent's namespace
---> 45     module = importlib.import_module(self.__name__)
     46     self._parent_module_globals[self._local_name] = module
     47 

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1 import estimator
     11 
     12 del _print_function

/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1.estimator import experimental
     11 from tensorflow_estimator._api.v1.estimator import export
     12 from tensorflow_estimator._api.v1.estimator import inputs

/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
     11 from tensorflow_estimator.python.estimator.canned.kmeans import KMeansClustering as KMeans
     12 from tensorflow_estimator.python.estimator.canned.linear import LinearSDCA

/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/dnn.py in <module>
     29 from tensorflow.python.keras.utils import losses_utils
     30 from tensorflow.python.util.tf_export import estimator_export
---> 31 from tensorflow_estimator.python.estimator import estimator
     32 from tensorflow_estimator.python.estimator.canned import head as head_lib
     33 from tensorflow_estimator.python.estimator.canned import optimizers

/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py in <module>
     50 from tensorflow.python.util.tf_export import estimator_export
     51 from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
---> 52 from tensorflow_estimator.python.estimator import run_config
     53 from tensorflow_estimator.python.estimator import util as estimator_util
     54 from tensorflow_estimator.python.estimator.export import export_lib

/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/run_config.py in <module>
     28 from tensorflow.core.protobuf import rewriter_config_pb2
     29 from tensorflow.python.distribute import estimator_training as distribute_coordinator_training
---> 30 from tensorflow.python.distribute import parameter_server_strategy_v2
     31 from tensorflow.python.util import compat_internal
     32 from tensorflow.python.util import function_utils

ImportError: cannot import name 'parameter_server_strategy_v2'

**Comment by gowthamkpr** [comment]
Not sure why you are using both tensorflow 2.2.0 and tf-nightly. Can you uninstall tensorflow 2.2.0 and reinstall tf-nightly in a new environment and let me know if it works . Thanks!

**Comment by kja815** [comment]
@gowthamkpr 

I still got the same error in tensorflow 2.3.0 and 2.2.0

I attached packages list in my environment
Package                Version            
---------------------- -------------------
absl-py                0.9.0              
asn1crypto             0.24.0             
astor                  0.8.1              
astunparse             1.6.3              
attrs                  19.3.0             
backcall               0.1.0              
bleach                 3.1.0              
cachetools             4.0.0              
certifi                2019.11.28         
chardet                3.0.4              
cryptography           2.1.4              
cycler                 0.10.0             
decorator              4.4.1              
defusedxml             0.6.0              
entrypoints            0.3                
enum34                 1.1.6              
future                 0.18.2             
gast                   0.3.3              
google-auth            1.10.0             
google-auth-oauthlib   0.4.1              
google-pasta           0.1.8              
grpcio                 1.26.0             
h5py                   2.10.0             
idna                   2.6                
imageio                2.8.0              
imgaug                 0.4.0              
importlib-metadata     1.4.0              
ipykernel              5.1.3              
ipython                7.11.1             
ipython-genutils       0.2.0              
ipywidgets             7.5.1              
jedi                   0.15.2             
Jinja2                 2.10.3             
json5                  0.9.5              
jsonschema             3.2.0              
jupyter                1.0.0              
jupyter-client         5.3.4              
jupyter-console        6.0.0              
jupyter-core           4.6.1              
jupyter-http-over-ws   0.0.7              
jupyterlab             2.2.8              
jupyterlab-server      1.2.0              
Keras-Applications     1.0.8              
Keras-Preprocessing    1.1.2              
keyring                10.6.0             
keyrings.alt           3.0                
kiwisolver             1.1.0              
lab                    6.1                
Markdown               3.1.1              
MarkupSafe             1.1.1              
matplotlib             3.1.2              
mistune                0.8.4              
more-itertools         8.0.2              
nbconvert              5.6.1              
nbformat               5.0.3              
networkx               2.4                
notebook               6.0.2              
numpy                  1.18.1             
oauthlib               3.1.0              
opencv-python          4.2.0.34           
opt-einsum             3.1.0              
pandocfilters          1.4.2              
parso                  0.5.2              
pexpect                4.7.0              
pickleshare            0.7.5              
Pillow                 7.1.2              
pip                    19.3.1             
prometheus-client      0.7.1              
prompt-toolkit         2.0.10             
protobuf               3.11.3             
ptyprocess             0.6.0              
pyasn1                 0.4.8              
pyasn1-modules         0.2.8              
pycrypto               2.6.1              
Pygments               2.5.2              
pygobject              3.26.1             
pyparsing              2.4.6              
pyrsistent             0.15.7             
python-apt             1.6.4              
python-dateutil        2.8.1              
PyWavelets             1.1.1              
pyxdg                  0.25               
pyzmq                  18.1.1             
qtconsole              4.6.0              
requests               2.22.0             
requests-oauthlib      1.3.0              
rsa                    4.0                
scikit-image           0.16.2             
scipy                  1.4.1              
SecretStorage          2.3.1              
Send2Trash             1.5.0              
setuptools             44.0.0             
Shapely                1.7.0              
simplejson             3.17.2             
six                    1.13.0             
ssh-import-id          5.7                
tb-nightly             2.3.0a20200722     
tensorboard            2.3.0              
tensorboard-plugin-wit 1.7.0              
tensorflow-estimator   2.3.0              
tensorflow-gpu         2.3.0              
tensorflow-hub         0.8.0              
termcolor              1.1.0              
terminado              0.8.3              
testpath               0.4.4              
tf-estimator-nightly   2.4.0.dev2020101301
tf-nightly             2.4.0.dev20200708  
torch                  1.5.0              
tornado                6.0.3              
traitlets              4.3.3              
txt2tags               3.7                
urllib3                1.25.7             
wcwidth                0.1.8              
webencodings           0.5.1              
Werkzeug               0.16.0             
wheel                  0.30.0             
widgetsnbextension     3.5.1              
wrapt                  1.11.2             
zipp                   0.6.0

**Comment by kja815** [comment]
@gowthamkpr 
I can import tensorflow_hub successfully in version 2.4.0-dev20201012
