### ISSUE TITLE
Performance issue with a big module

### ISSUE THREAD

**Issue by ozlerhakan** [tensorflow/hub#693]
Hi everyone,

We have a performance issue based on our large word2vec module generated using [export_v2.py](https://github.com/tensorflow/hub/blob/master/examples/text_embeddings_v2/export_v2.py) which localates in this repository. The module size is around 5GB. After loading the module, when we query one sample we wait 10-20 seconds:

```
module = hub.load(model_file_path)
module("hello world").numpy().tolist()
```

Do you have any suggestions about how to reduce the latency of a query? 

Thanks 🙌

**Comment by WGierke** [comment]
Hi ozlerhakan,
Is querying the sample via `module("hello world")` also slow or is the problem related to converting the result to numpy and then to a list?
Could you check whether your RAM suffices to load the module and that your OS is not swapping to hard drive?
Is the time scaling linearly when you query more samples?

**Comment by ozlerhakan** [comment]
Hi @WGierke ,

> Is querying the sample via module("hello world") also slow or is the problem related to converting the result to numpy and then to a list?

query is slow via module("hello world"), yes.

> Could you check whether your RAM suffices to load the module and that your OS is not swapping to hard drive?

We have loaded the module without receiving a message starting like  "%10 exceed memory..."

> Is the time scaling linearly when you query more samples?

When we send 100 concurrent users at the same time, since we wait a long period per query, we do not have a cpu problem whereas the memory fluctuated too much.

cpu idle:
<img width="776" alt="Screen Shot 2020-10-28 at 23 09 28" src="https://user-images.githubusercontent.com/1964927/97491053-b1823a00-1972-11eb-97b4-4516c4f06031.png">
free memory:
<img width="778" alt="Screen Shot 2020-10-28 at 23 09 19" src="https://user-images.githubusercontent.com/1964927/97491147-d37bbc80-1972-11eb-9571-4d3063385cad.png">


Here is the performance metrics of  universal sentence encoder v3 when we use id as well:

cpu idle:
<img width="768" alt="Screen Shot 2020-10-28 at 23 07 15" src="https://user-images.githubusercontent.com/1964927/97490845-754ed980-1972-11eb-81a3-bff2f479b0ca.png">
free memory:
<img width="775" alt="Screen Shot 2020-10-28 at 23 08 32" src="https://user-images.githubusercontent.com/1964927/97490908-8566b900-1972-11eb-9c51-852968887e4a.png">

**Comment by WGierke** [comment]
Hi @ozlerhakan 
My apologies for the late reply!
Unlike USE, word2vec uses a very large lookup table that may result in elevated latency and memory usage depending on the local machine's configuration and the number tokens in the batch. You can use [TF Profiler](https://www.tensorflow.org/guide/profiler) to further drill down to understand the issue, if it still exists. Hope that helps!
