### ISSUE TITLE
Inclusion of FaceNet TFLite model to TF-Hub

### ISSUE THREAD

**Issue by shubham0204** [tensorflow/hub#698]
FaceNet has been one of the most efficient models to produce face embeddings from a picture. Inclusion of this model in TensorFlow Hub would enable developers, especially working on face detection/classification systems, to leverage the ability of a FaceNet model to generate unique embeddings ( N-dimensional vectors ).  Different faces could be identified by comparing these embeddings using a suitable metric.

Also, the FaceNet can be quantized, so as to achieve a reduced file size and low latencies on edge devices. There could be numerous use-cases wherein the model could be used in Android/iOS apps. I have demonstrated one such use-case effectively in an Android app in this [project](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android).

It will be super helpful for both TF and Android/iOS developers to have a FaceNet model featured at TensorFlow Hub in the TFLIte format. 

I would request the TF-Hub team to consider this inclusion.

**Comment by shubham0204** [comment]
Do I need to sign the Contributor License Agreement now? Please let me know, this is my first contribution to an open-source project.

**Comment by rmothukuru** [comment]
@shubham0204,
Yes, signing CLA is mandatory for contributions. Please refer [this link](https://cla.developers.google.com/about/google-individual?csw=1) for details on CLA. Thanks!

**Comment by shubham0204** [comment]
@rmothukuru Thanks for the confirmation. I have signed the CLA. Please tell more on how I can publish the FaceNet model on TF-Hub.

**Comment by maringeo** [comment]
Hi @shubham0204, if you want to contribute a model to www.tfhub.dev you can have a look at the publishing guide at https://www.tensorflow.org/hub/publish. 

tfhub.dev content was recently migrated to the https://github.com/tensorflow/tfhub.dev which is now the correct repository to contribute PRs related to tfhub.dev. Let me know if you encounter any problems.
