### ISSUE TITLE
Progan-128 implementation

### ISSUE THREAD

**Issue by jppgks** [tensorflow/hub#7]
I find the TF Hub project commendable and I’m looking forward to seeing more modules being available.

One remark that I have now is that I can’t seem to find a module’s implementation. Are there any plans to release these? I’m especially interested in the progressive GAN source code.

**Comment by vbardiovskyg** [comment]
Hi, and thanks for the interest!

At this point there are no ongoing efforts for open-sourcing of the Progressive GANs code that was used to build the module. I would not rule out a possibility of this happening in the future, but it is not in the scope of the TensorFlow Hub project.

You can still refer to the paper which served as a basis for the implementation: https://arxiv.org/abs/1710.10196.
