### ISSUE TITLE
The dimensions of unpooled features from efficientnetb7 are not 1*19*19*2560

### ISSUE THREAD

**Issue by wangdomg** [tensorflow/hub#701]
As descripted in the title, the dimensions of unpooled features from efficientnetb7 are 1 * 19 * 19 * 640, which are different from the 1 * 19 * 19 * 2560 metioned in the original paper.  How can I get the 1 * 19 * 19 * 2560 unpooled features?

**Comment by rmothukuru** [comment]
@wangdomg,
Can you please provide the references/links with respect to your question. Thanks!

**Comment by wangdomg** [comment]
> @wangdomg,
> Can you please provide the references/links with respect to your question. Thanks!

Hi, thanks for your reply, in https://github.com/lukemelas/EfficientNet-PyTorch and https://github.com/qubvel/efficientnet, the  unpooled features from efficientnetb7 are 1 * 19 * 19 * 2560

**Comment by rmothukuru** [comment]
@wangdomg,
The references that you provided correspond to Pytorch. Please raise the issue in the respective repository. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
