### ISSUE TITLE
LaREQA/mBERT_X_Y/1/uncompressed does not exist

### ISSUE THREAD

**Issue by DesiKeki** [tensorflow/hub#706]
Dear Team,

I am trying to use LAReQA/mBERT_X_Y as per the given example at https://tfhub.dev/google/LAReQA/mBERT_X_Y/1.

For the following code:
```
import tensorflow.compat.v2 as tf
import tensorflow_hub as hub
import numpy as np

loaded = hub.load("https://tfhub.dev/google/LaREQA/mBERT_X_Y/1")
```

I get following error:
```
----> 5 loaded = hub.load("https://tfhub.dev/google/LaREQA/mBERT_X_Y/1")
OSError: gs://tfhub-modules/google/LaREQA/mBERT_X_Y/1/uncompressed does not exist.
```

Please let me know what I might be missing here.

**Comment by kempy** [comment]
The model name is incorrectly capitalized (LAReQA vs. LaREQA), I will go ahead and update the model documentation, but the following code snippet should work correctly

```python
!pip install tensorflow-text

import tensorflow.compat.v2 as tf
import tensorflow_hub as hub
import numpy as np
import tensorflow_text

loaded = hub.load("https://tfhub.dev/google/LAReQA/mBERT_X_Y/1")
```

**Comment by DesiKeki** [comment]
Thanks @kempy 
It was helpful.

Can you also please let me know or point me to an example of how to make use of this LAReQA model to retrieve scores in terms of start and end token ids of a possible answer from the context? I wish to use this model for cross lingual QA without any fine-tuning as of now.

**Comment by rmothukuru** [comment]
@DesiKeki,
As your original issue has been resolved, please raise a new issue for other problems. Thanks!

**Comment by DesiKeki** [comment]
Sure @rmothukuru 
Closing this issue.
