### ISSUE TITLE
TF-hub BIG-GAN example on Colab hangs while tf.Session initialization

### ISSUE THREAD

**Issue by atsukoba** [tensorflow/hub#709]
<https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/biggan_generation_with_tf_hub.ipynb>

in the 6th cell berow, `sess.run(initializer)`  always hangs on running.

```python
initializer = tf.global_variables_initializer()
sess = tf.Session()
sess.run(initializer)
```

**Comment by rmothukuru** [comment]
@atsukoba,
It didn't hang but it took very long time (almost 20 minutes). Please ensure that `Runtime` in the `Google Colab` is `GPU`. Thanks!

**Comment by WGierke** [comment]
Hi @atsukoba 
Thanks for bringing up this issue! Currently, tensorflow_hub directly reads uncompressed models from GCS when being executed on Colab. While this is favorable in environments with little disk space and a fast network connection, there are some models for which it can take a considerable amount of time to finish reading them from GCS. A quick fix is changing the loading behavior to COMPRESSED, which downloads, extracts and caches a compressed archive of the model. You can do that via
```python
import os
os.environ['TFHUB_MODEL_LOAD_FORMAT'] = 'COMPRESSED'
```
I've updated the Colab with that change. Please let us know if the problem persists for you!
