### ISSUE TITLE
programmatic access to model metadata in python package

### ISSUE THREAD

**Issue by rbroc** [tensorflow/hub#710]
hi folks - enhancement suggestion for the python library. Would it be possible to make metadata on individual models, e.g. problem domain, input type (images, text, audio...), available programmatically?

And, bonus request, would it be possible to add functionality to access a list of available models by domain?

That'd be really handy. 
My usage case: I'm wrapping the python library into a library for DL-based annotation of a variety of experimental stimuli for cognitive science - and it'd be nice to be able to have an overview of which models are available by domain and input modality.

**Comment by akhorlin** [comment]
Thank you for the feature suggestion. We will keep the request in mind when
prioritizing future feature development. Currently, we were not planning on
enabling programmatic access. But we will reevaluate in the future.

**Comment by rbroc** [comment]
cool, thanks for your reply. Not even for basic features such as input shape where a fixed shape is required (e.g. https://tfhub.dev/google/imagenet/mobilenet_v1_050_160/classification/4) ?

**Comment by akhorlin** [comment]
Currently this information is not stored in TF Hub in a structured manner.
So the feature request would involve actually capturing this information so
it can be returned by a hypothetical API. We will keep this discussion
under consideration.

**Comment by rbroc** [comment]
thanks, that'd be awesome to have! :)

**Comment by akhorlin** [comment]
Closing this issue for now, since there are no active plans to add such API.
