### ISSUE TITLE
Progressive GAN -  Controllable Generation

### ISSUE THREAD

**Issue by jecaJeca** [tensorflow/hub#711]
Hello,

I would like to use ProGAN model from tensorflow hub in order to make controllable generation of faces. Basically, I would need to use ProGAN model in combination with pretrained classifier (face attributes) to get gradients of the output class with respect to input noise.  Further, I would do gradient ascend on the noise vector in order to make classification prediction (on generated images) more accurate for desired class.

So far, have done this : 

```
import tensorflow_hub as hub
progan = hub.load("https://tfhub.dev/google/progan-128/1").signatures['default']

noise = tf.Variable(tf.random.normal(shape=(n_images, 512)),trainable=True)
for i in range(grad_step):
  with tf.GradientTape() as tape:
    tape.watch(noise)
    fake_image = progan(noise)['default']
    pred = tf.math.reduce_mean(cls(fake_image)[:, target_indices])
 grad = tape.gradient(pred,noise)
...

```

But I am getting error 
`InvalidArgumentError: cannot compute __inference_pruned_6282 as input #0(zero-based) was expected to be a float tensor but is a resource tensor [Op:__inference_pruned_6282]` on line `fake_image = progan(noise)['default']`.

Can you, please, tell me what I am doing wrong here and how to properly  use hub models for those cases?

Thanks,
Jelica

**Comment by WGierke** [comment]
Hi Jelica,
My apologies for the late reply. Could you share a stand-alone Colab notebook to reproduce the issue? Also, you might want to check out [this](https://stackoverflow.com/q/59304025) SO question. Hope that helps!

**Comment by WGierke** [comment]
Feel free to re-open the issue if the problem persists.
