### ISSUE TITLE
Vggish Feature Extraction Model

### ISSUE THREAD

**Issue by atanumandal0491** [tensorflow/hub#716]
I was trying to use "vggish" for feature extraction of my work. I used "vggish_inference_demo.py" for feature extraction. Input to the code was mono audio with sample rate 16KHz. Few audio giving output embedding vectors of shape of (1, 128) whereas few giving (0,128). I am unable to identify why few audio are not giving any vectors.
Help will be appreciated.

**Comment by saikumarchalla** [comment]
@atanumandal0491 I see  you have raised the same [issue](https://github.com/tensorflow/models/issues/9585) in models repo as well.Thanks!

**Comment by arnoegw** [comment]
Thanks @saikumarchalla! As far as I can see, the concern is really about tensorflow/models and not tensorflow/hub, so let me close this here.
