### ISSUE TITLE
SavedModel built with BERT preprocessing models keeps using Hub's original vocab file path

### ISSUE THREAD

**Issue by arnoegw** [tensorflow/hub#719]
From https://stackoverflow.com/questions/65511729 by mattdeak:

Saving a Keras Model that involves hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2") or ".../1" creates a SavedModel that keeps referring to vocab.txt for table initialization at the location from which the TF Hub model was loaded, not from the actual location of the new SavedModel.

I can reproduce the problem, but more analysis is needed.

**Comment by vforvoid** [comment]
https://github.com/tensorflow/tensorflow/issues/46293
Having the same issue here.

**Comment by vforvoid** [comment]
Is there any way to bypass this problem for now? I kind of blocked here by this issue. I've created Docker container to mitigate this issue for now but we have to deploy our SavedModel to cloud and my solution won't really help.

```
FROM tensorflow/serving:2.4.0

COPY ./modelname/ /models/classify/1
COPY ./modelnameassets/vocab.txt /tmp/tfhub_modules/09bd4e665682e6f03bc72fbcff7a68bf6879910e/assets/vocab.txt

ENV MODEL_NAME=modelname
```

Maybe there's a way to manually patch the `vocab.txt` path in the model before saving it?

**Comment by arnoegw** [comment]
I'm hoping to publish new preprocessing models within the next few days that avoid this issue, please stay tuned.

**Comment by arnoegw** [comment]
The problem should be fixed with https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3. (The model content is live, but documentation needs some time to propagate to the tfhub.dev UI. Other docs will be updated soon.)

My analysis of the root cause is in https://github.com/tensorflow/tensorflow/issues/46456. The updated models were built with the workaround from commit https://github.com/tensorflow/models/commit/d03930565a70997b10e1d252c2d521587716af18
