### ISSUE TITLE
TF Hub image load issue

### ISSUE THREAD

**Issue by aw-west** [tensorflow/hub#720]
On TF Hub you use `matplotlib` to load images, however this is an inconsistent method as `jpg`∈[0,255] and `png`∈[0,1.].

Do you agree it be better to replace `plt.imread` with `tf.io.decode_image`?

For example, the content image would change as below, this would also avoid transparency channels causing errors.
```
content_image = plt.imread(content_image_path)
content_image = content_image.astype(np.float32)[np.newaxis, ...] / 255.
```
```
content_image = tf.io.decode_image(tf.io.read_file(content_image_path), channels=3, dtype=tf.float32)[tf.newaxis, ...]
```

**Comment by rmothukuru** [comment]
@aw-west,
Can you please give references to the code which uses **MatPlotLib** to Load Images? Thanks!

**Comment by aw-west** [comment]
`matplotlib.pyplot.imread` uses `matplotlib.image.imread` which uses `matplotlib.image.pil_to_array` or for `ext='png'` (line 1477) `matplotlib.image._pil_png_to_float_array`

*"Convert a PIL `PNGImageFile` to a 0-1 float array.
Unlike pil_to_array this converts to 0-1 float32s for backcompat with the old libpng-based loader."*
[matplotlib.image](https://github.com/matplotlib/matplotlib/blob/v3.3.3/lib/matplotlib/image.py)._pil_png_to_float_array (lines 1646-1648)

This changed in [v3.3.0](https://github.com/matplotlib/matplotlib/blob/v3.3.0/lib/matplotlib/image.py) as [v3.2.x](https://github.com/matplotlib/matplotlib/blob/v3.3.0/lib/matplotlib/image.py) does have a `_pil_png_to_float_array` although I see no mention of it in the [v3.3.0 changelog](https://matplotlib.org/3.3.0/users/whats_new.html)

**Comment by akhorlin** [comment]
Thank you for the suggestion. We submitted a fix to the code in question.
