### ISSUE TITLE
TFHub models cannot be loaded by tensorflows summarize_graph

### ISSUE THREAD

**Issue by paulgavrikov** [tensorflow/hub#725]
**Describe the current behavior**

`summarize_graph` is not able to load downloaded and extracted models from TFHub e.g. https://tfhub.dev/deepmind/biggan-128/2 due to parsing errors. I extract the tar and try to load `saved_model.pb`. The TensorFlow (tensorflow/tensorflow#46494) team asked me to open an issue here as this seems to be TFHub related.

```
$ bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph='/media/paulgavrikov/DATA/noCNN/model_conversion/biggan/compare_gan_ssgan_128x128_1/saved_model.pb'  --print_structure=true
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Error parsing text-format tensorflow.GraphDef: 1:1: Invalid control characters encountered in text.
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Error parsing text-format tensorflow.GraphDef: 1:2: Interpreting non ascii codepoint 154.
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Error parsing text-format tensorflow.GraphDef: 1:2: Expected identifier, got: �
2021-01-17 12:13:33.563477: E tensorflow/tools/graph_transforms/summarize_graph_main.cc:320] Loading graph '/media/paulgavrikov/DATA/noCNN/model_conversion/biggan/compare_gan_ssgan_128x128_1/saved_model.pb' failed with Can't parse /media/paulgavrikov/DATA/noCNN/model_conversion/biggan/compare_gan_ssgan_128x128_1/saved_model.pb as binary proto
	 (both text and binary parsing failed for file /media/paulgavrikov/DATA/noCNN/model_conversion/biggan/compare_gan_ssgan_128x128_1/saved_model.pb)
2021-01-17 12:13:33.563504: E tensorflow/tools/graph_transforms/summarize_graph_main.cc:322] usage: bazel-bin/tensorflow/tools/graph_transforms/summarize_graph
```

**Describe the expected behavior**

Extracted models should be loaded by summarize_graph.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: Python 3.8.6 (default, Oct  9 2020, 11:59:16) 
- Bazel version (if compiling from source): Bazelisk version: v1.6.1
- GCC/Compiler version (if compiling from source): [GCC 9.3.0] on linux
- CUDA/cuDNN version: not relevant
- GPU model and memory: not relevant

**Comment by rmothukuru** [comment]
@paulgavrikov,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by paulgavrikov** [comment]
@rmothukuru See this colab nb: https://colab.research.google.com/drive/1tmgY7gcm_0-5SAoS8-OVfqC8wJFzW1Yx?usp=sharing

**Comment by WGierke** [comment]
Hi @paulgavrikov ,
Thanks a lot for the code snippet! Unfortunately, this tool only works on SavedModels exported for serving while hub models are exported for reuse. We are not planning to extend the support to hub models at this time.
