### ISSUE TITLE
 Max length of the text for  the Universal Sentence Encoder input

### ISSUE THREAD

**Issue by lessenko** [tensorflow/hub#726]
What is the max length of the text for the Universal Sentence Encoder input?
https://tfhub.dev/google/universal-sentence-encoder/4

Thanks.

**Comment by Arghya999** [comment]
In the link :- https://tfhub.dev/google/universal-sentence-encoder/4 , max length is not mentioned.
The line "The input is variable length English text and the output is a 512 dimensional vector." implies that max length is not a definite entity.
Please confirm if this works good for you.

**Comment by arghyaganguly** [comment]
@lessenko , the input is a variable length English text as mentioned in the link.
Max length is not a definite entity.
Please confirm if this works for you.

**Comment by lessenko** [comment]
Thanks. It works for me. I tested 4KB and 16KB text without limit notice.

**Comment by arghyaganguly** [comment]
Closing #726
