### ISSUE TITLE
How to extract hidden layers from pretrained models in hub?

### ISSUE THREAD

**Issue by Huntersts** [tensorflow/hub#727]
I want to use InceptionV3 as backbone in my network, but I just need some layers in InceptionV3 and some features in InceptionV3. I'm trying to use **hub.KerasLayer** to load pretrained model, but it seems like I can't use hidden layers in this way. So can anyone tell me how to figure out this problem?
```python
import tensorflow_hub as hub
hub.KerasLayer("https://tfhub.dev/google/tf2-preview/inception_v3/classification/4", output_shape=[1001])
```

**Comment by arghyaganguly** [comment]
related issue :- https://github.com/tensorflow/hub/issues/453

**Comment by arghyaganguly** [comment]
@Huntersts , i believe changing the headline to "how to extract hidden layers from pretrained models in hub?" might make it more on point.
Please confirm on this.
If so, please edit the headline.

**Comment by Huntersts** [comment]
I think  I can use **get_weights()**  to reassign the parameters in another network which is make up by hidden layers of pretrained model to figure out this problem.

**Comment by WGierke** [comment]
Hi @Huntersts 
Could you check out https://tfhub.dev/google/imagenet/inception_v3/feature_vector/4, please? For a given image, it generates a feature vector of size 2048 using InceptionV3. You can add more layers on top of it via e.g.
```python
m = tf.keras.Sequential([
    hub.KerasLayer("https://tfhub.dev/google/imagenet/inception_v3/feature_vector/4"),
    tf.keras.layers.Dense(num_classes, activation='softmax')
])
m.build([None, 299, 299, 3])  # Batch input shape.
```
as described in the documentation. Hope that helps!
