### ISSUE TITLE
incorporating non default signature into tf.estimator

### ISSUE THREAD

**Issue by r-wheeler** [tensorflow/hub#73]
A few questions around combining tensorflow_hub and `tf.estimator`. I am using a non default signature to embed words with ELMO. Is this the best practice for doing so? 

elmo is instantiated in the model function: 

```
def model_fn(features, labels, mode, params):
    #tf.logging.set_verbosity(tf.logging.ERROR) 
    elmo = hub.Module("https://tfhub.dev/google/elmo/1", trainable=False)
    
    with tf.variable_scope("elmo"+ str(np.random.rand())):
            
    #Elmo requires padded raw text
    words = tf.string_split(features['text'])
    dense_words = tf.sparse_to_dense(sparse_indices=words.indices, 
                                     sparse_values=words.values,
                                     default_value="", 
                                     output_shape=[params.batch_size, 
                                                   params.max_seq_len])
    #(B x W_t, 1024)
    elmo_embeddings = elmo(
        inputs={
            "tokens": dense_words,
            "sequence_len": tf.cast(tf.reshape(features['word_pad'], 
                                  shape=[BATCH_SIZE,]), tf.int32)
        },
        signature="tokens",
        as_dict=True)["elmo"]
```
This does not use hub.text_embedding_column. 
This also breaks viewing the graph in tensorboard. 

Is this the best way to use hub in estimator? 
Is there a way to view the graph in tensorboard?

**Comment by andresusanopinto** [comment]
The feature column api is high level and does not allows one to easily create arbitrary features, as so we followed the same pattern on `hub.text_embedding_column` and only designed it to give access to simple and clear features from a module (i.e. the default signature with default output).

However the fact that `hub.text_embedding_column` accepts a `module_spec` allows one to wrap more advanced logic in a feature column than was previously possible, so you could create a new module spec that wraps the specific case of elmo you are interested. E.g.:

```
def elmo_embedding():
  text_feature = tf.placeholder(tf.string)
  words = tf.string_split(text_feature)
  dense_words = ...
  elmo = hub.Module("https://tfhub.dev/google/elmo/1", trainable=False)
  elmo_embeddings = elmo(dense_words, signature=..., as_dict=True)["elmo"]
  hub.add_signature(inputs=text_feature, outputs=elmo_embeddings)

...
elmo_spec = hub.create_module_spec(elmo_embedding)
hub.text_embedding_column("text", elmo_spec)
```

PS 0: Your example using np.random.rand() looks very suspicious.
PS 1: Please open a specific bug about the tensorboard viewing.
PS 2: I have not tried the above snippet but it should document the overall idea.

**Comment by r-wheeler** [comment]
Thanks -- This approach looks promising, reading through the source for hub.text_embedding_column helped me see what was going on. 

Also confirmed the hub is not instantiated on every call of model_fn. 

Re: PS0 
Thanks --Just a slight hack to quickly evaluate in a notebook and avoid name collisions.
