### ISSUE TITLE
How to use TF1 Fine Tuning Resnet50 and Exporting TF1 Module?

### ISSUE THREAD

**Issue by maxlv7** [tensorflow/hub#733]
I am a fresh man for use TF1;
when i want to fine tune resnet50 at `https://hub.tensorflow.google.cn/google/imagenet/resnet_v2_50/classification/3`
For fine Fine-tuning, It give me some sample code such as
```
module = hub.Module("https://hub.tensorflow.google.cn/google/imagenet/resnet_v2_50/classification/3",
                    trainable=True, tags={"train"})
logits = module(inputs=dict(images=images, batch_norm_momentum=0.997),
                signature="image_classification_with_bn_hparams")
```
I don't know how to use it next. Can someone give me a complete example?
Thank you very much !

**Comment by arghyaganguly** [comment]
@maxlv7 , please explore  https://www.kaggle.com/curiousprogrammer/chest-x-ray-image-classification-tf-hub-resnet50 for more information.
Please note that TF1 is depreciated and TF2 usage is suggested.

**Comment by maxlv7** [comment]
> @maxlv7 , please explore  https://www.kaggle.com/curiousprogrammer/chest-x-ray-image-classification-tf-hub-resnet50 for more information.
> Please note that TF1 is depreciated and TF2 usage is suggested.

very thanks,i will try it soon
