### ISSUE TITLE
EfficientDet lite variants are invalid urls.

### ISSUE THREAD

**Issue by sebastian-sz** [tensorflow/hub#738]
It's impossible to load Efficient Det Lite models via hub url. I tested only few but they all throw exceptions:

```python
import tensorflow_hub as hub

base_model = hub.KerasLayer("https://tfhub.dev/tensorflow/efficientdet/lite4/detection/1")
```

This will raise error:
```python
NotFoundError: /tmp/tfhub_modules/22316a549b1eeec307b04bab99b9ce54176fe5c1.34e1f5349dc244848a4e8178ec97b47c.tmp/variables/variables.data-00000-of-00001; No such file or directory
```
The similar happens with other efficientdet lite models.

**Comment by WGierke** [comment]
Hi @sebastian-sz 
Thank you for bringing this issue to our attention! It should now be possible to load all formerly affected models.

**Comment by sebastian-sz** [comment]
I tested few URL's and it seems to work. Thank you for the quick resolve!
