### ISSUE TITLE
Change the seq_length in Text preprocessing for BERT

### ISSUE THREAD

**Issue by YangHan-Morningstar** [tensorflow/hub#740]
Hi, I'm using bert to do a text classification but I want to change my seq_length to another, the document confused so much

![image](https://user-images.githubusercontent.com/67748964/109500845-bea26780-7ad1-11eb-9b9f-9e23a7bfd150.png)

How can I change the seq_length instead of 128 default(one input is only one sentence)? I read this demo

![image](https://user-images.githubusercontent.com/67748964/109500994-f0b3c980-7ad1-11eb-9cd1-86efcd3fdd7a.png)

But which is the mode input? text_inputs or tokenized_inputs? Could you give me a whole process? Thanks a lot!

**Comment by arghyaganguly** [comment]
@YangHan-Morningstar ,please check [link](https://blog.tensorflow.org/2020/12/making-bert-easier-with-preprocessing-models-from-tensorflow-hub.html) and confirm if your questions are answered.

**Comment by YangHan-Morningstar** [comment]
OK, I have solve my question, just change the text_inputs to one element is ok, thanks a lot!
