### ISSUE TITLE
tf.hub model with BERT preprocessing can't be loaded

### ISSUE THREAD

**Issue by hanneshapke** [tensorflow/hub#747]
I am trying to reduce the default token length with the tf.hub BERT preprocessing models. The model training and export works fine. However, I can't load the exported model, since the encoder expects a list of RaggedTensors ([Colab with a minimal demo example and the error message](https://colab.research.google.com/drive/1SbEuM9NF89dvH3-32vHYkPpfvMCrIMyg?usp=sharing)).

If I use the default sequence length and load the preprocessing and encoder model via the `KerasLayer`, everything works fine. 

As soon as I am running the tokenization explicitly in order to set the sequence length in the following packer step, I am running into the error.

```
tokenizer = hub.KerasLayer(bert_preprocess.tokenize, name='tokenizer')
segments = [tokenizer(s) for s in input_segments]
```

When I try to load the model with the custom sequence length with the following code
```
with tf.device('/job:localhost'):
    exported_model = tf.keras.models.load_model(export_path)
```

I am receiving this error message:
```
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("inputs:0", shape=(None,), dtype=int32), row_splits=Tensor("inputs_2:0", shape=(None,), dtype=int64)), row_splits=Tensor("inputs_1:0", shape=(None,), dtype=int64))
    * False
  Keyword arguments: {}

Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (2 total):
    * [RaggedTensorSpec(TensorShape([None, None, None]), tf.int32, 2, tf.int64)]
    * False
  Keyword arguments: {}
```

From the docs:
```
The call to tokenize() returns an int32 RaggedTensor of shape [batch_size, (tokens)]. Correspondingly, the call to bert_pack_inputs() accepts a RaggedTensor of shape [batch_size, (tokens)].
```

What can cause that the `tokenize()` function only returns a single `RaggedTensor` instead of a list as expected?

The error is independent from the BERT model variant. I have tried a variety of types, small BERT, BERT, ALBERT. Same result.

Is this a problem with the preprocessing model or with the way I save the model?

**Comment by arghyaganguly** [comment]
@hanneshapke , i changed the below segments of code to save/load the model with no errors :- 

```
# Export the model

export_path = "exported_model/"
save_options = tf.saved_model.SaveOptions(experimental_io_device='/job:localhost')
model.save(export_path, include_optimizer=False, options=save_options)
 ```

to 
```
# Export the model

export_path = "exported_model/"
save_options = tf.saved_model.SaveOptions(experimental_io_device='/job:localhost')
model.save_weights(export_path)
 ```
and to load the model(weights) :- 
 ```
# Load the exported model again ===> Exported model can't be loaded
with tf.device('/job:localhost'):
    # exported_model = tf.saved_model.load(export_path)
      exported_model = tf.keras.models.load_model(export_path)
``` 

with 

```
# Load the exported model again ===> Exported model can't be loaded

with tf.device('/job:localhost'):
    # exported_model = tf.saved_model.load(export_path)
    # exported_model = tf.keras.models.load_model(export_path)
      exported_model = model.load_weights(export_path)
```

**Comment by hanneshapke** [comment]
Thank you @arghyaganguly for you prompt reply. I can confirm the workflow is working. But it seems like a workaround, would you agree @arghyaganguly ? I was planning to export the saved model via TFX and reuse the model in a different pipeline, therefore I preferred the savedModel format.

Again, thank you very much for your quick reply! Very appreciated.

**Comment by kempy** [comment]
`exported_model = tf.saved_model.load(export_path)` instead of `exported_model = tf.keras.models.load_model(export_path)` works for me and gives a restored object that is callable. Can you confirm that it works for you?

**Comment by hanneshapke** [comment]
Thank you @kempy for your reply. `tf.saved_model.load` seems to return a concrete function. In my downstream process where I assemble this and other models in an ensemble, I have trouble using concrete function as a layer in a new `tf.keras` model. 

Have you seen a `tf.keras` implementation which is using a concrete function as a layer? If that work, this route would work for me. Otherwise I have to fall back to using `tf.keras.models.load_model`.

**Comment by kempy** [comment]
You can use `hub.KerasLayer(export_path)` to restore a SavedModel (from Hub or from a local filesystem) as a Keras Layer that is composable with other TF code.

**Comment by kempy** [comment]
Also, just to clarify, tf.saved_model.load restores an object with python functions attached that map to specific functions/concrete functions restored from the SavedModel. So the __call__ function on the restored object is mapped to a particular function that corresponds to the __call__ function from the serialized Keras Layer or model that was written.

**Comment by hanneshapke** [comment]
Thank you again @kempy for the hint regarding `hub.KerasLayer`. I totally forgot this options for my own savedModels. This workflow works perfectly. I would be happy to close this issue. Thank you all for your fast replies and suggestions.

**Comment by arghyaganguly** [comment]
Closing this following the above commment by @hanneshapke .
