### ISSUE TITLE
tokenize a string by tf-hub tokenizer

### ISSUE THREAD

**Issue by ZahraGithub** [tensorflow/hub#749]
Hi

When I use the following code in the following link:

`bert_preprocess = hub.load(tfhub_handle_preprocess) tok = bert_preprocess.tokenize(tf.constant(['Hello TensorFlow!'])) print(tok)`

https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/text/solve_glue_tasks_using_bert_on_tpu.ipynb#scrollTo=-ePjboKOPmv4

the output would be:
<tf.RaggedTensor [[[7592], [23435, 12314], [999]]]>

returned token ids are relevant to "Hello", "Tensor", "Flow", "!", I guess. Now, I want to have these equivalent tokens. How could I convert those token ids to these tokens?

Best Regards,
Thanks

**Comment by hanneshapke** [comment]
@ZahraGithub you can convert the ids back to tokens by reading the `vocab.txt` file from the preprocessing model (you can find the `vocab.txt` file in the `assets` folder of the model. Check out the `tfhub_modules` folder where tf.hub stores the downloaded models).

If you read the file line by line, the index of line X corresponds to token id X.

Maybe there is a simpler way. But I don't think that the preprocess model can return string tokens. Btw, tf.text can do that.

**Comment by hanneshapke** [comment]
@arghyaganguly Do you know if the tokenizer from the preprocessor model allows additional arguments for the tokenization?
The sentence piece tokenizer allows subword regularization (https://github.com/google/sentencepiece#subword-regularization-and-bpe-dropout). I have a specific NLP problem were I would like to prevent the tokenizer from using subword tokens with more than 2 characters. Do you know if the tf.hub model tokenizer can support that scenario?

**Comment by akhorlin** [comment]
These options are not currently supported. Under the hood, the TF Hub tokenizer relies [tf.text](https://github.com/tensorflow/text/blob/master/docs/api_docs/python/text.md) library for [in-Graph](https://github.com/tensorflow/text/blob/master/docs/index.md), TF text parsing operations. tf.text provides [SentencePieceTokenizer](https://github.com/tensorflow/text/blob/master/docs/api_docs/python/text/SentencepieceTokenizer.md) that could be used directly. Though taking a cursory look at it, it might not have these options either.
