### ISSUE TITLE
How to get the vocab size of the preprocessor layer?

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/hub#752]
```
  preprocessor = hub.KerasLayer("/root/yanan/berts/albert_en_preprocess_3")

  text_input = tf.keras.layers.Input(shape=(), dtype=tf.string) # shape=(None,) dtype=string

  encoder_inputs = preprocessor(text_input)
```
I use the tokenizer and vocab of the pre-trained model, loaded from the tensorflow hub.
Is there any elegant way to the vocab size of the `preprocessor` ?

Currently, I use this way:
```
  preprocessor_file = "./albert_en_preprocess_3"
  preprocessor = hub.load(preprocessor_file)
  vocab_size = preprocessor.tokenize.get_special_tokens_dict()['vocab_size'].numpy()
```
which I suppose is not elegant.

**Comment by arghyaganguly** [comment]
@yananchen1989 , your snippet matches the approach shown in "Custom input packing and MLM support" section in [https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3](url).

**Comment by akhorlin** [comment]
The code snippet is a reasonable way for getting the vocab size.
