### ISSUE TITLE
Cannot import tensorflow_hub

### ISSUE THREAD

**Issue by chalbiophysics** [tensorflow/hub#753]
Hi everyone,

I have installed tensorflow-hub with anaconda prompt :  `conda install -c conda-forge tensorflow-hub `

This code : `import tensorflow_hub as hub` provides this error : `AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'`

I have noticed that this issue has already been reported [https://github.com/tensorflow/hub/issues/289](url) but I uninstalled and reinstalled all packages and problem persists.

Here is my configuration : 
- Windows 10 64 bits
- Python 3.7
- tensorflow 2.1
- tensorflow_gpu 2.1
- tensorflow_hub 0.9
- GPU : Nvidia quadro k620
- cuda toolkit 10.1
- cudnn 7.6
- tensorRT 6.0

Please, could you let me know if you have faced similar issue and how you solved it...

Kindly !

**Comment by arghyaganguly** [comment]
@chalbiophysics ,could you please try updating your TensorFlow version to the latest stable 2.4.1 and let us know if the issue persists?

**Comment by chalbiophysics** [comment]
Hello @arghyaganguly . I update tensorflow-gpu to version 2.3 (version 2.4 not yet available on anaconda). Indeed, it solved my issue with tensorflow-hub ... but my GPU is not recognized anymore ! One day at time is enough !

**Comment by chalbiophysics** [comment]
Just in case people might be interested, version of tensorflow-estimator should be the same as tensorflow-gpu (2.3 in my case).
