### ISSUE TITLE
Finetune tfhub object detection model on Custom data (TensorFlow 2)

### ISSUE THREAD

**Issue by ameyparanjape** [tensorflow/hub#756]
I am interested in training object detectors using efficientdet models. I was able to train the model using the official repo, but I could not train the efficientdet-lite models using the official repo. So I'm interested in using tfhub lite model/feature vector to finetune/retrain on custom data. It seems possible, but I could not find any documentation/notes on how to retrain tfhub object detector. All the docs show the inference only. Any help on this would be greatly appreciated!

**Comment by WGierke** [comment]
Hi @ameyparanjape 

Please note that only [these efficientdet-lite models](https://tfhub.dev/s?fine-tunable=yes&subtype=module,placeholder&q=efficientdet-lite) are fine-tunable.
Unfortunately, we don't have specific instructions for these models but when you have a look at https://github.com/tensorflow/hub/issues/678 you'll find a reference to the [TensorFlow Object Detection API ](https://github.com/tensorflow/models/tree/master/research/object_detection) as well as to the [
Eager Few Shot Object Detection Colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb) that shows how to fine-tune a RetinaNet. Hope that helps!

**Comment by arghyaganguly** [comment]
Closing this issue as stale.Please feel free to reopen.Thanks.
