### ISSUE TITLE
[Help needed] Issue with using USE

### ISSUE THREAD

**Issue by Param-29** [tensorflow/hub#759]
I am referring to the code given here:
https://heartbeat.fritz.ai/introduction-to-googles-universal-sentence-encoder-a-state-of-art-model-377c025afaca

Following is my code
```
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
model = hub.Module("https://tfhub.dev/google/universal-sentence-encoder-lite/2")
model(["Hello world"])
```

This gives me following error
> TypeError: Signature expects multiple inputs. Use a dict.

Is there anything I am missing out here?

**Comment by WGierke** [comment]
Please note that you are using a different model than the one used in the blog article. Replacing the line starting with `model =` with `model = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")` fixes your snippet. If you really want to use the `universal-sentence-encoder-lite` model, you can find a usage example on its model page at https://tfhub.dev/google/universal-sentence-encoder-lite/2.
