### ISSUE TITLE
MUSE returning different embeddings for same string

### ISSUE THREAD

**Issue by mariokostelac** [tensorflow/hub#760]
I've noticed that MUSE does not return stable embeddings if the same string is passed in multiple times. I've also noticed that it depends on where that string is in the batch.

Here is the repro notebook I've created
https://colab.research.google.com/drive/1dVCJRxShGUNi0nId1OhHosiyzJHs-m1v?usp=sharing.

I think the fastest repro in the console would be

```python
import numpy as np
import os
import tensorflow.compat.v2 as tf
import tensorflow_hub as hub
from tensorflow_text import SentencepieceTokenizer

module_url = 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'

model = hub.load(module_url)

def embed_text(input):
  return model(input)

# last sentence won't embed the same
english_sentences = ['dog', 'Puppies are nice.', 'I enjoy taking long walks along the beach with my dog.']
emb1 = embed_text(english_sentences)
emb2 = embed_text(english_sentences)
diff = emb1 - emb2
max_per_emb = np.max(diff, axis=1)

assert max_per_emb[0] == 0.0
assert max_per_emb[1] == 0.0
assert max_per_emb[2] != 0.0  # it's different

# same sentences, reordered will embed exactly the same
english_sentences = ['I enjoy taking long walks along the beach with my dog.', 'dog', 'Puppies are nice.']
emb1 = embed_text(english_sentences)
emb2 = embed_text(english_sentences)
assert np.max(emb1 - emb2) == 0.0. # now it's the same! Embedding process seem to be order dependent!
```

Is that expected behaviour or it's a bug? If it's a bug, what could be causing it?

----

I've observed this first time after TF1 -> TF2 migration.

**Comment by arghyaganguly** [comment]
Non-deterministic behavior.
Related issue - #362

**Comment by WGierke** [comment]
Hi @mariokostelac 
Thank you for the short and working snippet!
It appears as if your Colab uses a GPU runtime, is that correct? I cannot reproduce the issue with a CPU runtime but with a GPU runtime.
I've forwarded the observations to the publisher.

**Comment by mariokostelac** [comment]
@WGierke you're right. I can't repro that on the CPU-based instance. Is that expected on GPU-based instances?

**Comment by akhorlin** [comment]
This might due to the numerical stability of the hardware device. If the difference is very small like 1e-08, it could be usually treated as normal (e.g. assert np.max(emb1 - emb2) < 1e-06 to test instead of making sure they are 0.0). Such difference should not cause the performance issue of downstream tasks.

**Comment by mariokostelac** [comment]
> This might due to the numerical stability of the hardware device. 

Thanks for replying. Any chance you can point to some good resourced around numerical instability?

**Comment by akhorlin** [comment]
Numerical stability is quite an extensive topic. There are myriad textbooks
(example <https://link.springer.com/chapter/10.1007/978-3-642-15939-8_31>),
papers (example <https://arxiv.org/pdf/1705.03341>) and discussions (example
<https://github.com/tensorflow/tensorflow/issues/8657>) that might be
relevant if you are looking to learn more about it.
