### ISSUE TITLE
Why use ImageNet as pretrain datasets.

### ISSUE THREAD

**Issue by kento-kobayashi** [tensorflow/hub#761]
Why use ImageNet as pretrain datasets?
I have question for pretrain dataset for https://tfhub.dev/google/remote_sensing/bigearthnet-resnet50/1. In this paper(https://arxiv.org/pdf/2001.06372.pdf) say that pretraining ImageNet is not good way for remote sensing dataset. But, ImageNet is used as "Pre-training datasets" in this page https://tfhub.dev/google/collections/remote_sensing/1.
I think that bigearthnet-resnet50 should be trained without ImageNet.

**Comment by arghyaganguly** [comment]
@kento-kobayashi,this is an interesting find.Thanks for reporting this.
Observation :- [BigEarthNet Dataset with A New
Class-Nomenclature for Remote Sensing Image
Understanding](https://arxiv.org/pdf/2001.06372.pdf) is a more recent paper than [In-domain representation learning for remote sensing](https://arxiv.org/abs/1911.06721) which is being referenced in [link.](https://tfhub.dev/google/collections/remote_sensing/1)
