### ISSUE TITLE
_create_unverified_context

### ISSUE THREAD

**Issue by orsaada** [tensorflow/hub#762]
https://github.com/tensorflow/hub/blob/master/examples/colab/action_recognition_with_tf_hub.ipynb
 
i tried to convert this notebook to .py file and run it on pycharm.
is there a file the same .py ?

i have problem with the ssl not recognized this function:
```unverified_context = ssl._create_unverified_context()```

macos pycharm python 3.7

**Comment by arghyaganguly** [comment]
@orsaada , please try this [workaround](https://github.com/GENI-NSF/geni-tools/issues/776#issuecomment-103277243) and  check if it solves your problem.

**Comment by arghyaganguly** [comment]
Closing this as it has been awaiting response for some time.Please feel free to reopen with information/insights based on above comment trace.
