### ISSUE TITLE
USE-QA v3 to KerasLayer with trainable = True fail on fine-tune the model

### ISSUE THREAD

**Issue by mrpeerat** [tensorflow/hub#763]
(i) I define USE-QA for response and question encodes 
`USE_qa_response =  hub.KerasLayer('use-model/use-qa-model',
                       input_shape=[],
                       dtype=tf.string,
                      output_key='outputs',
                      signature='response_encoder',
                       trainable=True)
`
`
USE_qa_question =  hub.KerasLayer('use-model/use-qa-model',
                       input_shape=(),
                       dtype=tf.string,
                      output_key='outputs',
                      signature='question_encoder',
                       trainable=True)
`

(ii) Then, create a network for fine-tune the USE-QA
`encode1 = USE_qa_response({'input': input1, 'context': context1})`
`
  encode2 = USE_qa_question(questions)
`

(iii) After that, the error show 
    `ValueError: Setting hub.KerasLayer.trainable = True is unsupported when calling a SavedModel signature.`
<img width="798" alt="Screen Shot 2021-05-13 at 12 30 11 PM" src="https://user-images.githubusercontent.com/21156980/118082215-f76e8f00-b3e6-11eb-8e2b-002d50bd0e26.png">

Environment:
`tensorflow == 2.4.1
tensorflow-hub == 0.11.0`

If I change `trainable = False` it works! but the USE-QA won't fine-tune or change any parameter inside the model.
What should I do?

**Comment by rmothukuru** [comment]
@mrpeerat,
The behavior seems to be expected as per the [documentation of Arguments of Hub Keras Layer](https://www.tensorflow.org/hub/api_docs/python/hub/KerasLayer#attributes), mentioned below:

> trainable | Optional. A boolean controlling whether this layer is trainable. Must not be set to True when using a signature (raises ValueError), including the use of legacy TF1 Hub format.

Since you are using **`signature='response_encoder'`**, the argument, **`trainable`** should be set to **`False`**.

**Comment by mrpeerat** [comment]
> @mrpeerat,
> The behavior seems to be expected as per the [documentation of Arguments of Hub Keras Layer](https://www.tensorflow.org/hub/api_docs/python/hub/KerasLayer#attributes), mentioned below:
> 
> > trainable | Optional. A boolean controlling whether this layer is trainable. Must not be set to True when using a signature (raises ValueError), including the use of legacy TF1 Hub format.
> 
> Since you are using **`signature='response_encoder'`**, the argument, **`trainable`** should be set to **`False`**.

But if we set `trainable = False` the USE-QA will update the value or parameter inside the model?
Or what if we delete `signature='response_encoder'`, I can't imagine how to implement fine-tune the USE-QA without the `signature` parameter, any suggestion?

**Comment by maringeo** [comment]
Here is more information on why `trainable = True` is not supported when calling a SavedModel signature: https://github.com/tensorflow/hub/blob/a452309e69a9ec85641534a84016e92007785451/tensorflow_hub/keras_layer.py#L259

https://github.com/tensorflow/hub/issues/428#issuecomment-647191531 discusses a very similar problem and potential workarounds. Please reopen if you have further questions.
