### ISSUE TITLE
StringLookup layer adds None to list of saved model variables which breaks hub.KerasLayer

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/hub#764]
Reference https://github.com/tensorflow/tensorflow/issues/42553
I'm fighting this issue since TF 2.3 and there is no progress in TF to solve it.

Maybe it could be solved faster inside tf-hub ?

**Comment by akhorlin** [comment]
TF Hub is open to external contributions. Do you have a specific fix in
mind?

**Comment by akhorlin** [comment]
One option that could be tried first is to define a class that would extend from hub.KerasLayer and that would override self.add_weight to handle nulls by ignoring them. It might be worth a try.
