### ISSUE TITLE
Cannot import tensorflow hub

### ISSUE THREAD

**Issue by MatanSandori** [tensorflow/hub#765]
Hi everyone,

I have installed Tensor Flow hub through:  pip install tensorflow_hub.

> windows 10 64 bit
> python 3.8
> tensorflow 4.0 / 4.1 (Tested on both versions)
> tensorflow-gpu 4.0 / 4.1 
> tensorflow-hub 0.12.0 / 0.11.0 / ...

![Tensorflow_hubIssuse](https://user-images.githubusercontent.com/83867477/118280569-0469ac00-b4d5-11eb-81ee-f26993b97d12.JPG)

If you know a solution to the problem can you let me know? 
Thanks!

**Comment by MorganR** [comment]
Hello @MatanSandori , it looks like there is a typo in your import. It should read:

`import tensorflow_hub as hub`

You've accidentally swapped the s and the o

**Comment by MatanSandori** [comment]
This was not part of the problem but thanks for noticing, VScode did not find tensorflow_hub.
I replaced the environment and the problem worked out.

Thank you!

> Hello @MatanSandori , it looks like there is a typo in your import. It should read:
> 
> `import tensorflow_hub as hub`
> 
> You've accidentally swapped the s and the o
