### ISSUE TITLE
BERT model tutorial code "Solve GLUE tasks using BERT on TPU" on Colab is broken

### ISSUE THREAD

**Issue by Hangjun-Chen** [tensorflow/hub#766]
It seems Colab has just upgraded tensorflow version and now tensorflow-text is now not compatible.

In the colab notebook
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/text/solve_glue_tasks_using_bert_on_tpu.ipynb

After ran the following lines

!pip install -q -U tensorflow-text
!pip install -q -U tf-models-official

the following error message showed up:
ERROR: tensorflow-text 2.4.3 has requirement tensorflow<2.5,>=2.4.0, but you'll have tensorflow 2.5.0 which is incompatible.

Is there a way to exactly specify tensorflow and tensorflow-text to some versions that match?

Thanks!

**Comment by arghyaganguly** [comment]
@Hangjun-Chen , thanks for reporting this issue.I was able to reproduce it in colab.

**Comment by maringeo** [comment]
Hi @Hangjun-Chen, specifying the version of tf-models-official to 2.4.0 should fix the Colab:

`!pip install -q -U tf-models-official==2.4.0`

**Comment by Hangjun-Chen** [comment]
Hi @maringeo Yes this fixes it. Thanks!
