### ISSUE TITLE
change movenet to batch inference

### ISSUE THREAD

**Issue by flyingmrwang** [tensorflow/hub#768]
Hi, movenet has pretty good performance and accuracy. So I wanna deploy it on my T4 gpu server. 
It accepts input tensor with 4 dims. While the first dim (batch size) cannot be larger than 1. 
At the same time, I checked the input dims of tflite model from tf.hub. It is fixed to 1 as well.
I do not know how to change the saved model to dynamic batch size or simply constant number like 10.
So could any one provide batch version of movenet or tell me how to modify by myself?

**Comment by maringeo** [comment]
If you plan to use the model only for inference, then the simplest approach is to apply the model to each tensor in the batch. To speed this up, you could wrap it in [tf.map_fn](https://www.tensorflow.org/api_docs/python/tf/map_fn) or [tf.vectorized_map](https://www.tensorflow.org/api_docs/python/tf/vectorized_map) - see documentation for tradeoffs between the two functions.

Another idea is to manually rewire the saved_model.pb, but this is very error-prone.

**Comment by flyingmrwang** [comment]
@maringeo @arghyaganguly 
Thanks for your reply. Actually, the reason I require batch inference is to increase throughput of my gpu. So after reading the doc for tf.map_fn and  tf.vectorized_map. I think they works like for loop and just vectorize to parallel simple computations rather than model inference (need time to double check though). 
And for manually rewrite the saved_model.pb. Yes, I was trying but there is no generally used method found so far. Also don't understand why it is error-prone.
Maybe another way is to migrate from gpu to cpu for multi-instance computation. 
By the way, I was always curious if models designed for edge inference (movenet for example) can be migrated to gpu server as long as I don't require such high accuracy. Or they are specific for edge device and not quite fit for production on server size which require high throughput.

**Comment by TheAnirudhan** [comment]
> @maringeo @arghyaganguly Thanks for your reply. Actually, the reason I require batch inference is to increase throughput of my gpu. So after reading the doc for tf.map_fn and tf.vectorized_map. I think they works like for loop and at most vectorize to parallel simple computations rather than model inference (need time to double check though). And for manually rewrite the saved_model.pb. Yes, I was trying but there is no generally used method found so far. Also don't understand why it is error-prone. Maybe another way is to migrate from gpu to cpu for multi-instance computation. By the way, I was always curious if models designed for edge inference (movenet for example) can be migrated to gpu server as long as I don't require such high accuracy. Or they are specific for edge device and not quite fit for production on server side which require high throughput.

Hey! I would like to do the same, to increase my GPU throughput and would like to un batch wise inference on my single GPU. Have you found any solution to that yet?
