### ISSUE TITLE
Extending the semantic search with ANN tutorial to images?

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/hub#770]
I really like the tutorial on [Semantic Search with Approximate Nearest Neighbors and Text Embeddings](https://www.tensorflow.org/hub/tutorials/tf2_semantic_approximate_nearest_neighbors). I think a sister tutorial covering the same things for images might be good for developers. 

I am skeptical about how well random projection (the dimensionality reduction technique used in the tutorial) would play out with precomputed image features (with a pre-trained network) but I am hopeful. What do you folks think?

**Comment by WGierke** [comment]
Thank you for the proposal, Sayak! We can add a comment to this issue once such a tutorial has been published.
