### ISSUE TITLE
[Feature Request] Modification of layers in tfhub models

### ISSUE THREAD

**Issue by ujjwal-researcher** [tensorflow/hub#777]
`hub.KerasLayer` object does not allow modification of existing layer parameters. This is debilitating to users who would like to use tfhub models in their own architecture with minor changes. Some specific use cases are mentioned below 

1.  Residual networks (2D and 3D) can be dilated appropriately to increase the size of feature maps and they have been known to benefit performance in tasks such as semantic segmentation and image classification such as [here](https://arxiv.org/abs/1705.09914).
2. Removing temporal pooling in 3D CNNs. In many applications such as tracking and action detection, it is of interest to remove temporal pooling to keep same number of frames in input and output. This also requires modification of layer parameters.
3. Access to intermediate activations is also important for explanability issues. This requires accessing intermediate layers which is currently not supported.
4. Access to intermediate layers is also important to utilize multiple layers of a CNN directly in cases such as FPN and in some object detectors such as MSCNN. 

I therefore believe that usability of tfhub models would increase tremendously if `hub.KerasLayer` object is allowed to be modified.

**Comment by akhorlin** [comment]
The question has been responded to on [TF Forum](https://discuss.tensorflow.org/t/modification-of-layers-in-hub-keraslayer/2508)
