### ISSUE TITLE
Error in importing the tensorflow_hub

### ISSUE THREAD

**Issue by AslanDevbrat** [tensorflow/hub#784]
My code
```
import os
from six.moves import urllib

import matplotlib.pyplot as plt
import mediapy as media
import numpy as np
from PIL import Image
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

from official.vision.beta.configs import video_classification
from official.vision.beta.projects.movinet.configs import movinet as movinet_configs
from official.vision.beta.projects.movinet.modeling import movinet
from official.vision.beta.projects.movinet.modeling import movinet_layers
from official.vision.beta.projects.movinet.modeling import movinet_model
```

I am getting error
```

ImportError                               Traceback (most recent call last)
<ipython-input-17-b6dba9fae7c3> in <module>()
      8 import tensorflow as tf
      9 import tensorflow_datasets as tfds
---> 10 import tensorflow_hub as hub
     11 
     12 from official.vision.beta.configs import video_classification

21 frames
/usr/local/lib/python3.7/dist-packages/keras/api/_v2/keras/__init__.py in <module>()
      8 import sys as _sys
      9 
---> 10 from keras import __version__
     11 from keras.api._v2.keras import activations
     12 from keras.api._v2.keras import applications

ImportError: cannot import name '__version__' from 'keras' (/usr/local/lib/python3.7/dist-packages/keras/__init__.py)

```

My TensorFlow Version is : 2.7.0-dev20210719

Can anyone help me resolve this error

**Comment by arghyaganguly** [comment]
@AslanDevbrat , please guide me to the location of the branch for Tensorflow :- 2.7.0-dev20210719.
Also , when i reproduced with latest stable release , i got no error.Please try with the below config:-
tensorflow==2.5.0
tensorflow_hub==0.12.0
Keras==2.4.3

**Comment by AslanDevbrat** [comment]
@arghyaganguly thanks for reaching out. Yeah, the problem was in those versions. I solved that issue by changing the version of the following libraries:


- `tensorflow==2.7.0-dev20210719`  to `tensorflow==2.5.0`
- `tensorflow_hub==0.12.0` # same as previous
- `keras==2.4.3` to `keras==2.5.0`
- `tensorflow_datasets==4.0.1` to `tensorflow_datasets==4.3.0 `

Actually, I was trying to this [MoViNet tutorial ](https://colab.research.google.com/github/tensorflow/models/blob/master/official/vision/beta/projects/movinet/movinet_tutorial.ipynb) In that I faced this issue
