### ISSUE TITLE
can't get access to tfhub

### ISSUE THREAD

**Issue by hsx479** [tensorflow/hub#789]
I have tried to load a tfhub model in my program,but get a connection error, and when i tried to load the model manualy, i just could't get access to  tfhub.dev, so is there any problem with the server, or something wrong with my environment?

**Comment by arghyaganguly** [comment]
@hsx479 , I am able to load models from tfhub.dev.Please find the github [gist](https://colab.research.google.com/gist/arghyaganguly/8132625a1dca77b916286e3058a8ee4d/object-detection-inference-on-tf-2-and-tf-hub.ipynb)
I have also tried loading [USE](https://tfhub.dev/google/universal-sentence-encoder/1) and [inceptiion v1's feature vector](https://tfhub.dev/google/imagenet/inception_v1/feature_vector/1) without any error in a linux env.

To help us expedite the debug process, please provide a snippet of your code with the model  link for which the problem occurs.

**Comment by arghyaganguly** [comment]
@hsx479 , please update on your latest status.

**Comment by hsx479** [comment]
> @hsx479 , please update on your latest status.

Thank you for you reply! I think there is something wrong with my computer, I use another computer and the problem is gone!

**Comment by arghyaganguly** [comment]
@hsx479 , thank you for the update.Please close this ticket if your issue is resolved.
