### ISSUE TITLE
Add support for changing dtype of model

### ISSUE THREAD

**Issue by AyhmRB** [tensorflow/hub#790]
Hello,
I came across this issue when I was trying to fine-tune a hub model while using automatic mixed precision, it came to my attention from [this](https://github.com/tensorflow/hub/commit/27357e928160f0a29890de6aa56c656919547aa7) that you cannot change any of the model's dtypes after loading it in as it's static, and it comes to luck if the model author published a version for MAP or not.
I want to ask, are there plans of adding support for non-static dtypes? and if so when is the estimated date for it.

**Comment by akhorlin** [comment]
This is a fundamental limitation of the [TF SavedModel](https://www.tensorflow.org/guide/saved_model) format used to serialize a model. There are long-term options under discussions but nothing that can land in the immediate future.
