### ISSUE TITLE
"UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape." for TFHub BERT encoder

### ISSUE THREAD

**Issue by HannaLochOlszewska** [tensorflow/hub#791]
Hi,
I'm using a saved-down BERT encoder (https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/2) inside a TimeDistributed Keras layer and it keeps throwing me the following error out of gradient_tape:
`UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.`
Is it anything I can do with it as a user? Or I correctly assume that's on the side of the saved-down BERT model?
Thanks in advance!

**Comment by arghyaganguly** [comment]
@HannaLochOlszewska , please provide a snippet of your code to help us understand the part where you are facing this warning.
It is a warning than an actual error.If it is not killing your training/retraining,it is safe to ignore it.
To suppress warnings, you might try out :- 
a) use the below code before your tensorflow imports -
 
 ```
 import warnings
warnings.filterwarnings('ignore')
```
or
b)
 ```
import logging
tf.get_logger().setLevel(logging.ERROR)
 ```

**Comment by arghyaganguly** [comment]
@HannaLochOlszewska  , please update on your latest status.

**Comment by arghyaganguly** [comment]
@HannaLochOlszewska , closing this as there has been no response for sometime.Please feel free to reopen if required.
