### ISSUE TITLE
Movenet in wild multi person

### ISSUE THREAD

**Issue by aafaqin** [tensorflow/hub#792]
Can someone help how to do inference on movement pose estimation if multi person are there in the same frame nearby?
Is there a way to get 3D pose estimation data like VideoPose3D(FAIR)

**Comment by yuhuichen1015** [comment]
Thanks for your interest in using MoveNet. Yes, we are in the process of releasing MoveNet.Multipose model that can detect multiple people at the same time. The targeted release date is 8/17/2021. The model will be available on tf.hub by then. We'll keep you posted about it.

**Comment by BenjaminPosselt** [comment]
Hello! 
Are there any updates on the depth prediction? ^^
Would love to be able to have a 3d MoveNet.Multipose model
