### ISSUE TITLE
 Performance issues in tensorflow_hub/tools/make_nearest_neighbour_index/index_builder.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [tensorflow/hub#794]
Hello,I found some performance issues.
**The first one** is in the definition of `_infer_dimensions` ,tensorflow_hub/tools/make_nearest_neighbour_index/index_builder.py,
[tf.data.TFRecordDataset(embed_file).map](https://github.com/tensorflow/hub/blob/e2dbee5c0a503185f41c84eb5e3b0b195be9cbc4/tensorflow_hub/tools/make_nearest_neighbour_index/index_builder.py#L45) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

The same issues also exist in [dataset.map(_parse_example)](https://github.com/tensorflow/hub/blob/e2dbee5c0a503185f41c84eb5e3b0b195be9cbc4/tensorflow_hub/tools/make_nearest_neighbour_index/index_builder.py#L83) ,
[tf.data.Dataset.range(5).map](https://github.com/tensorflow/hub/blob/e2dbee5c0a503185f41c84eb5e3b0b195be9cbc4/examples/mnist_export_v2/export_test.py#L35)

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

**The socond one** is in thedefinition of `build_eval_session`,.
[eval_sess = tf.Session(graph=eval_graph)](https://github.com/tensorflow/hub/blob/e2dbee5c0a503185f41c84eb5e3b0b195be9cbc4/examples/image_retraining/retrain.py#L883)  was repeatedly called and was not closed.
I think it will increase the efficiency and avoid out of memory if you close this session after using it.

Here are two files to support this issue,[support1](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/Session.html#close) and [support2](https://stackoverflow.com/questions/48051647/tensorflow-how-to-perform-image-categorisation-on-multiple-images)

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by MorganR** [comment]
Hello @DLPerf, welcome to TF Hub! These seem like reasonable things to fix, though note that the `image_retraining` tool is considered deprecated.

You're welcome to file a PR to address these changes so that we can review it.

**Comment by UsharaniPagadala** [comment]
@DLPerf 
Could you please confirm if the changes requested in the [PR](https://github.com/tensorflow/hub/pull/802) have done.Thanks

**Comment by WGierke** [comment]
Closing since https://github.com/tensorflow/hub/pull/843 was submitted. Thank you!
