### ISSUE TITLE
Issue with caching

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/hub#807]
There seems to be a caching issue for the BERT models (including the preprocessors and the encoders). I am referring to the BERT models mentioned in this blog post: https://blog.tensorflow.org/2020/12/making-bert-easier-with-preprocessing-models-from-tensorflow-hub.html. 

For reproducing this issue, one can run code from any of the tutorials mentioned in the above blog post. 

The error is as follows:

```
OSError: SavedModel file does not exist at: /var/folders/z_/d29z43w90kz6f4kbzv5c9m9r0000gn/T/tfhub_modules/602d30248ff7929470db09f7385fc895e9ceb4c0/{saved_model.pbtxt|saved_model.pb}
```

The issue seems to go after rerunning the code from scratch. Is there a better workaround?

**Comment by pindinagesh** [comment]
@sayakpaul 

Could you please refer the similar issues [link1](https://github.com/tensorflow/tensorflow/issues/22480) and [link2](https://stackoverflow.com/questions/61699140/oserror-savedmodel-file-does-not-exist-at-dnn-mpg-model-h5-saved-model-pbt), and let us know if it helps. Thanks

**Comment by sayakpaul** [comment]
They do not.

**Comment by akhorlin** [comment]
Running colabs mentioned in https://blog.tensorflow.org/2020/12/making-bert-easier-with-preprocessing-models-from-tensorflow-hub.html on CPU, GPU and TPU (for advanced example) works. The issue might have been resolved. If you still see the issue, please let us know.
