### ISSUE TITLE
TFHub "Updated" field for any model is always set to a current date

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/hub#810]
TFHub "Updated" field for any model is always set to a current date  
This makes it impossible to see which models are recently added or updated

I addition, I suggest to add "First published" field as well

**Comment by vladmandic** [comment]
@akhorlin Ping since no update - this impacts usability of TFHub a lot (espenially given its recent growth) since there is no way to see which models are new (in many cases there are new and old variants of the same model)

Also, how come issue is marked as type:support` when it's clearly a product issue and nothing to do with support?

**Comment by WGierke** [comment]
#859 is a superset of this issue. Will close this one.
