### ISSUE TITLE
Non-deterministic inference for MobileBERT models

### ISSUE THREAD

**Issue by thisisjoshstone** [tensorflow/hub#811]
Hello!

I'm running into some issues with determinism at inference time for the MobileBERT tfhub-hosted models. Even after setting `trainable`/`training` kwargs to `False`, I'm finding that the model output can be slightly different for each run. I'm seeing differences between a pair of runs about 70-80% of the time, I'd guess.

The issue may be related to batching, as a number of issues related to non-determinism are (https://github.com/tensorflow/hub/issues/760, https://github.com/tensorflow/hub/issues/658) because I haven't been able to reproduce this behavior for inference on a single example. However, the discrepancies between runs don't seem to be tied to a particular instance (e.g. the _first_ instance).

Standalone example:
```
Python 3.8.12 (default, Aug 31 2021, 04:08:54) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow_hub as hub; import tensorflow_text as text; import tensorflow_datasets as tfds; import numpy as np

In [2]: data = tfds.as_dataframe(tfds.load('wikipedia/20201201.en', split='train[:500]'))
2021-10-12 17:01:41.060950: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-10-12 17:01:41.105245: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)

In [3]: text = [x.decode() for x in data['text']]

In [4]: preprocessor = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_multi_cased_preprocess/3', trainable=False)

In [5]: mobilebert = hub.KerasLayer('https://tfhub.dev/tensorflow/mobilebert_multi_cased_L-24_H-128_B-512_A-4_F-4_OPT/1', trainable=False)

In [6]: tokens = preprocessor(text)

In [7]: out1 = mobilebert(tokens, training=False)

In [8]: out2 = mobilebert(tokens, training=False)

In [9]: (out1['sequence_output'] == out2['sequence_output']).numpy().all()
Out[9]: False

In [10]: out1['sequence_output'].shape
Out[10]: TensorShape([500, 128, 512])

In [11]: n = 500 * 128 * 512

In [12]: np.isclose(out1['sequence_output'], out2['sequence_output'], atol=1e-8).sum() / n
Out[12]: 0.9247514953613282

In [13]: np.isclose(out1['sequence_output'], out2['sequence_output'], atol=1e-5).sum() / n
Out[13]: 0.9986796569824219

In [14]: out1['sequence_output'].numpy()[0, 0, :20]
Out[14]: 
array([ 3.0125302e+07, -3.0325088e+07,  5.2809875e+06, -3.0241195e+06,
        2.1857081e+05, -2.5145612e+07,  1.1009095e+07,  3.5610953e+05,
       -1.8388678e+06,  1.7959348e+05,  1.3435962e+05,  2.2917802e+06,
        8.1790590e+06, -2.0771199e+06, -5.2795070e+06, -2.2314192e+05,
       -9.2535694e+05, -3.7628302e+06,  4.9339680e+07,  4.4200164e+04],
      dtype=float32)

In [15]: out2['sequence_output'].numpy()[0, 0, :20]
Out[15]: 
array([ 3.0125312e+07, -3.0325100e+07,  5.2809895e+06, -3.0241222e+06,
        2.1856905e+05, -2.5145616e+07,  1.1009097e+07,  3.5610888e+05,
       -1.8388689e+06,  1.7959197e+05,  1.3436147e+05,  2.2917812e+06,
        8.1790595e+06, -2.0771199e+06, -5.2795090e+06, -2.2314170e+05,
       -9.2535888e+05, -3.7628325e+06,  4.9339696e+07,  4.4200629e+04],
      dtype=float32)
```

I've observed the same behavior for [MobileBERT en-uncased](https://tfhub.dev/tensorflow/mobilebert_en_uncased_L-24_H-128_B-512_A-4_F-4_OPT/1). However, this does not seem to be an issue for the BERT models generally, at least as far as I can tell testing [this version](https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/4) a few times.

Any ideas for how to make the models behave deterministically?

System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina (10.15.7)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- Python version: 3.8.12
- TF/TF-hub version: 2.5.0/0.12.0
- Installed using virtualenv? pip? conda?: virtualenv
- GPU model and memory: n/a

**Comment by thisisjoshstone** [comment]
@pindinagesh @MorganR Not sure what if anything can be done here, but just wanting to follow up to see if there are any potential answers. Tested again this morning and observed the same behavior.

**Comment by maringeo** [comment]
Thank you @thisisjoshstone for the detailed report. I was able to repro this on Colab (CPU) and I've reached to the model authors to clarify whether this behavior is expected. I'll update this thread once I hear back from them.

**Comment by thisisjoshstone** [comment]
@maringeo Just checking in here -- did you ever receive word back from the model authors?

**Comment by akhorlin** [comment]
Unfortunately, the author of the model could not be reached. I tried the code above with batches 50, 100, 200, and 300 (500, or even >400, was OOMing my colab's runtime) and the results matched. So it may be the case of some fixes in core TF or behavior that is dependent on particular CPU architecture. The code was run under TF 2.8.2
