### ISSUE TITLE
Regarding Keypoints for joint angles in MoveNet

### ISSUE THREAD

**Issue by Adhithiyan03** [tensorflow/hub#812]
Hi,

I am using the MoveNet Thunder model for pose-estimation and used the model on google colab for calculating the keypoints of the estimated markers. 
I, then used the markers to calculate the joint angles of the knee and Hip.
The angles and the graph which I got from the markers are good enough but the values of the angles are differing by 20 degrees at the maximum
![image (6)](https://user-images.githubusercontent.com/83748642/137173260-24b8cbd6-1423-4e7e-8064-37c505e84740.png)
.
In the fig, the angle estimated is coming roughly around 60 degrees, but we were getting around 40 degrees as the maxmimum.
![image (4)](https://user-images.githubusercontent.com/83748642/137172247-09fee3fc-8ead-4faa-9fb2-dd71a24a7a1a.png)
Please refer the above diagram for better understanding.

At first, we thought that we had calculated it wrong but then we realised that it had something to do with MoveNet code.
I have also attached the marker file we got.

[sample5boy_movenet-Thunder.csv](https://github.com/tensorflow/hub/files/7339857/sample5boy_movenet-Thunder.csv)

Please look into and resolve the matter as soon as possible

**Comment by yuhuichen1015** [comment]
Hi,

Sorry I'm a bit confused about the issue. Could you help me answer the following questions?

1) When you say "differing by 20 degrees", what is the "groundtruth" angles you are comparing with? It seems like there are three possible values:
    a) The angle measured directly from the image/keypoint visualizations as the image you attached.
    b) The angle computed using the MoveNet keypoint locations.
    c) The angle computed using the OpenPose keypoint locations.

2) When you say "realized that it had something to do with MoveNet code", could you elaborate what exactly that makes you think there is something wrong in the code? For example:
   a) Does the MoveNet model give you inaccurate/biased keypoint predictions? If so, did you notice it by visualizing the keypoint? Could you share the example image with us?

3)  MoveNet model has no notion about the joint angles but just to predict where it believes the keypoints are. If your lgoic is to estimate the joint angle from the keypoint coordinates and you are getting different values between different models, I'd recommend double checking whether the two models share the same coordination systems, e.g. whether they produce absolute coordinate/normalized coordinate. If it is the latter, does your logic multiply the image height/width to the normalized coordinates to get the absolute coordinates back?

Thanks,
Yu-Hui
