### ISSUE TITLE
How to server the sentiment classifier 

### ISSUE THREAD

**Issue by bsat007** [tensorflow/hub#82]
https://github.com/tensorflow/hub/blob/master/examples/colab/text_classification_with_tf_hub_on_kaggle.ipynb

I want to write `serving_input_receiver_fn` for this task, and want to predict the sentiment of an input sentence. 

I am new to Tensorflow, this is how I've tried. 

```
def serving_input_receiver_fn():
    example_bytestring = tf.placeholder(
      shape=[None],
      dtype=tf.string,
    )
    features = tf.parse_example(
      example_bytestring,
      tf.feature_column.make_parse_example_spec([embedded_text_feature_column])
    )
    return tf.estimator.export.ServingInputReceiver(
      features, {'sentence': example_bytestring})

export_dir = estimator.export_savedmodel(
    export_dir_base="modelExport",
    serving_input_receiver_fn=serving_input_receiver_fn)
```

How do I do that?

**Comment by vbardiovskyg** [comment]
Hi,

this tutorial contains an end to end example: [GCP estimator tutorial](https://github.com/GoogleCloudPlatform/tf-estimator-tutorials/blob/master/08_Text_Analysis/05%20-%20Text%20Classification%20-%20Hacker%20News%20-%20End-to-End%20%2B%20TF-Hub%20Sentence%20Embedding.ipynb).
