### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Mohammedirfan25** [tensorflow/hub#820]
![Screenshot at 2021-11-01 20-31-51](https://user-images.githubusercontent.com/55286282/139695400-ee05bb5d-bf54-4ebc-89d5-739c5cf939db.png)

![Screenshot at 2021-11-01 20-56-47](https://user-images.githubusercontent.com/55286282/139696850-aa15f6ec-e3c5-4a3b-8bab-c148e1d26448.png)

![Screenshot at 2021-11-01 20-55-10](https://user-images.githubusercontent.com/55286282/139696637-5ec04ef6-0b70-4323-9115-488a187a1a62.png)

i am using latest tensorflow and i am getting error. kindly help me to fix this issue.
i saw some fixes they said me to use tensorflow version 1.5 but i have to use tensorflow version 2 is there any other ways to fix it?

**Comment by WGierke** [comment]
Try downgrading tensorflow-estimator to 2.6.0. If you use pip, run
`pip install -U tensorflow-estimator==2.6.0`
as described in #819.

**Comment by Mohammedirfan25** [comment]
Thank you for your response. I will try.

**Comment by Mohammedirfan25** [comment]
![Screenshot at 2021-11-02 09-39-01](https://user-images.githubusercontent.com/55286282/139785625-b2b3747b-b6ec-4e9e-9879-e85f51c300e3.png)
it doesn't work.

**Comment by pindinagesh** [comment]
@Mohammedirfan25 

Could you please move this to closed status as it is resolved. Thanks
