### ISSUE TITLE
TensorflowHub Citation

### ISSUE THREAD

**Issue by MarkKocherovsky** [tensorflow/hub#825]
Hello,

I would like to know if TF Hub has its own paper to cite or preferred citation (preferably in BibTex format). If not, then should we cite TF using the guidlines given [here](https://www.tensorflow.org/about/bib)?

Thank you.

**Comment by akhorlin** [comment]
There is no stand-alone paper covering TF Hub. Citing TF should be ok in
this case.

**Comment by MarkKocherovsky** [comment]
Alright, thank you!
