### ISSUE TITLE
Dead link in https://tfhub.dev/deepmind/mmt

### ISSUE THREAD

**Issue by LaurentBerger** [tensorflow/hub#827]
Hi
I think there is a dead link in https://tfhub.dev/deepmind/mmt/architecture_heads6-64/1 and all similar link https://tfhub.dev/deepmind/mmt/* for colab link

![image](https://user-images.githubusercontent.com/3591626/143720954-9ad93a73-ce9d-481d-b057-5ec39dece9e6.png)
_Overview

Code given something is wrong with newline?
![image](https://user-images.githubusercontent.com/3591626/143720984-ebe3e2ff-88d4-4c22-ab8d-fb2d7c8ddf2f.png)

and variable name  is it m or model?
![image](https://user-images.githubusercontent.com/3591626/143721003-41fe606e-1da1-4eef-8a4f-d4cee5ab99f5.png)

**Comment by akhorlin** [comment]
DeepMind folks are still in the process to publish a colab at this location.

**Comment by WGierke** [comment]
FYI the repo is now live :) https://github.com/deepmind/multimodal_transformers
