### ISSUE TITLE
Can't import tensorflow_hub

### ISSUE THREAD

**Issue by mcandemir** [tensorflow/hub#829]
Looks like I have some compatibility issues but couldn't find what causes this.

Main problem:
`AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'monitoring'
`
<br>
I use:

- tensorflow == 2.4.1
- tensorflow-base == 2.4.1
- tensorflow-estimator == 2.6.0
- tensorflow-gpu == 2.4.1
- tensorflow-hub == 0.7.0

I can also share the full traceback if needed..
Grateful for any feedbacks!

**Comment by WGierke** [comment]
When trying to install tensorflow-estimator v2.6.0 with TF 2.4.1 like you have, I'm getting
`tensorflow 2.4.1 requires tensorflow-estimator<2.5.0,>=2.4.0, but you have tensorflow-estimator 2.6.0 which is incompatible`. Can you try installing a different estimator version? If that doesn't help, would you mind sharing the full traceback?

**Comment by mcandemir** [comment]
I have downgraded my `tensorflow-estimator` from v2.6 to v2.4.1, and no issues encountered. Thanks!
