### ISSUE TITLE
unable to import tensorflow hub

### ISSUE THREAD

**Issue by muhammadmehranbinazam** [tensorflow/hub#830]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ae25cc1fd345> in <module>
      1 import tensorflow as tf
----> 2 import tensorflow_hub as hub

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_hub\__init__.py in <module>
     86 
     87 
---> 88 from tensorflow_hub.estimator import LatestModuleExporter
     89 from tensorflow_hub.estimator import register_module_for_export
     90 from tensorflow_hub.feature_column import image_embedding_column

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_hub\estimator.py in <module>
     59 
     60 
---> 61 class LatestModuleExporter(tf.compat.v1.estimator.Exporter):
     62   """Regularly exports registered modules into timestamped directories.
     63 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in __getattr__(self, item)
     60 
     61   def __getattr__(self, item):
---> 62     module = self._load()
     63     return getattr(module, item)
     64 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in _load(self)
     43     """Load the module and insert it into the parent's globals."""
     44     # Import the target module and insert it into the parent's namespace
---> 45     module = importlib.import_module(self.__name__)
     46     self._parent_module_globals[self._local_name] = module
     47 

C:\ProgramData\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1 import estimator
     11 
     12 del _print_function

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1.estimator import experimental
     11 from tensorflow_estimator._api.v1.estimator import export
     12 from tensorflow_estimator._api.v1.estimator import inputs

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
     11 from tensorflow_estimator.python.estimator.canned.kmeans import KMeansClustering as KMeans
     12 from tensorflow_estimator.python.estimator.canned.linear import LinearSDCA

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn.py in <module>
     27 from tensorflow_estimator.python.estimator import estimator
     28 from tensorflow_estimator.python.estimator.canned import head as head_lib
---> 29 from tensorflow_estimator.python.estimator.canned import optimizers
     30 from tensorflow_estimator.python.estimator.head import head_utils
     31 from tensorflow_estimator.python.estimator.head import regression_head

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\canned\optimizers.py in <module>
     32 
     33 _OPTIMIZER_CLS_NAMES_V2 = {
---> 34     'Adagrad': tf.keras.optimizers.Adagrad,
     35     'Adam': tf.keras.optimizers.Adam,
     36     'Ftrl': tf.keras.optimizers.Ftrl,

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in __getattr__(self, item)
     60 
     61   def __getattr__(self, item):
---> 62     module = self._load()
     63     return getattr(module, item)
     64 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in _load(self)
     43     """Load the module and insert it into the parent's globals."""
     44     # Import the target module and insert it into the parent's namespace
---> 45     module = importlib.import_module(self.__name__)
     46     self._parent_module_globals[self._local_name] = module
     47 

C:\ProgramData\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
     23 
     24 # See b/110718070#comment18 for more details about this import.
---> 25 from keras import models
     26 
     27 from keras.engine.input_layer import Input

C:\ProgramData\Anaconda3\lib\site-packages\keras\models.py in <module>
     17 
     18 import tensorflow.compat.v2 as tf
---> 19 from keras import backend
     20 from keras import metrics as metrics_module
     21 from keras import optimizer_v1

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in <module>
     23 from distutils.version import StrictVersion
     24 
---> 25 from ..utils.generic_utils import transpose_shape
     26 
     27 py_all = all

ImportError: cannot import name 'transpose_shape' from 'keras.utils.generic_utils' (C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\generic_utils.py)

**Comment by WGierke** [comment]
What versions of tensorflow, tensorflow_hub and keras are you using?

**Comment by pindinagesh** [comment]
@muhammadmehranbinazam 

We see that you are using old version of tensorflow, tensorflow_hub and keras, We recommend that you upgrade to newer versions of tensorflow, tensorflow_hub and keras and let us know if this issue still persists in newer versions. Thanks!
