### ISSUE TITLE
cannot import tensorflow hub

### ISSUE THREAD

**Issue by SleepwellWorkhard** [tensorflow/hub#836]
ImportError: cannot import name 'MomentumParameters' from 'tensorflow.python.tpu.tpu_embedding'

**Comment by pindinagesh** [comment]
@SleepwellWorkhard 

What versions of Python, TensorFlow and tensorflow_hub are you using?

**Comment by pindinagesh** [comment]
@SleepwellWorkhard 

Closing this issue. Please feel free to reopen if this still persists, and also refer [this.](https://github.com/tensorflow/hub/issues/819) Thanks
