### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'outer_context' when building a token classification model

### ISSUE THREAD

**Issue by popkristina** [tensorflow/hub#838]
Hi, I am training a token-classification model, and I use ELMO embeddings as one layer of my model.

I'm using elmo embeddings from tensorflow hub, and I am using them with tensorflow 2.7.0. The same model architecture worked when built in Tensorflow 1.x, but I need to migrate it to TF2. I followed the instructions on how to replace hub.Module() with hub.load() in order to use elmo in TF2. The example below is with hub.load(). 

Please note that the same model architecture worked in TF1, but I need a solution to make it work in TF2. The model is built properly, but the error occurs when calling model.fit 

This is how I'm building the model: 

```
def ElmoEmbedding(x):
    return elmo_model.signatures["tokens"](tokens = tf.squeeze(tf.cast(x, tf.string)), sequence_len = tf.constant(batch_size * [max_len]))["elmo"]

def build_model(max_len, n_words, n_tags): 
    word_input_layer = Input(shape=(max_len, 40, ))
    elmo_input_layer = Input(shape=(max_len,), dtype=tf.string)
    word_output_layer = Dense(n_tags, activation = 'softmax')(word_input_layer)
    elmo_output_layer = Lambda(ElmoEmbedding, output_shape=(None, 1024))(elmo_input_layer)

    output_layer = Concatenate()([word_output_layer, elmo_output_layer])
    output_layer = BatchNormalization()(output_layer)
    output_layer = Bidirectional(LSTM(units=512, return_sequences=True, recurrent_dropout=0.2, dropout=0.2))(output_layer)
    output_layer = TimeDistributed(Dense(n_tags, activation='softmax'))(output_layer)
    
    model = Model([elmo_input_layer, word_input_layer], output_layer)
    
    return model
```

And therefore want to train the model as follows:
```
elmo_model = hub.load('https://tfhub.dev/google/elmo/3')
model = build_model(max_len, n_words, n_tags)
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

history = model.fit([np.array(X1_train), np.array(X2_train).reshape((len(X2_train), max_len, 40))], 
                    y_train, 
                    validation_data=([np.array(X1_valid), np.array(X2_valid).reshape((len(X2_valid), max_len, 40))], y_valid),
                    batch_size=32, epochs=2, verbose=1)
```

To clarify, X1_train is a list of tokenized sentences and X2_train is a list of hand-picked features for every token in every sentence. 

The error that I'm getting when calling model.fit is the following one:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-7173cff2a6ea> in <module>
     55                     y_train,
     56                     validation_data=([np.array(X1_valid), np.array(X2_valid).reshape((len(X2_valid), max_len, 40))], y_valid),
---> 57                     batch_size=32, epochs=2, verbose=1)
     58 hist = pd.DataFrame(history.history)

/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

AttributeError: in user code:

    File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 808, in train_step
        y_pred = self(x, training=True)
    File "/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "<ipython-input-15-adbacb2acf37>", line 8, in ElmoEmbedding
        return elmo_model.signatures["tokens"](tokens = tf.squeeze(tf.cast(x, tf.string)), sequence_len = tf.constant(batch_size * [max_len]))["elmo"]

    AttributeError: Exception encountered when calling layer "lambda_2" (type Lambda).
    
    'NoneType' object has no attribute 'outer_context'
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(32, 300), dtype=string)
      • mask=None
      • training=True
```
Is it possible that I can't train a model with ELMO layer in TF 2 at all?

Any tips would help!

**Comment by akhorlin** [comment]
Unfortunately TF1 models cannot be fine-tuned in TF2, so training=True option is not supported. At this time, the authors of Elmo are not planning to release TF2 version of the model (https://github.com/tensorflow/hub/issues/644).

As a work-around, you could try using one of the smaller TF2 BERTs from https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/2

**Comment by popkristina** [comment]
Thank you!

**Comment by sara-02** [comment]
@popkristina @akhorlin I am still facing this issue even with `training=False`, I tried this notebook in colab withhttps://github.com/tensorflow/hub/blob/master/examples/colab/tf2_text_classification.ipynb with 
```
tf Version:  2.7.0
Eager mode:  True
Hub version:  0.12.0
```
and getting the following error
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

AttributeError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 816, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 531, in minimize
        loss, var_list=var_list, grad_loss=grad_loss, tape=tape)
    File "/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 583, in _compute_gradients
        grads_and_vars = self._get_gradients(tape, loss, var_list, grad_loss)
    File "/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 464, in _get_gradients
        grads = tape.gradient(loss, var_list, grad_loss)

    AttributeError: 'NoneType' object has no attribute 'outer_context'

**Comment by sara-02** [comment]
A quick update I was able to eventually run the setup but with "trainable=False" for Elmo and disabling eager execution
