### ISSUE TITLE
Unable to load modules, URL "does not appear to be a valid module"

### ISSUE THREAD

**Issue by bbartoldson** [tensorflow/hub#84]
I get an error trying to import hub modules with [code provided by TensorFlow](https://www.tensorflow.org/hub/modules/google/elmo/2). I'm using tensorflow-gpu 1.8 installed from binary on Ubuntu. 

**Update** I can load modules with tensorflow 1.8 on macOS now, but I still have the issue with the Ubuntu setup.

I was able to successfully import and use hub modules in the past, so I'm not sure what changed to cause the errors. Here's the code and error that's generated on the Ubuntu setup:

```python
import tensorflow as tf
import tensorflow_hub as hub
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
```

INFO:tensorflow:Downloading TF-Hub Module 'https://tfhub.dev/google/elmo/2'.

ValueError                                Traceback (most recent call last)
~/anaconda3/lib/python3.6/tarfile.py in nti(s)
    188             s = nts(s, "ascii", "strict")
--> 189             n = int(s.strip() or "0", 8)
    190         except ValueError:

ValueError: invalid literal for int() with base 8: '"text/ht'

During handling of the above exception, another exception occurred:

InvalidHeaderError                        Traceback (most recent call last)
~/anaconda3/lib/python3.6/tarfile.py in next(self)
   2294             try:
-> 2295                 tarinfo = self.tarinfo.fromtarfile(self)
   2296             except EOFHeaderError as e:

~/anaconda3/lib/python3.6/tarfile.py in fromtarfile(cls, tarfile)
   1090         buf = tarfile.fileobj.read(BLOCKSIZE)
-> 1091         obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
   1092         obj.offset = tarfile.fileobj.tell() - BLOCKSIZE

~/anaconda3/lib/python3.6/tarfile.py in frombuf(cls, buf, encoding, errors)
   1032 
-> 1033         chksum = nti(buf[148:156])
   1034         if chksum not in calc_chksums(buf):

~/anaconda3/lib/python3.6/tarfile.py in nti(s)
    190         except ValueError:
--> 191             raise InvalidHeaderError("invalid header")
    192     return n

InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

ReadError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/resolver.py in download_and_uncompress(filename, fileobj, dst_path)
    104   try:
--> 105     with tarfile.open(mode="r|*", fileobj=fileobj) as tgz:
    106       for tarinfo in tgz:

~/anaconda3/lib/python3.6/tarfile.py in open(cls, name, mode, fileobj, bufsize, **kwargs)
   1598             try:
-> 1599                 t = cls(name, filemode, stream, **kwargs)
   1600             except:

~/anaconda3/lib/python3.6/tarfile.py in __init__(self, name, mode, fileobj, format, tarinfo, dereference, ignore_zeros, encoding, errors, pax_headers, debug, errorlevel, copybufsize)
   1479                 self.firstmember = None
-> 1480                 self.firstmember = self.next()
   1481 

~/anaconda3/lib/python3.6/tarfile.py in next(self)
   2306                 elif self.offset == 0:
-> 2307                     raise ReadError(str(e))
   2308             except EmptyHeaderError:

ReadError: invalid header

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-13-6e0d5645526c> in <module>()
----> 1 elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/module.py in __init__(self, spec, trainable, name, tags)
    103     """
    104     self._graph = tf.get_default_graph()
--> 105     self._spec = as_module_spec(spec)
    106     self._trainable = trainable
    107 

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/module.py in as_module_spec(spec)
     29     return spec
     30   elif isinstance(spec, str):
---> 31     return native_module.load_module_spec(spec)
     32   else:
     33     raise ValueError("Unknown module spec type: %r" % type(spec))

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/native_module.py in load_module_spec(path)
     97     tf.OpError: on file handling exceptions.
     98   """
---> 99   path = compressed_module_resolver.get_default().get_module_path(path)
    100   module_def_path = _get_module_proto_path(path)
    101   module_def_proto = module_def_pb2.ModuleDef()

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/resolver.py in get_module_path(self, handle)
    383     """
    384     if self.is_supported(handle):
--> 385       return self._get_module_path(handle)
    386     else:
    387       raise UnsupportedHandleError(

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/resolver.py in _get_module_path(self, handle)
    465       raise UnsupportedHandleError(
    466           self._create_unsupported_handle_error_msg(handle))
--> 467     return resolver.get_module_path(handle)
    468 
    469   def _create_unsupported_handle_error_msg(self, handle):

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/resolver.py in get_module_path(self, handle)
    383     """
    384     if self.is_supported(handle):
--> 385       return self._get_module_path(handle)
    386     else:
    387       raise UnsupportedHandleError(

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py in _get_module_path(self, handle)
    103 
    104     return resolver.atomic_download(handle, download, module_dir,
--> 105                                     self._lock_file_timeout_sec())
    106 
    107   def _lock_file_timeout_sec(self):

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/resolver.py in atomic_download(handle, download_fn, module_dir, lock_file_timeout_sec)
    311     tf.logging.info("Downloading TF-Hub Module '%s'.", handle)
    312     tf.gfile.MakeDirs(tmp_dir)
--> 313     download_fn(handle, tmp_dir)
    314     # Write module descriptor to capture information about which module was
    315     # downloaded by whom and when. The file stored at the same level as a

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py in download(handle, tmp_dir)
    100       url_opener = url.build_opener(LoggingHTTPRedirectHandler)
    101       response = url_opener.open(request)
--> 102       return resolver.download_and_uncompress(cur_url, response, tmp_dir)
    103 
    104     return resolver.atomic_download(handle, download, module_dir,

~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/resolver.py in download_and_uncompress(filename, fileobj, dst_path)
    124               "Unexpected object type in tar archive: %s" % tarinfo.type)
    125   except tarfile.ReadError:
--> 126     raise IOError("%s does not appear to be a valid module." % filename)
    127 
    128 def _module_descriptor_file(module_dir):

OSError: https://tfhub.dev/google/elmo/2 does not appear to be a valid module.

**Comment by bbartoldson** [comment]
The Ubuntu machine was on a server, and its error messages were the result of my failure to put my credentials into a browser upon logging in to the server. The server couldn't connect to external sites without these credentials, which meant python couldn't download from tfhub.

**Comment by victorup** [comment]
I got the same question: "OSError: https://tfhub.dev/google/elmo/2 does not appear to be a valid module."
Have you solved the problem?

**Comment by imamslogic** [comment]
import tensorflow_hub as hub
elmo = hub.load("https://tfhub.dev/google/elmo/2")

let me know if that doesn't work
