### ISSUE TITLE
error:import tensorflow_hub

### ISSUE THREAD

**Issue by ligh2012** [tensorflow/hub#844]
tensorflow=2.4.1
tensorflow_hub=0.11.0

error:
AttributeError: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'monitoring'

**Comment by WGierke** [comment]
Please try upgrading TensorFlow to 2.8 as proposed by https://github.com/tensorflow/tensorflow/issues/54286#issuecomment-1031205739.
