### ISSUE TITLE
Bug: tfhub_module.pb does not exist for Universal Sentence Encoder

### ISSUE THREAD

**Issue by PythonJDoe** [tensorflow/hub#849]
### What happened?

I'm running python in Jupyter Lab 3.1.9. I would like to use Universal Sentence Encoder. Due to firewall setting I couldn't able to run the following command
`embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual/3")`
So I have downloaded the TF2.0 Saved Model (v3) & uploaded it on Jupyter Lab. Then I ran following command to unzip the file
```
import tarfile
file=tarfile.open('./universal-sentence-encoder-multilingual_3.tar.gz')
file.extractall('./Multilingual1')
```
Then I use following command to load the file

```
import tensorflow_hub as hub
embed = hub.Module("./Multilingual1")
```
But I got following error
`NotFoundError: ./Multilingual1/tfhub_module.pb; No such file or directory`
After unzipping universal-sentence-encoder-multilingual_3.tar.gz I couldn't find tfhub_module.pb in my directory.

Can you suggest me steps to resolve the issue?

### Relevant code

```python
import tarfile
file=tarfile.open('./universal-sentence-encoder-multilingual_3.tar.gz')
file.extractall('./Multilingual1')
import tensorflow_hub as hub
embed = hub.Module("./Multilingual1")
```

### Relevant log output

```shell
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
/tmp/ipykernel_2011/1867839697.py in <module>
      1 import tensorflow_hub as hub
      2 #embed = hub.Module("./Multilingual/universal-sentence-encoder-multilingual_3.tar.gz")
----> 3 embed = hub.Module("./Multilingual1")
      4 
      5 #embed = hub.Module("universal-sentence-encoder-multilingual_3.tar.gz")

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in __init__(self, spec, trainable, name, tags)
    155     """
    156     self._graph = tf.compat.v1.get_default_graph()
--> 157     self._spec = as_module_spec(spec)
    158     self._trainable = trainable
    159 

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in as_module_spec(spec)
     28     return spec
     29   elif isinstance(spec, str):
---> 30     return load_module_spec(spec)
     31   else:
     32     raise ValueError("Unknown module spec type: %r" % type(spec))

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in load_module_spec(path)
     63   """
     64   path = registry.resolver(path)
---> 65   return registry.loader(path)
     66 
     67 

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/registry.py in __call__(self, *args, **kwargs)
     49     for impl in reversed(self._impls):
     50       if impl.is_supported(*args, **kwargs):
---> 51         return impl(*args, **kwargs)
     52       else:
     53         fails.append(type(impl).__name__)

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/native_module.py in __call__(self, path)
    137 
    138   def __call__(self, path):
--> 139     module_def_proto = self._get_module_def_proto(path)
    140 
    141     if module_def_proto.format != module_def_pb2.ModuleDef.FORMAT_V3:

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/native_module.py in _get_module_def_proto(self, path)
    128     module_def_proto = module_def_pb2.ModuleDef()
    129     with tf.compat.v1.gfile.Open(module_def_path, "rb") as f:
--> 130       module_def_proto.ParseFromString(f.read())
    131     return module_def_proto
    132 

/opt/conda/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py in read(self, n)
    112       string if in string (regular) mode.
    113     """
--> 114     self._preread_check()
    115     if n == -1:
    116       length = self.size() - self.tell()

/opt/conda/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py in _preread_check(self)
     74         raise errors.PermissionDeniedError(None, None,
     75                                            "File isn't open for reading")
---> 76       self._read_buf = _pywrap_file_io.BufferedInputStream(
     77           compat.path_to_str(self.__name), 1024 * 512)
     78 

NotFoundError: ./Multilingual1/tfhub_module.pb; No such file or directory
```

### tensorflow_hub Version

0.12.0 (latest stable release)

### TensorFlow Version

2.8 (latest stable release)

### Python Version

3.x

### OS

Windows

**Comment by akhorlin** [comment]
The error message is expected. The model in question is a TF2 model. `hub.Module` API is a deprecated API used for TF1 models. To load TF2 models, please use `[hub.load()](https://www.tensorflow.org/hub/api_docs/python/hub/load)` or `[hub.KerasLayer](https://www.tensorflow.org/hub/api_docs/python/hub/KerasLayer)` APIs.

**Comment by PythonJDoe** [comment]
Due to firewall setting, I can't able to use hub.load(). Can you please suggest me the latest file which I can download in my system & use

**Comment by akhorlin** [comment]
`hub.load(<some local path>)` (e.g. `hub.load("./Multilingual1"))` should work. If hub.load("./Multilingual1") doesn't work, try specifying absolute path.

**Comment by PythonJDoe** [comment]
Specifying the absolute path is also not solving my issue. I don't have tfhub_module.pb file in my folder. I have downloaded the file from here https://tfhub.dev/google/universal-sentence-encoder/4. I think this is the latest file. Kindly let me know if I need to download the file from some other location

**Comment by akhorlin** [comment]
It's expected that  https://tfhub.dev/google/universal-sentence-encoder/4 doesn't have tfhub_module.pb. This file is not present for TF2 models. Please use hub.load() to load it instead of hub.Module. 

The other alternative is to use https://tfhub.dev/google/universal-sentence-encoder/2 which is an older, but functionally equivalent model in TF1 format and can be used with hub.Module API.

**Comment by PythonJDoe** [comment]
Tried both the method. For first one, I'm getting error message ----------------------------------------------------------------------```
----
NotFoundError                             Traceback (most recent call last)
/tmp/ipykernel_5524/359475816.py in <module>
      1 import tensorflow_hub as hub
      2 #embed = hub.Module("./se")
----> 3 embed = hub.Module("/home/jovyan/work/Multilingual/variables/se")

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in __init__(self, spec, trainable, name, tags)
    155     """
    156     self._graph = tf.compat.v1.get_default_graph()
--> 157     self._spec = as_module_spec(spec)
    158     self._trainable = trainable
    159 

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in as_module_spec(spec)
     28     return spec
     29   elif isinstance(spec, str):
---> 30     return load_module_spec(spec)
     31   else:
     32     raise ValueError("Unknown module spec type: %r" % type(spec))

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in load_module_spec(path)
     63   """
     64   path = registry.resolver(path)
---> 65   return registry.loader(path)
     66 
     67 

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/registry.py in __call__(self, *args, **kwargs)
     49     for impl in reversed(self._impls):
     50       if impl.is_supported(*args, **kwargs):
---> 51         return impl(*args, **kwargs)
     52       else:
     53         fails.append(type(impl).__name__)

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/native_module.py in __call__(self, path)
    137 
    138   def __call__(self, path):
--> 139     module_def_proto = self._get_module_def_proto(path)
    140 
    141     if module_def_proto.format != module_def_pb2.ModuleDef.FORMAT_V3:

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/native_module.py in _get_module_def_proto(self, path)
    128     module_def_proto = module_def_pb2.ModuleDef()
    129     with tf.compat.v1.gfile.Open(module_def_path, "rb") as f:
--> 130       module_def_proto.ParseFromString(f.read())
    131     return module_def_proto
    132 

/opt/conda/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py in read(self, n)
    112       string if in string (regular) mode.
    113     """
--> 114     self._preread_check()
    115     if n == -1:
    116       length = self.size() - self.tell()

/opt/conda/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py in _preread_check(self)
     74         raise errors.PermissionDeniedError(None, None,
     75                                            "File isn't open for reading")
---> 76       self._read_buf = _pywrap_file_io.BufferedInputStream(
     77           compat.path_to_str(self.__name), 1024 * 512)
     78 

NotFoundError: /home/jovyan/work/Multilingual/variables/se/tfhub_module.pb; No such file or directory
```

For second one again I'm getting same tfhub_module.pb; No such file or directory. Please refer below message
```
2022-04-28 12:05:06.369776: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-28 12:05:06.369806: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
/tmp/ipykernel_5844/1414757053.py in <module>
      1 import tensorflow_hub as hub
----> 2 embed = hub.Module("./SE")

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in __init__(self, spec, trainable, name, tags)
    155     """
    156     self._graph = tf.compat.v1.get_default_graph()
--> 157     self._spec = as_module_spec(spec)
    158     self._trainable = trainable
    159 

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in as_module_spec(spec)
     28     return spec
     29   elif isinstance(spec, str):
---> 30     return load_module_spec(spec)
     31   else:
     32     raise ValueError("Unknown module spec type: %r" % type(spec))

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/module.py in load_module_spec(path)
     63   """
     64   path = registry.resolver(path)
---> 65   return registry.loader(path)
     66 
     67 

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/registry.py in __call__(self, *args, **kwargs)
     49     for impl in reversed(self._impls):
     50       if impl.is_supported(*args, **kwargs):
---> 51         return impl(*args, **kwargs)
     52       else:
     53         fails.append(type(impl).__name__)

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/native_module.py in __call__(self, path)
    137 
    138   def __call__(self, path):
--> 139     module_def_proto = self._get_module_def_proto(path)
    140 
    141     if module_def_proto.format != module_def_pb2.ModuleDef.FORMAT_V3:

/opt/conda/lib/python3.9/site-packages/tensorflow_hub/native_module.py in _get_module_def_proto(self, path)
    128     module_def_proto = module_def_pb2.ModuleDef()
    129     with tf.compat.v1.gfile.Open(module_def_path, "rb") as f:
--> 130       module_def_proto.ParseFromString(f.read())
    131     return module_def_proto
    132 

/opt/conda/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py in read(self, n)
    112       string if in string (regular) mode.
    113     """
--> 114     self._preread_check()
    115     if n == -1:
    116       length = self.size() - self.tell()

/opt/conda/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py in _preread_check(self)
     74         raise errors.PermissionDeniedError(None, None,
     75                                            "File isn't open for reading")
---> 76       self._read_buf = _pywrap_file_io.BufferedInputStream(
     77           compat.path_to_str(self.__name), 1024 * 512)
     78 

NotFoundError: ./SE/tfhub_module.pb; No such file or directory
```
