### ISSUE TITLE
Warning needs be fixed: Deprecation, distutils Version classes are deprecated.

### ISSUE THREAD

**Issue by hwangdeyu** [tensorflow/hub#858]
When I run [tf2onnx ](https://github.com/onnx/tensorflow-onnx)which is using `tensorflow_hub`, there are some `DeprecationWarning` encoutered.
```
python3.9/site-packages/tensorflow_hub/__init__.py:74: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if (distutils.version.LooseVersion(tf.__version__) <
python3.9/site-packages/tensorflow_hub/__init__.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  distutils.version.LooseVersion(required_tensorflow_version)):
```

As the log shown, it may use `packaging.version` instead `packaging.version`.

**Comment by akhorlin** [comment]
The fix has been submitted (https://github.com/tensorflow/hub/commit/2e7e75a71293f3ec0c8f3c3cb0b62cc13fcc1f9a) It will pushed to the library in the next release.
