### ISSUE TITLE
Hub modules mobilenet_v2 and pnasnet_large have broken fine-tuning

### ISSUE THREAD

**Issue by arnoegw** [tensorflow/hub#86]
The following TensorFlow Hub modules are unusable for fine-tuning, that is, for use with `hub.Module(..., tags={"train"}, trainable=True)`:

  * `google/imagenet/pnasnet_large/*/1` (both types, i,e., feature_vector
     and classification),
  * `google/imagenet/mobilenet_v2_*_*/*/1` (all feature depths, sizes
     and types).

This is fixed in version /2 of the respective modules, which will be available on https://tfhub.dev/ very soon. (For documentation, please see [docs/modules/image.md](https://github.com/tensorflow/hub/blob/master/docs/modules/image.md) until the update to tensorflow.org has rolled out.)

**Hub users who seek to fine-tune of pnasnet_large or mobilenet_v2 should switch to module version /2 immediately.** For all other image modules, there is no update, and version /1 remains current.

Uses of a module without fine-tuning, notably by [examples/image_retraining/retrain.py](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py), are unaffected. Hub users doing that can update to version /2 at their leisure, with no difference expected.

The underlying technical problem with more information for module *creators* is described in issue https://github.com/tensorflow/hub/issues/85

**Comment by arnoegw** [comment]
The modules of sversion /2 are available now for use with `hub.Module("...")`.

Their documentation is available by browsing the GitHub repo in places like https://github.com/tensorflow/hub/blob/master/docs/modules/google/imagenet/mobilenet_v2_100_224/feature_vector/2.md

The documentation on tensorflow.org is not updated yet, hence the redirects through https://tfhub.dev/ do not work yet. (This includes the links found in the repo on docs/modules/image.md.) I'm keeping this issue open for this last item.

**Comment by arnoegw** [comment]
tensorflow.org/hub has been updated, and the redirects from tfhub.dev work. That completes the release of the fixed modules.

**Comment by XMK233** [comment]
Hi, arnoegw. I'm curious about what did you do to solve issue #85 . 

1. Did you add something in module_fn() to solve the tf.assign_sub() problems?

2. What are the differences between V1 and V2 modules resulting from the change you made?

Thank you very much.

**Comment by XMK233** [comment]
Hi, @arnoegw . I'm curious about what did you do to solve issue #85 .

Did you add something in module_fn() to solve the tf.assign_sub() problems?

What are the differences between V1 and V2 modules resulting from the change you made?

Thank you very much.

**Comment by arnoegw** [comment]
@XMK233 : No, I simply republished from an updated TensorFlow library with the fix mentioned in issue #85.

**Comment by XMK233** [comment]
Thank you.
