### ISSUE TITLE
Bug: Occlusion and tracking issue

### ISSUE THREAD

**Issue by SoumyajitMukherjee-droid** [tensorflow/hub#863]
### What happened?

How well the model performs in occlusion scenario and tracking scenario?

### Relevant code

```python
How well the model performs in occlusion scenario and tracking scenario?
```

### Relevant log output

```shell
How well the model performs in occlusion scenario and tracking scenario?
```

### tensorflow_hub Version

0.12.0 (latest stable release)

### TensorFlow Version

2.7

### Python Version

3.x

### OS

Windows

**Comment by singhniraj08** [comment]
@SoumyajitMukherjee-droid,

In order to expedite the trouble-shooting process, please provide more details on the issue reported here. Thank you!

**Comment by singhniraj08** [comment]
Closing as this issue is in "awaiting response" status for more than 14 days. Please post your comments(if you still have queries on this) and we will reopen this issue. Thank you!
