### ISSUE TITLE
ElMo not working

### ISSUE THREAD

**Issue by linnanwang** [tensorflow/hub#88]
Hello there,

Thank you for making TensorFlow Hub, it is an awesome tool to simplify the process. Recently I tied to use ELMO in TensorFlow Hub. However, I did the procedures online:
`elmo = hub.Module("https://tfhub.dev/google/elmo/1", trainable=True)`
This gives me 

INFO:tensorflow:Using /tmp/tfhub_modules to cache modules.
INFO:tensorflow:Initialize variable module/aggregation/scaling:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with aggregation/scaling
INFO:tensorflow:Initialize variable module/aggregation/weights:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with aggregation/weights
INFO:tensorflow:Initialize variable module/bilm/CNN/W_cnn_0:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/W_cnn_0
INFO:tensorflow:Initialize variable module/bilm/CNN/W_cnn_1:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/W_cnn_1
INFO:tensorflow:Initialize variable module/bilm/CNN/W_cnn_2:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/W_cnn_2
INFO:tensorflow:Initialize variable module/bilm/CNN/W_cnn_3:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/W_cnn_3
INFO:tensorflow:Initialize variable module/bilm/CNN/W_cnn_4:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/W_cnn_4
INFO:tensorflow:Initialize variable module/bilm/CNN/W_cnn_5:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/W_cnn_5
INFO:tensorflow:Initialize variable module/bilm/CNN/W_cnn_6:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/W_cnn_6
INFO:tensorflow:Initialize variable module/bilm/CNN/b_cnn_0:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/b_cnn_0
INFO:tensorflow:Initialize variable module/bilm/CNN/b_cnn_1:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/b_cnn_1
INFO:tensorflow:Initialize variable module/bilm/CNN/b_cnn_2:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/b_cnn_2
INFO:tensorflow:Initialize variable module/bilm/CNN/b_cnn_3:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/b_cnn_3
INFO:tensorflow:Initialize variable module/bilm/CNN/b_cnn_4:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/b_cnn_4
INFO:tensorflow:Initialize variable module/bilm/CNN/b_cnn_5:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/b_cnn_5
INFO:tensorflow:Initialize variable module/bilm/CNN/b_cnn_6:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN/b_cnn_6
INFO:tensorflow:Initialize variable module/bilm/CNN_high_0/W_carry:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_high_0/W_carry
INFO:tensorflow:Initialize variable module/bilm/CNN_high_0/W_transform:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_high_0/W_transform
INFO:tensorflow:Initialize variable module/bilm/CNN_high_0/b_carry:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_high_0/b_carry
INFO:tensorflow:Initialize variable module/bilm/CNN_high_0/b_transform:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_high_0/b_transform
INFO:tensorflow:Initialize variable module/bilm/CNN_high_1/W_carry:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_high_1/W_carry
INFO:tensorflow:Initialize variable module/bilm/CNN_high_1/W_transform:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_high_1/W_transform
INFO:tensorflow:Initialize variable module/bilm/CNN_high_1/b_carry:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_high_1/b_carry
INFO:tensorflow:Initialize variable module/bilm/CNN_high_1/b_transform:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_high_1/b_transform
INFO:tensorflow:Initialize variable module/bilm/CNN_proj/W_proj:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_proj/W_proj
INFO:tensorflow:Initialize variable module/bilm/CNN_proj/b_proj:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/CNN_proj/b_proj
INFO:tensorflow:Initialize variable module/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/bias:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/bias
INFO:tensorflow:Initialize variable module/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/kernel:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/kernel
INFO:tensorflow:Initialize variable module/bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/projection/kernel:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_0/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/projection/kernel
INFO:tensorflow:Initialize variable module/bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/bias:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/bias
INFO:tensorflow:Initialize variable module/bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel
INFO:tensorflow:Initialize variable module/bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/projection/kernel:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_0/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/projection/kernel
INFO:tensorflow:Initialize variable module/bilm/RNN_1/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/bias:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_1/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/bias
INFO:tensorflow:Initialize variable module/bilm/RNN_1/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/kernel:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_1/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/kernel
INFO:tensorflow:Initialize variable module/bilm/RNN_1/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/projection/kernel:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_1/RNN/MultiRNNCell/Cell0/rnn/lstm_cell/projection/kernel
INFO:tensorflow:Initialize variable module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/bias:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/bias
INFO:tensorflow:Initialize variable module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel
INFO:tensorflow:Initialize variable module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/projection/kernel:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/projection/kernel
INFO:tensorflow:Initialize variable module/bilm/char_embed:0 from checkpoint /tmp/tfhub_modules/0eadd30f548cbfd3065119697ded6bb381668285/variables/variables with bilm/char_embed

Then I tried this 

`
embeddings = elmo(
    ["the cat is on the mat", "dogs are in the fog"],
    signature="default",
    as_dict=True)["elmo"]

sess = tf.Session()

sess.run(elmo)
`

Then I got this error:

tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel)
	 [[Node: module_apply_default/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel/Read/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel)]]
	 [[Node: module_apply_default/bilm/add_1/ReadVariableOp/_177 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_562_module_apply_default/bilm/add_1/ReadVariableOp", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'module_apply_default/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel/Read/ReadVariableOp', defined at:
  File "<stdin>", line 4, in <module>
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow_hub/module.py", line 203, in __call__
    name=name)
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow_hub/native_module.py", line 447, in create_apply_graph
    restore_collections_predicate=(lambda key: key in import_collections))
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1955, in import_meta_graph
    **kwargs)
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 743, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 513, in import_graph_def
    _ProcessNewOps(graph)
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 303, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3540, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3428, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/data/lwang53/tensorflow-p2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Error while reading resource variable module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel)
	 [[Node: module_apply_default/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel/Read/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](module/bilm/RNN_1/RNN/MultiRNNCell/Cell1/rnn/lstm_cell/kernel)]]
	 [[Node: module_apply_default/bilm/add_1/ReadVariableOp/_177 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_562_module_apply_default/bilm/add_1/ReadVariableOp", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

I tried on 3 ubuntu machines, cuda is 9.0 and cudnn 7.0. The issue is consistent.
Any help is highly appreciated! Thank you very much!

**Comment by akhorlin** [comment]
Please try using https://tfhub.dev/google/elmo/2 (the version 2 of the
module) this version <https://www.tensorflow.org/hub/modules/google/elmo/2>
fixes the issue around making which variables are marked as trainable for
trainable=True mode that you are using.

**Comment by linnanwang** [comment]
thank you, just figured it out.
