### ISSUE TITLE
Custom implementation for Dequantize when converting .pb to .tflite

### ISSUE THREAD

**Issue by duplex143** [tensorflow/hub#89]
I'm trying to convert tensorflow quantised .pb file to .lite using toco. The command for creating .pb file is :
retrain.py is [here](https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/scripts/retrain.py) and [here](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py).
```
python retrain.py \
--bottleneck_dir=/mobilenet_q/bottlenecks \
--how_many_training_steps=4000 \
--output_graph=/mobilenet_q/retrained_graph_mobilenet_q_1_224.pb \
--output_labels=/mobilenet_q/retrained_labels_mobilenet_q_1_224.txt \
--image_dir=/data \
--architecture=mobilenet_1.0_224_quantized
```
When I'm trying to convert the .pb file to .tflite using toco command:
```
bazel run --config=opt //tensorflow/contrib/lite/toco:toco \
  -- --input_file= retrained_graph_mobilenet_q_1_224.pb \
  --output_file= retrained_graph_mobilenet_q_1_224.lite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape=1,224,224,3 \
  --input_array=input \
  --output_array=final_result \
  --inference_type=FLOAT \
  --input_data_type=FLOAT
```
I'm getting the error:
`Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.contrib.lite.toco_convert(). Here is a list of operators for which  you will need custom implementations: Dequantize.`

**Comment by akhorlin** [comment]
It looks like the discussion has moved [this issue](https://github.com/tensorflow/tensorflow/issues/20272). Please feel free to re-open the issue if that's not the case.
