### ISSUE TITLE
Bug: AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'

### ISSUE THREAD

**Issue by ming-gray** [tensorflow/hub#898]
### What happened?

I'm trying to import tensorflow_hub, module 'tensorflow_hub.tf_v1' has no attribute 'estimator'

### Relevant code

```python
import tensorflow_hub as hub
delf = hub.load('https://tfhub.dev/google/delf/1').signatures['default']
```

### Relevant log output

```shell
class LatestModuleExporter(tf_v1.estimator.Exporter):
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'
python-BaseException
```

### tensorflow_hub Version

other (please specify)

### TensorFlow Version

other (please specify)

### Other libraries

python                    3.6.13              
tb-nightly                2.11.0a20220816   
tensorboard               2.2.2          
tensorboard-data-server   0.6.1        
tensorboard-plugin-wit    1.8.1          
tensorflow                2.2.0                
tensorflow-base           2.0.0       
tensorflow-estimator      2.2.0           
tensorflow-gpu            2.2.0                   
tensorflow-hub            0.8.0             
tensorflow-probability    0.19.0         
termcolor                 1.1.0                   
tf-slim                   1.2.0    

### Python Version

3.x

### OS

Linux

**Comment by jpkrajewski** [comment]
@ming-gray How did you fix this issue?
