### ISSUE TITLE
Use TF Hub without networking?

### ISSUE THREAD

**Issue by draplater** [tensorflow/hub#90]
The module is usually big files and it is unfriendly for slow network. Is it possible to download a module as a file and install it from file?

**Comment by akhorlin** [comment]
This download already happens by default (
https://www.tensorflow.org/hub/basics). The module is downloaded into
system's temp directory. You can change the location of the download by
setting TFHUB_CACHED_DIR environment variable.

**Comment by mikefrandsen** [comment]
Minor typo - should be: TFHUB_CACHE_DIR (not CACHED)
