### ISSUE TITLE
Bug: Getting CORS issue in getting facemesh model.json

### ISSUE THREAD

**Issue by himi1203** [tensorflow/hub#902]
### What happened?

Getting CORS error in local as well as hosted environment - 

Access to fetch at 'https://tfhub.dev/mediapipe/tfjs-model/iris/1/default/2/model.json?tfjs-format=file' from origin 'http://localhost:3000' has been blocked by CORS policy

### Relevant code

```python
import * as faceLandmarksDetection from "@tensorflow-models/face-landmarks-detection";
import * as tf from "@tensorflow/tfjs-core";
require("@tensorflow/tfjs-backend-webgl");
```

### Relevant log output

```shell
Access to fetch at 'https://tfhub.dev/mediapipe/tfjs-model/iris/1/default/2/model.json?tfjs-format=file' from origin 'http://localhost:3000' has been blocked by CORS policy
```

### tensorflow_hub Version

0.13.0.dev (unstable development build)

### TensorFlow Version

2.8 (latest stable release)

### Python Version

3.x

### OS

Linux

**Comment by KeijiBranshi** [comment]
Hi @himi1203. Thanks for posting.

I'm having trouble reproducing this issue though. I don't see a CORS issue for the model resource on my hosted or local environment. 

Can you share a code fiddle that roughly mirrors your use-case? For example, here's my demo:

https://stackblitz.com/edit/vitejs-vite-rhhqe8?file=index.html

Let me know if that link works okay for you. 

Thanks!

**Comment by KeijiBranshi** [comment]
Going to close and consolidate this thread into #904. Added some investigation notes over there. Thanks again for reporting this!
