### ISSUE TITLE
Failure when running Semantic Similarity notebook

### ISSUE THREAD

**Issue by dazza5000** [tensorflow/hub#94]
The issues seems to arise here:

message_embeddings = session.run(embed(messages))

Full stacktrace:

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1306       return self._call_tf_sessionrun(
-> 1307           options, feed_dict, fetch_list, target_list, run_metadata)
   1308 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1408           self._session, options, feed_dict, fetch_list, target_list,
-> 1409           run_metadata)
   1410     else:

NotFoundError: No registered 'Size' OpKernel for GPU devices compatible with node module_2_apply_default/compound_bigrams/boolean_mask/Prod = Size[T=DT_STRING, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_2_apply_default/compound_bigrams/concat_2/_367, ^module_2_apply_default/compound_bigrams/boolean_mask/Shape_1/_371)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='CPU'; out_type in [DT_INT64]
  device='CPU'; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT32]; out_type in [DT_INT32]
  device='GPU'; T in [DT_VARIANT]; out_type in [DT_INT64]
  device='GPU'; T in [DT_VARIANT]; out_type in [DT_INT32]
  device='GPU'; T in [DT_BOOL]; out_type in [DT_INT64]
  device='GPU'; T in [DT_BOOL]; out_type in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; out_type in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; out_type in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; out_type in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT8]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT8]; out_type in [DT_INT32]
  device='GPU'; T in [DT_UINT8]; out_type in [DT_INT64]
  device='GPU'; T in [DT_UINT8]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_UINT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_UINT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT64]; out_type in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; out_type in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; out_type in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; out_type in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; out_type in [DT_INT32]
  device='GPU'; T in [DT_BFLOAT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_BFLOAT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_HALF]; out_type in [DT_INT64]
  device='GPU'; T in [DT_HALF]; out_type in [DT_INT32]

	 [[Node: module_2_apply_default/compound_bigrams/boolean_mask/Prod = Size[T=DT_STRING, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_2_apply_default/compound_bigrams/concat_2/_367, ^module_2_apply_default/compound_bigrams/boolean_mask/Shape_1/_371)]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-11-b76b84710602> in <module>()
     15 with tf.Session() as session:
     16   session.run([tf.global_variables_initializer(), tf.tables_initializer()])
---> 17   message_embeddings = session.run(embed(messages))
     18 
     19   for i, message_embedding in enumerate(np.array(message_embeddings).tolist()):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    898     try:
    899       result = self._run(None, fetches, feed_dict, options_ptr,
--> 900                          run_metadata_ptr)
    901       if run_metadata:
    902         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1133     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1134       results = self._do_run(handle, final_targets, final_fetches,
-> 1135                              feed_dict_tensor, options, run_metadata)
   1136     else:
   1137       results = []

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1314     if handle is None:
   1315       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1316                            run_metadata)
   1317     else:
   1318       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333         except KeyError:
   1334           pass
-> 1335       raise type(e)(node_def, op, message)
   1336 
   1337   def _extend_graph(self):

NotFoundError: No registered 'Size' OpKernel for GPU devices compatible with node module_2_apply_default/compound_bigrams/boolean_mask/Prod = Size[T=DT_STRING, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_2_apply_default/compound_bigrams/concat_2/_367, ^module_2_apply_default/compound_bigrams/boolean_mask/Shape_1/_371)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='CPU'; out_type in [DT_INT64]
  device='CPU'; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT32]; out_type in [DT_INT32]
  device='GPU'; T in [DT_VARIANT]; out_type in [DT_INT64]
  device='GPU'; T in [DT_VARIANT]; out_type in [DT_INT32]
  device='GPU'; T in [DT_BOOL]; out_type in [DT_INT64]
  device='GPU'; T in [DT_BOOL]; out_type in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; out_type in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; out_type in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; out_type in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT8]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT8]; out_type in [DT_INT32]
  device='GPU'; T in [DT_UINT8]; out_type in [DT_INT64]
  device='GPU'; T in [DT_UINT8]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_UINT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_UINT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT64]; out_type in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; out_type in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; out_type in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; out_type in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; out_type in [DT_INT32]
  device='GPU'; T in [DT_BFLOAT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_BFLOAT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_HALF]; out_type in [DT_INT64]
  device='GPU'; T in [DT_HALF]; out_type in [DT_INT32]

	 [[Node: module_2_apply_default/compound_bigrams/boolean_mask/Prod = Size[T=DT_STRING, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_2_apply_default/compound_bigrams/concat_2/_367, ^module_2_apply_default/compound_bigrams/boolean_mask/Shape_1/_371)]]

Caused by op 'module_2_apply_default/compound_bigrams/boolean_mask/Prod', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-b76b84710602>", line 17, in <module>
    message_embeddings = session.run(embed(messages))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_hub/module.py", line 203, in __call__
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_hub/native_module.py", line 447, in create_apply_graph
    restore_collections_predicate=(lambda key: key in import_collections))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1960, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3563, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3563, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3450, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): No registered 'Size' OpKernel for GPU devices compatible with node module_2_apply_default/compound_bigrams/boolean_mask/Prod = Size[T=DT_STRING, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_2_apply_default/compound_bigrams/concat_2/_367, ^module_2_apply_default/compound_bigrams/boolean_mask/Shape_1/_371)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='CPU'; out_type in [DT_INT64]
  device='CPU'; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT32]; out_type in [DT_INT32]
  device='GPU'; T in [DT_VARIANT]; out_type in [DT_INT64]
  device='GPU'; T in [DT_VARIANT]; out_type in [DT_INT32]
  device='GPU'; T in [DT_BOOL]; out_type in [DT_INT64]
  device='GPU'; T in [DT_BOOL]; out_type in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; out_type in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; out_type in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; out_type in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT8]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT8]; out_type in [DT_INT32]
  device='GPU'; T in [DT_UINT8]; out_type in [DT_INT64]
  device='GPU'; T in [DT_UINT8]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_UINT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_UINT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_type in [DT_INT64]
  device='GPU'; T in [DT_INT64]; out_type in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; out_type in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; out_type in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; out_type in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; out_type in [DT_INT32]
  device='GPU'; T in [DT_BFLOAT16]; out_type in [DT_INT64]
  device='GPU'; T in [DT_BFLOAT16]; out_type in [DT_INT32]
  device='GPU'; T in [DT_HALF]; out_type in [DT_INT64]
  device='GPU'; T in [DT_HALF]; out_type in [DT_INT32]

	 [[Node: module_2_apply_default/compound_bigrams/boolean_mask/Prod = Size[T=DT_STRING, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_2_apply_default/compound_bigrams/concat_2/_367, ^module_2_apply_default/compound_bigrams/boolean_mask/Shape_1/_371)]]

**Comment by akhorlin** [comment]
It looks like the environment is trying to execute this module runs on GPU.
Most text modules currently available perform string preprocessing
(tokenization, n-gramming) as part of the module. These operation are
usually either not GPU-friendly or outright not compatible with execution
on GPU. It seems that is what is going on here. What happens if you connect
to an environment that runs CPU?

**Comment by dazza5000** [comment]
Removing GPU support from the environment allowed the project to run successfully. Thank you for the help.

**Comment by amandalmia14** [comment]
> environment

Hi @dazza5000 , 
How did you remove GPU support?
