### ISSUE TITLE
can not download models and fatures from the given link

### ISSUE THREAD

**Issue by hansanjie** [tensorflow/hub#97]
I want to return the inception v3 models, but, when I run the retain.py, I didn't work anymore .it was failed because it can't down the models from the default link. when I down the models manully, it didn't work for me.
The link as follows: https://tfhub.dev/google/imagenet/inception_v3/classification/1
                               https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1

**Comment by andresusanopinto** [comment]
Can you paste in more information of the error?

**Comment by JIAZHEN** [comment]
Probably the same issue as https://github.com/tensorflow/hub/issues/53.

Cannot download the model anymore.

**Comment by JIAZHEN** [comment]
```
wget 'https://tfhub.dev/google/nnlm-en-dim128/1?tf-hub-format=compressed' -O /tmp/module.tar.gz
--2018-07-16 16:12:12--  https://tfhub.dev/google/nnlm-en-dim128/1?tf-hub-format=compressed
Resolving tfhub.dev... 127.0.0.1
Connecting to tfhub.dev|127.0.0.1|:443... connected.
ERROR: cannot verify tfhub.dev's certificate, issued by ‘CN=Puma-dev CA,O=Developer Certificate’:
  Unable to locally verify the issuer's authority.
To connect to tfhub.dev insecurely, use `--no-check-certificate'.
```

**Comment by andresusanopinto** [comment]
Looks like you have installed "puma-dev" which seems to be a software that used to take control over ".dev" domain. You should configure it to use some other domain such as ".test" or ".puma".

**Comment by JIAZHEN** [comment]
@andresusanopinto That may explains why. Thanks.
