### ISSUE TITLE
Flatten / clear saved model for serving

### ISSUE THREAD

**Issue by dskarlatos** [tensorflow/hub#98]
Hi,
currently after using retrain to get a new model for TF serving the graph as visualized in tensorboard holds many modules and save points from training.
Is there a way to get a single module clean/flat model for serving without all the necessary information and multiple modules? 
I just want the final format to contain a flat graph as it would be if it was exported by hand and not from tf hub. 
If there is no single way to do, it any direction on how to go about it it would be greatly appreciated it.

Thanks!!

**Comment by vbardiovskyg** [comment]
Hi,

could you please elaborate more on how you are exporting the final model? Perhaps you could also attach the tensorboard screenshot. It should be possible to export a clean model.
