### ISSUE TITLE
Export cached tf-hub module as a part of another tf model for serving

### ISSUE THREAD

**Issue by chiragjn** [tensorflow/hub#99]
I am trying to combine [sentencepiece](https://github.com/google/sentencepiece/tree/master/tensorflow/tf_sentencepiece) and universal sentence encoder lite as a single model.

```python
import os
import tensorflow as tf
import tensorflow_hub as hub
import tf_sentencepiece as tfs
# import sentencepiece as spm

class SPUSE(object):
    """
    Needs the tf_sentencepiece op installed
    """

    def __init__(self, use_path):
        self.use = hub.Module(use_path)

        with tf.Session() as session:
            spm_path = session.run(self.use(signature="spm_path"))

        model_proto = tf.gfile.GFile(spm_path, 'rb').read()

        # -- graph begin --
        self.text = tf.placeholder(tf.string, [None])
        self.input_placeholder = tfs.encode_sparse(
            self.text, model_proto=model_proto)
        self.input_placeholder = tf.cast(self.input_placeholder, tf.int64)
        self.encoded = self.use(
            inputs=dict(
                values=self.input_placeholder.values,
                indices=self.input_placeholder.indices,
                dense_shape=self.input_placeholder.dense_shape
            )
        )
        init_op = tf.group(
            [tf.global_variables_initializer(), tf.tables_initializer()])
        # -- graph end --
        self.session = tf.Session()
        self.session.run(init_op)

    def encode(self, sentences):
        encoded = self.session.run(self.encoded, feed_dict={
                                   self.text: sentences})
        return encoded

    def export(self, path, version):
        export_path = os.path.join(
            tf.compat.as_bytes(path),
            tf.compat.as_bytes(str(version)))
        print('Exporting trained model to', export_path)
        builder = tf.saved_model.builder.SavedModelBuilder(export_path)
        tensor_info_text = tf.saved_model.utils.build_tensor_info(self.text)
        tensor_info_encoded = tf.saved_model.utils.build_tensor_info(
            self.encoded)

        prediction_signature = (
            tf.saved_model.signature_def_utils.build_signature_def(
                inputs={'text': tensor_info_text},
                outputs={'encoded': tensor_info_encoded},
                method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME
            )
        )

        legacy_init_op = tf.group(tf.global_variables_initializer(
        ), tf.tables_initializer(), name='legacy_init_op')
        builder.add_meta_graph_and_variables(
            self.session, [tf.saved_model.tag_constants.SERVING],
            signature_def_map={
                'encode': prediction_signature,
            },
            legacy_init_op=legacy_init_op
        )
        builder.save()
        print('Done exporting!')

if __name__ == '__main__':
    use_encoder = SPUSE(
        "http://tfhub.dev/google/universal-sentence-encoder-lite/2")
    print(use_encoder.encode(
        ['hello world.', 'I have a dog.', 'I have an apple.']))
    use_encoder.export('/tmp/export_test/', 1)
```

The export is successful but when I move this saved model from one machine to another machine, tf-serving tries to load from the cached path of the machine the model was exported from

```bash
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /var/folders/zh/5mjzfxvj6s96_b3hp_xjrlc40000gn/T/tfhub_modules/88bcbc18de736c0d220e01461d380fdaaf71603c/variables/variables: Not found: /var/folders/zh/5mjzfxvj6s96_b3hp_xjrlc40000gn/T/tfhub_modules/88bcbc18de736c0d220e01461d380fdaaf71603c/variables; No such file or directory
```

How do I export it explicitly as a part of my larger model in path agnostic way?

**Comment by andresusanopinto** [comment]
Manually crafting correct SavedModels using SavedModelBuilder is hard.

I recomend using the [`tf.saved_model.simple_saver()`](https://www.tensorflow.org/api_docs/python/tf/saved_model/simple_save) as follows:

```python
...
        tf.saved_model.simple_save(
            self.session,
            export_path,
            inputs={'text': self.text},
            outputs={'encoded': self.encoded},
        )
...
```

If you want to use the lower level APIs then you will need to setup your init op to load the variables from the saved model checkpoint instead of runinng its initializers and also configure other things such as assets collection correctly.

**Comment by chiragjn** [comment]
This worked for me 👍 
Thanks, closing this issue.

**Comment by mhajiaghayi** [comment]
hi @chiragjn , quick question on this old post. when you export your model, then in loading and prediction time, does it still need tf_sentencepiece to be imported?

**Comment by mhajiaghayi** [comment]
I just tried it and it seem when loading it through,

 `    with tf.Session() as sess:

        tf.saved_model.loader.load(
            sess,
            [tag_constants.SERVING],
            'tmp/export_test/2/',
        )`
it still complains about sentencepiece missing operation! then the question is if you want to serve this model on other platform, how would you import tf_sentencepiece? am I missing something?

**Comment by chiragjn** [comment]
@mhajiaghayi
Since tf_sentencepiece is not a part of TensorFlow's built-in ops, it is considered a custom op
You have two options:

1. If you want to use it with TF serving, you will need to build the sentencepiece op and then statically link it with TF serving build
tf_sentencepiece op source: https://github.com/google/sentencepiece/tree/master/tensorflow
How to build tf serving with custom op: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/custom_op.md

2. If you are not using tf serving like you have shown above, but now since tf_sentencepiece is a part of your graph, you'll need to pick the correct .so file from here: https://github.com/google/sentencepiece/tree/master/tensorflow/tf_sentencepiece, place it besides the model, call `tf.load_op_library(<.so file path here>)` before you call `tf.saved_model.loader.load`

In the second method, you might run into other issues related to sentencepiece itself such as https://github.com/google/sentencepiece/issues/364, in that case you'll need to build the .so file from the source.

In the end, I gave up on exporting tf-sentencepiece as a part of the model itself because of too many steps involved and changed my placeholders to values, indices and dense_shape

**Comment by stefanondisponibile** [comment]
@chiragjn did you compile TF serving with tf_sentencepiece? If so, how? I've been long trying that with no luck.
